export type E4Option={code:string;label:string};
export type E4ConfigurationRow={code:string;crewCode:string;pantryCode:string;waterCode:string|null;serviceCode:string|null};
export type E4AdditionalRow={configurationCode:string;serviceCode:string};
export type AircraftE4Snapshot={canView:boolean;canEdit:boolean;revision:string;typeCode:string;subtype:string;applicabilityReviewed:boolean;active:boolean;additionalActive:boolean;configurations:E4ConfigurationRow[];additionalRows:E4AdditionalRow[];crewOptions:E4Option[];pantryOptions:E4Option[];waterOptions:E4Option[];serviceOptions:E4Option[]};
export class AircraftE4Invalid extends Error{} export class AircraftE4Denied extends Error{} export class AircraftE4Conflict extends Error{}
const code=(v:unknown,label:string)=>{const s=String(v??"").trim().toUpperCase();if(!/^[A-Z0-9]{1,3}$/.test(s))throw new AircraftE4Invalid(`${label} must contain one to three letters or numbers.`);return s};
export function validateE4Applicability(v:unknown){const x=v as{active?:unknown;additionalActive?:unknown};if(typeof x?.active!=="boolean"||typeof x?.additionalActive!=="boolean")throw new AircraftE4Invalid("Select the E4 section applicability.");return{active:x.active,additionalActive:x.active&&x.additionalActive}}
export function validateE4Configurations(v:unknown,s:AircraftE4Snapshot){if(!Array.isArray(v)||v.length<1)throw new AircraftE4Invalid("Add at least one complete Weight Configuration row.");const crew=new Set(s.crewOptions.map(x=>x.code)),pantry=new Set(s.pantryOptions.map(x=>x.code)),water=new Set(s.waterOptions.map(x=>x.code)),service=new Set(s.serviceOptions.map(x=>x.code)),seen=new Set<string>();return v.map((x,i)=>{const r=x as Partial<E4ConfigurationRow>,c=code(r.code,`Weight Configuration Code at row ${i+1}`),cc=String(r.crewCode??"").trim().toUpperCase(),pc=String(r.pantryCode??"").trim().toUpperCase(),wc=String(r.waterCode??"").trim().toUpperCase()||null,sc=String(r.serviceCode??"").trim().toUpperCase()||null;if(seen.has(c))throw new AircraftE4Invalid(`Weight Configuration Code ${c} is duplicated.`);seen.add(c);if(!crew.has(cc))throw new AircraftE4Invalid(`Select a Crew Code at row ${i+1}.`);if(!pantry.has(pc))throw new AircraftE4Invalid(`Select a Pantry Code at row ${i+1}.`);if(wc&&!water.has(wc))throw new AircraftE4Invalid(`Select a valid Potable Water Code at row ${i+1}.`);if(sc&&!service.has(sc))throw new AircraftE4Invalid(`Select a valid Service Weight item at row ${i+1}.`);return{code:c,crewCode:cc,pantryCode:pc,waterCode:wc,serviceCode:sc}})}
export function validateE4Additional(v:unknown,s:AircraftE4Snapshot){if(!Array.isArray(v)||v.length<1)throw new AircraftE4Invalid("Add at least one additional Service Weight Adjustment item.");const configs=new Set(s.configurations.map(x=>x.code)),services=new Set(s.serviceOptions.map(x=>x.code)),seen=new Set<string>();return v.map((x,i)=>{const r=x as Partial<E4AdditionalRow>,configurationCode=String(r.configurationCode??"").trim().toUpperCase(),serviceCode=String(r.serviceCode??"").trim().toUpperCase();if(!configs.has(configurationCode))throw new AircraftE4Invalid(`Select a Weight Configuration Code at row ${i+1}.`);if(!services.has(serviceCode))throw new AircraftE4Invalid(`Select a Service Weight Adjustment at row ${i+1}.`);const key=`${configurationCode}|${serviceCode}`;if(seen.has(key))throw new AircraftE4Invalid(`The additional Service Weight Adjustment at row ${i+1} is duplicated.`);seen.add(key);const main=s.configurations.find(x=>x.code===configurationCode)?.serviceCode;if(main===serviceCode)throw new AircraftE4Invalid(`The Service Weight Adjustment at row ${i+1} is already the primary item.`);return{configurationCode,serviceCode}})}
