export type E3WaterLocation={id:string;name:string;indexPerWeightUnit:number};
export type E3WaterRow={code:string;tankId:string;tankName:string;weight:number|null;index:number|null;remarks:string|null};
export type E3ServiceRow={code:string;description:string;weight:number|null;balanceArm:number|null;index:number|null;remarks:string|null};
export type AircraftE3Snapshot={canView:boolean;canEdit:boolean;revision:string;typeCode:string;subtype:string;applicabilityReviewed:boolean;waterAvailable:boolean;waterActive:boolean;serviceActive:boolean;waterRows:E3WaterRow[];serviceRows:E3ServiceRow[];waterLocations:E3WaterLocation[]};
export class AircraftE3Invalid extends Error{} export class AircraftE3Denied extends Error{} export class AircraftE3Conflict extends Error{}
const code=(v:unknown,label:string)=>{const s=String(v??"").trim().toUpperCase();if(!/^[A-Z0-9]{1,3}$/.test(s))throw new AircraftE3Invalid(`${label} must contain one to three letters or numbers.`);return s};
const text=(v:unknown,label:string,max:number)=>{const s=String(v??"").trim();if(!s||s.length>max)throw new AircraftE3Invalid(`Enter a valid ${label}.`);return s};
const optional=(v:unknown,label:string,max:number)=>{const s=String(v??"").trim();if(s.length>max)throw new AircraftE3Invalid(`${label} must not exceed ${max} characters.`);return s||null};
const whole=(v:unknown,label:string,zero=true)=>{const n=typeof v==="number"?v:Number(v);if(v===null||v===undefined||typeof v==="boolean"||String(v).trim()===""||!Number.isSafeInteger(n)||(zero?n<0:n===0)||Math.abs(n)>1e9)throw new AircraftE3Invalid(`Enter a valid whole-number ${label}.`);return n};
const finite=(v:unknown,label:string)=>{const n=typeof v==="number"?v:Number(v);if(v===null||v===undefined||typeof v==="boolean"||String(v).trim()===""||!Number.isFinite(n)||Math.abs(n)>1e9)throw new AircraftE3Invalid(`Enter a valid ${label}.`);return n};
const optionalFinite=(v:unknown,label:string)=>v===null||v===undefined||String(v).trim()===""?null:finite(v,label);
export function validateE3Applicability(v:unknown){const x=v as {waterActive?:unknown;serviceActive?:unknown};if(typeof x?.waterActive!=="boolean"||typeof x?.serviceActive!=="boolean")throw new AircraftE3Invalid("Select the E3 section applicability.");return{waterActive:x.waterActive,serviceActive:x.serviceActive}}
export function validateE3Water(v:unknown,locations:E3WaterLocation[]){if(!Array.isArray(v)||v.length<1)throw new AircraftE3Invalid("Add at least one complete Potable Water row.");const available=new Map(locations.map(x=>[x.id,x])),seen=new Set<string>();return v.map((x,i)=>{const r=x as Partial<E3WaterRow>,waterCode=code(r.code,`Potable Water Code at row ${i+1}`),tankId=String(r.tankId??"").trim().toUpperCase(),tank=available.get(tankId);if(!tank)throw new AircraftE3Invalid(`Select a D6 potable-water tank at row ${i+1}.`);const key=`${waterCode}|${tankId}`;if(seen.has(key))throw new AircraftE3Invalid(`Potable Water Code and Tank at row ${i+1} are duplicated.`);seen.add(key);const weight=whole(r.weight,`Weight at row ${i+1}`);return{code:waterCode,tankId,tankName:tank.name,weight,index:weight*tank.indexPerWeightUnit,remarks:optional(r.remarks,`Remarks at row ${i+1}`,500)}})}
export function validateE3Service(v:unknown){if(!Array.isArray(v)||v.length<1)throw new AircraftE3Invalid("Add at least one complete Service Weight Adjustment row.");const seen=new Set<string>();return v.map((x,i)=>{const r=x as Partial<E3ServiceRow>,adjustmentCode=code(r.code,`Adjustment Code at row ${i+1}`);if(seen.has(adjustmentCode))throw new AircraftE3Invalid(`Adjustment Code ${adjustmentCode} is duplicated.`);seen.add(adjustmentCode);return{code:adjustmentCode,description:text(r.description,`Description at row ${i+1}`,64),weight:whole(r.weight,`Weight at row ${i+1}`,false),balanceArm:optionalFinite(r.balanceArm,`Balance Arm at row ${i+1}`),index:finite(r.index,`Index at row ${i+1}`),remarks:optional(r.remarks,`Remarks at row ${i+1}`,500)}})}
