export type C2Output={code:string;name:string;group:string;displayOrder:number;validEdpPrelim:boolean;validAcarsPrelim:boolean;validEdpFinal:boolean;validAcarsFinal:boolean;selectedEdpPrelim:boolean;selectedAcarsPrelim:boolean;selectedEdpFinal:boolean;selectedAcarsFinal:boolean};
export type C2Document={code:string;name:string;ahmReference:string;suggested:boolean;required:boolean};
export type C2TrimOption={option:string;suggested:boolean;selected:boolean;priority:number|null};
export type C2OutputRemark={code:string;remarks:string;useReferenceChord:boolean};
export type AircraftC2Values={outputs:C2Output[];documents:C2Document[];trimOptions:C2TrimOption[];outputRemarks:C2OutputRemark[];passengerTrimRemarks:string;captainsInformation:string;preLmcLoadMessage:string};
export type AircraftC2Snapshot=AircraftC2Values&{canView:boolean;canEdit:boolean;exists:boolean;revision:string;typeCode:string;subtype:string;trimSaved:boolean};
export class AircraftC2Invalid extends Error{}
export class AircraftC2Denied extends Error{}
export class AircraftC2Conflict extends Error{}
const text=(value:unknown,max:number,label:string)=>{const clean=String(value??"").trim();if(clean.length>max)throw new AircraftC2Invalid(`${label} must be no more than ${max.toLocaleString()} characters.`);return clean;};
export function validateAircraftC2(input:unknown):AircraftC2Values{const v=input as Record<string,unknown>;if(!Array.isArray(v?.outputs)||!Array.isArray(v?.documents)||!Array.isArray(v?.trimOptions)||!Array.isArray(v?.outputRemarks))throw new AircraftC2Invalid("The C2 data is incomplete.");const outputs=v.outputs.map(value=>{const x=value as Record<string,unknown>;return{code:String(x.code??""),name:String(x.name??""),group:String(x.group??""),displayOrder:Number(x.displayOrder),validEdpPrelim:Boolean(x.validEdpPrelim),validAcarsPrelim:Boolean(x.validAcarsPrelim),validEdpFinal:Boolean(x.validEdpFinal),validAcarsFinal:Boolean(x.validAcarsFinal),selectedEdpPrelim:Boolean(x.selectedEdpPrelim),selectedAcarsPrelim:Boolean(x.selectedAcarsPrelim),selectedEdpFinal:Boolean(x.selectedEdpFinal),selectedAcarsFinal:Boolean(x.selectedAcarsFinal)}});for(const o of outputs){if(!o.code||!o.group||!Number.isInteger(o.displayOrder)||(!o.validEdpPrelim&&o.selectedEdpPrelim)||(!o.validAcarsPrelim&&o.selectedAcarsPrelim)||(!o.validEdpFinal&&o.selectedEdpFinal)||(!o.validAcarsFinal&&o.selectedAcarsFinal))throw new AircraftC2Invalid("A loadsheet output was selected for an unavailable document format.");}const documents=v.documents.map(value=>{const x=value as Record<string,unknown>;return{code:String(x.code??""),name:String(x.name??""),ahmReference:String(x.ahmReference??""),suggested:Boolean(x.suggested),required:Boolean(x.required)}});const trimOptions=v.trimOptions.map(value=>{const x=value as Record<string,unknown>;return{option:String(x.option??""),suggested:Boolean(x.suggested),selected:Boolean(x.selected),priority:x.selected?Number(x.priority):null}});const selected=trimOptions.filter(x=>x.selected);if(documents.some(x=>x.required)&&(!selected.length||selected.some(x=>!Number.isInteger(x.priority)||x.priority!<1||x.priority!>3)||new Set(selected.map(x=>x.priority)).size!==selected.length))throw new AircraftC2Invalid("Select at least one Passenger Trim option and give each selected option a different priority.");const outputRemarks=v.outputRemarks.map(value=>{const x=value as Record<string,unknown>;return{code:String(x.code??""),remarks:text(x.remarks,500,"Output Remarks"),useReferenceChord:Boolean(x.useReferenceChord)}});return{outputs,documents,trimOptions,outputRemarks,passengerTrimRemarks:text(v.passengerTrimRemarks,1000,"Passenger Trim Remarks"),captainsInformation:text(v.captainsInformation,2000,"Captain’s Information"),preLmcLoadMessage:text(v.preLmcLoadMessage,2000,"Pre-LMC Load Message")};}
