import type{StartWeightPrinciple}from"@/domain/aircraft-e11";
export type E5Approach="FLEET_WEIGHTS"|"INDIVIDUAL_AIRCRAFT_WEIGHTS";
export type E5Option={code:string;label:string};
export type E5Row={fleetRowId:string|null;registration:string;variantCode:string;weight:number|null;index:number|null;actualWeight:number|null;actualIndex:number|null;macPercent:number|null;balanceArm:number|null;weightConfigurationCode:string|null;pantryCode:string|null;crewCode:string|null;remarks:string|null};
export type AircraftE5Snapshot={canView:boolean;canEdit:boolean;revision:string;typeCode:string;subtype:string;principle:StartWeightPrinciple;approach:E5Approach|null;fleetWeight:number|null;fleetIndex:number|null;rows:E5Row[];variantOptions:E5Option[];configurationOptions:E5Option[];pantryOptions:E5Option[];crewOptions:E5Option[]};
export class AircraftE5Invalid extends Error{} export class AircraftE5Denied extends Error{} export class AircraftE5Conflict extends Error{}
const finite=(v:unknown,label:string,optional=false)=>{if(optional&&(v===null||v===undefined||String(v).trim()===""))return null;const n=typeof v==="number"?v:Number(v);if(!Number.isFinite(n)||Math.abs(n)>1e9)throw new AircraftE5Invalid(`Enter a valid ${label}.`);return n};
const whole=(v:unknown,label:string,positive=false)=>{const n=finite(v,label) as number;if(!Number.isSafeInteger(n)||(positive?n<=0:false))throw new AircraftE5Invalid(`Enter a valid whole-number ${label}.`);return n};
const option=(v:unknown,available:Set<string>,label:string)=>{const s=String(v??"").trim().toUpperCase();if(!s)return null;if(!available.has(s))throw new AircraftE5Invalid(`Select a valid ${label}.`);return s};
export function validateE5Approach(v:unknown):E5Approach{if(v!=="FLEET_WEIGHTS"&&v!=="INDIVIDUAL_AIRCRAFT_WEIGHTS")throw new AircraftE5Invalid("Select Fleet Weights or Individual Aircraft Weights.");return v}
export function validateE5Rows(v:unknown,s:AircraftE5Snapshot){if(!s.approach)throw new AircraftE5Invalid("Select the E5 weight recording approach first.");if(!Array.isArray(v)||v.length<1)throw new AircraftE5Invalid("Add at least one complete aircraft row.");if(s.approach==="FLEET_WEIGHTS"&&(s.fleetWeight===null||s.fleetIndex===null))throw new AircraftE5Invalid("Complete the Standard Fleet Weight and Standard Fleet Index on E1.2 first.");const variants=new Set(s.variantOptions.map(x=>x.code)),configs=new Set(s.configurationOptions.map(x=>x.code)),pantries=new Set(s.pantryOptions.map(x=>x.code)),crews=new Set(s.crewOptions.map(x=>x.code)),seen=new Set<string>();return v.map((x,i)=>{const r=x as Partial<E5Row>,registration=String(r.registration??"").trim().toUpperCase(),variantCode=String(r.variantCode??"").trim().toUpperCase();if(!/^[A-Z0-9][A-Z0-9-]{0,9}$/.test(registration))throw new AircraftE5Invalid(`Enter a valid aircraft registration at row ${i+1}.`);if(!variants.has(variantCode))throw new AircraftE5Invalid(`Select a valid Carrier Variant at row ${i+1}.`);if(seen.has(registration))throw new AircraftE5Invalid(`Aircraft registration ${registration} is duplicated.`);seen.add(registration);const fleet=s.approach==="FLEET_WEIGHTS",weight=whole(r.weight,`${fleet?"Weight Adjustment":"Weight"} at row ${i+1}`,!fleet),index=finite(r.index,`${fleet?"Index Adjustment":"Index"} at row ${i+1}`) as number,weightConfigurationCode=option(r.weightConfigurationCode,configs,`Weight Configuration Code at row ${i+1}`),pantryCode=fleet?option(r.pantryCode,pantries,`Pantry Code at row ${i+1}`):null,crewCode=fleet?option(r.crewCode,crews,`Crew Code at row ${i+1}`):null,remarks=String(r.remarks??"").trim()||null;if(remarks&&remarks.length>500)throw new AircraftE5Invalid(`Remarks at row ${i+1} must not exceed 500 characters.`);return{fleetRowId:typeof r.fleetRowId==="string"?r.fleetRowId:null,registration,variantCode,weight,index,actualWeight:fleet?(s.fleetWeight as number)+weight:weight,actualIndex:fleet?(s.fleetIndex as number)+index:index,macPercent:finite(r.macPercent,`%MAC at row ${i+1}`,true),balanceArm:finite(r.balanceArm,`Balance Arm at row ${i+1}`,true),weightConfigurationCode,pantryCode,crewCode,remarks}})}
