export type AircraftIdentity={typeCode:string;subtype:string;identityName:string;manufacturerId:string|null;manufacturerName:string};
export type AircraftOperatingRole="PASSENGER"|"FREIGHTER"|"COMBI";
export type CarrierAircraft={typeCode:string;subtype:string;aircraftName:string;identityName:string;manufacturerName:string;variantCodes:string[];operatingRole:AircraftOperatingRole;configured:boolean};
export type AircraftListSnapshot={canView:boolean;canCreateAircraft:boolean;canCreateIdentity:boolean;rows:CarrierAircraft[]};
export type AircraftC1Values={weight:string;length:string;liquidVolume:string;volume:string;fuelDensity:string;moment:string;remarks:string};
export type AircraftC1Snapshot={canView:boolean;canEdit:boolean;canAssignManufacturer:boolean;exists:boolean;revision:string;typeCode:string;subtype:string;manufacturerId:string|null;manufacturerName:string;identityName:string;aircraftName:string;variantCodes:string[];operatingRole:AircraftOperatingRole;values:AircraftC1Values};
export class AircraftC1Invalid extends Error{}
export class AircraftC1Denied extends Error{}
export class AircraftC1Conflict extends Error{}
export const aircraftCode=(value:string)=>value.trim().toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,3);
export const aircraftSubtype=(value:string)=>value.trim().toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,4);
export const aircraftVariant=aircraftSubtype;
export function validateVariantCodes(value:unknown,masterSubtype:string){if(!Array.isArray(value))throw new AircraftC1Invalid("Add at least one Carrier Variant.");const variants=[...new Set(value.map(x=>aircraftVariant(String(x))).filter(Boolean))];if(!variants.includes(masterSubtype)||variants.length>20)throw new AircraftC1Invalid(`Carrier Variants must include the Master Series ${masterSubtype}.`);return variants.sort();}
export function validateManufacturerAssignment(value:unknown){if(value===null||value===undefined||value==="")return null;const id=String(value);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id))throw new AircraftC1Invalid("Select an Aircraft Manufacturer from the suggested list.");return id;}
export function validateIdentity(input:unknown){const v=input as Record<string,unknown>;const typeCode=String(v?.typeCode??"").trim().toUpperCase(),subtype=String(v?.subtype??"").trim().toUpperCase(),identityName=String(v?.identityName??"").trim(),manufacturerId=v?.manufacturerId?String(v.manufacturerId):null,manufacturerName=String(v?.manufacturerName??"").trim();if(!/^[A-Z0-9]{3}$/.test(typeCode))throw new AircraftC1Invalid("Enter an Aircraft Type Code of exactly Three Letters or Numbers.");if(!/^[A-Z0-9]{1,4}$/.test(subtype))throw new AircraftC1Invalid("Enter a Series or Sub-Type of One to Four Letters or Numbers.");if(!identityName||identityName.length>64)throw new AircraftC1Invalid("Enter an Aircraft Identity Name of no more than 64 characters.");if(!manufacturerId&&(!manufacturerName||manufacturerName.length>64))throw new AircraftC1Invalid("Select or enter the Aircraft Manufacturer.");return{typeCode,subtype,identityName,manufacturerId,manufacturerName};}
export function validateC1(input:unknown){const v=input as Record<string,unknown>;const aircraftName=String(v?.aircraftName??"").trim(),operatingRole=String(v?.operatingRole??"").trim().toUpperCase() as AircraftOperatingRole;const values=v?.values as Record<string,unknown>;if(!aircraftName||aircraftName.length>64)throw new AircraftC1Invalid("Enter an Aircraft Name of no more than 64 characters.");if(!["PASSENGER","FREIGHTER","COMBI"].includes(operatingRole))throw new AircraftC1Invalid("Select Passenger, Freighter or Combi as the Aircraft Operating Role.");const allowed:Record<string,string[]>={weight:["KG","LB"],length:["CM","M","IN","FT"],liquidVolume:["L","US_GAL"],volume:["M3","FT3"],fuelDensity:["KG_L","LB_L","KG_US_GAL","LB_US_GAL"],moment:["KG_IN","LB_IN","KG_CM","LB_CM","KG_M","LB_M"]};const clean={} as Record<string,string>;for(const[key,options]of Object.entries(allowed)){const value=String(values?.[key]??"");if(!options.includes(value))throw new AircraftC1Invalid("Select one option in every Units of Measure group.");clean[key]=value;}const remarks=String(values?.remarks??"").trim();if(remarks.length>2000)throw new AircraftC1Invalid("Keep Remarks within 2,000 characters.");return{aircraftName,operatingRole,values:{...clean,remarks} as AircraftC1Values};}
export const carriesPassengers=(role:AircraftOperatingRole)=>role!=="FREIGHTER";
export const carrierCarriesPassengers=(rows:CarrierAircraft[])=>rows.length===0||rows.some(row=>carriesPassengers(row.operatingRole));
