export type F1Definition={tableId:string|null;tableName:string;limitCondition:string|null;limitConditionCode:string|null;limitFromDate:string|null;limitToDate:string|null;limitType:string|null;persisted:boolean};
export type F1VariantOption={code:string;label:string};
export type F1RegistrationOption={registration:string;variantCode:string};
export type F1WeightRow={rowId:string|null;tableName:string;variantCode:string;registration:string|null;zeroFuelWeight:number|null;landingWeight:number|null;takeOffWeight:number|null;rampTaxiWeight:number|null;remarks:string|null;persisted:boolean};
export type AircraftF1Snapshot={canView:boolean;canEdit:boolean;revision:string;typeCode:string;subtype:string;weightUnit:string;definitions:F1Definition[];rows:F1WeightRow[];variantOptions:F1VariantOption[];registrationOptions:F1RegistrationOption[];c5Source?:{mzfw:number|null;mlaw:number|null;mtow:number|null;mrw:number|null}};
export class AircraftF1Invalid extends Error{} export class AircraftF1Denied extends Error{} export class AircraftF1Conflict extends Error{}
const text=(v:unknown,max:number,label:string,required=false)=>{const s=String(v??"").trim();if(required&&!s)throw new AircraftF1Invalid(`${label} is required.`);if(s.length>max)throw new AircraftF1Invalid(`${label} is too long.`);return s||null};
const date=(v:unknown,label:string)=>{const s=String(v??"").trim();if(!s)return null;if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||Number.isNaN(Date.parse(s)))throw new AircraftF1Invalid(`${label} is invalid.`);return s};
const weight=(v:unknown,label:string)=>{if(typeof v!=="number"||!Number.isInteger(v)||v<=0)throw new AircraftF1Invalid(`${label} must be a positive whole number.`);return v};
export function validateF1Definitions(v:unknown){if(!Array.isArray(v)||!v.length)throw new AircraftF1Invalid("Add at least one Weight Table.");const seen=new Set<string>();const rows=v.map((x,i)=>{const r=x as Partial<F1Definition>,tableName=String(text(r.tableName,20,`Table Name at row ${i+1}`,true)).toUpperCase();if(!/^[A-Z0-9][A-Z0-9 /_-]{0,19}$/.test(tableName))throw new AircraftF1Invalid(`Table Name at row ${i+1} is invalid.`);if(tableName!=="ALL"&&!["MINIMUM","MAXIMUM"].includes(String(r.limitType??"").toUpperCase()))throw new AircraftF1Invalid(`Select Minimum or Maximum for ${tableName}.`);if(seen.has(tableName))throw new AircraftF1Invalid(`Weight Table ${tableName} is duplicated.`);seen.add(tableName);const from=date(r.limitFromDate,`Limit From Date at row ${i+1}`),to=date(r.limitToDate,`Limit To Date at row ${i+1}`);if(from&&to&&from>to)throw new AircraftF1Invalid(`Limit From Date cannot be after Limit To Date at row ${i+1}.`);return{tableId:typeof r.tableId==="string"?r.tableId:null,tableName,limitCondition:text(r.limitCondition,200,`Limit Condition at row ${i+1}`),limitConditionCode:text(r.limitConditionCode,20,`Limit Condition Code at row ${i+1}`)?.toUpperCase()??null,limitFromDate:from,limitToDate:to,limitType:text(r.limitType,30,`Limit Type at row ${i+1}`)?.toUpperCase()??null,persisted:Boolean(r.persisted)}});if(!seen.has("ALL"))throw new AircraftF1Invalid("The default ALL Weight Table is required.");return rows}
export function validateF1Rows(v:unknown,s:AircraftF1Snapshot){if(!Array.isArray(v)||!v.length)throw new AircraftF1Invalid("Add at least one complete Limiting Weight row.");const tables=new Set(s.definitions.map(x=>x.tableName)),variants=new Set(s.variantOptions.map(x=>x.code)),registrations=new Map(s.registrationOptions.map(x=>[x.registration,x.variantCode])),seen=new Set<string>();return v.map((x,i)=>{const r=x as Partial<F1WeightRow>,tableName=String(r.tableName??"").trim().toUpperCase(),variantCode=String(r.variantCode??"").trim().toUpperCase();const registration=String(r.registration??"").trim().toUpperCase()||null;if(!tables.has(tableName))throw new AircraftF1Invalid(`Select a valid Weight Table Name at row ${i+1}.`);if(!variants.has(variantCode))throw new AircraftF1Invalid(`Select a valid Series/Sub-Series at row ${i+1}.`);if((registration&&registrations.get(registration)!==variantCode))throw new AircraftF1Invalid(`Select a valid Registration for the Series/Sub-Series at row ${i+1}.`);const key=`${tableName}|${variantCode}|${registration??"ALL"}`;if(seen.has(key))throw new AircraftF1Invalid(`The ${tableName} / ${variantCode} / ${registration??"ALL"} row is duplicated.`);seen.add(key);if(tableName==="ALL"&&registration){const defaults=v.find(d=>d.tableName==="ALL"&&d.variantCode===variantCode&&!d.registration);if(!defaults)throw new AircraftF1Invalid(`Add ALL defaults for ${variantCode} before its registration exceptions.`);for(const field of ["zeroFuelWeight","landingWeight","takeOffWeight","rampTaxiWeight"] as const)if(typeof r[field]==="number"&&r[field]!>defaults[field])throw new AircraftF1Invalid(`Limits for ${registration} cannot exceed the ALL defaults for ${variantCode}.`);}const readWeight=(v:unknown,label:string)=>tableName!=="ALL"&&(v===null||v===undefined)?null:weight(v,label);const zeroFuelWeight=readWeight(r.zeroFuelWeight,`Zero Fuel Weight at row ${i+1}`),landingWeight=readWeight(r.landingWeight,`Landing Weight at row ${i+1}`),takeOffWeight=readWeight(r.takeOffWeight,`Take Off Weight at row ${i+1}`),rampTaxiWeight=readWeight(r.rampTaxiWeight,`Ramp/Taxi Weight at row ${i+1}`);if([zeroFuelWeight,landingWeight,takeOffWeight,rampTaxiWeight].every(x=>x===null))throw new AircraftF1Invalid(`Enter at least one limiting weight at row ${i+1}.`);if(tableName==="ALL"&&!(zeroFuelWeight!<=landingWeight!&&landingWeight!<=takeOffWeight!&&takeOffWeight!<=rampTaxiWeight!))throw new AircraftF1Invalid(`Weights at row ${i+1} must satisfy Zero Fuel ≤ Landing ≤ Take Off ≤ Ramp/Taxi.`);return{rowId:typeof r.rowId==="string"?r.rowId:null,tableName,variantCode,registration,zeroFuelWeight,landingWeight,takeOffWeight,rampTaxiWeight,remarks:text(r.remarks,500,`Remarks at row ${i+1}`),persisted:true}})}

export function newF1RegistrationException(rows:F1WeightRow[],registrations:F1RegistrationOption[]):F1WeightRow|null{
 for(const registration of registrations){
 const defaults=rows.find(r=>r.tableName==='ALL'&&!r.registration&&r.variantCode===registration.variantCode);
 if(defaults&&!rows.some(r=>r.tableName==='ALL'&&r.registration===registration.registration&&r.variantCode===registration.variantCode))return {...defaults,rowId:null,registration:registration.registration,persisted:false,remarks:null};
 }return null;
}
