export type E2CrewRow={crewCode:string;flightDeckLocationId:string;flightDeckSeats:number|null;cabinCrewLocationId:string;cabinCrewSeats:number|null;flightDeckBaggageLocation:string|null;cabinCrewBaggageLocation:string|null};
export type E2PantryRow={pantryCode:string;galleyLocations:string;totalWeight:number|null;balanceArm:number|null;index:number|null};
export type E2Location={id:string;description:string};
export type E2Hold={id:string;description:string};
export type AircraftE2Snapshot={canView:boolean;canEdit:boolean;revision:string;typeCode:string;subtype:string;crewRows:E2CrewRow[];pantryRows:E2PantryRow[];flightDeckLocations:E2Location[];cabinCrewLocations:E2Location[];holds:E2Hold[]};
export class AircraftE2Invalid extends Error{} export class AircraftE2Denied extends Error{} export class AircraftE2Conflict extends Error{}
const code=(v:unknown,label:string)=>{const s=String(v??"").trim().toUpperCase();if(!/^[A-Z0-9]$/.test(s))throw new AircraftE2Invalid(`${label} must contain one letter or number.`);return s};
const whole=(v:unknown,label:string)=>{const n=typeof v==="number"?v:Number(v);if(!Number.isInteger(n)||n<0||n>999)throw new AircraftE2Invalid(`${label} must be a whole number of zero or more.`);return n};
const finite=(v:unknown,label:string)=>{const n=typeof v==="number"?v:Number(v);if(!Number.isFinite(n)||Math.abs(n)>1e9)throw new AircraftE2Invalid(`Enter a valid ${label}.`);return n};
export function validateE2Crew(v:unknown,flight:E2Location[],cabin:E2Location[],holds:E2Hold[]){if(!Array.isArray(v))throw new AircraftE2Invalid("Crew Code rows are required.");const f=new Set(flight.map(x=>x.id)),c=new Set(cabin.map(x=>x.id)),h=new Set(holds.map(x=>x.id)),seen=new Set<string>();return v.map((x,i)=>{const r=x as Partial<E2CrewRow>,crewCode=code(r.crewCode,`Crew Code at row ${i+1}`),flightDeckLocationId=String(r.flightDeckLocationId??"").trim().toUpperCase(),cabinCrewLocationId=String(r.cabinCrewLocationId??"").trim().toUpperCase(),flightDeckBaggageLocation=String(r.flightDeckBaggageLocation??"").trim().toUpperCase()||null,cabinCrewBaggageLocation=String(r.cabinCrewBaggageLocation??"").trim().toUpperCase()||null;if(!f.has(flightDeckLocationId)||!c.has(cabinCrewLocationId))throw new AircraftE2Invalid(`Select valid crew locations at row ${i+1}.`);if((flightDeckBaggageLocation&&!h.has(flightDeckBaggageLocation))||(cabinCrewBaggageLocation&&!h.has(cabinCrewBaggageLocation)))throw new AircraftE2Invalid(`Select valid D2 holds for baggage locations at row ${i+1}.`);const key=[crewCode,flightDeckLocationId,cabinCrewLocationId].join("|");if(seen.has(key))throw new AircraftE2Invalid(`Crew Code location combination at row ${i+1} is duplicated.`);seen.add(key);return{crewCode,flightDeckLocationId,flightDeckSeats:whole(r.flightDeckSeats,`Flight Deck Seats at row ${i+1}`),cabinCrewLocationId,cabinCrewSeats:whole(r.cabinCrewSeats,`Cabin Crew Seats at row ${i+1}`),flightDeckBaggageLocation,cabinCrewBaggageLocation}})}
export function validateE2Pantry(v:unknown){if(!Array.isArray(v))throw new AircraftE2Invalid("Pantry Code rows are required.");const seen=new Set<string>();return v.map((x,i)=>{const r=x as Partial<E2PantryRow>,pantryCode=code(r.pantryCode,`Pantry Code at row ${i+1}`),galleyLocations=String(r.galleyLocations??"").trim();if(!galleyLocations||galleyLocations.length>64)throw new AircraftE2Invalid(`Enter Galley Locations at row ${i+1}.`);if(seen.has(pantryCode))throw new AircraftE2Invalid(`Pantry Code ${pantryCode} is duplicated.`);seen.add(pantryCode);return{pantryCode,galleyLocations,totalWeight:whole(r.totalWeight,`Total Weight at row ${i+1}`),balanceArm:finite(r.balanceArm,`Balance Arm at row ${i+1}`),index:finite(r.index,`Index at row ${i+1}`)}})}
