import{balanceArmFromIndexPerWeightUnit,validIndexPerWeightUnitFormula,type IndexPerWeightUnitFormula}from"@/domain/index-per-weight-unit";export type WaterLocation={id:string;name:string;maxWeight:number|null;centroid:number|null;index:number|null};
export type GalleyLocation={id:string;description:string;maxWeight:number|null;centroid:number|null;index:number|null};
export type AircraftD6Snapshot={canView:boolean;canEdit:boolean;revision:string;typeCode:string;subtype:string;waterApplicable:boolean|null;galleyApplicable:boolean|null;waterLocations:WaterLocation[];galleyLocations:GalleyLocation[];balanceFormula?:IndexPerWeightUnitFormula|null};
export type D6Section="waterLocations"|"galleyLocations";
export class AircraftD6Invalid extends Error{} export class AircraftD6Denied extends Error{} export class AircraftD6Conflict extends Error{}
const text=(v:unknown,label:string,max:number)=>{const s=String(v??"").trim();if(!s||s.length>max)throw new AircraftD6Invalid(`Enter a valid ${label}.`);return s};
const id=(v:unknown,label:string)=>{const s=text(v,label,3).toUpperCase();if(!/^[A-Z0-9]{1,3}$/.test(s))throw new AircraftD6Invalid(`${label} may contain up to three letters or numbers.`);return s};
const num=(v:unknown,label:string,positive=false)=>{const n=typeof v==="number"?v:Number(v);if(v===null||v===""||typeof v==="boolean"||!Number.isFinite(n)||Math.abs(n)>1e9||(positive&&n<=0))throw new AircraftD6Invalid(`Enter a valid ${label}.`);return n};
export function validateD6Section(section:D6Section,input:unknown,formula?:IndexPerWeightUnitFormula|null){if(!Array.isArray(input)||input.length<1)throw new AircraftD6Invalid("Add at least one complete row.");return input.map((v,i)=>{const r=v as Partial<WaterLocation&GalleyLocation>,index=num(r.index,`Index per Weight Unit at row ${i+1}`);if(!validIndexPerWeightUnitFormula(formula))throw new AircraftD6Invalid(`Row ${i+1}: configure C4 before calculating Balance Arm Centroid.`);return{id:id(r.id,`Short Code at row ${i+1}`),...(section==="waterLocations"?{name:text(r.name,`Tank Name at row ${i+1}`,64)}:{description:text(r.description,`Description at row ${i+1}`,64)}),maxWeight:num(r.maxWeight,`Maximum Weight at row ${i+1}`,true),centroid:balanceArmFromIndexPerWeightUnit(index,formula),index}})}
