import type{StartWeightPrinciple}from"@/domain/aircraft-e11";
export type FuelSystemConfiguration={code:string;description:string;actCount:number;maximumWeights:{mrw:number|null;tow:number|null;law:number|null;zfw:number|null}};
export type E12Registration={fleetRowId:string|null;registration:string;variantCode:string;fuelConfigurationCode:string|null;weight:number|null;index:number|null};
export type AircraftE12Snapshot={canView:boolean;canEdit:boolean;revision:string;typeCode:string;subtype:string;principle:StartWeightPrinciple;standardFleetWeight:number|null;standardFleetIndex:number|null;variantOptions:string[];fuelConfigurations:FuelSystemConfiguration[];registrations:E12Registration[]};
export class AircraftE12Invalid extends Error{} export class AircraftE12Denied extends Error{} export class AircraftE12Conflict extends Error{}
const finite=(v:unknown,label:string,positive=false)=>{if(v===null||v==="")return null;const n=typeof v==="number"?v:Number(v);if(!Number.isFinite(n)||Math.abs(n)>1e9||(positive&&n<=0))throw new AircraftE12Invalid(`Enter a valid ${label}.`);return n};
export function validateE12Standard(v:unknown){const x=v as Record<string,unknown>;return{standardFleetWeight:finite(x?.standardFleetWeight,"Standard Fleet Weight",true),standardFleetIndex:finite(x?.standardFleetIndex,"Standard Fleet Index")}}
export function validateFuelSystemConfigurations(v:unknown){if(!Array.isArray(v))throw new AircraftE12Invalid("Fuel-system configurations are required.");const seen=new Set<string>();return v.map((x,i)=>{const r=x as Partial<FuelSystemConfiguration>,code=String(r.code??"").trim().toUpperCase(),description=String(r.description??"").trim(),actCount=Number(r.actCount),raw=r.maximumWeights??{} as FuelSystemConfiguration["maximumWeights"];if(!/^[A-Z0-9][A-Z0-9-]{0,11}$/.test(code))throw new AircraftE12Invalid(`Enter a valid fuel-configuration code at row ${i+1}.`);if(seen.has(code))throw new AircraftE12Invalid(`Fuel configuration ${code} is duplicated.`);seen.add(code);if(!Number.isSafeInteger(actCount)||actCount<0||actCount>9)throw new AircraftE12Invalid(`ACT count at row ${i+1} must be a whole number from 0 to 9.`);const maximumWeights={mrw:finite(raw.mrw,`MRW at row ${i+1}`,true),tow:finite(raw.tow,`MTOW at row ${i+1}`,true),law:finite(raw.law,`MLAW at row ${i+1}`,true),zfw:finite(raw.zfw,`MZFW at row ${i+1}`,true)};const present=Object.values(maximumWeights).filter((n):n is number=>n!==null);if(present.length&&present.length!==4)throw new AircraftE12Invalid(`Complete all four structural maximum weights for ${code}, or leave all four empty.`);if(present.length===4&&!(maximumWeights.zfw!<=maximumWeights.law!&&maximumWeights.law!<=maximumWeights.tow!&&maximumWeights.tow!<=maximumWeights.mrw!))throw new AircraftE12Invalid(`Structural weights for ${code} must satisfy MZFW ≤ MLAW ≤ MTOW ≤ MRW.`);return{code,description,actCount,maximumWeights}})}
export function validateE12Registrations(v:unknown,variantOptions:string[],fuelConfigurations:FuelSystemConfiguration[]){if(!Array.isArray(v))throw new AircraftE12Invalid("Registration rows are required.");const seen=new Set<string>(),variants=new Set(variantOptions),fuelCodes=new Set(fuelConfigurations.map(item=>item.code));return v.map((x,i)=>{const r=x as Partial<E12Registration>,registration=String(r.registration??"").trim().toUpperCase(),variantCode=String(r.variantCode??"").trim().toUpperCase(),fuelConfigurationCode=String(r.fuelConfigurationCode??"").trim().toUpperCase()||null;if(!/^[A-Z0-9][A-Z0-9-]{0,9}$/.test(registration))throw new AircraftE12Invalid(`Enter a valid aircraft registration at row ${i+1}.`);if(!variants.has(variantCode))throw new AircraftE12Invalid(`Select a valid Carrier Variant at row ${i+1}.`);if(fuelConfigurations.length>0&&(!fuelConfigurationCode||!fuelCodes.has(fuelConfigurationCode)))throw new AircraftE12Invalid(`Select a valid fuel configuration for ${registration}.`);if(seen.has(registration))throw new AircraftE12Invalid(`Aircraft registration ${registration} is duplicated.`);seen.add(registration);return{fleetRowId:typeof r.fleetRowId==="string"?r.fleetRowId:null,registration,variantCode,fuelConfigurationCode,weight:finite(r.weight,`weight at row ${i+1}`,true),index:finite(r.index,`index at row ${i+1}`)}})}
