import type{FuelLoadingSchedule,FuelScheduleQuantityBasis}from"./aircraft-c8";
import{csvAircraftIdentityError,csvAircraftIdentityHeaders,normaliseCsvAircraftIdentity,type CsvAircraftIdentity}from"./csv-aircraft-identity";

export type ScheduleImportResult={schedules:FuelLoadingSchedule[];errors:string[];source:CsvAircraftIdentity|null};

export const scheduleCsvTemplate=(typeCode:string,subtype:string,includeBlank=true)=>`${csvAircraftIdentityHeaders.join(",")},Configuration Code,Schedule Name,Specific Gravity,Step,Tank Code(s),Volume Amount,Weight Amount\n${includeBlank?`${normaliseCsvAircraftIdentity(typeCode)},${normaliseCsvAircraftIdentity(subtype)},,,,,,\n`:""}`;

const headerKey=(value:string)=>value.trim().toLowerCase().replace(/[^a-z0-9]/g,"");
const aliases={aircraftType:["aircrafttypeiata"],aircraftSubtype:["seriessubtype"],configurationCode:["configurationcode","fuelconfiguration","configuration"],name:["schedulename","distributionname","name"],specificGravity:["specificgravity","sg","fueldensity"],step:["step","stepnumber","sequence"],tankCodes:["tankcodes","tankcode","tanknames","tankname","tanks"],volume:["volumeamount","volume","vol"],weight:["weightamount","weight","wt"]};

function csvRows(text:string){const rows:string[][]=[];let row:string[]=[],field="",quoted=false;for(let index=0;index<text.length;index++){const char=text[index];if(quoted){if(char==='"'&&text[index+1]==='"'){field+='"';index++}else if(char==='"')quoted=false;else field+=char}else if(char==='"')quoted=true;else if(char===','){row.push(field);field=""}else if(char==='\n'){row.push(field.replace(/\r$/,"").trim());if(row.some(value=>value!==""))rows.push(row);row=[];field=""}else field+=char}row.push(field.replace(/\r$/,"").trim());if(row.some(value=>value!==""))rows.push(row);return rows}
const numeric=(value:string|undefined)=>{if(value===undefined||value.trim()==="")return null;const parsed=Number(value);return Number.isFinite(parsed)?parsed:Number.NaN};

export function parseScheduleCsv(text:string,expected?:CsvAircraftIdentity,configurationCodes:string[]=[]):ScheduleImportResult{
 const raw=csvRows(text.replace(/^\uFEFF/,"")),errors:string[]=[];let source:CsvAircraftIdentity|null=null;
 if(raw.length===0)return{schedules:[],errors:["The CSV file is empty."],source};
 const normalisedConfigurations=new Set(configurationCodes.map(code=>code.trim().toUpperCase())),reportedInvalidConfigurations=new Set<string>();
 const headers=raw[0].map(headerKey),column=(key:keyof typeof aliases)=>headers.findIndex(header=>aliases[key].includes(header)),columns={aircraftType:column("aircraftType"),aircraftSubtype:column("aircraftSubtype"),configurationCode:column("configurationCode"),name:column("name"),specificGravity:column("specificGravity"),step:column("step"),tankCodes:column("tankCodes"),volume:column("volume"),weight:column("weight")};
 for(const [key,label] of [["name","Schedule Name"],["specificGravity","Specific Gravity"],["step","Step"],["tankCodes","Tank Code(s)"]] as const)if(columns[key]<0)errors.push(`Missing required column: ${label}.`);
 if(columns.volume<0&&columns.weight<0)errors.push("Include at least one of Volume Amount or Weight Amount.");
 if(expected){if(columns.aircraftType<0)errors.push(`Missing required column: ${csvAircraftIdentityHeaders[0]}.`);if(columns.aircraftSubtype<0)errors.push(`Missing required column: ${csvAircraftIdentityHeaders[1]}.`)}
 if(errors.length)return{schedules:[],errors:[...errors,...(expected?["Download a new template for this aircraft."]:[])],source};
 type Parsed={line:number;configurationCode:string|null;name:string;specificGravity:number;step:number;tankCodes:string[];basis:FuelScheduleQuantityBasis;amount:number};const parsed:Parsed[]=[];
 raw.slice(1).forEach((values,rowIndex)=>{const line=rowIndex+2,at=(index:number)=>index<0?undefined:values[index],rowSource={typeCode:normaliseCsvAircraftIdentity(at(columns.aircraftType)),subtype:normaliseCsvAircraftIdentity(at(columns.aircraftSubtype))},rawConfiguration=String(at(columns.configurationCode)??"").trim().toUpperCase(),configurationCode=!rawConfiguration||rawConfiguration==="ALL"?null:rawConfiguration,name=String(at(columns.name)??"").trim(),specificGravity=numeric(at(columns.specificGravity)),step=numeric(at(columns.step)),tankCodes=String(at(columns.tankCodes)??"").split(/[+;|/]/).map(code=>code.trim().toUpperCase()).filter(Boolean),volume=numeric(at(columns.volume)),weight=numeric(at(columns.weight));
  if(expected){const identityError=csvAircraftIdentityError(rowSource,expected,line);if(identityError)errors.push(identityError);else if(source&&(source.typeCode!==rowSource.typeCode||source.subtype!==rowSource.subtype))errors.push(`Line ${line}: aircraft identity differs from earlier rows.`);else source=rowSource}
  const invalidConfiguration=Boolean(configurationCode&&!normalisedConfigurations.has(configurationCode));if(invalidConfiguration&&!reportedInvalidConfigurations.has(configurationCode!)){errors.push(normalisedConfigurations.size===0?`No fitted fuel configurations are defined for this aircraft. Use ALL or leave Configuration Code blank instead of ${configurationCode}.`:`Configuration Code ${configurationCode} is not defined on E1.2 for this aircraft. Use ALL for a schedule common to every fitted configuration.`);reportedInvalidConfigurations.add(configurationCode!)}
  if(!name||name.length>100)errors.push(`Line ${line}: Schedule Name is required and may contain up to 100 characters.`);
  if(specificGravity===null||!Number.isFinite(specificGravity)||specificGravity<=0)errors.push(`Line ${line}: Specific Gravity must be greater than zero.`);
  if(step===null||!Number.isSafeInteger(step)||step<=0)errors.push(`Line ${line}: Step must be a positive whole number.`);
  if(tankCodes.length===0)errors.push(`Line ${line}: enter at least one Tank Code.`);else for(const code of tankCodes)if(!/^[A-Z0-9]{1,6}$/.test(code))errors.push(`Line ${line}: Tank Code ${code} must contain one to six letters or numbers.`);
  const hasVolume=volume!==null,hasWeight=weight!==null;if(hasVolume===hasWeight)errors.push(`Line ${line}: complete either Volume Amount or Weight Amount, but not both.`);
  const amount=hasVolume?volume:weight,basis:FuelScheduleQuantityBasis=hasVolume?"VOLUME":"WEIGHT";if(amount===null||!Number.isFinite(amount)||amount<=0)errors.push(`Line ${line}: the selected Amount must be greater than zero.`);
  if(!invalidConfiguration&&!errors.some(error=>error.startsWith(`Line ${line}:`)))parsed.push({line,configurationCode,name,specificGravity:specificGravity!,step:step!,tankCodes:[...new Set(tankCodes)],basis,amount:amount!})
 });
 const groups=new Map<string,Parsed[]>();for(const row of parsed){const key=`${row.configurationCode??"ALL"}|${row.name}|${row.specificGravity}`;groups.set(key,[...(groups.get(key)??[]),row])}
 const schedules:FuelLoadingSchedule[]=[];for(const rows of groups.values()){const first=rows[0],bases=new Set(rows.map(row=>row.basis)),steps=rows.map(row=>row.step).sort((a,b)=>a-b);if(bases.size>1)errors.push(`${first.name}: use Volume Amount or Weight Amount consistently for every step.`);if(new Set(steps).size!==steps.length)errors.push(`${first.name}: each Step number may appear only once.`);if(steps.some((step,index)=>step!==index+1))errors.push(`${first.name}: Steps must run consecutively from 1.`);schedules.push({...(first.configurationCode?{configurationCode:first.configurationCode}:{}),name:first.name,specificGravity:first.specificGravity,quantityBasis:first.basis,steps:rows.sort((a,b)=>a.step-b.step).map(row=>({amount:row.amount,tankCodes:row.tankCodes}))})}
 return{schedules,errors,source};
}

export function mergeScheduleImport(current:FuelLoadingSchedule[],imported:FuelLoadingSchedule[]){const keys=new Set(imported.map(schedule=>`${schedule.configurationCode??"ALL"}|${schedule.name.toUpperCase()}|${schedule.specificGravity}`));return[...current.filter(schedule=>!keys.has(`${schedule.configurationCode??"ALL"}|${schedule.name.toUpperCase()}|${schedule.specificGravity}`)),...imported]}
