export type H1CodeOption={code:string;description:string;prohibited:boolean};
export type H1HoldOption={id:string;name:string;holdType:"BULK"|"ULD"};
export type H1LocationOption={holdId:string;id:string;locationType:"COMPARTMENT"|"POSITION"};
export type H1ExceptionRow={code:string;incompatibleWith:string;remarks:string|null};
export type H1SpecialLoadRow={holdId:string;code:string;locationRef:string|null;maximumQuantity:number|null;remarks:string|null};
export type H1MasterIncompatibility={code:string;incompatibleWith:string};
export const H1_BULK_ZERO_REMARK="Not Permitted This Hold";
export type AircraftH1Snapshot={canView:boolean;canEdit:boolean;revision:string;typeCode:string;subtype:string;applicabilityReviewed:boolean;dgrActive:boolean;iataActive:boolean;specialLoadsActive:boolean;isUldAircraft:boolean;dgrRows:H1ExceptionRow[];iataRows:H1ExceptionRow[];specialLoadRows:H1SpecialLoadRow[];codeOptions:H1CodeOption[];holdOptions:H1HoldOption[];locationOptions:H1LocationOption[];masterIncompatibilities:H1MasterIncompatibility[];codeClasses:Record<string,string[]>};
export class AircraftH1Invalid extends Error{} export class AircraftH1Denied extends Error{} export class AircraftH1Conflict extends Error{}
const optional=(v:unknown,label:string)=>{const s=String(v??"").trim();if(s.length>500)throw new AircraftH1Invalid(`${label} must not exceed 500 characters.`);return s||null};
export function validateH1Applicability(v:unknown){const x=v as Record<string,unknown>;if(typeof x?.dgrActive!=="boolean"||typeof x?.iataActive!=="boolean"||typeof x?.specialLoadsActive!=="boolean")throw new AircraftH1Invalid("Select the H1 section applicability.");return{dgrActive:x.dgrActive,iataActive:x.iataActive,specialLoadsActive:x.specialLoadsActive}}
export function validateH1Exceptions(v:unknown,codes:H1CodeOption[]){if(!Array.isArray(v)||v.length<1)throw new AircraftH1Invalid("Add at least one complete exception row.");const available=new Set(codes.map(x=>x.code)),seen=new Set<string>();return v.map((x,i)=>{const r=x as Partial<H1ExceptionRow>,code=String(r.code??"").trim().toUpperCase(),other=String(r.incompatibleWith??"").trim().toUpperCase();if(!available.has(code)||!available.has(other))throw new AircraftH1Invalid(`Select valid Special Load Codes at row ${i+1}.`);if(code===other)throw new AircraftH1Invalid(`The two codes at row ${i+1} must be different.`);const key=[code,other].sort().join("|");if(seen.has(key))throw new AircraftH1Invalid(`The exception at row ${i+1} is duplicated.`);seen.add(key);return{code,incompatibleWith:other,remarks:optional(r.remarks,`Remarks at row ${i+1}`)}})}
export function validateH1SpecialLoads(v:unknown,s:AircraftH1Snapshot){if(!Array.isArray(v)||v.length<1)throw new AircraftH1Invalid("Add at least one complete Special Loads row.");const holds=new Map(s.holdOptions.map(x=>[x.id,x.holdType])),codes=new Set(s.codeOptions.map(x=>x.code)),locations=new Map(s.locationOptions.map(x=>[`${x.holdId}|${x.id}`,x.locationType])),seen=new Set<string>();return v.map((x,i)=>{const r=x as Partial<H1SpecialLoadRow>,holdId=String(r.holdId??"").trim().toUpperCase(),code=String(r.code??"").trim().toUpperCase(),locationRef=String(r.locationRef??"").trim().toUpperCase()||null,n=typeof r.maximumQuantity==="number"?r.maximumQuantity:Number(r.maximumQuantity),holdType=holds.get(holdId);if(!holdType)throw new AircraftH1Invalid(`Select a D2 hold at row ${i+1}.`);if(!codes.has(code))throw new AircraftH1Invalid(`Select a valid Special Load Code at row ${i+1}.`);if(locationRef){const locationType=locations.get(`${holdId}|${locationRef}`),expected=holdType==="BULK"?"COMPARTMENT":"POSITION";if(locationType!==expected)throw new AircraftH1Invalid(`Select a ${expected==="COMPARTMENT"?"compartment":"position"} belonging to Hold ${holdId} at row ${i+1}.`)}if(!Number.isSafeInteger(n)||n<0)throw new AircraftH1Invalid(`Enter a whole Maximum Quantity of zero or more at row ${i+1}.`);const key=`${holdId}|${code}|${locationRef??""}`;if(seen.has(key))throw new AircraftH1Invalid(`The Special Loads row ${i+1} is duplicated.`);seen.add(key);const suppliedRemark=optional(r.remarks,`Remarks at row ${i+1}`),remarks=holdType==="BULK"?(n===0?H1_BULK_ZERO_REMARK:suppliedRemark===H1_BULK_ZERO_REMARK?null:suppliedRemark):suppliedRemark;return{holdId,code,locationRef,maximumQuantity:n,remarks}})}
