export class FlightScheduleInvalid extends Error{}
export class FlightScheduleDenied extends Error{}
export class FlightScheduleConflict extends Error{}
export function firstAircraftConfiguration(rows:Array<{typeCode:string;subtype:string;code:string}>,typeCode:string,subtype:string){return rows.find(item=>item.typeCode===typeCode&&item.subtype===subtype)?.code??null}
export function scheduleAircraftConfiguration(value:string|null){const code=(value??"").trim().toUpperCase();return !code||code==="XX"?null:code}
export function scheduleAircraftSubtype(leg:{aircraftSubtype:string|null;parameters:{aircraftSubtype:string}|null},fallback:string=""){return leg.parameters?.aircraftSubtype??leg.aircraftSubtype??fallback}
export function scheduleAircraftCarriesPassengers(rows:Array<{typeCode:string;subtype:string;operatingRole:"PASSENGER"|"FREIGHTER"|"COMBI"}>,typeCode:string|null,subtype:string|null){return rows.find(item=>item.typeCode===typeCode&&item.subtype===subtype)?.operatingRole!=="FREIGHTER"}
export function scheduleCodesForSubtype(rows:Array<{typeCode:string;subtype:string;code:string}>,typeCode:string|null,subtype:string){return[...new Set(rows.filter(item=>item.typeCode===typeCode&&item.subtype===subtype).map(item=>item.code.trim()).filter(Boolean))]}
export function scheduleOnlyCode(rows:Array<{typeCode:string;subtype:string;code:string}>,typeCode:string|null,subtype:string){const codes=scheduleCodesForSubtype(rows,typeCode,subtype);return codes.length===1?codes[0]:null}

type ItineraryLeg={scheduleImportId:string;scheduleName:string;scheduleLegId:string;flightNumber:string;operationalSuffix:string;itineraryVariation:string;legSequence:number;serviceType:string;periodStart:string;periodEnd:string;operatingDays:string;departureAirport:string;arrivalAirport:string;aircraftType:string|null;aircraftSubtype:string|null;aircraftConfiguration:string|null;parameters:unknown|null};
export type PublishedScheduleItinerary<T extends ItineraryLeg=ItineraryLeg>={key:string;scheduleName:string;flightNumber:string;operationalSuffix:string;legs:T[];route:string;sectorCount:number};

function itineraryKey(leg:ItineraryLeg){return[leg.scheduleImportId,leg.flightNumber,leg.operationalSuffix,leg.itineraryVariation,leg.serviceType].join("|")}
function itineraryRoute(legs:ItineraryLeg[]){const sequence=new Map<number,ItineraryLeg>();for(const leg of legs)if(!sequence.has(leg.legSequence))sequence.set(leg.legSequence,leg);const ordered=[...sequence.values()].sort((a,b)=>a.legSequence-b.legSequence);if(!ordered.length)return"";const airports=[ordered[0].departureAirport];for(const leg of ordered){if(airports.at(-1)!==leg.departureAirport)airports.push(leg.departureAirport);airports.push(leg.arrivalAirport)}return airports.join(" → ")}
export function publishedScheduleItineraries<T extends ItineraryLeg>(legs:T[]){const groups=new Map<string,T[]>();for(const leg of legs){const key=itineraryKey(leg),group=groups.get(key);if(group)group.push(leg);else groups.set(key,[leg])}return[...groups.entries()].map(([key,group])=>{const ordered=[...group].sort((a,b)=>a.periodStart.localeCompare(b.periodStart)||a.operatingDays.localeCompare(b.operatingDays)||a.legSequence-b.legSequence||a.scheduleLegId.localeCompare(b.scheduleLegId));return{key,scheduleName:ordered[0].scheduleName,flightNumber:ordered[0].flightNumber,operationalSuffix:ordered[0].operationalSuffix,legs:ordered,route:itineraryRoute(ordered),sectorCount:new Set(ordered.map(leg=>leg.legSequence)).size}})}
export function filterPublishedScheduleItineraries<T extends ItineraryLeg>(itineraries:PublishedScheduleItinerary<T>[],iata:string,query:string,readiness:"ALL"|"READY"|"INCOMPLETE"){const needle=query.trim().toUpperCase();return itineraries.filter(itinerary=>{const searchable=`${iata}${itinerary.flightNumber}${itinerary.operationalSuffix} ${itinerary.route} ${itinerary.legs.map(leg=>`${leg.departureAirport} ${leg.arrivalAirport} ${leg.aircraftType??""}`).join(" ")}`.toUpperCase(),matchesSearch=!needle||searchable.includes(needle),matchesReadiness=readiness==="ALL"||itinerary.legs.some(leg=>(readiness==="READY")===Boolean(leg.parameters));return matchesSearch&&matchesReadiness})}
