import{effectiveAircraftD2Snapshot,type AircraftD2Snapshot}from"@/domain/aircraft-d2";
import{effectiveAircraftD3Snapshot,type AircraftD3Snapshot}from"@/domain/aircraft-d3";
import type{AircraftD4Snapshot}from"@/domain/aircraft-d4";
import type{AircraftC7Snapshot}from"@/domain/aircraft-c7";
import type{AircraftE12Snapshot}from"@/domain/aircraft-e12";
import type{AircraftE2Snapshot}from"@/domain/aircraft-e2";
import type{AircraftH1Snapshot}from"@/domain/aircraft-h1";
import{balanceArmFromIndexPerWeightUnit}from"@/domain/index-per-weight-unit";
import type{OperationalFlightDetail}from"@/ports/operational-flight-repository";
import{LoadPlanningProblemInvalid,validateLoadPlanningProblem,type LoadPlanningProblem,type SolverIncompatibility,type SolverPosition}from"@/domain/load-planning-solver";

export type FreightAutoloadContext={problem:LoadPlanningProblem;warnings:string[];unloadingAccessibilityComplete:boolean};

const scaled=(value:number)=>Math.round(value*100_000);
export const freightAutoloadTimeLimitSeconds=(loadCount:number)=>Math.max(2,Math.min(10,Math.ceil(loadCount/10)));
const interpolate=(points:Array<{weight:number;indexValue:number|null}>,weight:number)=>{const rows=points.filter((point):point is{weight:number;indexValue:number}=>point.indexValue!==null).sort((a,b)=>a.weight-b.weight);if(!rows.length)return null;if(weight<=rows[0].weight)return rows[0].indexValue;if(weight>=rows.at(-1)!.weight)return rows.at(-1)!.indexValue;const upper=rows.find(point=>point.weight>=weight)!,lower=rows[rows.indexOf(upper)-1],fraction=(weight-lower.weight)/(upper.weight-lower.weight);return lower.indexValue+(upper.indexValue-lower.indexValue)*fraction};
const standardDgrPairs:[[string,string,string],[string,string,string],[string,string,string]]=[
 ["DGR:3","DGR:5.1","IATA DGR Table 9.3.A: Classes 3 and 5.1 require segregation"],
 ["DGR:4.2","DGR:5.1","IATA DGR Table 9.3.A: Classes 4.2 and 5.1 require segregation"],
 ["DGR:4.3","DGR:8","IATA DGR Table 9.3.A: Classes 4.3 and 8 require segregation"],
];
const otherCargoPairs:[[string,string,string],[string,string,string],[string,string,string],[string,string,string],[string,string,string]]=[
 ["CODE:AVI","CODE:RCL","IATA DGR: live animals require segregation from cryogenic liquids"],
 ["CODE:AVI","CODE:RRW","IATA DGR: live animals require segregation from radioactive material"],
 ["CODE:AVI","CODE:RRY","IATA DGR: live animals require segregation from radioactive material"],
 ["CODE:AVI","CODE:ICE","IATA DGR: live animals require segregation from dry ice"],
 ["CODE:FIL","CODE:RRY","IATA DGR: undeveloped film requires segregation from Category II/III radioactive material"],
];
const class9WithoutConditionalBatteryRule=new Set(["ICE","RCL","RLI","RLM","RMD"]);
const unique=(values:string[])=>[...new Set(values.map(value=>value.trim().toUpperCase()).filter(Boolean))];
const pairKey=(left:string,right:string)=>[left,right].sort().join("|");
const buildPairs=(h1:AircraftH1Snapshot)=>{const pairs:SolverIncompatibility[]=[],seen=new Set<string>(),add=(left:string,right:string,reason:string)=>{const key=pairKey(left,right);if(left===right||seen.has(key))return;seen.add(key);pairs.push({left,right,reason})};for(const[left,right,reason]of standardDgrPairs)add(left,right,reason);for(const[left,right,reason]of otherCargoPairs)add(left,right,reason);for(const row of h1.masterIncompatibilities)add(`CODE:${row.code}`,`CODE:${row.incompatibleWith}`,"MASTER Special Load incompatibility");if(h1.dgrActive)for(const row of h1.dgrRows)add(`CODE:${row.code}`,`CODE:${row.incompatibleWith}`,row.remarks||"Aircraft H1 DGR incompatibility");if(h1.iataActive)for(const row of h1.iataRows)add(`CODE:${row.code}`,`CODE:${row.incompatibleWith}`,row.remarks||"Aircraft H1 special-load incompatibility");return pairs};

export function buildFreightAutoloadProblem(input:{flight:OperationalFlightDetail;d2:AircraftD2Snapshot;d3:AircraftD3Snapshot;d4:AircraftD4Snapshot;c7:AircraftC7Snapshot;e12:AircraftE12Snapshot;e2:AircraftE2Snapshot;h1:AircraftH1Snapshot;locks?:Record<string,string>}):FreightAutoloadContext{
 const{flight,d4,c7,e12,e2,h1}=input,warnings:string[]=[];
 if(flight.freightAcceptance.status!=="RELEASED"&&flight.freightAcceptance.status!=="ACCEPTED")throw new LoadPlanningProblemInvalid("Release the freight statement before running AUTOLOAD.");
 const registration=flight.freightPlanning.registration?e12.registrations.find(row=>row.registration===flight.freightPlanning.registration):null,fuelConfiguration=registration?.fuelConfigurationCode??null,d2=effectiveAircraftD2Snapshot(input.d2,fuelConfiguration),d3=effectiveAircraftD3Snapshot(input.d3,fuelConfiguration),remainingLegs=flight.itinerary.legs.filter(leg=>leg.legSequence>=flight.legSequence),unloadOrder=new Map(remainingLegs.map((leg,index)=>[leg.arrivalAirport,index]));
 const doors=new Map(d4.doors.filter(door=>door.forwardArm!==null&&door.aftArm!==null).map(door=>[door.holdId,(door.forwardArm!+door.aftArm!)/2])),holdDecks=new Map(d2.rows.map(hold=>[hold.id??hold.name,hold.deckCode]));
 const rawPositions:Array<Omit<SolverPosition,"balanceArm">&{arm:number|null}>=[];
 for(const config of d3.configurations)for(const row of config.rows){if(row.rowType!=="POSITION"||row.maxWeight===null||row.indexPerWeightUnit===null||!row.uldCode)continue;const arm=row.balanceCentroid,distance=arm===null||doors.get(config.holdId)===undefined?0:Math.abs(arm-doors.get(config.holdId)!);rawPositions.push({id:`ULD:${config.holdId}:${config.code}:${row.positionId}:${row.uldCode}`,description:`${config.holdId} · ${row.positionId} · ${row.uldCode}`,loadType:"ULD",acceptedUldCodes:[row.uldCode],maximumWeightKg:Math.floor(row.maxWeight),maximumVolumeLitres:null,occupiedBayIds:row.occupiedBayIds.map(bay=>`${config.holdId}:${bay}`),handlingRank:Math.round(distance*100),simplicityGroup:`ULD:${config.holdId}:${row.compartmentId??""}`,indexPerKgScaled:scaled(row.indexPerWeightUnit),holdId:config.holdId,locationRef:row.positionId,segregationGroup:`ULD:${config.holdId}:${row.compartmentId??"UNSPECIFIED"}`,deckCode:holdDecks.get(config.holdId)??config.holdId,arm});}
 for(const hold of d2.rows.filter(row=>row.holdType==="BLK")){const holdId=hold.id??hold.name,areas=hold.compartments.flatMap(compartment=>compartment.areas.map(area=>({compartment,area})));if(areas.length){for(const{compartment,area}of areas){if(area.maxWeight===null||area.indexPerWeightUnit===null)continue;const arm=d2.balanceFormula?balanceArmFromIndexPerWeightUnit(area.indexPerWeightUnit,d2.balanceFormula):hold.balanceCentroid,distance=arm===null||doors.get(holdId)===undefined?0:Math.abs(arm-doors.get(holdId)!);rawPositions.push({id:`BULK:${hold.deckCode}:${hold.name}:${compartment.id}:${area.id}`,description:`${hold.name} · ${compartment.id} · ${area.id}`,loadType:"BULK",acceptedUldCodes:[],maximumWeightKg:Math.floor(area.maxWeight),maximumVolumeLitres:area.maxVolume==null||area.maxVolume<=0?null:Math.max(1,Math.round(area.maxVolume*1000)),occupiedBayIds:[`BULK:${hold.deckCode}:${hold.name}:${compartment.id}:${area.id}`],handlingRank:Math.round(distance*100),simplicityGroup:`BULK:${hold.deckCode}:${hold.name}:${compartment.id}`,indexPerKgScaled:scaled(area.indexPerWeightUnit),holdId,locationRef:compartment.id,segregationGroup:`BULK:${holdId}:${compartment.id}`,deckCode:hold.deckCode,arm})}}else if(hold.maxWeight!==null&&hold.indexPerWeightUnit!==null){const arm=hold.balanceCentroid,distance=arm===null||doors.get(holdId)===undefined?0:Math.abs(arm-doors.get(holdId)!);rawPositions.push({id:`BULK:${hold.deckCode}:${hold.name}`,description:`${hold.name} · complete Bulk hold`,loadType:"BULK",acceptedUldCodes:[],maximumWeightKg:Math.floor(hold.maxWeight),maximumVolumeLitres:hold.maxVolume==null||hold.maxVolume<=0?null:Math.max(1,Math.round(hold.maxVolume*1000)),occupiedBayIds:[`BULK:${hold.deckCode}:${hold.name}`],handlingRank:Math.round(distance*100),simplicityGroup:`BULK:${hold.deckCode}:${hold.name}`,indexPerKgScaled:scaled(hold.indexPerWeightUnit),holdId,locationRef:null,segregationGroup:`BULK:${holdId}`,deckCode:hold.deckCode,arm})}}
 const positionedUldHolds=[...new Set(rawPositions.filter(position=>position.loadType==="ULD").map(position=>position.holdId))],missingUldDoorHolds=positionedUldHolds.filter(holdId=>!doors.has(holdId));
 for(const holdId of missingUldDoorHolds){const hold=d2.rows.find(row=>(row.id??row.name)===holdId),deck=hold?.deckCode==="MDECK"?"Main Deck":hold?.deckCode==="LOWER"?"Lower Deck":hold?.deckCode,label=hold?`${deck} hold ${hold.name}`:holdId;warnings.push(`${label} has no configured cargo door in D4. AUTOLOAD cannot optimise unloading accessibility on that deck; its placement is preliminary until the door is recorded.`)}
 const loads=flight.freightAcceptance.items.map((item,index)=>{const identity=item.uldId??`Bulk for ${item.unloadingStation}`,specialLoadCodes=unique([...item.specialHandlingCodes,...item.includedLoads.map(load=>load.code)]),dangerousCodes=unique(item.includedLoads.filter(load=>load.dangerousGoods).map(load=>load.code)),dangerousGoodsClasses=unique(dangerousCodes.flatMap(code=>h1.codeClasses[code]??[]));if(item.dangerousGoods&&!dangerousCodes.length)throw new LoadPlanningProblemInvalid(`${identity} is marked Dangerous Goods without a specific included-load code. Add the applicable IATA code before AUTOLOAD.`);const classOne=dangerousGoodsClasses.find(value=>value.startsWith("1")&&value!=="1.4S");if(classOne)throw new LoadPlanningProblemInvalid(`${identity} contains Class ${classOne}. Record its explosive compatibility group before AUTOLOAD.`);const conditionalClassNine=dangerousCodes.find(code=>(h1.codeClasses[code]??[]).includes("9")&&!class9WithoutConditionalBatteryRule.has(code));if(conditionalClassNine)throw new LoadPlanningProblemInvalid(`${identity} contains ${conditionalClassNine}. Record the UN number and packing instruction before AUTOLOAD so the conditional Class 9 segregation rule can be applied.`);if(dangerousCodes.includes("RMD"))warnings.push(`${identity} contains RMD. AUTOLOAD may produce a preliminary plan, but final dangerous-goods validation requires the complete NOTOC details.`);return{id:item.lineId,description:`${item.loadType==="ULD"?item.uldId:"BULK"} · unload ${item.unloadingStation}`,loadType:item.loadType,weightKg:Math.round(item.grossWeight),volumeLitres:item.loadType==="BULK"&&item.volume!=null?Math.max(0,Math.round(item.volume*1000)):null,uldCode:item.loadType==="ULD"?item.uldId!.slice(0,3):null,unloadOrder:unloadOrder.get(item.unloadingStation)??remainingLegs.length+index,lockedPositionId:input.locks?.[item.lineId]??null,specialLoadCodes,dangerousGoodsClasses}});
 const startIndex=registration?.index??e12.standardFleetIndex,crewIndex=e2.crewRows.find(row=>row.crewCode===flight.freightPlanning.crewCode)?.indexAdjustment??0,pantryIndex=e2.pantryRows.find(row=>row.pantryCode===flight.freightPlanning.pantryCode)?.indexAdjustment??0,zfw=(flight.freightPlanning.planningAircraftWeight??0)+flight.freightAcceptance.totalWeight,idealIndex=c7.values.idealTrim.enabled?interpolate(c7.values.idealTrim.points,zfw):null,idealTrimIndexScaled=idealIndex!==null&&startIndex!==null?scaled(idealIndex-startIndex-crewIndex-pantryIndex):null;
 if(idealTrimIndexScaled===null)warnings.push("Ideal Trim cannot be scored until C7 and the applicable aircraft starting index are available.");
 const positions=rawPositions.map(({arm,...position})=>({...position,balanceArm:arm})),incompatiblePairs=buildPairs(h1),specialLoadLimits=h1.specialLoadsActive?h1.specialLoadRows.map(row=>({code:row.code,holdId:row.holdId,locationRef:row.locationRef,maximumQuantity:row.maximumQuantity??0})):[],problem=validateLoadPlanningProblem({version:1,timeLimitSeconds:freightAutoloadTimeLimitSeconds(loads.length),idealTrimIndexScaled,loads,positions,incompatiblePairs,specialLoadLimits});
 if(incompatiblePairs.length)warnings.push("AUTOLOAD applied master, IATA DGR and aircraft H1 incompatibility rules. Incompatible loads are kept in separate configured cargo compartments.");
 return{problem,warnings,unloadingAccessibilityComplete:missingUldDoorHolds.length===0};
}
