import{effectiveAircraftD2Snapshot,type AircraftD2Snapshot}from"@/domain/aircraft-d2";
import{effectiveAircraftD3Snapshot,type AircraftD3Snapshot}from"@/domain/aircraft-d3";
import type{AircraftD4Snapshot}from"@/domain/aircraft-d4";
import type{AircraftC7Snapshot}from"@/domain/aircraft-c7";
import type{AircraftE12Snapshot}from"@/domain/aircraft-e12";
import type{AircraftE2Snapshot}from"@/domain/aircraft-e2";
import{balanceArmFromIndexPerWeightUnit}from"@/domain/index-per-weight-unit";
import type{OperationalFlightDetail}from"@/ports/operational-flight-repository";
import{LoadPlanningProblemInvalid,validateLoadPlanningProblem,type LoadPlanningProblem,type SolverPosition}from"@/domain/load-planning-solver";

export type FreightAutoloadContext={problem:LoadPlanningProblem;warnings:string[]};

const scaled=(value:number)=>Math.round(value*100_000);
const interpolate=(points:Array<{weight:number;indexValue:number|null}>,weight:number)=>{const rows=points.filter((point):point is{weight:number;indexValue:number}=>point.indexValue!==null).sort((a,b)=>a.weight-b.weight);if(!rows.length)return null;if(weight<=rows[0].weight)return rows[0].indexValue;if(weight>=rows.at(-1)!.weight)return rows.at(-1)!.indexValue;const upper=rows.find(point=>point.weight>=weight)!,lower=rows[rows.indexOf(upper)-1],fraction=(weight-lower.weight)/(upper.weight-lower.weight);return lower.indexValue+(upper.indexValue-lower.indexValue)*fraction};

export function buildFreightAutoloadProblem(input:{flight:OperationalFlightDetail;d2:AircraftD2Snapshot;d3:AircraftD3Snapshot;d4:AircraftD4Snapshot;c7:AircraftC7Snapshot;e12:AircraftE12Snapshot;e2:AircraftE2Snapshot;locks?:Record<string,string>}):FreightAutoloadContext{
 const{flight,d4,c7,e12,e2}=input,warnings:string[]=[];
 if(flight.freightAcceptance.status!=="RELEASED"&&flight.freightAcceptance.status!=="ACCEPTED")throw new LoadPlanningProblemInvalid("Release the freight statement before running AUTOLOAD.");
 const registration=flight.freightPlanning.registration?e12.registrations.find(row=>row.registration===flight.freightPlanning.registration):null,fuelConfiguration=registration?.fuelConfigurationCode??null,d2=effectiveAircraftD2Snapshot(input.d2,fuelConfiguration),d3=effectiveAircraftD3Snapshot(input.d3,fuelConfiguration),remainingLegs=flight.itinerary.legs.filter(leg=>leg.legSequence>=flight.legSequence),unloadOrder=new Map(remainingLegs.map((leg,index)=>[leg.arrivalAirport,index]));
 const doors=new Map(d4.doors.filter(door=>door.forwardArm!==null&&door.aftArm!==null).map(door=>[door.holdId,(door.forwardArm!+door.aftArm!)/2]));
 const rawPositions:Array<SolverPosition&{arm:number|null}>=[];
 for(const config of d3.configurations)for(const row of config.rows){if(row.rowType!=="POSITION"||row.maxWeight===null||row.indexPerWeightUnit===null||!row.uldCode)continue;const arm=row.balanceCentroid,distance=arm===null||doors.get(config.holdId)===undefined?0:Math.abs(arm-doors.get(config.holdId)!);rawPositions.push({id:`ULD:${config.holdId}:${config.code}:${row.positionId}:${row.uldCode}`,description:`${config.holdId} · ${row.positionId} · ${row.uldCode}`,loadType:"ULD",acceptedUldCodes:[row.uldCode],maximumWeightKg:Math.floor(row.maxWeight),occupiedBayIds:row.occupiedBayIds.map(bay=>`${config.holdId}:${bay}`),handlingRank:Math.round(distance*100),simplicityGroup:`ULD:${config.holdId}:${row.compartmentId??""}`,indexPerKgScaled:scaled(row.indexPerWeightUnit),arm});}
 for(const hold of d2.rows.filter(row=>row.holdType==="BLK")){const areas=hold.compartments.flatMap(compartment=>compartment.areas.map(area=>({compartment,area})));if(areas.length){for(const{compartment,area}of areas){if(area.maxWeight===null||area.indexPerWeightUnit===null)continue;const arm=d2.balanceFormula?balanceArmFromIndexPerWeightUnit(area.indexPerWeightUnit,d2.balanceFormula):hold.balanceCentroid,distance=arm===null||doors.get(hold.id??hold.name)===undefined?0:Math.abs(arm-doors.get(hold.id??hold.name)!);rawPositions.push({id:`BULK:${hold.deckCode}:${hold.name}:${compartment.id}:${area.id}`,description:`${hold.name} · ${compartment.id} · ${area.id}`,loadType:"BULK",acceptedUldCodes:[],maximumWeightKg:Math.floor(area.maxWeight),occupiedBayIds:[`BULK:${hold.deckCode}:${hold.name}:${compartment.id}:${area.id}`],handlingRank:Math.round(distance*100),simplicityGroup:`BULK:${hold.deckCode}:${hold.name}:${compartment.id}`,indexPerKgScaled:scaled(area.indexPerWeightUnit),arm})}}else if(hold.maxWeight!==null&&hold.indexPerWeightUnit!==null){const arm=hold.balanceCentroid,distance=arm===null||doors.get(hold.id??hold.name)===undefined?0:Math.abs(arm-doors.get(hold.id??hold.name)!);rawPositions.push({id:`BULK:${hold.deckCode}:${hold.name}`,description:`${hold.name} · complete Bulk hold`,loadType:"BULK",acceptedUldCodes:[],maximumWeightKg:Math.floor(hold.maxWeight),occupiedBayIds:[`BULK:${hold.deckCode}:${hold.name}`],handlingRank:Math.round(distance*100),simplicityGroup:`BULK:${hold.deckCode}:${hold.name}`,indexPerKgScaled:scaled(hold.indexPerWeightUnit),arm})}}
 if(rawPositions.some(position=>position.handlingRank===0)&&!d4.doors.some(door=>door.forwardArm!==null&&door.aftArm!==null))warnings.push("D4 door positions are unavailable; AUTOLOAD cannot yet prefer door-accessible positions for unloading sequence.");
 const loads=flight.freightAcceptance.items.map((item,index)=>({id:item.lineId,description:`${item.loadType==="ULD"?item.uldId:"BULK"} · unload ${item.unloadingStation}`,loadType:item.loadType,weightKg:Math.round(item.grossWeight),uldCode:item.loadType==="ULD"?item.uldId!.slice(0,3):null,unloadOrder:unloadOrder.get(item.unloadingStation)??remainingLegs.length+index,lockedPositionId:input.locks?.[item.lineId]??null}));
 const startIndex=registration?.index??e12.standardFleetIndex,crewIndex=e2.crewRows.find(row=>row.crewCode===flight.freightPlanning.crewCode)?.indexAdjustment??0,pantryIndex=e2.pantryRows.find(row=>row.pantryCode===flight.freightPlanning.pantryCode)?.indexAdjustment??0,zfw=(flight.freightPlanning.planningAircraftWeight??0)+flight.freightAcceptance.totalWeight,idealIndex=c7.values.idealTrim.enabled?interpolate(c7.values.idealTrim.points,zfw):null,idealTrimIndexScaled=idealIndex!==null&&startIndex!==null?scaled(idealIndex-startIndex-crewIndex-pantryIndex):null;
 if(idealTrimIndexScaled===null)warnings.push("Ideal Trim cannot be scored until C7 and the applicable aircraft starting index are available.");
 const positions=rawPositions.map(({arm:_,...position})=>position),problem=validateLoadPlanningProblem({version:1,timeLimitSeconds:10,idealTrimIndexScaled,loads,positions});
 return{problem,warnings};
}
