import{OperationalFlightInvalid}from"@/domain/operational-flights";
export const freightCommodities=["CARGO","MAIL","SPECIAL_LOAD","DANGEROUS_GOODS"]as const;
export type FreightCommodity=(typeof freightCommodities)[number];
export type FreightLoadSource="MANUAL"|"CSV"|"AHM581";
export type FreightLoadItem={lineId:string;loadType:"ULD"|"BULK";uldId:string|null;grossWeight:number;netWeight:number|null;unloadingStation:string;destination:string;commodity:FreightCommodity;pieces:number|null;volume:number|null;specialHandlingCodes:string[];dangerousGoods:boolean;remarks:string|null;source:FreightLoadSource;sourceReference:string|null};
export type FreightAcceptanceInput={source:FreightLoadSource|"MIXED";sourceReference:string|null;rawMessage:string|null;items:FreightLoadItem[]};
export type FreightAcceptanceCsvContext={iata:string;flightNumber:string;serviceDate:string};
export type FreightAcceptanceParseResult={items:FreightLoadItem[];errors:string[];sourceReference:string|null};
const id=()=>globalThis.crypto?.randomUUID?.()??`line-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const clean=(value:unknown)=>String(value??"").trim();
const upper=(value:unknown)=>clean(value).toUpperCase();
const codeList=(value:unknown)=>[...new Set(upper(value).split(/[\s,;/]+/).filter(Boolean))];
const decimal=(value:unknown,label:string,required:boolean)=>{const text=clean(value);if(!text&&!required)return null;const parsed=Number(text);if(!Number.isFinite(parsed)||(required&&parsed<=0)||(!required&&parsed<0))throw new OperationalFlightInvalid(`${label} must be ${required?"greater than zero":"zero or greater"}.`);return parsed};
const whole=(value:unknown,label:string)=>{const text=clean(value);if(!text)return null;const parsed=Number(text);if(!Number.isSafeInteger(parsed)||parsed<0)throw new OperationalFlightInvalid(`${label} must be a whole number, zero or greater.`);return parsed};
export function validFreightLoadItem(value:unknown,index=0):FreightLoadItem{const row=value as Partial<FreightLoadItem>,loadType=upper(row?.loadType),uldId=upper(row?.uldId)||null,grossWeight=decimal(row?.grossWeight,`Row ${index+1} gross weight`,true)as number,netWeight=decimal(row?.netWeight,`Row ${index+1} net weight`,false),unloadingStation=upper(row?.unloadingStation),destination=upper(row?.destination),commodity=upper(row?.commodity)as FreightCommodity,pieces=whole(row?.pieces,`Row ${index+1} pieces`),volume=decimal(row?.volume,`Row ${index+1} volume`,false),dangerousGoods=Boolean(row?.dangerousGoods)||commodity==="DANGEROUS_GOODS",remarks=clean(row?.remarks)||null,source=upper(row?.source)as FreightLoadSource,sourceReference=clean(row?.sourceReference)||null,specialHandlingCodes=codeList(row?.specialHandlingCodes);if(loadType!=="ULD"&&loadType!=="BULK")throw new OperationalFlightInvalid(`Row ${index+1} must be ULD or Bulk.`);if(loadType==="ULD"&&!uldId)throw new OperationalFlightInvalid(`Row ${index+1} requires an IATA ULD ID.`);if(loadType==="ULD"&&!/^[A-Z]{3}[A-Z0-9]{4,8}$/.test(uldId??""))throw new OperationalFlightInvalid(`Row ${index+1} has an invalid IATA ULD ID.`);if(loadType==="BULK"&&uldId)throw new OperationalFlightInvalid(`Row ${index+1} Bulk load cannot include a ULD ID.`);if(!/^[A-Z]{3}$/.test(unloadingStation)||!/^[A-Z]{3}$/.test(destination))throw new OperationalFlightInvalid(`Row ${index+1} requires valid unloading and destination stations.`);if(!freightCommodities.includes(commodity))throw new OperationalFlightInvalid(`Row ${index+1} requires a valid commodity.`);if(netWeight!==null&&netWeight>grossWeight)throw new OperationalFlightInvalid(`Row ${index+1} net weight cannot exceed gross weight.`);if(loadType==="ULD"&&volume!==null)throw new OperationalFlightInvalid(`Row ${index+1} ULD load does not use volume.`);if(!["MANUAL","CSV","AHM581"].includes(source))throw new OperationalFlightInvalid(`Row ${index+1} has an invalid source.`);return{lineId:clean(row?.lineId)||id(),loadType,uldId,grossWeight,netWeight,unloadingStation,destination,commodity,pieces,volume,specialHandlingCodes,dangerousGoods,remarks,source,sourceReference}}
export function validFreightAcceptance(value:unknown):FreightAcceptanceInput{const row=value as Partial<FreightAcceptanceInput>,items=Array.isArray(row?.items)?row.items.map(validFreightLoadItem):[];if(!items.length)throw new OperationalFlightInvalid("Add at least one cargo, mail or special-load entry.");if(items.length>250)throw new OperationalFlightInvalid("Keep each acceptance statement within 250 entries.");const ulds=new Set<string>();for(const item of items)if(item.uldId){if(ulds.has(item.uldId))throw new OperationalFlightInvalid(`ULD ${item.uldId} appears more than once.`);ulds.add(item.uldId)}const source=upper(row.source)as FreightAcceptanceInput["source"];if(!["MANUAL","CSV","AHM581","MIXED"].includes(source))throw new OperationalFlightInvalid("Select a valid acceptance source.");const rawMessage=clean(row.rawMessage)||null;if(rawMessage&&rawMessage.length>100000)throw new OperationalFlightInvalid("The AHM581 message is too large.");return{source,sourceReference:clean(row.sourceReference)||null,rawMessage,items}}
function csvRows(text:string){const rows:string[][]=[];let row:string[]=[],field="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else if(c==='"')quoted=true;else if(c===','){row.push(field);field=""}else if(c==='\n'){row.push(field.replace(/\r$/,""));if(row.some(x=>x.trim()))rows.push(row);row=[];field=""}else field+=c}row.push(field.replace(/\r$/,""));if(row.some(x=>x.trim()))rows.push(row);return rows}
const normal=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"");
const csvHeaders=["Carrier IATA","Flight Number","Service Date","Load Type","ULD ID","Gross Weight","Net Weight","Station of Unloading","Destination","Commodity","Pieces","Volume m3","Special Handling Codes","Dangerous Goods","Remarks"];
export const freightAcceptanceCsvTemplate=(context:FreightAcceptanceCsvContext)=>`${csvHeaders.join(",")}\n${[context.iata,context.flightNumber,context.serviceDate,"ULD","AKE12345ZZ","","","","","CARGO","","","","N",""] .join(",")}\n${[context.iata,context.flightNumber,context.serviceDate,"BULK","","","","","","MAIL","","","","N",""] .join(",")}\n`;
export function parseFreightAcceptanceCsv(text:string,context:FreightAcceptanceCsvContext):FreightAcceptanceParseResult{const records=csvRows(text.replace(/^\uFEFF/,"")),errors:string[]=[],items:FreightLoadItem[]=[];if(!records.length)return{items,errors:["The CSV file is empty."],sourceReference:null};const actual=records[0].map(normal),missing=csvHeaders.filter(h=>!actual.includes(normal(h)));if(missing.length)return{items,errors:[`Missing columns: ${missing.join(", ")}. Download a new template.`],sourceReference:null};const col=(row:string[],name:string)=>row[actual.indexOf(normal(name))];records.slice(1).forEach((record,i)=>{const line=i+2;if(upper(col(record,"Carrier IATA"))!==context.iata.toUpperCase()||upper(col(record,"Flight Number"))!==context.flightNumber.toUpperCase()||clean(col(record,"Service Date"))!==context.serviceDate){errors.push(`Line ${line}: carrier, flight number and service date must match this flight.`);return}try{items.push(validFreightLoadItem({loadType:col(record,"Load Type"),uldId:col(record,"ULD ID"),grossWeight:col(record,"Gross Weight"),netWeight:col(record,"Net Weight"),unloadingStation:col(record,"Station of Unloading"),destination:col(record,"Destination"),commodity:col(record,"Commodity"),pieces:col(record,"Pieces"),volume:col(record,"Volume m3"),specialHandlingCodes:col(record,"Special Handling Codes"),dangerousGoods:/^(Y|YES|TRUE|1)$/i.test(clean(col(record,"Dangerous Goods"))),remarks:col(record,"Remarks"),source:"CSV",sourceReference:"CSV upload"},i))}catch(error){errors.push(error instanceof Error?`Line ${line}: ${error.message.replace(/^Row \d+ /,"")}`:`Line ${line}: invalid entry.`)}});return{items,errors,sourceReference:"CSV upload"}}
function commodityFrom(text:string):FreightCommodity{const value=upper(text);if(/\b(DG|DGR|DANGEROUS)\b/.test(value))return"DANGEROUS_GOODS";if(/\b(MAIL|M)\b/.test(value))return"MAIL";if(/\b(SPECIAL|AVI|HEA|HUM|VAL|PER|RRY|RRE)\b/.test(value))return"SPECIAL_LOAD";return"CARGO"}
export function parseAhm581(text:string,defaultDestination:string):FreightAcceptanceParseResult{const raw=text.replace(/\r/g,"").trim(),lines=raw.split("\n").map(x=>x.trim()).filter(Boolean),errors:string[]=[],items:FreightLoadItem[]=[];if(!/^UWS\b/i.test(lines[0]??""))errors.push("The message must start with UWS.");let bulk=false;const header=lines.find(line=>line!=="UWS"&&!line.startsWith("-")&&!/^BULK$/i.test(line))??null;for(const line of lines){if(/^BULK$/i.test(line)){bulk=true;continue}if(!line.startsWith("-"))continue;const fields=line.slice(1).split("/").map(x=>x.trim());if(!bulk&&/^[A-Z]{3}[A-Z0-9]{4,8}$/.test(upper(fields[0]))){const weightMatch=upper(fields[2]).match(/^(\d+(?:\.\d+)?)([A-Z]*)$/);if(fields.length<3||!/^[A-Z]{3}$/.test(upper(fields[1]))||!weightMatch){errors.push(`Could not read ULD line: ${line}`);continue}const notes=fields.slice(3).join(" "),commodity=commodityFrom(`${weightMatch[2]} ${notes}`);try{items.push(validFreightLoadItem({loadType:"ULD",uldId:fields[0],grossWeight:weightMatch[1],netWeight:null,unloadingStation:fields[1],destination:defaultDestination,commodity,pieces:null,volume:null,specialHandlingCodes:notes,dangerousGoods:commodity==="DANGEROUS_GOODS",remarks:notes||null,source:"AHM581",sourceReference:header},items.length))}catch(error){errors.push(error instanceof Error?error.message:`Could not read ULD line: ${line}`)}continue}if(bulk){const weightMatch=upper(fields[1]).match(/^(\d+(?:\.\d+)?)([A-Z]*)$/);if(fields.length<2||!/^[A-Z]{3}$/.test(upper(fields[0]))||!weightMatch){errors.push(`Could not read Bulk line: ${line}`);continue}const notes=fields.slice(2).join(" "),commodity=commodityFrom(`${weightMatch[2]} ${notes}`);try{items.push(validFreightLoadItem({loadType:"BULK",uldId:null,grossWeight:weightMatch[1],netWeight:null,unloadingStation:fields[0],destination:defaultDestination,commodity,pieces:null,volume:null,specialHandlingCodes:notes,dangerousGoods:commodity==="DANGEROUS_GOODS",remarks:notes||null,source:"AHM581",sourceReference:header},items.length))}catch(error){errors.push(error instanceof Error?error.message:`Could not read Bulk line: ${line}`)}}else errors.push(`Could not read ULD line: ${line}`)}if(!items.length&&!errors.length)errors.push("No ULD or Bulk weight lines were found.");return{items,errors,sourceReference:header}}
