import test from"node:test";import assert from"node:assert/strict";import{aircraftC2Statuses,aircraftC5ApplicabilityFromC2}from"../src/domain/aircraft-c2-status";import type{AircraftC2Snapshot}from"../src/domain/aircraft-c2";
const base:AircraftC2Snapshot={canView:true,canEdit:true,exists:true,revision:"1",typeCode:"319",subtype:"100",trimSaved:true,documents:[{code:"LS EDP FINAL",name:"EDP Loadsheet Final",ahmReference:"AHM518",suggested:true,required:true}],outputs:[{code:"DOW",name:"Dry Operating Weight",group:"Essential Weight/Index",displayOrder:1,validEdpPrelim:false,validAcarsPrelim:false,validEdpFinal:true,validAcarsFinal:false,selectedEdpPrelim:false,selectedAcarsPrelim:false,selectedEdpFinal:true,selectedAcarsFinal:false}],trimOptions:[{option:"SEAT ROW",suggested:true,selected:true,priority:1}],outputRemarks:[],passengerTrimRemarks:"",captainsInformation:"",preLmcLoadMessage:""};
test("C2 is skipped when no loadsheet document is selected",()=>{const value={...base,documents:base.documents.map(document=>({...document,required:false}))};assert.deepEqual(aircraftC2Statuses(value),{page:"skipped",documents:"skipped",balance:"skipped",trim:"skipped"});});
test("C2 is configured when active documents have balance and passenger trim selections",()=>{assert.deepEqual(aircraftC2Statuses(base),{page:"configured",documents:"configured",balance:"configured",trim:"configured"});});
test("C2 is incomplete when neither required output section has a selection",()=>{const value={...base,outputs:base.outputs.map(output=>({...output,selectedEdpFinal:false})),trimOptions:base.trimOptions.map(option=>({...option,selected:false,priority:null}))};assert.deepEqual(aircraftC2Statuses(value),{page:"incomplete",documents:"configured",balance:"incomplete",trim:"incomplete"});});
test("C2 is partial when only one required output section is configured",()=>{const value={...base,trimOptions:base.trimOptions.map(option=>({...option,selected:false,priority:null}))};assert.equal(aircraftC2Statuses(value).page,"partial");});
test("inactive document columns do not configure Balance Output",()=>{const value={...base,documents:[{...base.documents[0],required:false},{code:"LS ACARS FINAL",name:"ACARS Loadsheet Final",ahmReference:"AHM517",suggested:false,required:true}],outputs:base.outputs.map(output=>({...output,validAcarsFinal:true,selectedEdpFinal:true,selectedAcarsFinal:false}))};assert.equal(aircraftC2Statuses(value).balance,"incomplete");});
test("C5.1 envelope applicability follows the matching laden Index or MAC output",()=>{const outputs=[...base.outputs,{...base.outputs[0],code:"LIZFW",name:"Laden Index Zero Fuel Weight",selectedEdpFinal:true},{...base.outputs[0],code:"MACZFW",name:"Zero Fuel Weight MAC",selectedEdpFinal:false},{...base.outputs[0],code:"LITOW",name:"Laden Index Take Off Weight",selectedEdpFinal:false},{...base.outputs[0],code:"MACTOW",name:"Take Off Weight MAC",selectedEdpFinal:true},{...base.outputs[0],code:"LILAW",name:"Laden Index Landing Weight",selectedEdpFinal:false},{...base.outputs[0],code:"MACLAW",name:"Landing Weight MAC",selectedEdpFinal:false}];assert.deepEqual(aircraftC5ApplicabilityFromC2({...base,outputs}),{tow:true,law:false,zfw:true})});
test("C2 does not require Passenger Trim for a Freighter",()=>assert.deepEqual(aircraftC2Statuses({...base,trimOptions:[]},"FREIGHTER"),{page:"configured",documents:"configured",balance:"configured",trim:"not_required"}));
