import test from"node:test";import assert from"node:assert/strict";import{aircraftE12Status,e12RegistrationsStatus,e12StandardStatus}from"@/domain/aircraft-e12-status";import{validateE12Registrations,validateFuelSystemConfigurations,type AircraftE12Snapshot}from"@/domain/aircraft-e12";
const base:AircraftE12Snapshot={canView:true,canEdit:true,revision:"x",typeCode:"319",subtype:"100",principle:"DRY_OPERATING_WEIGHT",standardFleetWeight:null,standardFleetIndex:null,variantOptions:["100","111"],fuelConfigurations:[],registrations:[]};
test("E1.2 requires both standard fleet values",()=>{assert.equal(e12StandardStatus(base),"incomplete");assert.equal(e12StandardStatus({...base,standardFleetWeight:42000}),"partial");assert.equal(e12StandardStatus({...base,standardFleetWeight:42000,standardFleetIndex:41}),"configured")});
test("E1.2 registration section needs one complete row",()=>{assert.equal(e12RegistrationsStatus({...base,registrations:[{fleetRowId:null,registration:"G-EUPA",variantCode:"111",fuelConfigurationCode:null,weight:null,index:null}]}),"partial");assert.equal(e12RegistrationsStatus({...base,registrations:[{fleetRowId:null,registration:"G-EUPA",variantCode:"111",fuelConfigurationCode:null,weight:42000,index:41}]}),"configured")});
test("E1.2 page is configured only when both subsections are configured",()=>assert.equal(aircraftE12Status({...base,standardFleetWeight:42000,standardFleetIndex:41,registrations:[{fleetRowId:null,registration:"G-EUPA",variantCode:"111",fuelConfigurationCode:null,weight:42000,index:41}]}),"configured"));
test("E1.2 rejects duplicate registrations",()=>assert.throws(()=>validateE12Registrations([{registration:"G-EUPA",variantCode:"111",fuelConfigurationCode:null,weight:1,index:1},{registration:"G-EUPA",variantCode:"111",fuelConfigurationCode:null,weight:2,index:2}],base.variantOptions,base.fuelConfigurations)));
test("E1.2 rejects a variant not configured on C1",()=>assert.throws(()=>validateE12Registrations([{registration:"G-EUPA",variantCode:"999",weight:1,index:1}],base.variantOptions,base.fuelConfigurations)));
test("fuel configurations retain ACT count and ordered structural weights",()=>assert.deepEqual(validateFuelSystemConfigurations([{code:"2act",description:"Two tanks",actCount:2,maximumWeights:{zfw:75600,law:79200,tow:97000,mrw:97400}}]),[{code:"2ACT",description:"Two tanks",actCount:2,maximumWeights:{zfw:75600,law:79200,tow:97000,mrw:97400}}]));
test("registrations require a fitted configuration when configurations are defined",()=>{const fuelConfigurations=validateFuelSystemConfigurations([{code:"2ACT",description:"",actCount:2,maximumWeights:{zfw:null,law:null,tow:null,mrw:null}}]);assert.throws(()=>validateE12Registrations([{registration:"G-EUPA",variantCode:"111",fuelConfigurationCode:null,weight:42000,index:41}],base.variantOptions,fuelConfigurations));assert.equal(validateE12Registrations([{registration:"G-EUPA",variantCode:"111",fuelConfigurationCode:"2act",weight:42000,index:41}],base.variantOptions,fuelConfigurations)[0].fuelConfigurationCode,"2ACT")});
