import test from"node:test";import assert from"node:assert/strict";import{AircraftG1Invalid,resolvedG1Rows,validateG1Rows,type AircraftG1Snapshot}from"../src/domain/aircraft-g1";import{aircraftG1DashboardStatus,aircraftG1Status}from"../src/domain/aircraft-g1-status";
const snap=(value:Partial<AircraftG1Snapshot>={}):AircraftG1Snapshot=>({canView:true,canEdit:true,revision:"r",typeCode:"320",subtype:"200",applicable:true,bays:[{holdId:"1",bayId:"11"},{holdId:"1",bayId:"12"}],uldTypes:["LD3-45"],uldIdentities:[{code:"AKE",type:"LD3-45"},{code:"PKC",type:"LD3-45"}],rows:[],suggestions:[{bayId:"11",uldType:"LD3-45",compatible:true},{bayId:"12",uldType:"LD3-45",compatible:true}],...value});
test("G1 is Not Required when D2 ULD Holds are inactive",()=>assert.equal(aircraftG1Status(snap({applicable:false})),"not_required"));
test("dashboard excludes G1 when D2 ULD Holds are inactive even if the G1 read is unavailable",()=>assert.equal(aircraftG1DashboardStatus(null,false),"not_required"));
test("G1 is configured automatically from complete D3 and B5 base-code matches",()=>assert.equal(aircraftG1Status(snap()),"configured"));
test("saved reviews override derived matches",()=>{const snapshot=snap({rows:[{bayId:"11",uldType:"LD3-45",compatible:false}]});assert.deepEqual(resolvedG1Rows(snapshot),[{bayId:"11",uldType:"LD3-45",compatible:false},{bayId:"12",uldType:"LD3-45",compatible:true}]);assert.equal(aircraftG1Status(snapshot),"configured")});
test("G1 remains partial when a base-code match cannot be derived",()=>assert.equal(aircraftG1Status(snap({suggestions:[{bayId:"11",uldType:"LD3-45",compatible:true},{bayId:"12",uldType:"LD3-45",compatible:null}]})),"partial"));
test("false is a valid compatibility answer",()=>assert.deepEqual(validateG1Rows([{bayId:"11",uldType:"LD3-45",compatible:false},{bayId:"12",uldType:"LD3-45",compatible:true}],snap())[0].compatible,false));
test("G1 rejects incomplete and duplicate matrices",()=>{assert.throws(()=>validateG1Rows([{bayId:"11",uldType:"LD3-45",compatible:true}],snap()),AircraftG1Invalid);assert.throws(()=>validateG1Rows([{bayId:"11",uldType:"LD3-45",compatible:true},{bayId:"11",uldType:"LD3-45",compatible:false}],snap()),AircraftG1Invalid)});
