import test from"node:test";import assert from"node:assert/strict";import{AircraftH1Invalid,validateH1Exceptions,validateH1SpecialLoads,type AircraftH1Snapshot}from"../src/domain/aircraft-h1";import{aircraftH1Status,h1DgrStatus,h1SpecialLoadsStatus}from"../src/domain/aircraft-h1-status";
const snap=(v:Partial<AircraftH1Snapshot>={}):AircraftH1Snapshot=>({canView:true,canEdit:true,revision:"r",typeCode:"319",subtype:"100",applicabilityReviewed:true,dgrActive:false,iataActive:false,specialLoadsActive:false,isUldAircraft:false,dgrRows:[],iataRows:[],specialLoadRows:[],codeOptions:[{code:"AVI",description:"Live Animal",prohibited:false},{code:"ICE",description:"Dry Ice",prohibited:false}],holdOptions:[{id:"1",name:"Hold 1",holdType:"BULK"}],locationOptions:[{holdId:"1",id:"11",locationType:"COMPARTMENT"}],masterIncompatibilities:[],codeClasses:{},...v});
test("inactive H1 sections are Not Active and a reviewed page is configured",()=>{const s=snap();assert.equal(h1DgrStatus(s),"not_active");assert.equal(aircraftH1Status(s),"configured")});
test("active H1 section requires one complete row",()=>{const s=snap({dgrActive:true});assert.equal(aircraftH1Status(s),"incomplete");const done=snap({dgrActive:true,dgrRows:[{code:"AVI",incompatibleWith:"ICE",remarks:null}]});assert.equal(aircraftH1Status(done),"configured")});
test("H1 rejects mirrored duplicate exception pairs",()=>assert.throws(()=>validateH1Exceptions([{code:"AVI",incompatibleWith:"ICE"},{code:"ICE",incompatibleWith:"AVI"}],snap().codeOptions),AircraftH1Invalid));
test("non-ULD Special Loads accept a nullable compartment and zero adds the prohibition remark",()=>{const s=snap({specialLoadsActive:true,specialLoadRows:[{holdId:"1",code:"AVI",locationRef:null,maximumQuantity:0,remarks:null}]});assert.equal(h1SpecialLoadsStatus(s),"configured");assert.equal(validateH1SpecialLoads(s.specialLoadRows,s)[0].remarks,"Not Permitted This Hold");assert.equal(validateH1SpecialLoads([{...s.specialLoadRows[0],maximumQuantity:1,remarks:"Not Permitted This Hold"}],s)[0].remarks,null);assert.throws(()=>validateH1SpecialLoads([{...s.specialLoadRows[0],maximumQuantity:-1}],s),AircraftH1Invalid)});
test("a compartment must belong to its selected hold",()=>assert.throws(()=>validateH1SpecialLoads([{holdId:"1",code:"AVI",locationRef:"99",maximumQuantity:1,remarks:null}],snap()),AircraftH1Invalid));
test("mixed aircraft keep compartments with bulk holds and positions with ULD holds",()=>{const s=snap({isUldAircraft:true,holdOptions:[{id:"1",name:"Hold 1",holdType:"ULD"},{id:"5",name:"Hold 5",holdType:"BULK"}],locationOptions:[{holdId:"1",id:"11P",locationType:"POSITION"},{holdId:"5",id:"51",locationType:"COMPARTMENT"}]});assert.equal(validateH1SpecialLoads([{holdId:"1",code:"AVI",locationRef:"11P",maximumQuantity:1,remarks:null},{holdId:"5",code:"ICE",locationRef:"51",maximumQuantity:2,remarks:null}],s).length,2);assert.throws(()=>validateH1SpecialLoads([{holdId:"1",code:"AVI",locationRef:"51",maximumQuantity:1,remarks:null}],s),AircraftH1Invalid)});
test("ULD zero quantities do not receive the Bulk Hold automatic remark",()=>{const s=snap({isUldAircraft:true,holdOptions:[{id:"1",name:"Hold 1",holdType:"ULD"}],locationOptions:[{holdId:"1",id:"11P",locationType:"POSITION"}]});assert.equal(validateH1SpecialLoads([{holdId:"1",code:"AVI",locationRef:"11P",maximumQuantity:0,remarks:null}],s)[0].remarks,null)});
