import test from"node:test";import assert from"node:assert/strict";import{aggregateConfigurationStatuses,configurationStatusLabels}from"../src/domain/configuration-status";import{aircraftC5Statuses}from"../src/domain/aircraft-c5-status";import type{AircraftC5Values}from"../src/domain/aircraft-c5";

const boundary=(maximum:number)=>({fwd:[{weight:35000,indexValue:20,macValue:18},{weight:maximum,indexValue:45,macValue:22}],aft:[{weight:35000,indexValue:30,macValue:28},{weight:maximum,indexValue:60,macValue:32}]});
const complete=():AircraftC5Values=>({curtailed:false,inputMode:"INDEX",effectiveDow:35000,effectiveDowSource:"fleet",maximumWeights:{mrw:70500,tow:70000,law:62500,zfw:58500},envelopes:{tow:boundary(70000),law:boundary(62500),zfw:boundary(58500)}});

test("uses the approved exact uppercase status labels",()=>assert.deepEqual([configurationStatusLabels.incomplete,configurationStatusLabels.partial,configurationStatusLabels.configured],["INCOMPLETE","PARTIALLY CONFIGURED","CONFIGURED"]));
test("uses the concise neutral status labels",()=>assert.deepEqual([configurationStatusLabels.skipped,configurationStatusLabels.unsupported,configurationStatusLabels.out_of_scope],["SKIPPED","UNSUPPORTED","OUT OF SCOPE"]));
test("aggregates only all-green pages as configured",()=>{assert.equal(aggregateConfigurationStatuses(["configured","configured"]),"configured");assert.equal(aggregateConfigurationStatuses(["incomplete","incomplete"]),"incomplete");assert.equal(aggregateConfigurationStatuses(["configured","incomplete"]),"partial")});
test("marks a complete C5.1 page and every visible section configured",()=>assert.deepEqual(aircraftC5Statuses(complete()),{status:"configured",tow:"configured",law:"configured",zfw:"configured",page:"configured"}));
test("marks C5.1 partial when an envelope is incomplete",()=>{const value=complete();value.envelopes.law.aft.pop();const statuses=aircraftC5Statuses(value);assert.equal(statuses.law,"partial");assert.equal(statuses.page,"partial")});
test("marks an envelope partial when its structural maximum increases beyond the last point",()=>{const value=complete();value.maximumWeights.tow=70500;value.maximumWeights.mrw=71000;const statuses=aircraftC5Statuses(value);assert.equal(statuses.tow,"partial");assert.equal(statuses.page,"partial")});
test("marks an envelope partial when its first row is above the smallest effective DOW",()=>{const value=complete();value.effectiveDow=34000;const statuses=aircraftC5Statuses(value);assert.equal(statuses.tow,"partial");assert.equal(statuses.page,"partial")});
test("marks an untouched C5.1 page incomplete",()=>{const empty:AircraftC5Values={curtailed:null,inputMode:"INDEX",effectiveDow:0,effectiveDowSource:"unavailable",maximumWeights:{mrw:0,tow:0,law:0,zfw:0},envelopes:{tow:{fwd:[],aft:[]},law:{fwd:[],aft:[]},zfw:{fwd:[],aft:[]}}};assert.equal(aircraftC5Statuses(empty).page,"incomplete")});
test("excludes C2 envelopes that are not required from C5.1 completion",()=>{const value=complete();value.envelopes.tow={fwd:[],aft:[]};value.envelopes.law={fwd:[],aft:[]};assert.deepEqual(aircraftC5Statuses(value,{tow:false,law:false,zfw:true}),{status:"configured",tow:"not_required",law:"not_required",zfw:"configured",page:"configured"})});
