import test from"node:test";
import assert from"node:assert/strict";
import{createFlightSchedules}from"../src/application/flight-schedules";
import{filterPublishedScheduleItineraries,firstAircraftConfiguration,publishedScheduleItineraries,scheduleAircraftCarriesPassengers,scheduleAircraftConfiguration,scheduleAircraftSubtype,scheduleCodesForSubtype,scheduleOnlyCode,FlightScheduleInvalid}from"../src/domain/flight-schedules";
import type{FlightScheduleParameters,FlightScheduleRepository,FlightScheduleWorkspace,ManualScheduleLegInput}from"../src/ports/flight-schedule-repository";

const emptyWorkspace:FlightScheduleWorkspace={canView:true,canConfigure:true,publishedImportId:null,legs:[],segmentDefaults:[],weightOptions:{passenger:{available:false,defaultBasis:"STANDARD",variations:[]},baggage:{available:false,defaultBasis:"STANDARD",variations:[]}},serviceTypes:[],airports:[],aircraft:[],aircraftConfigurations:[],crewCodes:[],pantryCodes:[],variations:[]};
function setup(){let saved:ManualScheduleLegInput|null=null,savedItinerary:ManualScheduleLegInput[]=[],savedSegment:{departure:string;arrival:string;type:string;values:FlightScheduleParameters}|null=null;const repository:FlightScheduleRepository={list:async()=>[],workspace:async()=>emptyWorkspace,createAndStage:async()=>({importId:"",status:"VALIDATED",records:0,accepted:0,rejected:0,normalizedLegs:0,coverageStart:null,coverageEnd:null}),publish:async()=>({importId:"",status:"PUBLISHED",records:0,accepted:0,rejected:0,normalizedLegs:0,coverageStart:null,coverageEnd:null}),createRevision:async()=>"33333333-3333-3333-3333-333333333333",saveParameters:async()=>emptyWorkspace,saveSegmentDefault:async(_iata,departure,arrival,type,values)=>{savedSegment={departure,arrival,type,values};return emptyWorkspace},deleteSegmentDefault:async()=>emptyWorkspace,createManual:async()=>"11111111-1111-1111-1111-111111111111",saveManualLeg:async(_iata,_import,_leg,values)=>{saved=values;return{importId:"11111111-1111-1111-1111-111111111111",scheduleLegId:"22222222-2222-2222-2222-222222222222",status:"VALIDATED"}},saveManualItinerary:async(_iata,_import,values)=>{savedItinerary=values;return{importId:"11111111-1111-1111-1111-111111111111",scheduleLegIds:values.map((_,index)=>`${index}`),status:"VALIDATED"}},edition:async()=>({importId:"11111111-1111-1111-1111-111111111111",name:"Manual",sourceFormat:"MANUAL",status:"VALIDATED",seasonCode:null,coverageStart:null,coverageEnd:null,recordCount:0,legCount:0,rejectedCount:0,canEdit:true,canDelete:true,legs:[]}),deleteManualLeg:async()=>({importId:"11111111-1111-1111-1111-111111111111",name:"Manual",sourceFormat:"MANUAL",status:"DRAFT",seasonCode:null,coverageStart:null,coverageEnd:null,recordCount:0,legCount:0,rejectedCount:0,canEdit:true,canDelete:true,legs:[]}),deleteEdition:async()=>{}};const service=createFlightSchedules({currentUser:async()=>({id:"u",email:null}),signIn:async()=>{},signOut:async()=>{}},{listAuthorised:async()=>[],findAuthorised:async()=>({iata:"ZZ",name:"Zenith",icao:"ZZZ"})},repository);return{service,saved:()=>saved,savedItinerary:()=>savedItinerary,savedSegment:()=>savedSegment}}

test("manual schedule entry preserves a four-digit flight and seven-day pattern",async()=>{const{service,saved}=setup();await service.saveManualLeg("ZZ","11111111-1111-1111-1111-111111111111",null,{flightNumber:"1040",itineraryVariation:"01",legSequence:1,serviceType:"j",periodStart:"2026-10-25",periodEnd:"2027-03-27",operatingDays:"1111111",departureAirport:"mle",arrivalAirport:"rsi",departureTime:"19:40",arrivalTime:"00:40",arrivalDayOffset:1,aircraftType:"319",aircraftSubtype:"100",aircraftConfiguration:"XX"});assert.partialDeepStrictEqual(saved(),{airlineDesignator:"ZZ",flightNumber:"1040",serviceType:"J",departureAirport:"MLE",arrivalAirport:"RSI",operatingDays:"1111111"})});

test("manual schedule entry rejects a flight number longer than four digits",async()=>{const{service}=setup();await assert.rejects(()=>service.saveManualLeg("ZZ","11111111-1111-1111-1111-111111111111",null,{flightNumber:"10400",itineraryVariation:"01",legSequence:1,serviceType:"J",periodStart:"2026-10-25",periodEnd:"2027-03-27",operatingDays:"1111111",departureAirport:"MLE",arrivalAirport:"RSI",departureTime:"19:40",arrivalTime:"00:40",arrivalDayOffset:1,aircraftType:"319",aircraftSubtype:"100"}),FlightScheduleInvalid)});

test("manual schedule entry accepts a final alphabetic flight character",async()=>{const{service,saved}=setup();await service.saveManualLeg("ZZ","11111111-1111-1111-1111-111111111111",null,{flightNumber:"401a",itineraryVariation:"01",legSequence:1,serviceType:"J",periodStart:"2026-10-25",periodEnd:"2027-03-27",operatingDays:"1111111",departureAirport:"MLE",arrivalAirport:"RSI",departureTime:"19:40",arrivalTime:"00:40",arrivalDayOffset:1,aircraftType:"319",aircraftSubtype:"100"});assert.equal(saved()?.flightNumber,"401A")});

test("manual schedule entry rejects an alphabetic character before the end",async()=>{const{service}=setup();await assert.rejects(()=>service.saveManualLeg("ZZ","11111111-1111-1111-1111-111111111111",null,{flightNumber:"40A1",itineraryVariation:"01",legSequence:1,serviceType:"J",periodStart:"2026-10-25",periodEnd:"2027-03-27",operatingDays:"1111111",departureAirport:"MLE",arrivalAirport:"RSI",departureTime:"19:40",arrivalTime:"00:40",arrivalDayOffset:1,aircraftType:"319",aircraftSubtype:"100"}),FlightScheduleInvalid)});

test("manual schedule entry requires at least one operating day",async()=>{const{service}=setup();await assert.rejects(()=>service.saveManualLeg("ZZ","11111111-1111-1111-1111-111111111111",null,{flightNumber:"040",itineraryVariation:"01",legSequence:1,serviceType:"J",periodStart:"2026-10-25",periodEnd:"2027-03-27",operatingDays:"0000000",departureAirport:"MLE",arrivalAirport:"RSI",departureTime:"19:40",arrivalTime:"00:40",arrivalDayOffset:1,aircraftType:"319",aircraftSubtype:"100"}),FlightScheduleInvalid)});

test("manual itinerary saves consecutive connected segments in one operation",async()=>{const{service,savedItinerary}=setup(),shared={flightNumber:"040",itineraryVariation:"01",serviceType:"J",periodStart:"2026-10-25",periodEnd:"2027-03-27",operatingDays:"1111111",aircraftType:"319",aircraftSubtype:"100",aircraftConfiguration:"A"};await service.saveManualItinerary("ZZ","11111111-1111-1111-1111-111111111111",[{...shared,legSequence:1,departureAirport:"MLE",arrivalAirport:"AUH",departureTime:"09:00",arrivalTime:"13:00",arrivalDayOffset:0},{...shared,legSequence:2,departureAirport:"AUH",arrivalAirport:"LHR",departureTime:"14:30",arrivalTime:"19:00",arrivalDayOffset:0}]);assert.deepEqual(savedItinerary().map(leg=>[leg.legSequence,leg.departureAirport,leg.arrivalAirport]),[[1,"MLE","AUH"],[2,"AUH","LHR"]])});

test("manual itinerary rejects a disconnected segment",async()=>{const{service}=setup(),shared={flightNumber:"040",itineraryVariation:"01",serviceType:"J",periodStart:"2026-10-25",periodEnd:"2027-03-27",operatingDays:"1111111",aircraftType:"319",aircraftSubtype:"100"};await assert.rejects(()=>service.saveManualItinerary("ZZ","11111111-1111-1111-1111-111111111111",[{...shared,legSequence:1,departureAirport:"MLE",arrivalAirport:"AUH",departureTime:"09:00",arrivalTime:"13:00",arrivalDayOffset:0},{...shared,legSequence:2,departureAirport:"DOH",arrivalAirport:"LHR",departureTime:"14:30",arrivalTime:"19:00",arrivalDayOffset:0}]),FlightScheduleInvalid)});

test("aircraft selection defaults to the first listed cabin configuration",()=>{const rows=[{typeCode:"319",subtype:"100",code:"A"},{typeCode:"319",subtype:"100",code:"B"}];assert.equal(firstAircraftConfiguration(rows,"319","100"),"A");assert.equal(firstAircraftConfiguration(rows,"321","200"),null)});

test("SSIM XX aircraft configuration is treated as unspecified",()=>{assert.equal(scheduleAircraftConfiguration("XX"),null);assert.equal(scheduleAircraftConfiguration(" A "),"A")});

test("schedule passenger parameters follow the selected aircraft operating role",()=>{const aircraft=[{typeCode:"321",subtype:"200",operatingRole:"PASSENGER" as const},{typeCode:"321",subtype:"P2F",operatingRole:"FREIGHTER" as const},{typeCode:"763",subtype:"300",operatingRole:"COMBI" as const}];assert.equal(scheduleAircraftCarriesPassengers(aircraft,"321","P2F"),false);assert.equal(scheduleAircraftCarriesPassengers(aircraft,"321","200"),true);assert.equal(scheduleAircraftCarriesPassengers(aircraft,"763","300"),true);assert.equal(scheduleAircraftCarriesPassengers(aircraft,"359","900"),true)});
test("schedule parameters default to the subtype saved on the flight leg",()=>{assert.equal(scheduleAircraftSubtype({aircraftSubtype:"P2F",parameters:null},"200"),"P2F");assert.equal(scheduleAircraftSubtype({aircraftSubtype:"P2F",parameters:{aircraftSubtype:"200"}},"P2F"),"200");assert.equal(scheduleAircraftSubtype({aircraftSubtype:null,parameters:null},"200"),"200")});
test("a single configured crew or pantry code is an automatic choice",()=>{const rows=[{typeCode:"319",subtype:"100",code:" A "},{typeCode:"319",subtype:"100",code:"A"},{typeCode:"319",subtype:"200",code:"B"}];assert.deepEqual(scheduleCodesForSubtype(rows,"319","100"),["A"]);assert.equal(scheduleOnlyCode(rows,"319","100"),"A")});
test("multiple configured codes remain a user decision",()=>{const rows=[{typeCode:"319",subtype:"100",code:"A"},{typeCode:"319",subtype:"100",code:"E"}];assert.equal(scheduleOnlyCode(rows,"319","100"),null)});

test("published schedule groups every leg despite an overnight date and operating-day shift",()=>{const shared={operationalSuffix:"",itineraryVariation:"01",serviceType:"J",periodEnd:"2027-03-26",aircraftType:"319",aircraftSubtype:"100",aircraftConfiguration:null,parameters:{}};const itineraries=publishedScheduleItineraries([{...shared,scheduleLegId:"2",flightNumber:"081",legSequence:2,periodStart:"2026-11-01",operatingDays:"1001001",departureAirport:"RSI",arrivalAirport:"MLE"},{...shared,scheduleLegId:"1",flightNumber:"081",legSequence:1,periodStart:"2026-10-31",operatingDays:"0010010",departureAirport:"MXP",arrivalAirport:"RSI"}]);assert.equal(itineraries.length,1);assert.equal(itineraries[0].route,"MXP → RSI → MLE");assert.deepEqual(itineraries[0].legs.map(leg=>leg.legSequence),[1,2])});

test("published schedule route does not repeat airports across seasonal records",()=>{const shared={operationalSuffix:"",itineraryVariation:"01",serviceType:"J",periodEnd:"2027-03-26",operatingDays:"0010010",aircraftType:"319",aircraftSubtype:"100",aircraftConfiguration:null,parameters:{}};const itineraries=publishedScheduleItineraries([{...shared,scheduleLegId:"1",flightNumber:"090",legSequence:1,periodStart:"2026-10-26",departureAirport:"MLE",arrivalAirport:"DWC"},{...shared,scheduleLegId:"2",flightNumber:"090",legSequence:2,periodStart:"2026-10-27",departureAirport:"DWC",arrivalAirport:"ZRH"},{...shared,scheduleLegId:"3",flightNumber:"090",legSequence:1,periodStart:"2027-02-01",departureAirport:"MLE",arrivalAirport:"DWC"},{...shared,scheduleLegId:"4",flightNumber:"090",legSequence:2,periodStart:"2027-02-02",departureAirport:"DWC",arrivalAirport:"ZRH"}]);assert.equal(itineraries[0].route,"MLE → DWC → ZRH")});

test("published schedule search retains the complete matching itinerary",()=>{const shared={operationalSuffix:"",itineraryVariation:"01",serviceType:"J",periodStart:"2026-10-31",periodEnd:"2027-03-26",operatingDays:"0010010",aircraftType:"319",aircraftSubtype:"100",aircraftConfiguration:null,parameters:{}};const itineraries=publishedScheduleItineraries([{...shared,scheduleLegId:"1",flightNumber:"080",legSequence:1,departureAirport:"MLE",arrivalAirport:"RSI"},{...shared,scheduleLegId:"2",flightNumber:"080",legSequence:2,departureAirport:"RSI",arrivalAirport:"MXP"},{...shared,scheduleLegId:"3",flightNumber:"040",legSequence:1,departureAirport:"MLE",arrivalAirport:"RUH"}]);const result=filterPublishedScheduleItineraries(itineraries,"ZZ","MXP","READY");assert.equal(result.length,1);assert.equal(result[0].flightNumber,"080");assert.deepEqual(result[0].legs.map(leg=>`${leg.departureAirport}-${leg.arrivalAirport}`),["MLE-RSI","RSI-MXP"])});

test("a published schedule can create an editable revision",async()=>{const{service}=setup();assert.equal(await service.createRevision("ZZ","11111111-1111-1111-1111-111111111111"),"33333333-3333-3333-3333-333333333333");await assert.rejects(()=>service.createRevision("ZZ","bad"),FlightScheduleInvalid)});

test("load-control parameters require variation codes only for variation methods",async()=>{const{service}=setup();await assert.rejects(()=>service.saveParameters("ZZ","22222222-2222-2222-2222-222222222222",{aircraftSubtype:"100",crewCode:"A",pantryCode:"A",passengerWeightBasis:"VARIATION",passengerVariation:"",baggageWeightBasis:"STANDARD",remarks:""}),FlightScheduleInvalid)});

test("segment defaults normalise a directional route and its operating parameters",async()=>{const{service,savedSegment}=setup();await service.saveSegmentDefault("ZZ"," mle ","rsi","319",{aircraftSubtype:"100",crewCode:"a",pantryCode:"e",passengerWeightBasis:"standard",passengerVariation:"IGNORED",baggageWeightBasis:"actual",baggageVariation:"IGNORED",remarks:" Normal operation "});assert.deepEqual(savedSegment(),{departure:"MLE",arrival:"RSI",type:"319",values:{aircraftSubtype:"100",crewCode:"A",pantryCode:"E",passengerWeightBasis:"STANDARD",passengerVariation:null,baggageWeightBasis:"ACTUAL",baggageVariation:null,remarks:"Normal operation"}})});

test("segment defaults reject a route whose departure and arrival are the same",async()=>{const{service}=setup();await assert.rejects(()=>service.saveSegmentDefault("ZZ","MLE","mle","319",{aircraftSubtype:"100",crewCode:"A",pantryCode:"E",passengerWeightBasis:"STANDARD",baggageWeightBasis:"STANDARD"}),FlightScheduleInvalid)});
