import test from"node:test";import assert from"node:assert/strict";
import{cargoOfferLimitingLabel,freightAcceptanceCsvTemplate,freightUnderloadTone,parseAhm581,parseFreightAcceptanceCsv,validFreightAcceptance,type FreightSpecialLoadOption}from"@/domain/freight-acceptance";
const uldLimits=[{code:"PAJ",type:"LD7",tareWeight:88,maximumGrossWeight:4626},{code:"AKH",type:"LD3-45",tareWeight:67,maximumGrossWeight:1588}];
const specialLoadOptions:FreightSpecialLoadOption[]=[{code:"RFL",description:"Flammable Liquid",dangerousGoods:true,cargoAircraftOnly:false},{code:"ICE",description:"Carbon Dioxide, Solid",dangerousGoods:true,cargoAircraftOnly:false},{code:"RRY",description:"Radioactive Material",dangerousGoods:true,cargoAircraftOnly:false}];
test("predicted underload uses green, amber and red Cargo Offer thresholds",()=>{assert.equal(freightUnderloadTone(1387,27728),"green");assert.equal(freightUnderloadTone(1386.4,27728),"amber");assert.equal(freightUnderloadTone(1,27728),"amber");assert.equal(freightUnderloadTone(0,27728),"red");assert.equal(freightUnderloadTone(-1,27728),"red");assert.equal(freightUnderloadTone(null,27728),"neutral")});
test("Cargo Offer reports its operational limiting basis",()=>{assert.equal(cargoOfferLimitingLabel("MZFW"),"WEIGHT LIMITING");assert.equal(cargoOfferLimitingLabel("HOLD_CAPACITY"),"VOLUME LIMITING")});
test("AHM581 UWS keeps inclusive special loads inside the complete uplift",()=>{const result=parseAhm581(`UWS\nMS758/08.DXB\n-AKE04636MS/CAI/1000A/C/RFL/25\n-AKE04938MS/CAI/550M\nBULK\n-CAI/100C/ICE/10`,"DXB",[],specialLoadOptions);assert.deepEqual(result.errors,[]);assert.equal(result.items.length,3);assert.equal(result.items[0].grossWeight,1000);assert.deepEqual(result.items[0].includedLoads,[{code:"RFL",weight:25,dangerousGoods:true}]);assert.equal(result.items[1].commodity,"MAIL");assert.deepEqual(result.items[2].includedLoads,[{code:"ICE",weight:10,dangerousGoods:true}])});
test("freight CSV binds every row to the selected flight and reads inclusive loads",()=>{const context={iata:"ZZ",flightNumber:"4101",serviceDate:"2026-10-08",specialLoadOptions},headers=freightAcceptanceCsvTemplate(context).split("\n")[0],text=`${headers}\nZZ,4101,2026-10-08,ULD,AKE12345ZZ,1000,HKG,DWC,CARGO,10,,,RFL:25:DG,Y,General cargo\nZZ,4101,2026-10-08,BULK,,500,HKG,DWC,MAIL,4,2.5,,,N,Mail`;const result=parseFreightAcceptanceCsv(text,context);assert.deepEqual(result.errors,[]);assert.equal(result.items.length,2);assert.equal(result.items[0].source,"CSV");assert.equal(result.items[0].includedLoads[0].weight,25)});

test("CSV optional columns may be omitted and Bulk volume uses B1 density",()=>{const text="Carrier IATA,Flight Number,Service Date,Load Type,Gross Weight,Station of Unloading,Commodity\nZZ,4101,2026-10-08,BULK,500,BKK,CARGO\nZZ,4101,2026-10-08,BULK,250,DWC,MAIL",result=parseFreightAcceptanceCsv(text,{iata:"ZZ",flightNumber:"4101",serviceDate:"2026-10-08",unloadingStations:["BKK","DWC"],planningDensities:{cargo:200,mail:250,baggage:176}});assert.deepEqual(result.errors,[]);assert.equal(result.items[0].destination,null);assert.equal(result.items[0].pieces,null);assert.equal(result.items[0].volume,2.5);assert.equal(result.items[1].volume,1)});
test("CSV accepts its downloaded carrier-prefixed flight number and a day-first service date",()=>{const text="Carrier IATA,Flight Number,Service Date,Load Type,ULD ID,Gross Weight,Station of Unloading,Commodity\nZZ,ZZ4101,08/10/2026,ULD,AKH0001ZZ,930,BKK,CARGO",result=parseFreightAcceptanceCsv(text,{iata:"ZZ",flightNumber:"ZZ4101",serviceDate:"2026-10-08",unloadingStations:["BKK","DWC"]});assert.deepEqual(result.errors,[]);assert.equal(result.items.length,1)});
test("CSV, UWS and manual inputs derive net weight from gross weight and configured tare",()=>{const csv=parseFreightAcceptanceCsv("Carrier IATA,Flight Number,Service Date,Load Type,ULD ID,Gross Weight,Station of Unloading,Commodity\nZZ,4101,2026-10-08,ULD,AKH0001ZZ,930,BKK,CARGO",{iata:"ZZ",flightNumber:"4101",serviceDate:"2026-10-08",uldLimits}),uws=parseAhm581("UWS\nZZ4101/08.HKG\n-AKH0002ZZ/BKK/930A/C","DWC",[],[],uldLimits),manual=validFreightAcceptance({source:"MANUAL",items:[{lineId:"1",loadType:"ULD",uldId:"AKH0003ZZ",grossWeight:930,netWeight:1,unloadingStation:"BKK",destination:"DWC",commodity:"CARGO",pieces:null,volume:null,specialHandlingCodes:[],includedLoads:[],dangerousGoods:false,remarks:null,source:"MANUAL",sourceReference:null}]},[],[],uldLimits);assert.equal(csv.items[0].netWeight,863);assert.equal(uws.items[0].netWeight,863);assert.equal(manual.items[0].netWeight,863)});
test("Bulk net weight equals its gross input",()=>{const result=parseFreightAcceptanceCsv("Carrier IATA,Flight Number,Service Date,Load Type,Gross Weight,Station of Unloading,Commodity\nZZ,4101,2026-10-08,BULK,500,BKK,CARGO",{iata:"ZZ",flightNumber:"4101",serviceDate:"2026-10-08"});assert.equal(result.items[0].netWeight,500)});
test("acceptance rejects duplicate ULD identities",()=>{const item={lineId:"1",loadType:"ULD",uldId:"AKE04636MS",grossWeight:685,netWeight:600,unloadingStation:"CAI",destination:"DXB",commodity:"CARGO",pieces:null,volume:null,specialHandlingCodes:[],includedLoads:[],dangerousGoods:false,remarks:null,source:"MANUAL",sourceReference:null};assert.throws(()=>validFreightAcceptance({source:"MANUAL",items:[item,{...item,lineId:"2"}]}),/appears more than once/)});
test("acceptance permits only remaining-route unloading stations",()=>{const item={lineId:"1",loadType:"ULD",uldId:"AKE04636MS",grossWeight:685,netWeight:600,unloadingStation:"HKG",destination:"DWC",commodity:"CARGO",pieces:null,volume:null,specialHandlingCodes:[],includedLoads:[],dangerousGoods:false,remarks:null,source:"MANUAL",sourceReference:null};assert.throws(()=>validFreightAcceptance({source:"MANUAL",items:[item]},["BKK","DWC"]),/not a station on the remaining flight route/);assert.doesNotThrow(()=>validFreightAcceptance({source:"MANUAL",items:[{...item,unloadingStation:"DWC"}]},["BKK","DWC"]))});
test("CSV and AHM581 reject unloading stations outside the flight route",()=>{const context={iata:"ZZ",flightNumber:"4101",serviceDate:"2026-10-08",unloadingStations:["BKK","DWC"],specialLoadOptions},headers=freightAcceptanceCsvTemplate(context).split("\n")[0],csv=parseFreightAcceptanceCsv(`${headers}\nZZ,4101,2026-10-08,ULD,AKE12345ZZ,1000,HKG,DWC,CARGO,10,,,,N,General cargo`,context),message=parseAhm581("UWS\nZZ4101/08.HKG\n-AKE12345ZZ/HKG/1000A/C","DWC",context.unloadingStations,specialLoadOptions);assert.match(csv.errors.join(" "),/HKG is not a station/);assert.match(message.errors.join(" "),/HKG is not a station/)});
test("special-load codes are validated against the IATA master",()=>{const item={lineId:"1",loadType:"BULK",uldId:null,grossWeight:100,netWeight:null,unloadingStation:"BKK",destination:"DWC",commodity:"CARGO",pieces:null,volume:1,specialHandlingCodes:[],includedLoads:[{code:"XXX",weight:10,dangerousGoods:false}],dangerousGoods:false,remarks:null,source:"MANUAL",sourceReference:null};assert.throws(()=>validFreightAcceptance({source:"MANUAL",items:[item]},["BKK","DWC"],specialLoadOptions),/not in the IATA special-load code master/)});

test("ULD gross weight cannot exceed the configured ULD-type maximum",()=>{const base={lineId:"1",loadType:"ULD",uldId:"PAJ12345ZZ",grossWeight:4627,netWeight:null,unloadingStation:"BKK",destination:"DWC",commodity:"CARGO",pieces:null,volume:null,specialHandlingCodes:[],includedLoads:[],dangerousGoods:false,remarks:null,source:"MANUAL",sourceReference:null};assert.throws(()=>validFreightAcceptance({source:"MANUAL",items:[base]},["BKK","DWC"],specialLoadOptions,uldLimits),/maximum gross weight of 4,626 KG/);assert.doesNotThrow(()=>validFreightAcceptance({source:"MANUAL",items:[{...base,grossWeight:4626}]},["BKK","DWC"],specialLoadOptions,uldLimits))});
test("UWS flags an unconfigured ULD for review and rejects an overweight configured ULD",()=>{const unknown=parseAhm581("UWS\nZZ4101/08.HKG\n-AKE12345ZZ/BKK/1000A/C","DWC",["BKK","DWC"],specialLoadOptions,uldLimits),over=parseAhm581("UWS\nZZ4101/08.HKG\n-PAJ12345ZZ/BKK/4627A/C","DWC",["BKK","DWC"],specialLoadOptions,uldLimits);assert.deepEqual(unknown.errors,[]);assert.equal(unknown.items[0].uldResolution?.status,"REQUIRES_REVIEW");assert.match(over.errors.join(" "),/maximum gross weight of 4,626 KG/)});
test("an unusual ULD can be confirmed against a compatible configured fitment",()=>{const base={lineId:"1",loadType:"ULD",uldId:"AKE12345ZZ",grossWeight:1000,netWeight:null,unloadingStation:"BKK",destination:"DWC",commodity:"CARGO",pieces:null,volume:null,specialHandlingCodes:[],includedLoads:[],dangerousGoods:false,remarks:null,source:"MANUAL",sourceReference:null};const result=validFreightAcceptance({source:"MANUAL",items:[{...base,uldResolution:{status:"CONFIRMED",tareWeight:82,maximumGrossWeight:1588,compatibleUldCode:"AKH"}}]},["BKK","DWC"],specialLoadOptions,uldLimits);assert.equal(result.items[0].uldResolution?.status,"CONFIRMED");assert.throws(()=>validFreightAcceptance({source:"MANUAL",items:[{...base,grossWeight:1600,uldResolution:{status:"CONFIRMED",tareWeight:82,maximumGrossWeight:1588,compatibleUldCode:"AKH"}}]},["BKK","DWC"],specialLoadOptions,uldLimits),/confirmed maximum gross weight of 1,588 KG/)});
