import test from"node:test";import assert from"node:assert/strict";
import{freightAcceptanceCsvTemplate,parseAhm581,parseFreightAcceptanceCsv,validFreightAcceptance,type FreightSpecialLoadOption}from"@/domain/freight-acceptance";
const specialLoadOptions:FreightSpecialLoadOption[]=[{code:"RFL",description:"Flammable Liquid",dangerousGoods:true,cargoAircraftOnly:false},{code:"ICE",description:"Carbon Dioxide, Solid",dangerousGoods:true,cargoAircraftOnly:false},{code:"RRY",description:"Radioactive Material",dangerousGoods:true,cargoAircraftOnly:false}];
test("AHM581 UWS keeps inclusive special loads inside the complete uplift",()=>{const result=parseAhm581(`UWS\nMS758/08.DXB\n-AKE04636MS/CAI/1000A/C/RFL/25\n-AKE04938MS/CAI/550M\nBULK\n-CAI/100C/ICE/10`,"DXB",[],specialLoadOptions);assert.deepEqual(result.errors,[]);assert.equal(result.items.length,3);assert.equal(result.items[0].grossWeight,1000);assert.deepEqual(result.items[0].includedLoads,[{code:"RFL",weight:25,dangerousGoods:true}]);assert.equal(result.items[1].commodity,"MAIL");assert.deepEqual(result.items[2].includedLoads,[{code:"ICE",weight:10,dangerousGoods:true}])});
test("freight CSV binds every row to the selected flight and reads inclusive loads",()=>{const context={iata:"ZZ",flightNumber:"4101",serviceDate:"2026-10-08",specialLoadOptions},headers=freightAcceptanceCsvTemplate(context).split("\n")[0],text=`${headers}\nZZ,4101,2026-10-08,ULD,AKE12345ZZ,1000,900,HKG,DWC,CARGO,10,,,RFL:25:DG,Y,General cargo\nZZ,4101,2026-10-08,BULK,,500,,HKG,DWC,MAIL,4,2.5,,,N,Mail`;const result=parseFreightAcceptanceCsv(text,context);assert.deepEqual(result.errors,[]);assert.equal(result.items.length,2);assert.equal(result.items[0].source,"CSV");assert.equal(result.items[0].includedLoads[0].weight,25)});
test("acceptance rejects duplicate ULD identities",()=>{const item={lineId:"1",loadType:"ULD",uldId:"AKE04636MS",grossWeight:685,netWeight:600,unloadingStation:"CAI",destination:"DXB",commodity:"CARGO",pieces:null,volume:null,specialHandlingCodes:[],includedLoads:[],dangerousGoods:false,remarks:null,source:"MANUAL",sourceReference:null};assert.throws(()=>validFreightAcceptance({source:"MANUAL",items:[item,{...item,lineId:"2"}]}),/appears more than once/)});
test("acceptance permits only remaining-route unloading stations",()=>{const item={lineId:"1",loadType:"ULD",uldId:"AKE04636MS",grossWeight:685,netWeight:600,unloadingStation:"HKG",destination:"DWC",commodity:"CARGO",pieces:null,volume:null,specialHandlingCodes:[],includedLoads:[],dangerousGoods:false,remarks:null,source:"MANUAL",sourceReference:null};assert.throws(()=>validFreightAcceptance({source:"MANUAL",items:[item]},["BKK","DWC"]),/not a station on the remaining flight route/);assert.doesNotThrow(()=>validFreightAcceptance({source:"MANUAL",items:[{...item,unloadingStation:"DWC"}]},["BKK","DWC"]))});
test("CSV and AHM581 reject unloading stations outside the flight route",()=>{const context={iata:"ZZ",flightNumber:"4101",serviceDate:"2026-10-08",unloadingStations:["BKK","DWC"],specialLoadOptions},headers=freightAcceptanceCsvTemplate(context).split("\n")[0],csv=parseFreightAcceptanceCsv(`${headers}\nZZ,4101,2026-10-08,ULD,AKE12345ZZ,1000,900,HKG,DWC,CARGO,10,,,,N,General cargo`,context),message=parseAhm581("UWS\nZZ4101/08.HKG\n-AKE12345ZZ/HKG/1000A/C","DWC",context.unloadingStations,specialLoadOptions);assert.match(csv.errors.join(" "),/HKG is not a station/);assert.match(message.errors.join(" "),/HKG is not a station/)});
test("special-load codes are validated against the IATA master",()=>{const item={lineId:"1",loadType:"BULK",uldId:null,grossWeight:100,netWeight:null,unloadingStation:"BKK",destination:"DWC",commodity:"CARGO",pieces:null,volume:1,specialHandlingCodes:[],includedLoads:[{code:"XXX",weight:10,dangerousGoods:false}],dangerousGoods:false,remarks:null,source:"MANUAL",sourceReference:null};assert.throws(()=>validFreightAcceptance({source:"MANUAL",items:[item]},["BKK","DWC"],specialLoadOptions),/not in the IATA special-load code master/)});
