import test from"node:test";import assert from"node:assert/strict";
import{buildFreightAutoloadProblem,freightAutoloadTimeLimitSeconds}from"@/domain/freight-autoload";

const input=()=>({flight:{status:"LOAD_PLANNING",legSequence:1,itinerary:{legs:[{legSequence:1,arrivalAirport:"BKK"},{legSequence:2,arrivalAirport:"DWC"}]},freightPlanning:{registration:null,crewCode:"A",pantryCode:"C",planningAircraftWeight:46000},freightAcceptance:{status:"RELEASED",totalWeight:1700,items:[{lineId:"1",loadType:"ULD",uldId:"AKH0001ZZ",grossWeight:900,unloadingStation:"BKK",specialHandlingCodes:[],includedLoads:[],dangerousGoods:false},{lineId:"2",loadType:"BULK",uldId:null,grossWeight:800,unloadingStation:"DWC",specialHandlingCodes:[],includedLoads:[],dangerousGoods:false}]}} as never,d2:{rows:[{id:"LOWER:ALB",name:"ALB",holdType:"BLK",deckCode:"LOWER",maxWeight:1500,indexPerWeightUnit:.002,balanceCentroid:20,compartments:[],configurationCodes:[],configurationOverrides:[]}],balanceFormula:null}as never,d3:{configurations:[{holdId:"LOWER:ULD",code:"A",atomicBays:[],expectedPositionCount:1,description:null,rows:[{rowType:"POSITION",positionId:"31P",compartmentId:"1",uldCode:"AKH",uldType:"LD3-45",uldBaseCode:null,groupId:null,occupiedBayIds:["31L"],maxWeight:1588,indexPerWeightUnit:.001,balanceCentroid:10}]}]}as never,d4:{doors:[{holdId:"LOWER:ULD",forwardArm:9,aftArm:11},{holdId:"LOWER:ALB",forwardArm:19,aftArm:21}]}as never,c7:{values:{idealTrim:{enabled:true,points:[{weight:47000,indexValue:50},{weight:48000,indexValue:52}]}}}as never,e12:{standardFleetIndex:40,registrations:[]}as never,e2:{crewRows:[{crewCode:"A",indexAdjustment:1}],pantryRows:[{pantryCode:"C",indexAdjustment:2}]}as never,h1:{dgrActive:false,iataActive:false,specialLoadsActive:false,dgrRows:[],iataRows:[],specialLoadRows:[],masterIncompatibilities:[{code:"AVI",incompatibleWith:"ICE"}],codeClasses:{RFL:["3"],ROX:["5.1"],RMD:["9"]}}as never});
test("freight AUTOLOAD builds ULD and Bulk positions and an Ideal Trim target",()=>{const result=buildFreightAutoloadProblem(input());assert.equal(result.problem.loads.length,2);assert.deepEqual(result.problem.positions.map(position=>position.loadType).sort(),["BULK","ULD"]);assert.equal(result.problem.idealTrimIndexScaled,840000);assert.equal(result.estimatedZfwWeight,47700);assert.equal(result.operationalBaseIndex,43);assert.ok(result.problem.incompatiblePairs.some(pair=>pairKey(pair.left,pair.right)===pairKey("DGR:3","DGR:5.1")))});
test("freight AUTOLOAD applies DGR classes from included special loads",()=>{const value=input(),items=(value.flight as never as{freightAcceptance:{items:Array<{includedLoads:Array<{code:string;weight:number;dangerousGoods:boolean}>;dangerousGoods:boolean}>}}).freightAcceptance.items;items[0].includedLoads=[{code:"RFL",weight:25,dangerousGoods:true}];items[0].dangerousGoods=true;items[1].includedLoads=[{code:"ROX",weight:10,dangerousGoods:true}];items[1].dangerousGoods=true;const result=buildFreightAutoloadProblem(value);assert.deepEqual(result.problem.loads[0].dangerousGoodsClasses,["3"]);assert.deepEqual(result.problem.loads[0].specialLoadDetails,["RFL/25KG"]);assert.deepEqual(result.problem.loads[1].dangerousGoodsClasses,["5.1"]);assert.deepEqual(result.problem.loads[1].specialLoadDetails,["ROX/10KG"])});
test("freight AUTOLOAD permits RMD in a preliminary plan with a NOTOC warning",()=>{const value=input(),item=(value.flight as never as{freightAcceptance:{items:Array<{includedLoads:Array<{code:string;weight:number;dangerousGoods:boolean}>;dangerousGoods:boolean}>}}).freightAcceptance.items[0];item.includedLoads=[{code:"RMD",weight:10,dangerousGoods:true}];item.dangerousGoods=true;const result=buildFreightAutoloadProblem(value);assert.match(result.warnings.join(" "),/preliminary plan/);assert.match(result.warnings.join(" "),/complete NOTOC details/)});
test("freight AUTOLOAD uses a short budget for ordinary flights and scales for large freighters",()=>{assert.equal(freightAutoloadTimeLimitSeconds(2),2);assert.equal(freightAutoloadTimeLimitSeconds(20),2);assert.equal(freightAutoloadTimeLimitSeconds(50),5);assert.equal(freightAutoloadTimeLimitSeconds(100),10);assert.equal(buildFreightAutoloadProblem(input()).problem.timeLimitSeconds,2)});
test("freight AUTOLOAD identifies each ULD hold whose cargo door is not configured",()=>{const value=input(),d4=value.d4 as never as{doors:Array<{holdId:string;forwardArm:number|null;aftArm:number|null}>};d4.doors=d4.doors.filter(door=>door.holdId!=="LOWER:ULD");const result=buildFreightAutoloadProblem(value);assert.equal(result.unloadingAccessibilityComplete,false);assert.match(result.warnings.join(" "),/LOWER:ULD has no configured cargo door in D4/);assert.match(result.warnings.join(" "),/placement is preliminary/)});
const pairKey=(left:string,right:string)=>[left,right].sort().join("|");
