import test from"node:test";import assert from"node:assert/strict";
import{validateLoadPlanningProblem,validateLoadPlanningSolution,type LoadPlanningProblem}from"@/domain/load-planning-solver";

const problem=():LoadPlanningProblem=>({version:1,timeLimitSeconds:5,idealTrimIndexScaled:1000,loads:[{id:"AKH0001ZZ",description:"BKK",loadType:"ULD",weightKg:930,volumeLitres:null,uldCode:"AKH",unloadOrder:0,lockedPositionId:null,specialLoadCodes:[],dangerousGoodsClasses:[]},{id:"AKH0002ZZ",description:"DWC",loadType:"ULD",weightKg:745,volumeLitres:null,uldCode:"AKH",unloadOrder:1,lockedPositionId:null,specialLoadCodes:[],dangerousGoodsClasses:[]}],positions:[{id:"31P",description:"Forward",loadType:"ULD",acceptedUldCodes:["AKH"],maximumWeightKg:1588,maximumVolumeLitres:null,occupiedBayIds:["31L"],handlingRank:0,simplicityGroup:"LOWER",indexPerKgScaled:10,holdId:"LOWER",locationRef:"31P",segregationGroup:"LOWER:FWD",balanceArm:10,deckCode:"LOWER"},{id:"32P",description:"Aft",loadType:"ULD",acceptedUldCodes:["AKH"],maximumWeightKg:1588,maximumVolumeLitres:null,occupiedBayIds:["32L"],handlingRank:1,simplicityGroup:"LOWER",indexPerKgScaled:12,holdId:"LOWER",locationRef:"32P",segregationGroup:"LOWER:AFT",balanceArm:20,deckCode:"LOWER"}],incompatiblePairs:[],specialLoadLimits:[]});
test("AUTOLOAD validates a complete solver-neutral problem",()=>{assert.deepEqual(validateLoadPlanningProblem(problem()),problem())});
test("AUTOLOAD rejects a load without a compatible position",()=>{const value=problem();value.loads[0].weightKg=2000;assert.throws(()=>validateLoadPlanningProblem(value),/no compatible loading position/)});
test("AUTOLOAD independently rejects overlapping solver output",()=>{const value=problem();value.positions[1].occupiedBayIds=["31L"];assert.throws(()=>validateLoadPlanningSolution(value,{status:"FEASIBLE",engine:"test",solveMilliseconds:1,assignments:[{loadId:"AKH0001ZZ",positionId:"31P"},{loadId:"AKH0002ZZ",positionId:"32P"}],sequencePenalty:0,usedSimplicityGroups:1,trimDeviationScaled:0,messages:[]}),/overlapping assignment/)});
test("AUTOLOAD independently rejects incompatible loads in one compartment",()=>{const value=problem();value.loads[0].dangerousGoodsClasses=["3"];value.loads[1].dangerousGoodsClasses=["5.1"];value.positions[1].segregationGroup="LOWER:FWD";value.incompatiblePairs=[{left:"DGR:3",right:"DGR:5.1",reason:"IATA DGR Table 9.3.A"}];assert.throws(()=>validateLoadPlanningSolution(value,{status:"FEASIBLE",engine:"test",solveMilliseconds:1,assignments:[{loadId:"AKH0001ZZ",positionId:"31P"},{loadId:"AKH0002ZZ",positionId:"32P"}],sequencePenalty:0,usedSimplicityGroups:1,trimDeviationScaled:0,messages:[]}),/same cargo compartment/)});
test("AUTOLOAD independently rejects a Bulk volume exceedance",()=>{const value=problem();for(const load of value.loads){load.loadType="BULK";load.uldCode=null;load.volumeLitres=600}for(const position of value.positions){position.loadType="BULK";position.acceptedUldCodes=[];position.maximumWeightKg=3000;position.maximumVolumeLitres=1000}assert.throws(()=>validateLoadPlanningSolution(value,{status:"FEASIBLE",engine:"test",solveMilliseconds:1,assignments:[{loadId:"AKH0001ZZ",positionId:"31P"},{loadId:"AKH0002ZZ",positionId:"31P"}],sequencePenalty:0,usedSimplicityGroups:1,trimDeviationScaled:0,messages:[]}),/Bulk volume limit/)});
