import type{OperationalFlightStatus}from"@/domain/operational-flights";
export type OperationalItineraryLeg={scheduleLegId:string|null;legSequence:number;departureAirport:string;arrivalAirport:string;departureTime:string;arrivalTime:string;arrivalDayOffset:number;aircraftType:string;aircraftSubtype:string|null;aircraftConfiguration:string|null;current:boolean};
export type OperationalItinerary={key:string;route:string;legs:OperationalItineraryLeg[]};
export type DailyBoardFlight={operationalFlightId:string|null;scheduleLegId:string|null;sourceType:"SCHEDULED"|"AD_HOC";status:OperationalFlightStatus;flightNumber:string;airlineDesignator:string;operationalSuffix:string;legSequence:number;departureAirport:string;arrivalAirport:string;departureLocal:string;arrivalLocal:string;aircraftType:string;aircraftSubtype:string|null;aircraftConfiguration:string|null;aircraftRegistration:string|null;crewCode:string|null;pantryCode:string|null;passengerWeightBasis:string|null;baggageWeightBasis:string|null;itinerary:OperationalItinerary;ready:boolean;canStart:boolean;scheduleName:string|null;updatedAt:string|null};
export type DailyLoadControlBoard={serviceDate:string;airport:string|null;canOperate:boolean;flights:DailyBoardFlight[];airports:{iata:string;name:string}[];aircraft:{typeCode:string;subtype:string;name:string}[];serviceTypes:{code:string;name:string}[]};
export type OperationalFlightEvent={eventId:number;eventType:string;previousStatus:string|null;newStatus:string|null;occurredAt:string};
export type OperationalFlightDetail={operationalFlightId:string;sourceType:"SCHEDULED"|"AD_HOC";serviceDate:string;airlineDesignator:string;flightNumber:string;operationalSuffix:string;status:OperationalFlightStatus;legSequence:number;departureAirport:string;arrivalAirport:string;departureLocal:string;arrivalLocal:string;departureUtcOffsetMinutes:number|null;arrivalUtcOffsetMinutes:number|null;aircraftType:string;aircraftSubtype:string;aircraftConfiguration:string|null;aircraftRegistration:string|null;crewCode:string|null;pantryCode:string|null;passengerWeightBasis:string|null;baggageWeightBasis:string|null;itinerary:OperationalItinerary;remarks:string|null;version:number;startedAt:string;updatedAt:string;events:OperationalFlightEvent[]};
export type AdHocFlightInput={serviceDate:string;flightNumber:string;operationalSuffix:string;serviceType:string;departureAirport:string;arrivalAirport:string;departureTime:string;arrivalTime:string;arrivalDayOffset:number;aircraftType:string;aircraftSubtype:string;aircraftConfiguration:string|null;aircraftRegistration:string|null;remarks:string|null};
export interface OperationalFlightRepository{board(iata:string,date:string,airport:string|null):Promise<DailyLoadControlBoard>;start(iata:string,scheduleLegId:string,date:string):Promise<string>;createAdHoc(iata:string,input:AdHocFlightInput):Promise<string>;get(iata:string,id:string):Promise<OperationalFlightDetail>}
