import type{OperationalFlightStatus}from"@/domain/operational-flights";
import type{FreightPlanningInput}from"@/domain/operational-flights";
import type{FreightAcceptanceInput,FreightLoadItem,FreightPlanningDensities,FreightSpecialLoadOption,FreightUldLimit}from"@/domain/freight-acceptance";
export type OperationalItineraryLeg={scheduleLegId:string|null;legSequence:number;departureAirport:string;arrivalAirport:string;departureTime:string;arrivalTime:string;arrivalDayOffset:number;aircraftType:string;aircraftSubtype:string|null;aircraftConfiguration:string|null;current:boolean};
export type OperationalItinerary={key:string;route:string;legs:OperationalItineraryLeg[]};
export type DailyBoardFlight={operationalFlightId:string|null;scheduleLegId:string|null;sourceType:"SCHEDULED"|"AD_HOC";status:OperationalFlightStatus;flightNumber:string;airlineDesignator:string;operationalSuffix:string;legSequence:number;departureAirport:string;arrivalAirport:string;departureLocal:string;arrivalLocal:string;aircraftType:string;aircraftSubtype:string|null;aircraftConfiguration:string|null;aircraftRegistration:string|null;crewCode:string|null;pantryCode:string|null;passengerWeightBasis:string|null;baggageWeightBasis:string|null;itinerary:OperationalItinerary;ready:boolean;canStart:boolean;scheduleName:string|null;updatedAt:string|null};
export type DailyLoadControlBoard={serviceDate:string;airport:string|null;canOperate:boolean;flights:DailyBoardFlight[];airports:{iata:string;name:string}[];aircraft:{typeCode:string;subtype:string;name:string;operatingRole?:string}[];serviceTypes:{code:string;name:string}[]};
export type OperationalFlightEvent={eventId:number;eventType:string;previousStatus:string|null;newStatus:string|null;occurredAt:string};
export type FreightPlanningOption={code:string;isBase:boolean};
export type FreightRegistrationOption={registration:string;weight:number|null};
export type FreightUldPositionGroup={deck:string;uldType:string;uldCode:string|null;positionCount:number;maximumWeight:number};
export type FreightBulkHold={holdId:string;name:string;maximumWeight:number;volume:number;planningWeight:number};
export type OperationalFreightPlanning={applicable:boolean;operatingRole:string;canEdit:boolean;version:number;weightBasis:"FLEET_WEIGHT"|"REGISTRATION";registration:string|null;crewCode:string|null;pantryCode:string|null;startWeightPrinciple:string;fleetWeight:number|null;planningAircraftWeight:number|null;crewWeightAdjustment:number;pantryWeightAdjustment:number;mzfw:number|null;structuralCapacity:number|null;cargoPlanningDensity:number|null;uldPositionGroups:FreightUldPositionGroup[];uldWeightCapacity:number;bulkHolds:FreightBulkHold[];bulkWeightCapacity:number;spaceWeightCapacity:number;cargoOfferWeight:number|null;limitingFactor:"MZFW"|"HOLD_CAPACITY";ready:boolean;missing:string[];registrationOptions:FreightRegistrationOption[];crewOptions:FreightPlanningOption[];pantryOptions:FreightPlanningOption[]};
export type OperationalFreightAcceptance={applicable:boolean;canEdit:boolean;version:number;status:"EMPTY"|"NEEDS_REVIEW"|"ACCEPTED"|"RELEASED";source:"MANUAL"|"CSV"|"AHM581"|"MIXED"|null;sourceReference:string|null;rawMessage:string|null;items:FreightLoadItem[];totalWeight:number;cargoOfferWeight:number|null;remainingOffer:number|null;predictedUnderload:number|null;releasedAt:string|null;withinOffer:boolean;updatedAt:string|null;specialLoadOptions:FreightSpecialLoadOption[];uldLimits:FreightUldLimit[];planningDensities:FreightPlanningDensities};
export type OperationalFlightDetail={operationalFlightId:string;sourceType:"SCHEDULED"|"AD_HOC";serviceDate:string;airlineDesignator:string;flightNumber:string;operationalSuffix:string;status:OperationalFlightStatus;legSequence:number;departureAirport:string;arrivalAirport:string;departureLocal:string;arrivalLocal:string;departureUtcOffsetMinutes:number|null;arrivalUtcOffsetMinutes:number|null;aircraftType:string;aircraftSubtype:string;aircraftConfiguration:string|null;aircraftRegistration:string|null;crewCode:string|null;pantryCode:string|null;passengerWeightBasis:string|null;baggageWeightBasis:string|null;itinerary:OperationalItinerary;remarks:string|null;version:number;startedAt:string;updatedAt:string;events:OperationalFlightEvent[];freightPlanning:OperationalFreightPlanning;freightAcceptance:OperationalFreightAcceptance};
export type AdHocFlightInput={serviceDate:string;flightNumber:string;operationalSuffix:string;serviceType:string;departureAirport:string;arrivalAirport:string;departureTime:string;arrivalTime:string;arrivalDayOffset:number;aircraftType:string;aircraftSubtype:string;aircraftConfiguration:string|null;aircraftRegistration:string|null;remarks:string|null};
export interface OperationalFlightRepository{board(iata:string,date:string,airport:string|null):Promise<DailyLoadControlBoard>;start(iata:string,scheduleLegId:string,date:string):Promise<string>;createAdHoc(iata:string,input:AdHocFlightInput):Promise<string>;get(iata:string,id:string):Promise<OperationalFlightDetail>;saveFreightPlanning(iata:string,id:string,version:number,input:FreightPlanningInput):Promise<OperationalFreightPlanning>;saveFreightAcceptance(iata:string,id:string,version:number,input:FreightAcceptanceInput):Promise<OperationalFreightAcceptance>}
