import Link from"next/link";
import{notFound,redirect}from"next/navigation";
import{operationalFlightServices}from"@/composition/services";
import{AuthenticationRequired,CarrierUnavailable}from"@/domain/models";
import{OperationalFlightInvalid}from"@/domain/operational-flights";
import{WorkspaceShell}from"@/components/workspace-shell";
import{DailyLoadControlBoard}from"@/components/daily-load-control-board";
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Manila",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
export default async function LoadControlPage({params,searchParams}:{params:Promise<{iata:string}>;searchParams:Promise<{date?:string;airport?:string}>}){const{iata}=await params,query=await searchParams,date=query.date??today(),airport=query.airport??"";const result=await(await operationalFlightServices()).board(iata,date,airport).catch(error=>{if(error instanceof AuthenticationRequired)redirect("/login");if(error instanceof CarrierUnavailable)notFound();if(error instanceof OperationalFlightInvalid)redirect(`/carrier/${encodeURIComponent(iata)}/load-control`);throw error});if(airport&&!result.board.airports.some(row=>row.iata===airport.toUpperCase()))redirect(`/carrier/${encodeURIComponent(iata)}/load-control?date=${encodeURIComponent(result.board.serviceDate)}`);return <WorkspaceShell user={result.user}><Link href={`/carrier/${encodeURIComponent(iata)}/dashboard`} className="back">← Carrier Home</Link><p className="eyebrow">LOAD CONTROL / {result.carrier.iata}</p><div className="load-control-heading"><div><h1>Daily Load Control</h1><p className="dashboard-intro">Start today’s scheduled sectors, add operational flights without changing the published schedule, and open each flight’s working record.</p></div><form><label>Date<input type="date" name="date" defaultValue={result.board.serviceDate}/></label><label>Airport<select name="airport" defaultValue={result.board.airport??""}><option value="">All airports</option>{result.board.airports.map(a=><option value={a.iata} key={a.iata}>{a.iata} · {a.name}</option>)}</select></label><button type="submit">VIEW BOARD</button></form></div><DailyLoadControlBoard iata={iata} board={result.board}/></WorkspaceShell>}
