begin;
alter table "Basic_Carrier_Record"."Aircraft_Configurations"
 add constraint "Aircraft_Configurations_Code_check" check (btrim("Configuration_Code") ~ '^[A-Z0-9]$'),
 add constraint "Aircraft_Configurations_Class_Seats_check" check ("Seat_Class_Code_1">=0 and coalesce("Seat_Class_Code_2",0)>=0 and coalesce("Seat_Class_Code_3",0)>=0 and coalesce("Seat_Class_Code_4",0)>=0),
 add constraint "Aircraft_Configurations_Total_Seats_check" check ("Total_Seats_Cabin_Area_ID">0 and "Total_Seats_Cabin_Area_ID"="Seat_Class_Code_1"+coalesce("Seat_Class_Code_2",0)+coalesce("Seat_Class_Code_3",0)+coalesce("Seat_Class_Code_4",0)),
 add constraint "Aircraft_Configurations_BA_Order_check" check ("Cabin_Area_BA_Start"<="Cabin_Area_BA_Centroid" and "Cabin_Area_BA_Centroid"<="Cabin_Area_BA_End"),
 add constraint "Aircraft_Configurations_Index_check" check (abs("Cabin_Area_Index_Per_Weight_Unit")<=1000000000);
create or replace function "Basic_Carrier_Record".get_aircraft_d9(p_iata text,p_type_code text,p_subtype text) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare tc text:=upper(btrim(p_type_code));st text:=upper(btrim(p_subtype));can_view boolean:=(select auth.uid()) is not null and (private.has_carrier_permission(p_iata,'AIRCRAFT_CONFIG_VIEW') or private.has_global_permission('AIRCRAFT_CONFIG_VIEW'));can_edit boolean:=private.has_carrier_permission(p_iata,'AIRCRAFT_CONFIG_EDIT') or private.has_global_permission('AIRCRAFT_CONFIG_EDIT');areas jsonb;classes jsonb;configs jsonb:='[]';cfg record;rows jsonb;
begin if not can_view then raise exception 'Not authorised' using errcode='42501';end if;
 select coalesce(jsonb_agg(jsonb_build_object('id',btrim("Cabin_Area_ID"),'rowFrom',"Cabin_Area_Start_Row",'rowTo',"Cabin_Area_End_Row",'centroid',"Cabin_Area_BA_Centroid",'from',"Cabin_Area_BA_Start",'to',"Cabin_Area_BA_End",'index',"Cabin_Area_Index_Per_Weight_Unit") order by "Cabin_Area_Start_Row"),'[]') into areas from "Basic_Carrier_Record"."Aircraft_Cabin_Areas" where "Carrier_IATA"=p_iata and "Aircraft_Type_IATA"=tc and "Aircraft_Series_Subtype"=st;
 select coalesce(jsonb_build_array(jsonb_build_object('slot',1,'code',btrim("Carrier_Class_1_Code"),'name',btrim("Carrier_Class_1_Name")),jsonb_build_object('slot',2,'code',btrim("Carrier_Class_2_Code"),'name',btrim("Carrier_Class_2_Name")),jsonb_build_object('slot',3,'code',btrim("Carrier_Class_3_Code"),'name',btrim("Carrier_Class_3_Name")),jsonb_build_object('slot',4,'code',btrim("Carrier_Class_4_Code"),'name',btrim("Carrier_Class_4_Name"))),'[]') into classes from "Basic_Carrier_Record"."Carrier_Class_Codes" where "Carrier_IATA"=p_iata;
 for cfg in select btrim("Configuration_Code") code,min(btrim("Configuration_Code_Description")) description from "Basic_Carrier_Record"."Aircraft_Configurations" where "Carrier_IATA"=p_iata and "Aircraft_Type_IATA"=tc and "Aircraft_Series_Subtype"=st group by btrim("Configuration_Code") order by 1 loop
  select coalesce(jsonb_agg(jsonb_build_object('areaId',btrim("Cabin_Area_ID"),'classSeats',jsonb_build_array("Seat_Class_Code_1",coalesce("Seat_Class_Code_2",0),coalesce("Seat_Class_Code_3",0),coalesce("Seat_Class_Code_4",0)),'totalSeats',"Total_Seats_Cabin_Area_ID",'centroid',"Cabin_Area_BA_Centroid",'from',"Cabin_Area_BA_Start",'to',"Cabin_Area_BA_End",'index',"Cabin_Area_Index_Per_Weight_Unit") order by btrim("Cabin_Area_ID")),'[]') into rows from "Basic_Carrier_Record"."Aircraft_Configurations" where "Carrier_IATA"=p_iata and "Aircraft_Type_IATA"=tc and "Aircraft_Series_Subtype"=st and btrim("Configuration_Code")=cfg.code;
  configs:=configs||jsonb_build_array(jsonb_build_object('code',cfg.code,'description',cfg.description,'rows',rows));end loop;
 return jsonb_build_object('canView',can_view,'canEdit',can_edit,'revision',md5((areas||classes||configs)::text),'typeCode',tc,'subtype',st,'cabinAreas',areas,'classes',classes,'configurations',configs);end $$;
revoke all on function "Basic_Carrier_Record".get_aircraft_d9(text,text,text) from public,anon;grant execute on function "Basic_Carrier_Record".get_aircraft_d9(text,text,text) to authenticated;
create or replace function "Basic_Carrier_Record".save_aircraft_d9(p_iata text,p_type_code text,p_subtype text,p_revision text,p_original_code text,p_values jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare tc text:=upper(btrim(p_type_code));st text:=upper(btrim(p_subtype));code text:=upper(btrim(p_values->>'code'));description text:=btrim(p_values->>'description');item jsonb;
begin if not (private.has_carrier_permission(p_iata,'AIRCRAFT_CONFIG_EDIT') or private.has_global_permission('AIRCRAFT_CONFIG_EDIT')) then raise exception 'Not authorised' using errcode='42501';end if;if "Basic_Carrier_Record".get_aircraft_d9(p_iata,tc,st)->>'revision'<>p_revision then raise exception 'Conflict' using errcode='40001';end if;if jsonb_array_length(p_values->'rows')<1 then raise exception 'Rows required' using errcode='22023';end if;
 if p_original_code is not null then delete from "Basic_Carrier_Record"."Aircraft_Configurations" where "Carrier_IATA"=p_iata and "Aircraft_Type_IATA"=tc and "Aircraft_Series_Subtype"=st and btrim("Configuration_Code")=upper(btrim(p_original_code));end if;
 for item in select value from jsonb_array_elements(p_values->'rows') loop insert into "Basic_Carrier_Record"."Aircraft_Configurations"("Carrier_IATA","Aircraft_Type_IATA","Aircraft_Series_Subtype","Configuration_Code","Configuration_Code_Description","Cabin_Area_ID","Seat_Class_Code_1","Seat_Class_Code_2","Seat_Class_Code_3","Seat_Class_Code_4","Total_Seats_Cabin_Area_ID","Cabin_Area_BA_Centroid","Cabin_Area_BA_Start","Cabin_Area_BA_End","Cabin_Area_Index_Per_Weight_Unit") values(p_iata,tc,st,code,description,btrim(item->>'areaId'),(item->'classSeats'->>0)::integer,(item->'classSeats'->>1)::integer,(item->'classSeats'->>2)::integer,(item->'classSeats'->>3)::integer,(item->>'totalSeats')::integer,(item->>'centroid')::double precision,(item->>'from')::double precision,(item->>'to')::double precision,(item->>'index')::double precision);end loop;return "Basic_Carrier_Record".get_aircraft_d9(p_iata,tc,st);end $$;
revoke all on function "Basic_Carrier_Record".save_aircraft_d9(text,text,text,text,text,jsonb) from public,anon;grant execute on function "Basic_Carrier_Record".save_aircraft_d9(text,text,text,text,text,jsonb) to authenticated;commit;
