"use server";
import{revalidatePath}from"next/cache";
import{aircraftC7Services,aircraftD2Services,aircraftD3Services,aircraftD4Services,aircraftE12Services,aircraftE2Services,operationalFlightServices}from"@/composition/services";
import{OperationalFlightConflict,OperationalFlightDenied,OperationalFlightInvalid}from"@/domain/operational-flights";
import{buildFreightAutoloadProblem}from"@/domain/freight-autoload";
import{LoadPlanningProblemInvalid,type LoadPlanningProblem,type LoadPlanningSolution}from"@/domain/load-planning-solver";
import{createCpSatLoadPlanningSolver}from"@/infrastructure/solver/cp-sat-load-planning-solver";
export type LoadControlActionState={ok:boolean;message:string;operationalFlightId?:string};
const message=(error:unknown)=>error instanceof OperationalFlightInvalid||error instanceof OperationalFlightConflict||error instanceof OperationalFlightDenied||error instanceof LoadPlanningProblemInvalid?error.message:"The Load Control operation was not completed. Please try again.";
export async function startOperationalFlight(iata:string,scheduleLegId:string,date:string):Promise<LoadControlActionState>{try{const operationalFlightId=await(await operationalFlightServices()).start(iata,scheduleLegId,date);revalidatePath(`/carrier/${iata}/load-control`);return{ok:true,message:"Operational flight started.",operationalFlightId}}catch(error){console.error("[Operational flight start]",error);return{ok:false,message:message(error)}}}
export async function createAdHocOperationalFlight(iata:string,input:unknown):Promise<LoadControlActionState>{try{const operationalFlightId=await(await operationalFlightServices()).createAdHoc(iata,input);revalidatePath(`/carrier/${iata}/load-control`);return{ok:true,message:"Ad-hoc operational flight created.",operationalFlightId}}catch(error){console.error("[Ad-hoc operational flight]",error);return{ok:false,message:message(error)}}}
export async function saveOperationalFreightPlanning(iata:string,operationalFlightId:string,version:number,input:unknown){try{const planning=await(await operationalFlightServices()).saveFreightPlanning(iata,operationalFlightId,version,input);revalidatePath(`/carrier/${iata}/load-control/${operationalFlightId}`);revalidatePath(`/carrier/${iata}/load-control`);return{ok:true,message:"Freight planning basis saved.",planning}}catch(error){console.error("[Freight planning save]",error);return{ok:false,message:message(error),planning:null}}}
export async function saveOperationalFreightAcceptance(iata:string,operationalFlightId:string,version:number,input:unknown){try{const acceptance=await(await operationalFlightServices()).saveFreightAcceptance(iata,operationalFlightId,version,input);revalidatePath(`/carrier/${iata}/load-control/${operationalFlightId}`);revalidatePath(`/carrier/${iata}/load-control`);return{ok:true,message:acceptance.status==="NEEDS_REVIEW"?"Statement saved for review. Resolve every unusual ULD before load planning.":`Payload released for load planning. Initial Predicted Underload: ${Math.round(acceptance.predictedUnderload??0).toLocaleString()} KG.`,acceptance}}catch(error){console.error("[Freight acceptance save]",error);return{ok:false,message:message(error),acceptance:null}}}

export type AutoloadActionState={ok:boolean;message:string;problem:LoadPlanningProblem|null;solution:LoadPlanningSolution|null;warnings:string[]};
export async function proposeOperationalAutoload(iata:string,operationalFlightId:string):Promise<AutoloadActionState>{try{const result=await(await operationalFlightServices()).get(iata,operationalFlightId),flight=result.flight,type=flight.aircraftType,subtype=flight.aircraftSubtype;if(!subtype)throw new LoadPlanningProblemInvalid("Assign an aircraft subtype before running AUTOLOAD.");const[d2,d3,d4,c7,e12,e2]=await Promise.all([(await aircraftD2Services()).get(iata,type,subtype),(await aircraftD3Services()).get(iata,type,subtype),(await aircraftD4Services()).get(iata,type,subtype),(await aircraftC7Services()).get(iata,type,subtype),(await aircraftE12Services()).get(iata,type,subtype),(await aircraftE2Services()).get(iata,type,subtype)]),context=buildFreightAutoloadProblem({flight,d2,d3,d4,c7,e12,e2}),solution=await createCpSatLoadPlanningSolver().solve(context.problem);return{ok:solution.status==="OPTIMAL"||solution.status==="FEASIBLE",message:solution.status==="OPTIMAL"?"AUTOLOAD found and proved the best proposal for the configured priorities.":solution.status==="FEASIBLE"?"AUTOLOAD found a valid proposal within the time limit.":solution.status==="INFEASIBLE"?"AUTOLOAD could not place every released load within the configured constraints.":"AUTOLOAD did not find a complete proposal within the time limit.",problem:context.problem,solution,warnings:context.warnings}}catch(error){console.error("[Operational AUTOLOAD]",error);return{ok:false,message:message(error),problem:null,solution:null,warnings:[]}}}
