"use server";
import{revalidatePath}from"next/cache";
import{aircraftC2Services,aircraftC4Services,aircraftC5Services,aircraftC7Services,aircraftC8Services,aircraftD2Services,aircraftD3Services,aircraftD4Services,aircraftE12Services,aircraftE2Services,aircraftH1Services,operationalFlightServices}from"@/composition/services";
import{OperationalFlightConflict,OperationalFlightDenied,OperationalFlightInvalid}from"@/domain/operational-flights";
import{buildFreightAutoloadProblem}from"@/domain/freight-autoload";
import{LoadPlanningProblemInvalid,validateLoadPlanningSolution,type LoadPlanningProblem,type LoadPlanningSolution}from"@/domain/load-planning-solver";
import{createCpSatLoadPlanningSolver}from"@/infrastructure/solver/cp-sat-load-planning-solver";
import{loadHoldLayout}from"@/app/hold-layout-actions";
import type{HoldLayout}from"@/domain/hold-layout";
import type{AircraftC5Values}from"@/domain/aircraft-c5";
import type{AircraftC4Values}from"@/domain/aircraft-c4";
import type{AircraftC7Point}from"@/domain/aircraft-c7";
import{aircraftC5ApplicabilityFromC2,type AircraftC5Applicability}from"@/domain/aircraft-c2-status";
import{displayUnit}from"@/domain/display-standards";
export type LoadControlActionState={ok:boolean;message:string;operationalFlightId?:string};
const message=(error:unknown)=>error instanceof OperationalFlightInvalid||error instanceof OperationalFlightConflict||error instanceof OperationalFlightDenied||error instanceof LoadPlanningProblemInvalid?error.message:"The Load Control operation was not completed. Please try again.";
export async function startOperationalFlight(iata:string,scheduleLegId:string,date:string):Promise<LoadControlActionState>{try{const operationalFlightId=await(await operationalFlightServices()).start(iata,scheduleLegId,date);revalidatePath(`/carrier/${iata}/load-control`);return{ok:true,message:"Operational flight started.",operationalFlightId}}catch(error){console.error("[Operational flight start]",error);return{ok:false,message:message(error)}}}
export async function createAdHocOperationalFlight(iata:string,input:unknown):Promise<LoadControlActionState>{try{const operationalFlightId=await(await operationalFlightServices()).createAdHoc(iata,input);revalidatePath(`/carrier/${iata}/load-control`);return{ok:true,message:"Ad-hoc operational flight created.",operationalFlightId}}catch(error){console.error("[Ad-hoc operational flight]",error);return{ok:false,message:message(error)}}}
export async function saveOperationalFreightPlanning(iata:string,operationalFlightId:string,version:number,input:unknown){try{const planning=await(await operationalFlightServices()).saveFreightPlanning(iata,operationalFlightId,version,input);revalidatePath(`/carrier/${iata}/load-control/${operationalFlightId}`);revalidatePath(`/carrier/${iata}/load-control`);return{ok:true,message:"Freight planning basis saved.",planning}}catch(error){console.error("[Freight planning save]",error);return{ok:false,message:message(error),planning:null}}}
export async function saveOperationalFreightAcceptance(iata:string,operationalFlightId:string,version:number,input:unknown){try{const acceptance=await(await operationalFlightServices()).saveFreightAcceptance(iata,operationalFlightId,version,input);revalidatePath(`/carrier/${iata}/load-control/${operationalFlightId}`);revalidatePath(`/carrier/${iata}/load-control`);return{ok:true,message:acceptance.status==="NEEDS_REVIEW"?"Statement saved for review. Resolve every unusual ULD before load planning.":`Payload released for load planning. Initial Predicted Underload: ${Math.round(acceptance.predictedUnderload??0).toLocaleString()} KG.`,acceptance}}catch(error){console.error("[Freight acceptance save]",error);return{ok:false,message:message(error),acceptance:null}}}

export type AutoloadFuelCurve={id:string;label:string;points:Array<{fuelWeight:number;indexValue:number}>};
export type AutoloadEnvelopePreview={values:AircraftC5Values;applicability:AircraftC5Applicability;unit:string;formula:AircraftC4Values|null;idealTrimPoints:AircraftC7Point[];estimatedZfwWeight:number;operationalBaseIndex:number|null;fuelCurves:AutoloadFuelCurve[]};
export type AutoloadActionState={ok:boolean;message:string;problem:LoadPlanningProblem|null;solution:LoadPlanningSolution|null;warnings:string[];layout:HoldLayout|null;layoutOffsetX:number;envelope:AutoloadEnvelopePreview|null;edition:number|null};
type PreparedAutoload={services:Awaited<ReturnType<typeof operationalFlightServices>>;flight:Awaited<ReturnType<Awaited<ReturnType<typeof operationalFlightServices>>["get"]>>["flight"];context:ReturnType<typeof buildFreightAutoloadProblem>;layoutResult:Awaited<ReturnType<typeof loadHoldLayout>>;warnings:string[];envelope:AutoloadEnvelopePreview|null};
async function prepareOperationalAutoload(iata:string,operationalFlightId:string):Promise<PreparedAutoload>{
 const services=await operationalFlightServices(),result=await services.get(iata,operationalFlightId),flight=result.flight,type=flight.aircraftType,subtype=flight.aircraftSubtype;
 if(!subtype)throw new LoadPlanningProblemInvalid("Assign an aircraft subtype before running AUTOLOAD.");
 const[d2,d3,d4,c7,e12,e2,h1,c2,c4,c5]=await Promise.all([
  (await aircraftD2Services()).get(iata,type,subtype),(await aircraftD3Services()).get(iata,type,subtype),(await aircraftD4Services()).get(iata,type,subtype),(await aircraftC7Services()).get(iata,type,subtype),(await aircraftE12Services()).get(iata,type,subtype),(await aircraftE2Services()).get(iata,type,subtype),(await aircraftH1Services()).get(iata,type,subtype),
  (await aircraftC2Services()).get(iata,type,subtype).catch(error=>{console.error("[AUTOLOAD C2]",error);return null}),(await aircraftC4Services()).get(iata,type,subtype).catch(error=>{console.error("[AUTOLOAD C4]",error);return null}),(await aircraftC5Services()).get(iata,type,subtype).catch(error=>{console.error("[AUTOLOAD C5]",error);return null})
 ]),c8=await(await aircraftC8Services()).get(iata,type,subtype).catch(error=>{console.error("[AUTOLOAD C8]",error);return null}),context=buildFreightAutoloadProblem({flight,d2,d3,d4,c7,e12,e2,h1}),registration=flight.freightPlanning.registration?e12.registrations.find(row=>row.registration===flight.freightPlanning.registration):null,layoutResult=await loadHoldLayout(iata,type,subtype,registration?.fuelConfigurationCode??null),warnings=[...context.warnings],allFuelRows=c8?.canView&&c8.values.standard.enabled?c8.values.standard.rows:[],configurationRows=context.fuelConfigurationCode?allFuelRows.filter(row=>row.configurationCode===context.fuelConfigurationCode):[],fuelRows=configurationRows.length?configurationRows:allFuelRows.filter(row=>!row.configurationCode),fuelGroups=new Map<string,typeof fuelRows>();
 for(const row of fuelRows){const key=`${row.configurationCode??"ALL"}|${row.specificGravity}`,rows=fuelGroups.get(key)??[];rows.push(row);fuelGroups.set(key,rows)}
 const fuelCurves:AutoloadFuelCurve[]=[...fuelGroups].map(([id,rows])=>({id,label:`${rows[0].configurationCode??"ALL"} · SG ${rows[0].specificGravity.toFixed(3)}`,points:rows.map(row=>({fuelWeight:row.fuelWeight,indexValue:row.indexValue})).sort((a,b)=>a.fuelWeight-b.fuelWeight)})),envelope=c2&&c5?.canView?{values:c5.values,applicability:aircraftC5ApplicabilityFromC2(c2),unit:displayUnit(c5.weightUnit)||"Kg",formula:c4?.exists?c4.values:null,idealTrimPoints:c7.values.idealTrim.points,estimatedZfwWeight:context.estimatedZfwWeight,operationalBaseIndex:context.operationalBaseIndex,fuelCurves}:null;
 if(!layoutResult.ok)warnings.push(`The aircraft overlay is unavailable: ${layoutResult.error}`);
 return{services,flight,context,layoutResult,warnings,envelope};
}
const autoloadMessage=(solution:LoadPlanningSolution,unloadingAccessibilityComplete:boolean)=>solution.status==="OPTIMAL"?(unloadingAccessibilityComplete?"AUTOLOAD found and proved the best proposal for the configured priorities.":"AUTOLOAD found the best proposal for the available data. Unloading accessibility remains preliminary until every applicable cargo door is configured."):solution.status==="FEASIBLE"?"AUTOLOAD found a valid proposal within the time limit.":solution.status==="INFEASIBLE"?"AUTOLOAD could not place every released load within the configured constraints.":"AUTOLOAD did not find a complete proposal within the time limit.";
const preparedState=(prepared:PreparedAutoload,solution:LoadPlanningSolution,edition:number,message:string):AutoloadActionState=>({ok:solution.status==="OPTIMAL"||solution.status==="FEASIBLE",message,problem:prepared.context.problem,solution,warnings:prepared.warnings,layout:prepared.layoutResult.ok?prepared.layoutResult.layout:null,layoutOffsetX:prepared.layoutResult.ok?prepared.layoutResult.calibration.offsetX:0,envelope:prepared.envelope,edition});

export async function restoreOperationalLoadPlan(iata:string,operationalFlightId:string):Promise<AutoloadActionState>{try{const prepared=await prepareOperationalAutoload(iata,operationalFlightId),plan=prepared.flight.loadPlan;if(plan.edition<1||!plan.solution)throw new LoadPlanningProblemInvalid("No saved load-plan edition is available.");if(plan.createdAt&&prepared.flight.freightAcceptance.updatedAt&&new Date(prepared.flight.freightAcceptance.updatedAt).getTime()>new Date(plan.createdAt).getTime())throw new LoadPlanningProblemInvalid("The released uplift was amended after this load plan. Run AUTOLOAD to create a revised edition.");const solution=validateLoadPlanningSolution(prepared.context.problem,plan.solution);return preparedState(prepared,solution,plan.edition,`Load plan Edition ${plan.edition} restored.`)}catch(error){console.error("[Operational load plan restore]",error);return{ok:false,message:message(error),problem:null,solution:null,warnings:[],layout:null,layoutOffsetX:0,envelope:null,edition:null}}}

export async function proposeOperationalAutoload(iata:string,operationalFlightId:string,expectedEdition:number):Promise<AutoloadActionState>{try{const prepared=await prepareOperationalAutoload(iata,operationalFlightId),solution=await createCpSatLoadPlanningSolver().solve(prepared.context.problem),ok=solution.status==="OPTIMAL"||solution.status==="FEASIBLE",edition=ok?(await prepared.services.saveLoadPlan(iata,operationalFlightId,expectedEdition,"AUTOLOAD",solution)).edition:expectedEdition;return preparedState(prepared,solution,edition,autoloadMessage(solution,prepared.context.unloadingAccessibilityComplete))}catch(error){console.error("[Operational AUTOLOAD]",error);return{ok:false,message:message(error),problem:null,solution:null,warnings:[],layout:null,layoutOffsetX:0,envelope:null,edition:null}}}


export async function reviseOperationalLoadPlan(iata:string,operationalFlightId:string,expectedEdition:number,source:"MANUAL"|"RESET",problem:LoadPlanningProblem,solution:LoadPlanningSolution){try{validateLoadPlanningSolution(problem,solution);const plan=await(await operationalFlightServices()).saveLoadPlan(iata,operationalFlightId,expectedEdition,source,solution);revalidatePath(`/carrier/${iata}/load-control/${operationalFlightId}`);return{ok:true,message:`Load plan Edition ${plan.edition} saved.`,edition:plan.edition}}catch(error){console.error("[Operational load plan revision]",error);return{ok:false,message:message(error),edition:expectedEdition}}}
