import type { BaggageTables } from "./baggage-tables";
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
// Minimal read contract verified against the live schema on 2026-09-15.
// Database naming and types remain inside this adapter.
export type Database = {
  Basic_Carrier_Record: {
    Tables: BaggageTables & {
      Carrier_Units_of_Measure: {
        Row: {Carrier_IATA:string;Density_Checked_Baggage:number|null;Density_General_Cargo:number|null;Density_General_Mail:number|null};
        Insert: {Carrier_IATA:string;Density_Checked_Baggage:number|null;Density_General_Cargo:number|null;Density_General_Mail:number|null};
        Update: {Density_Checked_Baggage?:number|null;Density_General_Cargo?:number|null;Density_General_Mail?:number|null};
        Relationships: [];
      };
      Carrier_Configuration_Review_State:{
        Row:{Carrier_IATA:string;Page_Code:string;Section_Code:string;Review_State:string;Reviewed_At:string};
        Insert:{Carrier_IATA:string;Page_Code:string;Section_Code:string;Review_State:string;Reviewed_At?:string};
        Update:{Review_State?:string;Reviewed_At?:string};
        Relationships:[];
      };
      Carrier_Branding: {
        Row: { Carrier_IATA: string; logo_path: string | null; updated_at: string };
        Insert: { Carrier_IATA: string; logo_path?: string | null; updated_at?: string };
        Update: { Carrier_IATA?: string; logo_path?: string | null; updated_at?: string };
        Relationships: [];
      };
      MASTER_Carrier_Contact: {
        Row: { Carrier_IATA: string; Carrier_Name: string; Carrier_ICAO: string };
        Insert: { Carrier_IATA: string; Carrier_Name: string; Carrier_ICAO: string };
        Update: { Carrier_IATA?: string; Carrier_Name?: string; Carrier_ICAO?: string };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      aircraft_layout_library:{Args:Record<string,never>;Returns:Json};
      get_aircraft_layout:{Args:{p_iata:string;p_type:string;p_subtype:string};Returns:Json};
      activate_aircraft_layout:{Args:{p_id:string};Returns:undefined};
      get_carrier_ulds:{Args:{p_iata:string;p_type:string;p_subtype:string};Returns:Json};
      save_carrier_ulds:{Args:{p_iata:string;p_type:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      save_carrier_uld_applicability:{Args:{p_iata:string;p_type:string;p_subtype:string;p_revision:string;p_utilises:boolean};Returns:Json};
      get_carrier_densities:{Args:{p_iata:string};Returns:Json};
      save_carrier_densities:{Args:{p_iata:string;p_revision:string;p_values:Json};Returns:Json};
      get_carrier_passenger_weights: { Args: { p_iata: string }; Returns: Json };
      save_carrier_passenger_weights: { Args: { p_iata: string; p_revision: string; p_section: string; p_values: Json }; Returns: Json };
      save_carrier_crew_hold_baggage:{Args:{p_iata:string;p_revision:string;p_code:string|null;p_values:Json};Returns:Json};
      get_carrier_crew_weights: { Args: { p_iata: string }; Returns: Json };
      save_carrier_crew_weights: { Args: { p_iata: string; p_revision: string; p_values: Json }; Returns: Json };
      get_carrier_class_codes: { Args: { p_iata: string }; Returns: Json };
      save_carrier_class_codes: { Args: { p_iata: string; p_revision: string; p_rows: Json }; Returns: Json };
      get_carrier_commodity_codes: { Args: { p_iata: string }; Returns: Json };
      save_carrier_commodity_codes: { Args: { p_iata: string; p_revision: string; p_rows: Json }; Returns: Json };
      current_display_name: { Args: Record<string, never>; Returns: string | null };
      can_create_carrier:{Args:Record<string,never>;Returns:boolean};
      create_carrier:{Args:{p_iata:string;p_name:string;p_icao:string};Returns:Json};
      get_carrier_details: { Args: { p_iata: string }; Returns: Json };
      save_carrier_details: { Args: { p_iata: string; p_revision: string; p_values: Json }; Returns: Json };
      save_carrier_contacts: { Args: { p_iata: string; p_revision: string; p_values: Json }; Returns: Json };
      can_manage_carrier_logo: { Args: { p_iata: string }; Returns: boolean };
      set_carrier_logo: { Args: { p_iata: string; p_path: string | null }; Returns: string | null };
      get_carrier_aircraft:{Args:{p_iata:string};Returns:Json};
      get_aircraft_c1:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      assign_aircraft_manufacturer:{Args:{p_type_code:string;p_subtype:string;p_manufacturer_uuid:string};Returns:undefined};
      search_aircraft_identities:{Args:{p_query:string};Returns:Json};
      search_aircraft_manufacturers:{Args:{p_query:string};Returns:Json};
      create_aircraft_identity:{Args:{p_manufacturer_uuid:string|null;p_manufacturer_name:string;p_type_code:string;p_subtype:string;p_identity_name:string};Returns:Json};
      save_aircraft_c1:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_aircraft_name:string;p_values:Json};Returns:Json};
      get_aircraft_c2:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_c2:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_values:Json};Returns:Json};
      get_aircraft_c4:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_c4:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_values:Json};Returns:Json};
      get_aircraft_c5:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      get_aircraft_c5_effective_dow:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      get_aircraft_c5_input_mode:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_c5:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_section:string;p_values:Json};Returns:Json};
      save_aircraft_c5_status:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_values:Json};Returns:Json};
      get_aircraft_c8:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_c8:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_section:string;p_values:Json};Returns:Json};
      get_aircraft_c11:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_c11:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_values:Json};Returns:Json};
      get_aircraft_d2:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_d2:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_section:string;p_values:Json};Returns:Json};
      get_aircraft_d3:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_d3_configuration:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_original_code:string|null;p_values:Json};Returns:Json};
      delete_aircraft_d3_configuration:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_hold_id:string;p_code:string};Returns:Json};
      get_aircraft_d4:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_d4:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_doors:Json};Returns:Json};
      save_aircraft_d4_applicability:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_section:string;p_active:boolean};Returns:Json};
      get_aircraft_d5:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_d5:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_section:string;p_rows:Json};Returns:Json};
      get_aircraft_d6:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_d6:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_section:string;p_applicable:boolean;p_rows:Json};Returns:Json};
      get_aircraft_d8:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_d8:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_d9:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_d9:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_original_code:string|null;p_values:Json};Returns:Json};
      get_aircraft_d11:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_d11:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_e11:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_e11:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_value:Json};Returns:Json};
      get_aircraft_e12:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_e12_standard:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_value:Json};Returns:Json};
      save_aircraft_e12_registrations:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_e2:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_e2_crew:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      save_aircraft_e2_pantry:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_e3:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_e3_applicability:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_water_active:boolean;p_service_active:boolean};Returns:Json};
      save_aircraft_e3_water:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      save_aircraft_e3_service:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_e4:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_e4_applicability:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_active:boolean;p_additional_active:boolean};Returns:Json};
      save_aircraft_e4_configurations:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      save_aircraft_e4_additional:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_e5:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_e5_approach:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_approach:string};Returns:Json};
      save_aircraft_e5_rows:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_f1:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_f1_definitions:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      save_aircraft_f1_rows:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_g1:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_g1:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_h1:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_h1_applicability:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_dgr_active:boolean;p_iata_active:boolean;p_special_loads_active:boolean};Returns:Json};
      save_aircraft_h1_exceptions:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_kind:string;p_rows:Json};Returns:Json};
      save_aircraft_h1_special_loads:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_c7:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_c7:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_section:string;p_values:Json};Returns:Json};
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
