import type { BaggageTables } from "./baggage-tables";
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
// Minimal read contract verified against the live schema on 2026-09-15.
// Database naming and types remain inside this adapter.
export type Database = {
  Basic_Carrier_Record: {
    Tables: BaggageTables & {
      Carrier_Units_of_Measure: {
        Row: {Carrier_IATA:string;Density_Checked_Baggage:number|null;Density_General_Cargo:number|null;Density_General_Mail:number|null};
        Insert: {Carrier_IATA:string;Density_Checked_Baggage:number|null;Density_General_Cargo:number|null;Density_General_Mail:number|null};
        Update: {Density_Checked_Baggage?:number|null;Density_General_Cargo?:number|null;Density_General_Mail?:number|null};
        Relationships: [];
      };
      Carrier_Configuration_Review_State:{
        Row:{Carrier_IATA:string;Page_Code:string;Section_Code:string;Review_State:string;Reviewed_At:string};
        Insert:{Carrier_IATA:string;Page_Code:string;Section_Code:string;Review_State:string;Reviewed_At?:string};
        Update:{Review_State?:string;Reviewed_At?:string};
        Relationships:[];
      };
      Carrier_Branding: {
        Row: { Carrier_IATA: string; logo_path: string | null; updated_at: string };
        Insert: { Carrier_IATA: string; logo_path?: string | null; updated_at?: string };
        Update: { Carrier_IATA?: string; logo_path?: string | null; updated_at?: string };
        Relationships: [];
      };
      Aircraft_Dashboard_Status_Snapshots:{
        Row:{Carrier_IATA:string;Aircraft_Type_IATA:string;Aircraft_Series_Subtype:string;Overall_Status:string;Attention_Pages:Json;Page_Statuses:Json;Page_Progress:Json;Calculation_Version:number;Updated_At:string};
        Insert:{Carrier_IATA:string;Aircraft_Type_IATA:string;Aircraft_Series_Subtype:string;Overall_Status:string;Attention_Pages:Json;Page_Statuses:Json;Page_Progress:Json;Calculation_Version:number;Updated_At?:string};
        Update:{Overall_Status?:string;Attention_Pages?:Json;Page_Statuses?:Json;Page_Progress?:Json;Calculation_Version?:number;Updated_At?:string};
        Relationships:[];
      };
      Flight_Schedule_Imports:{
        Row:{Import_ID:string;Carrier_IATA:string;Source_Carrier_IATA:string;Source_Format:string;Original_File_Name:string;File_SHA256:string;File_Size_Bytes:number;Source_Encoding:string;SSIM_Edition:string|null;Season_Code:string|null;Creator_Reference:string|null;Coverage_Start_Date:string|null;Coverage_End_Date:string|null;Status:string;Total_Record_Count:number;Accepted_Record_Count:number;Rejected_Record_Count:number;Normalized_Leg_Count:number;Validation_Summary:Json;Uploaded_By:string;Uploaded_At:string;Validated_At:string|null;Published_By:string|null;Published_At:string|null;Superseded_At:string|null};
        Insert:{Import_ID?:string;Carrier_IATA:string;Source_Carrier_IATA:string;Source_Format?:string;Original_File_Name:string;File_SHA256:string;File_Size_Bytes:number;Source_Encoding?:string;SSIM_Edition?:string|null;Season_Code?:string|null;Creator_Reference?:string|null;Coverage_Start_Date?:string|null;Coverage_End_Date?:string|null;Status?:string;Total_Record_Count?:number;Accepted_Record_Count?:number;Rejected_Record_Count?:number;Normalized_Leg_Count?:number;Validation_Summary?:Json;Uploaded_By?:string;Uploaded_At?:string;Validated_At?:string|null;Published_By?:string|null;Published_At?:string|null;Superseded_At?:string|null};
        Update:{SSIM_Edition?:string|null;Season_Code?:string|null;Creator_Reference?:string|null};
        Relationships:[];
      };
      Flight_Schedule_Import_Records:{
        Row:{Import_ID:string;Carrier_IATA:string;Line_Number:number;Record_Type:string;Raw_Record:string;Parse_Status:string;Validation_Messages:Json;Parsed_Data:Json};
        Insert:{Import_ID:string;Carrier_IATA:string;Line_Number:number;Record_Type:string;Raw_Record:string;Parse_Status:string;Validation_Messages?:Json;Parsed_Data?:Json};
        Update:Record<string,never>;
        Relationships:[];
      };
      Scheduled_Flight_Legs:{
        Row:{Schedule_Leg_ID:string;Import_ID:string;Carrier_IATA:string;Source_Line_Number:number;Airline_Designator:string;Flight_Number:string;Operational_Suffix:string;Itinerary_Variation_Identifier:string;Leg_Sequence_Number:number;Service_Type:string;Period_Start_Date:string;Period_End_Date:string;Operating_Days:string;Departure_Airport_IATA:string;Arrival_Airport_IATA:string;Departure_Time_Local:string;Arrival_Time_Local:string;Arrival_Day_Offset:number;Departure_UTC_Offset_Minutes:number|null;Arrival_UTC_Offset_Minutes:number|null;Departure_Terminal:string|null;Arrival_Terminal:string|null;Aircraft_Type_IATA:string|null;Aircraft_Series_Subtype:string|null;Aircraft_Configuration:string|null;Traffic_Restriction_Codes:string|null;Additional_Data:Json};
        Insert:{Schedule_Leg_ID?:string;Import_ID:string;Carrier_IATA:string;Source_Line_Number:number;Airline_Designator:string;Flight_Number:string;Operational_Suffix?:string;Itinerary_Variation_Identifier?:string;Leg_Sequence_Number?:number;Service_Type:string;Period_Start_Date:string;Period_End_Date:string;Operating_Days:string;Departure_Airport_IATA:string;Arrival_Airport_IATA:string;Departure_Time_Local:string;Arrival_Time_Local:string;Arrival_Day_Offset?:number;Departure_UTC_Offset_Minutes?:number|null;Arrival_UTC_Offset_Minutes?:number|null;Departure_Terminal?:string|null;Arrival_Terminal?:string|null;Aircraft_Type_IATA?:string|null;Aircraft_Series_Subtype?:string|null;Aircraft_Configuration?:string|null;Traffic_Restriction_Codes?:string|null;Additional_Data?:Json};
        Update:Record<string,never>;
        Relationships:[];
      };
      MASTER_Flight_Service_Types:{
        Row:{Service_Type_Code:string;Service_Type_Name:string;Application:string|null;Type_Of_Operation:string|null;Description:string|null;Source_Reference:string;Active:boolean;Updated_At:string};
        Insert:{Service_Type_Code:string;Service_Type_Name:string;Application?:string|null;Type_Of_Operation?:string|null;Description?:string|null;Source_Reference?:string;Active?:boolean;Updated_At?:string};
        Update:{Service_Type_Name?:string;Application?:string|null;Type_Of_Operation?:string|null;Description?:string|null;Source_Reference?:string;Active?:boolean;Updated_At?:string};Relationships:[];
      };
      MASTER_Airports:{
        Row:{Airport_IATA:string;Airport_ICAO:string|null;Airport_Name:string;City_Name:string|null;Country_Code:string|null;IANA_Time_Zone:string;Active:boolean;Updated_At:string};
        Insert:{Airport_IATA:string;Airport_ICAO?:string|null;Airport_Name:string;City_Name?:string|null;Country_Code?:string|null;IANA_Time_Zone:string;Active?:boolean;Updated_At?:string};
        Update:{Airport_ICAO?:string|null;Airport_Name?:string;City_Name?:string|null;Country_Code?:string|null;IANA_Time_Zone?:string;Active?:boolean;Updated_At?:string};Relationships:[];
      };
      Scheduled_Flight_Load_Control_Parameters:{
        Row:{Schedule_Leg_ID:string;Carrier_IATA:string;Aircraft_Series_Subtype:string;Crew_Code_ID:string;Pantry_Code_ID:string;Passenger_Weight_Basis:string;Passenger_Flight_Variation:string|null;Baggage_Weight_Basis:string;Baggage_Flight_Variation:string|null;Remarks:string|null;Updated_By:string;Updated_At:string};
        Insert:{Schedule_Leg_ID:string;Carrier_IATA:string;Aircraft_Series_Subtype:string;Crew_Code_ID:string;Pantry_Code_ID:string;Passenger_Weight_Basis:string;Passenger_Flight_Variation?:string|null;Baggage_Weight_Basis:string;Baggage_Flight_Variation?:string|null;Remarks?:string|null};
        Update:{Aircraft_Series_Subtype?:string;Crew_Code_ID?:string;Pantry_Code_ID?:string;Passenger_Weight_Basis?:string;Passenger_Flight_Variation?:string|null;Baggage_Weight_Basis?:string;Baggage_Flight_Variation?:string|null;Remarks?:string|null};Relationships:[];
      };
      MASTER_Carrier_Contact: {
        Row: { Carrier_IATA: string; Carrier_Name: string; Carrier_ICAO: string };
        Insert: { Carrier_IATA: string; Carrier_Name: string; Carrier_ICAO: string };
        Update: { Carrier_IATA?: string; Carrier_Name?: string; Carrier_ICAO?: string };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      aircraft_layout_library:{Args:Record<string,never>;Returns:Json};
      get_aircraft_layout:{Args:{p_iata:string;p_type:string;p_subtype:string};Returns:Json};
      get_aircraft_overlay_calibration:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_overlay_kind:string};Returns:Json};
      save_aircraft_overlay_calibration:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_overlay_kind:string;p_offset_x:number};Returns:Json};
      activate_aircraft_layout:{Args:{p_id:string};Returns:undefined};
      get_carrier_ulds:{Args:{p_iata:string;p_type:string;p_subtype:string};Returns:Json};
      save_carrier_ulds:{Args:{p_iata:string;p_type:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      save_carrier_uld_inventory_applicability:{Args:{p_iata:string;p_type:string;p_subtype:string;p_revision:string;p_records:boolean};Returns:Json};
      save_carrier_uld_applicability:{Args:{p_iata:string;p_type:string;p_subtype:string;p_revision:string;p_utilises:boolean};Returns:Json};
      get_carrier_densities:{Args:{p_iata:string};Returns:Json};
      save_carrier_densities:{Args:{p_iata:string;p_revision:string;p_values:Json};Returns:Json};
      get_carrier_passenger_weights: { Args: { p_iata: string }; Returns: Json };
      save_carrier_passenger_weights: { Args: { p_iata: string; p_revision: string; p_section: string; p_values: Json }; Returns: Json };
      save_carrier_crew_hold_baggage:{Args:{p_iata:string;p_revision:string;p_code:string|null;p_values:Json};Returns:Json};
      get_carrier_crew_weights: { Args: { p_iata: string }; Returns: Json };
      save_carrier_crew_weights: { Args: { p_iata: string; p_revision: string; p_values: Json }; Returns: Json };
      get_carrier_class_codes: { Args: { p_iata: string }; Returns: Json };
      save_carrier_class_codes: { Args: { p_iata: string; p_revision: string; p_rows: Json }; Returns: Json };
      get_carrier_commodity_codes: { Args: { p_iata: string }; Returns: Json };
      save_carrier_commodity_codes: { Args: { p_iata: string; p_revision: string; p_rows: Json }; Returns: Json };
      current_display_name: { Args: Record<string, never>; Returns: string | null };
      can_create_carrier:{Args:Record<string,never>;Returns:boolean};
      create_carrier:{Args:{p_iata:string;p_name:string;p_icao:string};Returns:Json};
      get_carrier_details: { Args: { p_iata: string }; Returns: Json };
      create_ssim_schedule_import:{Args:{p_iata:string;p_source_carrier_iata:string;p_file_name:string;p_file_sha256:string;p_file_size_bytes:number;p_source_encoding?:string;p_ssim_edition?:string|null;p_season_code?:string|null;p_creator_reference?:string|null};Returns:string};
      stage_ssim_schedule_import:{Args:{p_iata:string;p_import_id:string;p_records:Json;p_legs:Json};Returns:Json};
      publish_ssim_schedule_import:{Args:{p_iata:string;p_import_id:string};Returns:Json};
      get_daily_flight_schedule:{Args:{p_iata:string;p_service_date:string;p_airport_iata?:string|null};Returns:{Schedule_Leg_ID:string;Import_ID:string;Carrier_IATA:string;Service_Date:string;Airline_Designator:string;Flight_Number:string;Operational_Suffix:string;Itinerary_Variation_Identifier:string;Leg_Sequence_Number:number;Service_Type:string;Departure_Airport_IATA:string;Arrival_Airport_IATA:string;Departure_Local:string;Arrival_Local:string;Departure_UTC_Offset_Minutes:number|null;Arrival_UTC_Offset_Minutes:number|null;Departure_Terminal:string|null;Arrival_Terminal:string|null;Aircraft_Type_IATA:string|null;Aircraft_Configuration:string|null;Additional_Data:Json}[]};
      get_flight_schedule_workspace:{Args:{p_iata:string};Returns:Json};
      get_flight_schedule_segment_defaults:{Args:{p_iata:string};Returns:Json};
      get_flight_schedule_service_types:{Args:Record<string,never>;Returns:Json};
      save_flight_schedule_leg_parameters:{Args:{p_iata:string;p_schedule_leg_id:string;p_values:Json};Returns:Json};
      save_flight_schedule_segment_default:{Args:{p_iata:string;p_departure_airport:string;p_arrival_airport:string;p_aircraft_type:string;p_values:Json};Returns:undefined};
      delete_flight_schedule_segment_default:{Args:{p_iata:string;p_departure_airport:string;p_arrival_airport:string;p_aircraft_type:string};Returns:undefined};
      create_manual_schedule_import:{Args:{p_iata:string;p_name:string;p_season_code?:string|null};Returns:string};
      create_manual_schedule_revision:{Args:{p_iata:string;p_source_import_id:string};Returns:string};
      save_manual_schedule_leg:{Args:{p_iata:string;p_import_id:string;p_schedule_leg_id:string|null;p_values:Json};Returns:Json};
      save_manual_schedule_itinerary:{Args:{p_iata:string;p_import_id:string;p_values:Json};Returns:Json};
      get_master_airport_configuration:{Args:Record<string,never>;Returns:Json};
      save_master_airport:{Args:{p_original_iata:string|null;p_values:Json};Returns:Json};
      get_flight_schedule_edition:{Args:{p_iata:string;p_import_id:string};Returns:Json};
      delete_manual_schedule_leg:{Args:{p_iata:string;p_import_id:string;p_schedule_leg_id:string};Returns:Json};
      delete_flight_schedule_edition:{Args:{p_iata:string;p_import_id:string};Returns:boolean};
      save_carrier_details: { Args: { p_iata: string; p_revision: string; p_values: Json }; Returns: Json };
      save_carrier_contacts: { Args: { p_iata: string; p_revision: string; p_values: Json }; Returns: Json };
      can_manage_carrier_logo: { Args: { p_iata: string }; Returns: boolean };
      set_carrier_logo: { Args: { p_iata: string; p_path: string | null }; Returns: string | null };
      get_carrier_aircraft:{Args:{p_iata:string};Returns:Json};
      get_aircraft_c1:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      assign_aircraft_manufacturer:{Args:{p_type_code:string;p_subtype:string;p_manufacturer_uuid:string};Returns:undefined};
      search_aircraft_identities:{Args:{p_query:string};Returns:Json};
      search_aircraft_manufacturers:{Args:{p_query:string};Returns:Json};
      create_aircraft_identity:{Args:{p_manufacturer_uuid:string|null;p_manufacturer_name:string;p_type_code:string;p_subtype:string;p_identity_name:string};Returns:Json};
      save_aircraft_c1:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_aircraft_name:string;p_values:Json};Returns:Json};
      get_aircraft_c2:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_c2:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_values:Json};Returns:Json};
      get_aircraft_c4:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_c4:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_values:Json};Returns:Json};
      get_aircraft_c5:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      get_aircraft_c5_effective_dow:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      get_aircraft_c5_input_mode:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_c5:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_section:string;p_values:Json};Returns:Json};
      save_aircraft_c5_envelope:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_phase:string;p_values:Json};Returns:Json};
      save_aircraft_c5_status:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_values:Json};Returns:Json};
      get_aircraft_c8:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_c8:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_section:string;p_values:Json};Returns:Json};
      get_aircraft_c11:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_c11:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_values:Json};Returns:Json};
      get_aircraft_d2:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_d2:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_section:string;p_values:Json};Returns:Json};
      import_aircraft_d2:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_source_type_code:string;p_source_subtype:string;p_bulk:Json|null;p_uld:Json|null};Returns:Json};
      get_aircraft_d3:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_d3_configuration:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_original_code:string|null;p_values:Json};Returns:Json};
      import_aircraft_d3_configurations:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_source_type_code:string;p_source_subtype:string;p_values:Json};Returns:Json};
      import_aircraft_g1:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_source_type_code:string;p_source_subtype:string;p_rows:Json};Returns:Json};
      delete_aircraft_d3_configuration:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_hold_id:string;p_code:string};Returns:Json};
      get_aircraft_d4:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_d4:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_doors:Json};Returns:Json};
      save_aircraft_d4_applicability:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_section:string;p_active:boolean};Returns:Json};
      get_aircraft_d5:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_d5:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_section:string;p_rows:Json};Returns:Json};
      get_aircraft_d6:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_d6:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_section:string;p_applicable:boolean;p_rows:Json};Returns:Json};
      get_aircraft_d8:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_d8:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_d9:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_d9:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_original_code:string|null;p_values:Json};Returns:Json};
      get_aircraft_d11:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_d11:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_e11:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_e11:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_value:Json};Returns:Json};
      get_aircraft_e12:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_fuel_configurations:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      save_aircraft_e12_standard:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_value:Json};Returns:Json};
      save_aircraft_e12_registrations:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_e2:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_e2_crew:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      save_aircraft_e2_pantry:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_e3:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_e3_applicability:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_water_active:boolean;p_service_active:boolean};Returns:Json};
      save_aircraft_e3_water:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      save_aircraft_e3_service:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_e4:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_e4_applicability:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_active:boolean;p_additional_active:boolean};Returns:Json};
      save_aircraft_e4_configurations:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      save_aircraft_e4_additional:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_e5:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_e5_approach:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_approach:string};Returns:Json};
      save_aircraft_e5_rows:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_f1:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_f1_definitions:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      save_aircraft_f1_rows:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_g1:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_g1:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_h1:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_h1_applicability:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_dgr_active:boolean;p_iata_active:boolean;p_special_loads_active:boolean};Returns:Json};
      save_aircraft_h1_exceptions:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_kind:string;p_rows:Json};Returns:Json};
      save_aircraft_h1_special_loads:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_rows:Json};Returns:Json};
      get_aircraft_c7:{Args:{p_iata:string;p_type_code:string;p_subtype:string};Returns:Json};
      save_aircraft_c7:{Args:{p_iata:string;p_type_code:string;p_subtype:string;p_revision:string;p_section:string;p_values:Json};Returns:Json};
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
