"use client";

import {useState} from "react";
import {saveAircraftC8} from "@/app/aircraft-c8-actions";
import {CsvImportHelp} from "@/components/csv-import-help";
import {SaveButton,SaveInput} from "@/components/save-feedback";
import {mergeStandardFuelImport,parseStandardFuelCsv,standardFuelCsvTemplate,type StandardFuelImportResult} from "@/domain/aircraft-c8-standard-import";
import type {AircraftC8Snapshot} from "@/domain/aircraft-c8";
import type {FuelSystemConfiguration} from "@/domain/aircraft-e12";

export function AircraftC8StandardImport({iata,snapshot,configurations,onSaved}:{iata:string;snapshot:AircraftC8Snapshot;configurations:FuelSystemConfiguration[];onSaved:(snapshot:AircraftC8Snapshot)=>void}){
 const[preview,setPreview]=useState<StandardFuelImportResult|null>(null),[name,setName]=useState(""),[pending,setPending]=useState(false),[saveError,setSaveError]=useState("");
 async function load(file:File|undefined){if(!file)return;setName(file.name);setPreview(parseStandardFuelCsv(await file.text(),{typeCode:snapshot.typeCode,subtype:snapshot.subtype},configurations.map(configuration=>configuration.code)));setSaveError("")}
 function close(){setPreview(null);setName("");setSaveError("")}
 function download(){const blob=new Blob([standardFuelCsvTemplate(snapshot.typeCode,snapshot.subtype,snapshot.values.standard.rows)],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`c8-standard-fuel-${snapshot.typeCode}-${snapshot.subtype}.csv`;link.click();URL.revokeObjectURL(url)}
 async function apply(){if(!preview||preview.errors.length||preview.rows.length===0||!preview.source||pending)return;setPending(true);setSaveError("");const result=await saveAircraftC8(iata,snapshot.typeCode,snapshot.subtype,snapshot.revision,"standard",{enabled:true,rows:mergeStandardFuelImport(snapshot.values.standard.rows,preview.rows)});setPending(false);if(!result.ok){setSaveError(result.error);return}onSaved(result.snapshot);close()}
 const tableLabels=preview?[...new Set(preview.rows.map(row=>`${row.configurationCode??"ALL"} · SG ${row.specificGravity.toFixed(3)}`))]:[];
 return <section className="c8-curve-import c8-standard-import"><div><h3>Import Standard Fuel Tables</h3><p>Upload one CSV containing one or more fitted-configuration and Specific Gravity tables.</p></div><div className="c8-import-actions"><CsvImportHelp kind="standard"/><label className="secondary button-like">IMPORT CSV<SaveInput type="file" accept=".csv,text/csv" onChange={event=>{void load(event.target.files?.[0]);event.currentTarget.value=""}}/></label><SaveButton type="button" className="secondary" onClick={download}>DOWNLOAD TEMPLATE</SaveButton></div>{preview&&<section className={`c8-import-preview${preview.errors.length?" has-errors":""}`}><strong>STANDARD FUEL IMPORT PREVIEW</strong><p>{name} · CSV aircraft {preview.source?`${preview.source.typeCode}-${preview.source.subtype}`:"—"} · Open page {snapshot.typeCode}-{snapshot.subtype}</p>{preview.errors.length?<><strong>Resolve these CSV issues:</strong><ul>{preview.errors.map((error,index)=><li key={`${error}-${index}`}>{error}</li>)}</ul></>:<div className="d3-hold-import-summary"><div><strong>{preview.tableCount} {preview.tableCount===1?"Table":"Tables"}</strong><span>{preview.rows.length} fuel rows</span><small>{tableLabels.join(" · ")}</small></div></div>}<p className="muted">Import &amp; Save replaces only the matching Configuration Code + Specific Gravity tables. Other Standard Fuel tables remain unchanged. The zero-weight origin is generated automatically.</p>{saveError&&<p className="field-error" role="alert"><strong>Import not saved.</strong> {saveError}</p>}<div className="d3-csv-preview-actions"><SaveButton type="button" className="secondary" disabled={pending} onClick={close}>CANCEL</SaveButton><SaveButton type="button" disabled={pending||preview.errors.length>0||preview.rows.length===0} onClick={()=>void apply()}>{pending?"IMPORTING & SAVING":"IMPORT & SAVE TABLES"}</SaveButton></div></section>}</section>;
}
