'use client';
import {useSaveFeedback,SaveScope,SaveButton,SaveInput,SaveCancel,SaveSubmit} from "@/components/save-feedback";
import {SeatMapViewer} from '@/components/seat-map-viewer';
import type {AircraftD8Snapshot} from '@/domain/aircraft-d8';
import{useState}from'react';
import{saveAircraftD9}from'@/app/aircraft-d9-actions';
import{ConfigurationStatusBadge}from'@/components/configuration-status-badge';
import{SectionHeader}from'@/components/section-header';
import{buildD9Rows,deriveD9ClassSummaries,suggestD9Description,d9SeatPlanProblem,d9UsableSeatTotal,spillD9ClassSeats,type AircraftD9Snapshot,type D9AreaRow,type D9Configuration,type D9IndexFormula}from'@/domain/aircraft-d9';
import{aircraftD9Status,d9ConfigurationStatuses}from'@/domain/aircraft-d9-status';
import{balanceArmFromIndexPerWeightUnit,validIndexPerWeightUnitFormula}from'@/domain/index-per-weight-unit';
import type{AircraftOperatingRole}from'@/domain/aircraft-c1';

const shown=(v:number|null|undefined,d=3)=>v==null?'—':v.toFixed(d);
type DraftValue=number|string|null;
type D9AreaRowDraft=Omit<D9AreaRow,'classSeats'|'totalSeats'|'from'|'to'|'index'>&{classSeats:[DraftValue,DraftValue,DraftValue,DraftValue];totalSeats:number|null;from:DraftValue;to:DraftValue;index:DraftValue};
type D9ConfigurationDraft=Omit<D9Configuration,'rows'>&{rows:D9AreaRowDraft[]};
const toDraftRows=(rows:D9AreaRow[]):D9AreaRowDraft[]=>rows.map(r=>({...r,classSeats:[...r.classSeats] as D9AreaRowDraft['classSeats']}));

export function AircraftD9({iata,initial,indexFormula,operatingRole,seatplan}:{seatplan:AircraftD8Snapshot;iata:string;initial:AircraftD9Snapshot;indexFormula:D9IndexFormula|null;operatingRole:AircraftOperatingRole}){
 const[saved,setSaved]=useState(initial),[selected,setSelected]=useState(initial.configurations[0]?.code??''),[draft,setDraft]=useState<D9ConfigurationDraft|null>(null),[original,setOriginal]=useState<string|null>(null),[error,setError]=useState(''),[pending,start,saveFeedback]=useSaveFeedback();
 const active=saved.configurations.find(c=>c.code===selected)??saved.configurations[0]??null;
 const select=(c:D9Configuration)=>{setSelected(c.code);setDraft(null);setError('')};
 const edit=()=>{if(active){const rows=toDraftRows(buildD9Rows(saved.cabinAreas,active.rows));setDraft({...active,rows});setOriginal(active.code)}};
 const add=()=>{setDraft({code:'',description:'',rows:toDraftRows(buildD9Rows(saved.cabinAreas,[]))});setOriginal(null);setSelected('')};
 const save=()=>draft&&start(async()=>{const result=await saveAircraftD9(iata,saved.typeCode,saved.subtype,saved.revision,original,draft);if(!result.ok){setError(result.error);return}setError("");setSaved(result.snapshot);saveFeedback.complete(()=>{setSelected(draft.code.toUpperCase());setDraft(null);setOriginal(null);setError('')});});
 if(operatingRole==='FREIGHTER')return <SaveScope feedback={saveFeedback}>{<section className="aircraft-d9"><SectionHeader id="aircraft-d9-heading" title="D9. CONFIGURATIONS" reference="(AHM565 Sheet D9)"><ConfigurationStatusBadge status="not_required" variant="large"/></SectionHeader><section className="d9-card"><p className="d2-empty">Passenger cabin configurations are not required for a Freighter aircraft. Existing saved data is retained.</p></section></section>}</SaveScope>;
 return <SaveScope feedback={saveFeedback}>{<section className="aircraft-d9"><SectionHeader id="aircraft-d9-heading" title="D9. CONFIGURATIONS" reference="(AHM565 Sheet D9)"><ConfigurationStatusBadge status={aircraftD9Status(saved,indexFormula??undefined,operatingRole)} variant="large"/></SectionHeader><p className="c5-intro">Define each saleable cabin configuration. Cabin areas come from D5; Class Information is calculated from the class-seat allocations, outer balance-arm limits and the configured C4 index formula.</p><div className="d9-toolbar"><div className="d9-selectors">{saved.configurations.map(c=><SaveButton type="button" key={c.code} className={active?.code===c.code&&!draft?'selected':''} onClick={()=>select(c)}><strong>{c.code}</strong><span>{c.description}</span></SaveButton>)}</div><div className="d9-toolbar-actions">{active&&!draft&&<SeatMapViewer iata={iata} snapshot={seatplan} configurationCode={active.code}/>}{saved.canEdit&&!draft&&<SaveButton type="button" className="secondary" onClick={add}>ADD CONFIGURATION</SaveButton>}</div></div>{draft?<ConfigurationEditor snapshot={saved} draft={draft} setDraft={setDraft} original={original} pending={pending} error={error} save={save} cancel={()=>{setDraft(null);setOriginal(null);setError('')}}/>:active?<ConfigurationView snapshot={saved} configuration={active} edit={edit} indexFormula={indexFormula}/>:<section className="d9-card"><p className="d2-empty">No saleable configuration has been entered.</p></section>}</section>}</SaveScope>
}

function ConfigurationView({snapshot,configuration,edit,indexFormula}:{snapshot:AircraftD9Snapshot;configuration:D9Configuration;edit:()=>void;indexFormula:D9IndexFormula|null}){const st=d9ConfigurationStatuses(configuration,snapshot.cabinAreas,snapshot.classes,indexFormula??undefined,snapshot.excludedRows),summaries=indexFormula?deriveD9ClassSummaries(configuration,snapshot.cabinAreas,snapshot.classes,indexFormula,snapshot.excludedRows):[],[cabinOpen,setCabinOpen]=useState(false),[classOpen,setClassOpen]=useState(false);return <><section className="d9-card"><D9Heading title="CABIN AREA INFORMATION" note={`${configuration.code} - ${configuration.description}`} open={cabinOpen} setOpen={setCabinOpen} edit={snapshot.canEdit?edit:undefined} status={st.cabin}/>{cabinOpen&&<p>Blocked centre-seat rows: {configuration.rows.flatMap(r=>r.blockedRows??[]).join(", ")||"None — all physical seats available"}</p>}{cabinOpen&&<CabinTable rows={buildD9Rows(snapshot.cabinAreas,configuration.rows)} classes={snapshot.classes}/>}</section><section className="d9-card"><D9Heading title="CLASS INFORMATION" note={indexFormula?'Calculated from the first/last available row boundaries and C4 index formula.':'C4 must be configured before Class Information can be calculated.'} open={classOpen} setOpen={setClassOpen} status={st.classInfo}/>{classOpen&&(indexFormula?<ClassTable rows={summaries} cabinTotal={configuration.rows.reduce((n,r)=>n+(r.totalSeats??0),0)}/>:<p className="d2-empty">Configure C4 Formulae to calculate the class centroid and Index Per Weight Unit.</p>)}</section></>}
function D9Heading({title,note,open,setOpen,edit,status}:{title:string;note:string;open:boolean;setOpen:(v:boolean)=>void;edit?:()=>void;status:'configured'|'partial'|'incomplete'}){return <div className="d4-heading"><div><h3>{title}</h3><p>{note}</p></div><div className="c5-heading-actions"><SaveButton type="button" className="secondary" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'CLOSE':'OPEN'}</SaveButton>{edit&&<SaveButton type="button" className="secondary" onClick={edit}>EDIT</SaveButton>}<ConfigurationStatusBadge status={status}/></div></div>}

function ConfigurationEditor({snapshot,draft,setDraft,original,pending,error,save,cancel}:{snapshot:AircraftD9Snapshot;draft:D9ConfigurationDraft;setDraft:(v:D9ConfigurationDraft)=>void;original:string|null;pending:boolean;error:string;save:()=>void;cancel:()=>void}){
 const[descriptionEditing,setDescriptionEditing]=useState(false);
 const[useSuggestedDescription,setUseSuggestedDescription]=useState(draft.description===''||draft.description===suggestD9Description(draft.rows,snapshot.classes));
 const activeSlots=new Set(snapshot.classes.filter(c=>c.code&&c.name).map(c=>c.slot));
 const displayedTotal=(r:D9AreaRowDraft)=>{const values=r.classSeats.filter((_,q)=>activeSlots.has((q+1) as 1|2|3|4)).map(v=>v===''||v===null?NaN:Number(v));return values.length&&values.every(v=>Number.isFinite(v)&&Number.isInteger(v)&&v>=0)?values.reduce((sum,v)=>sum+v,0):''};
 const displayedCentroid=(r:D9AreaRowDraft)=>{const value=Number(r.index);return r.index!==''&&r.index!==null&&Number.isFinite(value)&&validIndexPerWeightUnitFormula(snapshot.balanceFormula)?balanceArmFromIndexPerWeightUnit(value,snapshot.balanceFormula).toFixed(3):''};
 const seat=(i:number,j:number,v:string)=>{const rows=draft.rows.map((r,n)=>{if(n!==i)return r;const available=d9UsableSeatTotal(r.areaId,r.blockedRows??[],snapshot.seatRows??[]),classSeats=spillD9ClassSeats(r.classSeats,j,v,[...activeSlots],available),active=classSeats.filter((_,q)=>activeSlots.has((q+1) as 1|2|3|4)),numbers=active.map(x=>x===''||x===null?NaN:Number(x)),totalSeats=numbers.every(x=>Number.isFinite(x)&&Number.isInteger(x)&&x>=0)?numbers.reduce((x,y)=>x+y,0):null;return{...r,classSeats,totalSeats}});setDraft({...draft,description:useSuggestedDescription?suggestD9Description(rows,snapshot.classes):draft.description,rows})};
 const decimal=(i:number,k:'from'|'to'|'index',v:string)=>setDraft({...draft,rows:draft.rows.map((r,n)=>{if(n!==i)return r;const next={...r,[k]:v};if(k==='index'){const value=Number(v);next.centroid=Number.isFinite(value)&&v.trim()!==''&&validIndexPerWeightUnitFormula(snapshot.balanceFormula)?balanceArmFromIndexPerWeightUnit(value,snapshot.balanceFormula):null}return next})});
 return <section className="d9-card"><div className="d4-heading"><div><h3>{original?'EDIT CONFIGURATION':'NEW CONFIGURATION'}</h3><p>Complete every D5 Cabin Area. Total Seats, suggested Description and Balance Arm Centroid are calculated automatically. Balance Arm From and To are optional.</p></div><ConfigurationStatusBadge status="incomplete"/></div><div className="d9-meta"><label><span>Configuration Code</span><SaveInput value={draft.code} maxLength={1} disabled={original!==null} onChange={e=>setDraft({...draft,code:e.target.value.toUpperCase().replace(/[^A-Z]/g,'')})}/></label><label><span>Suggested Description</span><span className="d9-description-control"><SaveInput value={draft.description} maxLength={20} disabled={!descriptionEditing} onChange={e=>{setUseSuggestedDescription(false);setDraft({...draft,description:e.target.value})}}/><SaveButton type="button" className="secondary" onClick={()=>{if(descriptionEditing){const description=suggestD9Description(draft.rows,snapshot.classes);setUseSuggestedDescription(true);setDraft({...draft,description});setDescriptionEditing(false)}else setDescriptionEditing(true)}}>{descriptionEditing?'USE SUGGESTED':'EDIT DESCRIPTION'}</SaveButton></span></label></div><div className="d9-table"><CabinHeader classes={snapshot.classes}/>{draft.rows.map((r,i)=><div className="d9-cabin-row" key={r.areaId}><strong>{r.areaId}</strong>{r.classSeats.map((v,j)=>{const defined=activeSlots.has((j+1) as 1|2|3|4),carrierClass=snapshot.classes.find(c=>c.slot===j+1);return <SaveInput key={j} className={defined?'':'d9-disabled'} aria-label={defined?`${carrierClass?.code} Seats ${r.areaId}`:`Class ${j+1} Not Defined`} inputMode="numeric" disabled={!defined} value={defined?v??'':''} onChange={e=>seat(i,j,e.target.value)}/>})}<SaveInput aria-label={`Total Seats Calculated ${r.areaId}`} value={displayedTotal(r)} disabled/><SaveInput aria-label={`Centroid Calculated ${r.areaId}`} value={displayedCentroid(r)} disabled/><SaveInput aria-label={`From Optional ${r.areaId}`} placeholder="Optional" inputMode="decimal" value={r.from??''} onChange={e=>decimal(i,'from',e.target.value)}/><SaveInput aria-label={`To Optional ${r.areaId}`} placeholder="Optional" inputMode="decimal" value={r.to??''} onChange={e=>decimal(i,'to',e.target.value)}/><SaveInput aria-label={`Index Per Weight Unit ${r.areaId}`} inputMode="decimal" value={r.index??''} onChange={e=>decimal(i,'index',e.target.value)}/></div>)}</div><section className="d9-seat-options"><h3>SEAT MAP — BLOCKED CENTRE SEATS</h3><p>Physical row positions and groupings come from D8. Select rows whose centre seat in each three-seat group is unavailable in this configuration. Match the class allocations above to the usable seat totals.</p>{draft.rows.map((area,i)=>{
 const physical=(snapshot.seatRows??[]).filter(r=>r.areaId===area.areaId);
 const blocked=area.blockedRows??[];
 const eligible=physical.filter(r=>/^3(-3){0,3}$/.test(r.grouping??""));
 const usable=physical.reduce((sum,r)=>sum+(r.maximumSeats??0)-(blocked.includes(r.rowNumber)?(r.grouping??"").split("-").length:0),0);
 const problem=d9SeatPlanProblem(area,snapshot.seatRows??[]);
 return <fieldset key={area.areaId}><legend>Cabin Area {area.areaId} · {usable} usable seats</legend><div className="d9-blocked-rows">{eligible.map(row=><label key={row.rowNumber}><SaveInput type="checkbox" checked={blocked.includes(row.rowNumber)} onChange={e=>setDraft({...draft,rows:draft.rows.map((r,n)=>n===i?{...r,blockedRows:e.target.checked?[...blocked,row.rowNumber]:blocked.filter(n=>n!==row.rowNumber)}:r)})}/>Row {row.rowNumber}</label>)}</div>{!eligible.length&&<p>No three-seat groups are saved for this area on D8.</p>}{problem&&<p className="field-error">{problem}</p>}</fieldset>;
 })}</section>{error&&<p className="field-error" role="alert">{error}</p>}<div className="d8-actions"><SaveCancel className="secondary" disabled={pending} onClick={cancel}>CANCEL</SaveCancel><SaveSubmit disabled={pending} onClick={save}>{pending?'Saving…':'SAVE'}</SaveSubmit></div></section>
}

const slots=[1,2,3,4] as const;
function CabinHeader({classes}:{classes:AircraftD9Snapshot['classes']}){return <div className="d9-cabin-row d9-head"><span className="d9-head-area">Cabin Area</span><span className="d9-head-seats">Seats per Cabin Area and Class</span>{slots.map((slot,i)=>{const c=classes.find(x=>x.slot===slot),defined=!!c?.code&&!!c?.name;return <span className={`d9-head-class d9-head-class-${i+1}${defined?'':' d9-disabled'}`} key={slot}><span>{defined?c.name:'Not Defined'}</span><strong>{defined?c.code:'—'}</strong></span>})}<span className="d9-head-total">Total Seats<br/>(Calculated)</span><span className="d9-head-balance">Balance Arm</span><span className="d9-head-centroid">Centroid<br/>(Calculated)</span><span className="d9-head-from">From</span><span className="d9-head-to">To</span><span className="d9-head-index">Index Per Weight Unit</span></div>}
function CabinTable({rows,classes}:{rows:D9AreaRow[];classes:AircraftD9Snapshot['classes']}){const activeSlots=new Set(classes.filter(c=>c.code&&c.name).map(c=>c.slot));return <div className="d9-table"><CabinHeader classes={classes}/>{rows.map(r=><div className="d9-cabin-row" key={r.areaId}><strong>{r.areaId}</strong>{r.classSeats.map((v,i)=><span className={activeSlots.has((i+1) as 1|2|3|4)?'':'d9-disabled'} key={i}>{activeSlots.has((i+1) as 1|2|3|4)?v??'—':'—'}</span>)}<strong>{r.totalSeats??'—'}</strong><span>{shown(r.centroid)}</span><span>{shown(r.from)}</span><span>{shown(r.to)}</span><span>{shown(r.index,5)}</span></div>)}</div>}
function ClassTable({rows,cabinTotal}:{rows:ReturnType<typeof deriveD9ClassSummaries>;cabinTotal:number}){const classTotal=rows.reduce((n,r)=>n+r.totalSeats,0);return <><div className="d9-table"><div className="d9-class-row d9-head"><span>Class</span><span>First Row</span><span>Last Row</span><span>Total Number of Seats</span><span className="d9-disabled">Lateral Arm</span><span>Centroid</span><span>From</span><span>To</span><span>Index Per Weight Unit</span></div>{rows.map(r=><div className="d9-class-row" key={r.code}><strong>{r.code}<small>{r.name}</small></strong><span>{r.firstRow}</span><span>{r.lastRow}</span><strong>{r.totalSeats}</strong><span className="d9-disabled">—</span><span>{shown(r.centroid)}</span><span>{shown(r.from)}</span><span>{shown(r.to)}</span><span>{shown(r.index,5)}</span></div>)}</div><p className={`d9-total-check${classTotal===cabinTotal?' valid':' invalid'}`}>Class Total: <strong>{classTotal}</strong> · Cabin Area Total: <strong>{cabinTotal}</strong> · {classTotal===cabinTotal?'TOTALS MATCH':'TOTALS DO NOT MATCH'}</p></>}
