"use client";
import Link from"next/link";import{useEffect,useState,useTransition}from"react";import{useRouter}from"next/navigation";import{addAircraftIdentity,searchAircraftIdentities,searchAircraftManufacturers}from"@/app/aircraft-actions";import{aircraftCode,aircraftSubtype,type AircraftIdentity,type AircraftListSnapshot}from"@/domain/aircraft-c1";import{ConfigurationStatusBadge}from"@/components/configuration-status-badge";
export function AircraftSelector({iata,initial}:{iata:string;initial:AircraftListSnapshot}){const router=useRouter();const[pending,start]=useTransition();const[query,setQuery]=useState(""),[results,setResults]=useState<AircraftIdentity[]>([]),[error,setError]=useState(""),[adding,setAdding]=useState(false);const[manufacturerQuery,setManufacturerQuery]=useState(""),[manufacturers,setManufacturers]=useState<{id:string;name:string}[]>([]),[manufacturerId,setManufacturerId]=useState<string|null>(null),[typeCode,setTypeCode]=useState(""),[subtype,setSubtype]=useState(""),[identityName,setIdentityName]=useState("");
useEffect(()=>{if(query.trim().length<2)return;const timer=setTimeout(()=>start(async()=>{const r=await searchAircraftIdentities(query);if(r.ok)setResults(r.rows);else setError(r.error)}),220);return()=>clearTimeout(timer)},[query]);
useEffect(()=>{if(manufacturerId||manufacturerQuery.trim().length<2)return;const timer=setTimeout(()=>start(async()=>{const r=await searchAircraftManufacturers(manufacturerQuery);if(r.ok)setManufacturers(r.rows);else setError(r.error)}),220);return()=>clearTimeout(timer)},[manufacturerQuery,manufacturerId]);
function open(identity:AircraftIdentity){router.push(`/carrier/${encodeURIComponent(iata)}/aircraft/${identity.typeCode}/${identity.subtype}`)}
function create(){setError("");start(async()=>{const r=await addAircraftIdentity({manufacturerId,manufacturerName:manufacturerQuery,typeCode,subtype,identityName});if(!r.ok){setError(r.error);return}open(r.identity)})}
return <section className="aircraft-selector"><div className="details-heading"><div><h2>SELECT AN AIRCRAFT TYPE OR FLEET</h2><p className="sheet-reference">Section C aircraft context</p></div></div>
{initial.rows.length>0&&<div className="aircraft-card-grid">{initial.rows.map(row=><Link className="aircraft-card" key={`${row.typeCode}-${row.subtype}`} href={`/carrier/${encodeURIComponent(iata)}/aircraft/${row.typeCode}/${row.subtype}`}><span className="aircraft-code">{row.typeCode}</span><div><h3>{row.aircraftName}</h3><p>{row.manufacturerName&&<>{row.manufacturerName} · </>}Master Series {row.subtype} · Carrier Variants {row.variantCodes.join(", ")}</p></div><ConfigurationStatusBadge status={row.configured?"configured":"incomplete"}/></Link>)}</div>}
{initial.canCreateAircraft&&<div className="aircraft-search-panel"><h3>Add an Aircraft to this Carrier</h3><p>Begin typing an Aircraft Code, Name, Manufacturer or Series/Sub-Type.</p><label htmlFor="aircraft-search">Search Aircraft Identities</label><input id="aircraft-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Type at least two characters" autoComplete="off"/>{query.trim().length>=2&&results.length>0&&<ul className="autocomplete-results">{results.map(row=><li key={`${row.typeCode}-${row.subtype}`}><button type="button" onClick={()=>open(row)}><strong>{row.typeCode} · {row.subtype}</strong><span>{row.identityName} · {row.manufacturerName||"Manufacturer unassigned"}</span></button></li>)}</ul>}
{query.trim().length>=2&&!pending&&results.length===0&&<p className="muted">No Matching Aircraft Identity Found.</p>}
{initial.canCreateIdentity&&<button className="secondary add-identity" type="button" onClick={()=>setAdding(v=>!v)}>{adding?"Close Add Aircraft Identity":"Add Aircraft Identity"}</button>}
{adding&&<div className="add-identity-panel"><h3>Add Aircraft Identity</h3><div className="c1-form-grid"><div className="details-field autocomplete-field"><label>Manufacturer</label><input value={manufacturerQuery} onChange={e=>{setManufacturerQuery(e.target.value);setManufacturerId(null)}} placeholder="Search or enter a Manufacturer"/>{!manufacturerId&&manufacturerQuery.trim().length>=2&&manufacturers.length>0&&<ul className="autocomplete-results">{manufacturers.map(m=><li key={m.id}><button type="button" onClick={()=>{setManufacturerId(m.id);setManufacturerQuery(m.name);setManufacturers([])}}>{m.name}</button></li>)}</ul>}</div><div className="details-field"><label>Aircraft Type Code</label><input value={typeCode} onChange={e=>setTypeCode(aircraftCode(e.target.value))} maxLength={3}/></div><div className="details-field"><label>Series or Sub-Type</label><input value={subtype} onChange={e=>setSubtype(aircraftSubtype(e.target.value))} maxLength={4}/></div><div className="details-field"><label>Aircraft Identity Name</label><input value={identityName} onChange={e=>setIdentityName(e.target.value)} maxLength={64}/></div></div><button type="button" disabled={pending} onClick={create}>Create and Select Identity</button></div>}
{error&&<p className="field-error" role="alert">{error}</p>}</div>}</section>}
