"use client";

import {useState} from "react";
import {saveAircraftE2Crew,saveAircraftE2Pantry} from "@/app/aircraft-e2-actions";
import {ConfigurationStatusBadge} from "@/components/configuration-status-badge";
import {SectionHeader} from "@/components/section-header";
import {SaveButton,SaveCancel,SaveInput,SaveScope,SaveSelect,SaveSubmit,useSaveFeedback} from "@/components/save-feedback";
import {useIndexDecimalPlaces} from "@/components/index-display-preference";
import {aircraftE2Status,e2CrewStatus,e2PantryStatus} from "@/domain/aircraft-e2-status";
import type {AircraftE2Snapshot,E2CrewRow,E2PantryRow} from "@/domain/aircraft-e2";
import {availableGalleyLocations,calculatePantry,pantryDraft,type PantryDraft} from "@/domain/e2-pantry-allocations";
import {formatNumeric} from "@/domain/display-standards";

const number=(v:string)=>v===""?null:Number(v);
const blankCrew=():E2CrewRow=>({crewCode:"",flightDeckLocationId:"",flightDeckSeats:null,cabinCrewLocationId:"",cabinCrewSeats:null,flightDeckBaggageLocation:null,cabinCrewBaggageLocation:null,isBase:false,weightAdjustment:null,indexAdjustment:null});
const blankPantry=():E2PantryRow=>({pantryCode:"",adjustmentMethod:"BY_GALLEY",galleyLocations:"",totalWeight:null,balanceArm:null,index:null,isBase:false,weightAdjustment:null,indexAdjustment:null});
const signed=(value:number|null,decimals?:number)=>value===null||!Number.isFinite(value)?"—":`${value>0?"+":""}${decimals===undefined?value:value.toFixed(decimals)}`;

export function AircraftE2({iata,initial}:{iata:string;initial:AircraftE2Snapshot}){
  const[saved,setSaved]=useState(initial);
  const dow=saved.startWeightPrinciple==="DRY_OPERATING_WEIGHT";
  return <section className="aircraft-e2">
    <SectionHeader id="aircraft-e2-heading" title="E2. CREW & PANTRY CODES" reference="(AHM565 Sheet E2)"><ConfigurationStatusBadge status={aircraftE2Status(saved)} variant="large"/></SectionHeader>
    <p className="c5-intro">{dow?"This aircraft uses DOW/DOI. Select one base crew code and one base pantry code; each base is zero and every alternative records a signed change to DOW and DOI.":"Define crew complements, assigned locations, optional hold-baggage locations and absolute pantry loading codes for the BW/BI workflow."}</p>
    <Crew iata={iata} saved={saved} setSaved={setSaved}/><Pantry iata={iata} saved={saved} setSaved={setSaved}/>
  </section>;
}

function Crew({iata,saved,setSaved}:{iata:string;saved:AircraftE2Snapshot;setSaved:(s:AircraftE2Snapshot)=>void}){
  const dow=saved.startWeightPrinciple==="DRY_OPERATING_WEIGHT";
  const[editing,setEditing]=useState(false),[draft,setDraft]=useState(saved.crewRows),[pending,start,saveFeedback]=useSaveFeedback(),[error,setError]=useState(""),[message,setMessage]=useState("");
  const begin=()=>{setDraft(saved.crewRows.map(x=>({...x})));setEditing(true);setError("");setMessage("")};
  const change=(i:number,k:keyof E2CrewRow,v:string|boolean)=>setDraft(rows=>rows.map((r,j)=>j===i?{...r,[k]:k.endsWith("Seats")||k.endsWith("Adjustment")?number(String(v)):v||null,...(k==="cabinCrewSeats"&&number(String(v))===0?{cabinCrewLocationId:"",cabinCrewBaggageLocation:null}:{})}:r));
  const changeCode=(indices:number[],value:string)=>setDraft(rows=>rows.map((r,i)=>indices.includes(i)?{...r,crewCode:value}:r));
  const changeAdjustment=(indices:number[],key:"weightAdjustment"|"indexAdjustment",value:string)=>setDraft(rows=>rows.map((r,i)=>indices.includes(i)?{...r,[key]:number(value)}:r));
  const selectBase=(indices:number[])=>setDraft(rows=>rows.map((r,i)=>({...r,isBase:indices.includes(i),...(indices.includes(i)?{weightAdjustment:0,indexAdjustment:0}:{})})));
  const save=()=>start(async()=>{const r=await saveAircraftE2Crew(iata,saved.typeCode,saved.subtype,saved.revision,draft);if(!r.ok){setError(r.error);return}setError("");setSaved(r.snapshot);saveFeedback.complete(()=>{setDraft(r.snapshot.crewRows);setEditing(false);setMessage("SAVED")})});
  const text=dow?"Select one BASE crew code. Each alternative code records its crew distribution plus one aggregate DOW weight and DOI adjustment.":"Each crew code contains its flight-deck and cabin-crew distribution. Baggage locations are optional and must be saved D2 holds.";
  const source=editing?draft:saved.crewRows;
  const groups:Array<{key:string;code:string;indices:number[];rows:E2CrewRow[]}>=[];
  source.forEach((row,index)=>{const key=row.crewCode||`__blank_${index}`;let group=groups.find(x=>x.key===key);if(!group){group={key,code:row.crewCode,indices:[],rows:[]};groups.push(group)}group.indices.push(index);group.rows.push(row)});
  const distribution=(rows:E2CrewRow[],kind:"flight"|"cabin")=>rows.filter(r=>(kind==="flight"?r.flightDeckSeats:r.cabinCrewSeats)!==0).map(r=>`${kind==="flight"?r.flightDeckLocationId:r.cabinCrewLocationId} ${kind==="flight"?r.flightDeckSeats:r.cabinCrewSeats}`).join(", ")||"none";
  return <SaveScope feedback={saveFeedback}><section className="e2-card"><Heading title="CREW CODES" text={text} status={e2CrewStatus(saved)} canEdit={saved.canEdit} editing={editing} message={message} begin={begin}/>
    <div className="e2-crew-code-list">{groups.map(group=>{const first=group.rows[0],flightTotal=group.rows.reduce((n,r)=>n+(r.flightDeckSeats??0),0),cabinTotal=group.rows.reduce((n,r)=>n+(r.cabinCrewSeats??0),0);return <article className={`e2-crew-code${first.isBase?" base":""}`} key={group.key}>
      <div className="e2-crew-code-heading"><div>{editing?<label>Crew Code<SaveInput aria-label={`Crew Code ${group.code||"new"}`} value={group.code} onChange={e=>changeCode(group.indices,e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,1))}/></label>:<h4>CREW CODE {group.code}</h4>}<p><strong>Flight Deck {flightTotal}</strong> [{distribution(group.rows,"flight")}] · <strong>Cabin Crew {cabinTotal}</strong> [{distribution(group.rows,"cabin")}]</p></div>
      {dow&&<div className="e2-crew-delta">{editing?<><label className="e2-base-choice"><input type="radio" name="crew-code-base" checked={first.isBase} disabled={!group.code} onChange={()=>selectBase(group.indices)}/><span>{first.isBase?`BASE ${group.code}`:"SET AS BASE"}</span></label><label>DOW Weight Δ (kg)<SaveInput aria-label={`Crew Code ${group.code||"new"} DOW Weight Adjustment`} type="number" step="1" disabled={first.isBase} value={first.weightAdjustment??""} onChange={e=>changeAdjustment(group.indices,"weightAdjustment",e.target.value)}/></label><label>DOI Δ<SaveInput aria-label={`Crew Code ${group.code||"new"} DOI Adjustment`} type="number" step="any" disabled={first.isBase} value={first.indexAdjustment??""} onChange={e=>changeAdjustment(group.indices,"indexAdjustment",e.target.value)}/></label></>:<><span>{first.isBase?<b className="e2-base-badge">BASE · ZERO</b>:"ALTERNATIVE"}</span><span>DOW Δ <strong>{signed(first.weightAdjustment)} kg</strong></span><span>DOI Δ <strong>{signed(first.indexAdjustment)}</strong></span></>}</div>}
      {editing&&<SaveButton className="secondary" onClick={()=>setDraft(rows=>rows.filter((_,i)=>!group.indices.includes(i)))}>REMOVE CODE</SaveButton>}</div>
      <div className="e2-crew-locations"><div className="e2-crew-location head"><span>Flight Deck Location</span><span>Total</span><span>Baggage</span><span>Cabin Crew Location</span><span>Total</span><span>Baggage</span>{editing&&<span>Action</span>}</div>{group.rows.map((r,j)=>{const i=group.indices[j];return <div className="e2-crew-location" key={i}>{editing?<><SaveSelect aria-label={`Flight Deck Location row ${i+1}`} value={r.flightDeckLocationId} onChange={e=>change(i,"flightDeckLocationId",e.target.value)}><option value="">Select</option>{saved.flightDeckLocations.map(x=><option value={x.id} key={x.id}>{x.id} — {x.description}</option>)}</SaveSelect><SaveInput aria-label={`Flight Deck Total row ${i+1}`} inputMode="numeric" value={r.flightDeckSeats??""} onChange={e=>change(i,"flightDeckSeats",e.target.value)}/><SaveSelect aria-label={`Flight Deck Baggage Location row ${i+1}`} value={r.flightDeckBaggageLocation??""} onChange={e=>change(i,"flightDeckBaggageLocation",e.target.value)}><option value="">No baggage</option>{saved.holds.map(x=><option value={x.id} key={x.id}>{x.description}</option>)}</SaveSelect><SaveSelect aria-label={`Cabin Crew Location row ${i+1}`} value={r.cabinCrewLocationId??""} disabled={r.cabinCrewSeats===0} onChange={e=>change(i,"cabinCrewLocationId",e.target.value)}><option value="">{r.cabinCrewSeats===0?"No cabin crew":"Select"}</option>{saved.cabinCrewLocations.map(x=><option value={x.id} key={x.id}>{x.id} — {x.description}</option>)}</SaveSelect><SaveInput aria-label={`Cabin Crew Total row ${i+1}`} inputMode="numeric" value={r.cabinCrewSeats??""} onChange={e=>change(i,"cabinCrewSeats",e.target.value)}/><SaveSelect aria-label={`Cabin Crew Baggage Location row ${i+1}`} disabled={r.cabinCrewSeats===0} value={r.cabinCrewBaggageLocation??""} onChange={e=>change(i,"cabinCrewBaggageLocation",e.target.value)}><option value="">No baggage</option>{saved.holds.map(x=><option value={x.id} key={x.id}>{x.description}</option>)}</SaveSelect><SaveButton className="secondary" onClick={()=>setDraft(rows=>rows.filter((_,k)=>k!==i))}>REMOVE</SaveButton></>:<><span>{r.flightDeckLocationId}</span><span>{r.flightDeckSeats}</span><span>{r.flightDeckBaggageLocation??"—"}</span><span>{r.cabinCrewSeats===0?"No cabin crew":r.cabinCrewLocationId}</span><span>{r.cabinCrewSeats}</span><span>{r.cabinCrewBaggageLocation??"—"}</span></>}</div>})}</div>
      {editing&&<SaveButton className="secondary e2-add-location" onClick={()=>setDraft(rows=>[...rows,{...blankCrew(),crewCode:group.code,isBase:first.isBase,weightAdjustment:first.weightAdjustment,indexAdjustment:first.indexAdjustment,...(saved.cabinCrewLocations.length===0?{cabinCrewSeats:0}:{})}])}>ADD LOCATION</SaveButton>}
    </article>})}</div>
    {editing&&<SaveButton className="secondary e2-add" onClick={()=>setDraft(x=>[...x,{...blankCrew(),...(saved.cabinCrewLocations.length===0?{cabinCrewSeats:0}:{})}])}>ADD CREW CODE</SaveButton>}{error&&<p className="field-error">{error}</p>}{editing&&<Actions pending={pending} cancel={()=>{setEditing(false);setError("")}} save={save}/>}</section></SaveScope>;
}

function Pantry({iata,saved,setSaved}:{iata:string;saved:AircraftE2Snapshot;setSaved:(s:AircraftE2Snapshot)=>void}){
  const dow=saved.startWeightPrinciple==="DRY_OPERATING_WEIGHT",indexDecimalPlaces=useIndexDecimalPlaces();
  const[editing,setEditing]=useState(false),[draft,setDraft]=useState<PantryDraft[]>([]),[pending,start,saveFeedback]=useSaveFeedback(),[error,setError]=useState(""),[message,setMessage]=useState("");
  const galleys=saved.galleyLocations??[];
  const begin=()=>{setDraft(saved.pantryRows.map(pantryDraft));setEditing(true);setError("");setMessage("")};
  const update=(i:number,patch:Partial<PantryDraft>)=>{setDraft(rows=>rows.map((r,j)=>j===i?{...r,...patch}:r));setError("")};
  const selectBase=(i:number)=>setDraft(rows=>rows.map((r,j)=>({...r,isBase:j===i,...(j===i?{adjustmentMethod:"BY_GALLEY" as const,weightAdjustment:0,indexAdjustment:0}:{})})));
  const save=()=>start(async()=>{const r=await saveAircraftE2Pantry(iata,saved.typeCode,saved.subtype,saved.revision,draft);if(!r.ok){setError(r.error);return}setError("");setSaved(r.snapshot);saveFeedback.complete(()=>{setDraft(r.snapshot.pantryRows.map(pantryDraft));setEditing(false);setMessage("SAVED")})});
  const text=dow?"Select one BASE pantry code. Alternatives may use ALL GALLEYS for one aggregated adjustment, or BY GALLEY for a detailed allocation.":"Select saved D6 galleys and enter the weight loaded in each. Total Weight, Balance Arm and Index are calculated.";
  const displayedRows=(editing?draft:saved.pantryRows).map((row,i)=>{
    let r:E2PantryRow=row,problem="";
    const oneLine=dow&&!row.isBase&&row.adjustmentMethod==="ONE_LINE";
    if(editing&&!oneLine){try{r=calculatePantry(row as PantryDraft,galleys)}catch(e){problem=e instanceof Error?e.message:"Complete the galley weights.";r={...row,totalWeight:null,balanceArm:null,index:null}}}
    return <div className={`e2-row pantry${editing?" editing":""}${dow?" dow":""}`} key={i}>
      {editing?<SaveInput aria-label={`Pantry Code row ${i+1}`} maxLength={1} value={row.pantryCode} onChange={e=>update(i,{pantryCode:e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,1)})}/>:<strong>{r.pantryCode}</strong>}
      {dow?(editing?<SaveSelect aria-label={`Pantry adjustment method row ${i+1}`} value={row.adjustmentMethod} disabled={row.isBase} onChange={e=>update(i,{adjustmentMethod:e.target.value as PantryDraft["adjustmentMethod"]})}><option value="ONE_LINE">ALL GALLEYS</option><option value="BY_GALLEY">BY GALLEY</option></SaveSelect>:<strong>{r.adjustmentMethod==="ONE_LINE"?"ALL GALLEYS":"BY GALLEY"}</strong>):null}
      {oneLine?<div className="e2-one-line"><strong>ALL</strong><small>Aggregated pantry deviation</small></div>:editing?<div className="e2-galley-loads">{(row as PantryDraft).allocations.map((a,j)=><div className="e2-galley-load" key={j}><SaveSelect aria-label={`Galley row ${i+1} location ${j+1}`} value={a.locationId} onChange={e=>update(i,{allocations:(row as PantryDraft).allocations.map((x,k)=>j===k?{...x,locationId:e.target.value}:x)})}><option value="">Select D6 galley</option>{a.locationId&&!galleys.some(g=>g.id===a.locationId)&&<option value={a.locationId}>{a.locationId} (not on D6)</option>}{availableGalleyLocations(galleys,(row as PantryDraft).allocations,j).map(g=><option key={g.id} value={g.id}>{g.id} — {g.description}</option>)}</SaveSelect><SaveInput aria-label={`Galley weight row ${i+1} location ${j+1}`} placeholder="Weight" inputMode="numeric" value={a.weight??""} onChange={e=>{if(/^\d*$/.test(e.target.value))update(i,{allocations:(row as PantryDraft).allocations.map((x,k)=>j===k?{...x,weight:number(e.target.value)}:x)})}}/><SaveButton className="secondary" aria-label={`Remove galley ${j+1} from pantry row ${i+1}`} onClick={()=>update(i,{allocations:(row as PantryDraft).allocations.filter((_,k)=>j!==k)})}>×</SaveButton></div>)}<SaveButton className="secondary" disabled={!availableGalleyLocations(galleys,(row as PantryDraft).allocations,-1).length} onClick={()=>update(i,{allocations:[...(row as PantryDraft).allocations,{locationId:"",weight:null}]})}>ADD GALLEY</SaveButton>{problem&&<small className="field-error">{problem}</small>}</div>:<span>{r.galleyLocations}</span>}
      <span>{oneLine?"—":formatNumeric("maxWeight",r.totalWeight)}</span><span>{oneLine?"—":formatNumeric("balanceArm",r.balanceArm)}</span><span>{oneLine?"—":formatNumeric("index",r.index,indexDecimalPlaces)}</span>
      {dow&&(editing?<><label className="e2-base-choice"><input type="radio" name="pantry-base" checked={(row as PantryDraft).isBase} onChange={()=>selectBase(i)}/><span>{(row as PantryDraft).isBase?"BASE":"Set base"}</span></label><SaveInput aria-label={`Pantry DOW Weight Adjustment row ${i+1}`} type="number" step="1" disabled={(row as PantryDraft).isBase} value={(row as PantryDraft).weightAdjustment??""} onChange={e=>update(i,{weightAdjustment:number(e.target.value)})}/><SaveInput aria-label={`Pantry DOI Adjustment row ${i+1}`} type="number" step="any" disabled={(row as PantryDraft).isBase} value={(row as PantryDraft).indexAdjustment??""} onChange={e=>update(i,{indexAdjustment:number(e.target.value)})}/></>:<><span>{r.isBase?<b className="e2-base-badge">BASE · ZERO</b>:"—"}</span><span>{signed(r.weightAdjustment)}</span><span>{signed(r.indexAdjustment,indexDecimalPlaces)}</span></>)}
      {editing&&<SaveButton className="secondary" onClick={()=>setDraft(rows=>rows.filter((_,j)=>j!==i))}>REMOVE</SaveButton>}
    </div>;
  });
  return <SaveScope feedback={saveFeedback}><section className="e2-card"><Heading title="PANTRY CODES" text={text} status={e2PantryStatus(saved)} canEdit={saved.canEdit} editing={editing} message={message} begin={begin}/>
    {!galleys.length&&<p>Define Galley Locations on D6 before adding pantry loads.</p>}
    <div className={`e2-table ${dow?"e2-dow":""}`}><div className={`e2-row e2-head pantry${editing?" editing":""}${dow?" dow":""}`}><span>Pantry Code</span>{dow&&<span>Method</span>}<span>Galley Locations / Weight</span><span>Total Weight</span><span>Balance Arm</span><span>Index</span>{dow&&<><span>Base</span><span>DOW Weight Δ (kg)</span><span>DOI Δ</span></>}{editing&&<span>Action</span>}</div>
    {displayedRows}</div>
    {editing&&<SaveButton className="secondary e2-add" disabled={!galleys.length} onClick={()=>setDraft(rows=>[...rows,pantryDraft(blankPantry())])}>ADD PANTRY CODE</SaveButton>}{error&&<p className="field-error">{error}</p>}{editing&&<Actions pending={pending} cancel={()=>{setEditing(false);setError("")}} save={save}/>}</section></SaveScope>;
}

function Heading({title,text,status,canEdit,editing,message,begin}:{title:string;text:string;status:ReturnType<typeof e2CrewStatus>;canEdit:boolean;editing:boolean;message:string;begin:()=>void}){return <div className="d4-heading"><div><h3>{title}</h3><p>{text}</p></div><div className="c5-heading-actions">{message&&<span className="form-success c5-inline-success">{message}</span>}{canEdit&&!editing&&<SaveButton className="secondary" onClick={begin}>EDIT</SaveButton>}<ConfigurationStatusBadge status={status}/></div></div>}
function Actions({pending,cancel,save}:{pending:boolean;cancel:()=>void;save:()=>void}){return <div className="e12-actions"><SaveCancel className="secondary" disabled={pending} onClick={cancel}>CANCEL</SaveCancel><SaveSubmit disabled={pending} onClick={save}>{pending?"Saving…":"SAVE"}</SaveSubmit></div>}
