"use client";

import {useState} from "react";
import {saveAircraftC11} from "@/app/aircraft-c11-actions";
import {ConfigurationStatusBadge} from "@/components/configuration-status-badge";
import {CgMarker} from "@/components/cg-marker";
import {CsvImportHelp} from "@/components/csv-import-help";
import {SaveButton,SaveCancel,SaveInput,SaveScope,SaveSubmit,useSaveFeedback} from "@/components/save-feedback";
import {SectionHeader} from "@/components/section-header";
import {stabiliserZeroTrim,type AircraftC11MatrixRow,type AircraftC11Method,type AircraftC11Snapshot,type AircraftC11Values} from "@/domain/aircraft-c11";
import {c11MatrixCsvTemplate,parseC11MatrixCsv} from "@/domain/aircraft-c11-matrix-import";
import {aircraftC11Status} from "@/domain/aircraft-c11-status";

type LinearKey="macFwdLimit"|"macAftLimit"|"stabMaxValue"|"stabMinValue"|"variationFwd"|"variationAft";
type MatrixDraftRow={tow:string;trimValues:string[]};
type Draft={method:AircraftC11Method;linear:Record<LinearKey,string>;macColumns:string[];rows:MatrixDraftRow[]};
export type StabiliserChartPoint={tow:number;mac:number;trim:number};
const linearFields:[LinearKey,string][]=[["macFwdLimit","Forward MAC/RC Limit (%)"],["macAftLimit","Aft MAC/RC Limit (%)"],["stabMaxValue","Maximum Stabiliser Value (ANU)"],["stabMinValue","Minimum Stabiliser Value (AND)"],["variationFwd","Variation From (% MAC/RC)"],["variationAft","Variation To (% MAC/RC)"]];
const numericPattern=/^-?\d*(?:\.\d*)?$/;
const format=(value:number,places=2)=>Number.isFinite(value)?value.toFixed(places):"";
const weight=(value:number)=>new Intl.NumberFormat("en-US",{maximumFractionDigits:0}).format(value);
function wholeNumberAxis(values:number[]){const rawMin=Math.min(...values),rawMax=Math.max(...values),padding=Math.max(1,(rawMax-rawMin)*.1),minimum=rawMin>=0?0:Math.floor(rawMin-padding),requestedMax=Math.ceil(rawMax+padding),step=Math.max(1,Math.ceil((requestedMax-minimum)/5)),maximum=minimum+step*Math.ceil((requestedMax-minimum)/step);return{minimum,maximum,ticks:Array.from({length:(maximum-minimum)/step+1},(_,index)=>minimum+index*step)}}

function draftFrom(snapshot:AircraftC11Snapshot):Draft{
 const values=snapshot.values,method=values.method==="MATRIX"?"MATRIX":"LINEAR";
 return{method,linear:{macFwdLimit:String(values.macFwdLimit??0),macAftLimit:String(values.macAftLimit??0),stabMaxValue:String(values.stabMaxValue??0),stabMinValue:String(values.stabMinValue??0),variationFwd:String(values.variationFwd??0),variationAft:String(values.variationAft??0)},macColumns:(values.macColumns??[]).map(String),rows:(values.rows??[]).map(row=>({tow:String(row.tow),trimValues:row.trimValues.map(value=>value===null?"":String(value))}))};
}
function matrixSeed(draft:Draft):Draft{return draft.macColumns.length>=2&&draft.rows.length>=2?draft:{...draft,macColumns:["","",""],rows:[{tow:"",trimValues:["","",""]},{tow:"",trimValues:["","",""]},{tow:"",trimValues:["","",""]}]}}

function StabPoint({point,x,y,weightUnit}:{point:StabiliserChartPoint;x:(value:number)=>number;y:(value:number)=>number;weightUnit:string}){return <g className="c11-loadsheet-point"><CgMarker x={x(point.mac)} y={y(point.trim)} size={14}/><text x={x(point.mac)+12} y={y(point.trim)+4}>STABTO {point.trim.toFixed(1)} · TOW {weight(point.tow)} {weightUnit} · {point.mac.toFixed(1)}% MAC</text></g>}

function LinearChart({values,point,weightUnit}:{values:AircraftC11Values;point?:StabiliserChartPoint;weightUnit:string}){
 const zero=stabiliserZeroTrim(values),zeroLabel=zero?`ZERO TRIM ${zero.from.toFixed(2)}${zero.to!==zero.from?`–${zero.to.toFixed(2)}`:""}% MAC/RC`:"ZERO TRIM outside configured range",W=840,H=430,p={l:75,r:point?245:35,t:45,b:65},xs=[values.macFwdLimit,values.variationFwd,values.variationAft,values.macAftLimit,...(point?[point.mac]:[])],ys=[values.stabMaxValue,values.stabMinValue,...(point?[point.trim]:[])],rawXmin=Math.min(...xs),rawXmax=Math.max(...xs),xmin=Math.floor(rawXmin-3),xmax=Math.ceil(rawXmax+3),yAxis=wholeNumberAxis(ys),ymin=yAxis.minimum,ymax=yAxis.maximum,xTicks=[xmin,...xs,xmax].filter((a,i,list)=>list.indexOf(a)===i),yTicks=yAxis.ticks,x=(a:number)=>p.l+(a-xmin)/(xmax-xmin)*(W-p.l-p.r),y=(a:number)=>p.t+(ymax-a)/(ymax-ymin)*(H-p.t-p.b),points=`${x(values.macFwdLimit)},${y(values.stabMaxValue)} ${x(values.variationFwd)},${y(values.stabMaxValue)} ${x(values.variationAft)},${y(values.stabMinValue)} ${x(values.macAftLimit)},${y(values.stabMinValue)}`;
 return <><svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label={`Stabiliser trim setting by percent MAC. ${zeroLabel}`}><line x1={p.l} y1={y(0)} x2={W-p.r} y2={y(0)} className="c11-zero"/><line x1={p.l} y1={p.t} x2={p.l} y2={H-p.b} className="c11-axis"/><line x1={p.l} y1={H-p.b} x2={W-p.r} y2={H-p.b} className="c11-axis"/><polyline points={points} className="c11-line"/>{xTicks.map(a=><g key={a}><line x1={x(a)} y1={H-p.b} x2={x(a)} y2={H-p.b+7} className="c11-axis"/><text x={x(a)} y={H-p.b+25} textAnchor="middle">{a}%</text></g>)}{yTicks.map(a=><g key={a}><line x1={p.l-7} y1={y(a)} x2={p.l} y2={y(a)} className="c11-axis"/><text x={p.l-12} y={y(a)+4} textAnchor="end">{a}</text></g>)}{point&&<StabPoint point={point} x={x} y={y} weightUnit={weightUnit}/>}<text x={(p.l+W-p.r)/2} y={H-14} textAnchor="middle">% MAC/RC</text><text transform={`translate(19 ${H/2}) rotate(-90)`} textAnchor="middle">Stabiliser Trim Setting</text><text x={W-p.r} y={22} textAnchor="end">Rate {values.rateOfChange.toFixed(5)} per 1% MAC</text><text x={W-p.r} y={40} textAnchor="end" style={{fontSize:10}}>{zeroLabel}</text></svg></>;
}

const chartColours=["#17345f","#3f6db8","#66758f","#23806b","#8a5b24","#75539a","#a34545","#267294"];
function lineSegments(row:AircraftC11MatrixRow,columns:number[]){const segments:{x:number;y:number}[][]=[];let segment:{x:number;y:number}[]=[];row.trimValues.forEach((value,index)=>{if(value===null){if(segment.length)segments.push(segment);segment=[]}else segment.push({x:columns[index],y:value})});if(segment.length)segments.push(segment);return segments}
function MatrixChart({values,weightUnit,point}:{values:AircraftC11Values;weightUnit:string;point?:StabiliserChartPoint}){
 const W=900,H=470,p={l:80,r:point?245:35,t:35,b:70},allValues=values.rows.flatMap(row=>row.trimValues.filter((value):value is number=>value!==null)),xmin=Math.min(values.macColumns[0],point?.mac??Infinity),xmax=Math.max(values.macColumns.at(-1)!,point?.mac??-Infinity),yAxis=wholeNumberAxis([...allValues,...(point?[point.trim]:[])]),ymin=yAxis.minimum,ymax=yAxis.maximum,x=(value:number)=>p.l+(value-xmin)/(xmax-xmin)*(W-p.l-p.r),y=(value:number)=>p.t+(ymax-value)/(ymax-ymin)*(H-p.t-p.b),yTicks=yAxis.ticks;
 return <><svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Stabiliser trim setting by actual take-off weight and percent MAC"><line x1={p.l} y1={y(0)} x2={W-p.r} y2={y(0)} className="c11-zero"/><line x1={p.l} y1={p.t} x2={p.l} y2={H-p.b} className="c11-axis"/><line x1={p.l} y1={H-p.b} x2={W-p.r} y2={H-p.b} className="c11-axis"/>{values.macColumns.map(value=><g key={value}><line x1={x(value)} y1={p.t} x2={x(value)} y2={H-p.b} className="c11-gridline"/><text x={x(value)} y={H-p.b+25} textAnchor="middle">{value}%</text></g>)}{yTicks.map(value=><g key={value}><line x1={p.l} y1={y(value)} x2={W-p.r} y2={y(value)} className="c11-gridline"/><text x={p.l-12} y={y(value)+4} textAnchor="end">{value}</text></g>)}{values.rows.flatMap((row,rowIndex)=>lineSegments(row,values.macColumns).map((segment,segmentIndex)=>segment.length>1?<polyline key={`${rowIndex}-${segmentIndex}`} points={segment.map(point=>`${x(point.x)},${y(point.y)}`).join(" ")} className="c11-matrix-line" style={{stroke:chartColours[rowIndex%chartColours.length]}}/>:segment.map((point,pointIndex)=><circle key={`${rowIndex}-${segmentIndex}-${pointIndex}`} cx={x(point.x)} cy={y(point.y)} r="4" style={{fill:chartColours[rowIndex%chartColours.length]}}/>)))}{point&&<StabPoint point={point} x={x} y={y} weightUnit={weightUnit}/>}<text x={(p.l+W-p.r)/2} y={H-17} textAnchor="middle">Aircraft CG (%MAC)</text><text transform={`translate(22 ${H/2}) rotate(-90)`} textAnchor="middle">Stabiliser Trim Setting</text></svg><div className="c11-chart-legend">{values.rows.map((row,index)=><span key={row.tow}><i style={{background:chartColours[index%chartColours.length]}}/>ACT TOW {weight(row.tow)} {weightUnit}</span>)}</div></>;
}

export function StabiliserChart({values,weightUnit,onClose,point}:{values:AircraftC11Values;weightUnit:string;onClose:()=>void;point?:StabiliserChartPoint}){return <section className="c11-chart"><div className="c5-phase-heading"><div><h3>AHM565 Sheet C11.2 — Stabiliser Trim Chart</h3><p>{values.method==="MATRIX"?"One line is plotted for each configured Actual TOW row. Gaps remain wherever C11.1 has a blank cell.":"Automatically generated from the configured linear C11.1 values."}{point?" The black marker shows the calculated loadsheet STABTO at the actual TOW and take-off CG.":""}</p></div><SaveButton className="secondary" onClick={onClose}>CLOSE</SaveButton></div>{values.method==="MATRIX"?<MatrixChart values={values} weightUnit={weightUnit} point={point}/>:<LinearChart values={values} weightUnit={weightUnit} point={point}/>}</section>}

function MatrixEditor({draft,editing,weightUnit,typeCode,subtype,savedValues,onChange}:{draft:Draft;editing:boolean;weightUnit:string;typeCode:string;subtype:string;savedValues:AircraftC11Values;onChange:(next:Draft)=>void}){
 const[preview,setPreview]=useState<ReturnType<typeof parseC11MatrixCsv>|null>(null),[fileName,setFileName]=useState("");
 function changeColumn(index:number,value:string){if(!numericPattern.test(value))return;onChange({...draft,macColumns:draft.macColumns.map((stored,column)=>column===index?value:stored)})}
 function changeTow(index:number,value:string){if(!/^\d*$/.test(value))return;onChange({...draft,rows:draft.rows.map((row,position)=>position===index?{...row,tow:value}:row)})}
 function changeCell(rowIndex:number,columnIndex:number,value:string){if(!numericPattern.test(value))return;onChange({...draft,rows:draft.rows.map((row,position)=>position===rowIndex?{...row,trimValues:row.trimValues.map((stored,column)=>column===columnIndex?value:stored)}:row)})}
 function addColumn(){onChange({...draft,macColumns:[...draft.macColumns,""],rows:draft.rows.map(row=>({...row,trimValues:[...row.trimValues,""]}))})}
 function removeColumn(index:number){onChange({...draft,macColumns:draft.macColumns.filter((_,column)=>column!==index),rows:draft.rows.map(row=>({...row,trimValues:row.trimValues.filter((_,column)=>column!==index)}))})}
 function addRow(){onChange({...draft,rows:[...draft.rows,{tow:"",trimValues:draft.macColumns.map(()=>"")}]})}
 function removeRow(index:number){onChange({...draft,rows:draft.rows.filter((_,row)=>row!==index)})}
 function download(){const url=URL.createObjectURL(new Blob([c11MatrixCsvTemplate(typeCode,subtype,savedValues)],{type:"text/csv;charset=utf-8"})),anchor=document.createElement("a");anchor.href=url;anchor.download=`C11_1_${typeCode}_${subtype}_STAB_Matrix.csv`;anchor.click();URL.revokeObjectURL(url)}
 async function select(file:File|undefined){if(!file)return;setFileName(file.name);setPreview(parseC11MatrixCsv(await file.text(),{typeCode,subtype}))}
 function applyImport(){if(!preview||preview.errors.length)return;onChange({...draft,method:"MATRIX",macColumns:preview.macColumns.map(String),rows:preview.rows.map(row=>({tow:String(row.tow),trimValues:row.trimValues.map(value=>value===null?"":String(value))}))});setPreview(null);setFileName("")}
 return <section className="c11-matrix"><div className="c11-matrix-intro"><div><h3>Weight / %MAC Stabiliser Matrix</h3><p>Enter Actual TOW down the left and the source %MAC points across the top. Leave a trim cell blank when that weight/CG combination does not apply.</p></div>{editing&&<SaveButton className="secondary" onClick={addColumn}>ADD %MAC COLUMN</SaveButton>}</div>{editing&&<div className="c11-matrix-import"><SaveButton className="secondary" onClick={download}>DOWNLOAD CSV TEMPLATE</SaveButton><CsvImportHelp kind="c11"/><label className="secondary button-like">IMPORT MATRIX CSV<input type="file" accept=".csv,text/csv" onChange={event=>select(event.target.files?.[0])}/></label></div>}{preview&&<div className={`c8-import-preview ${preview.errors.length?"has-errors":""}`}><strong>{fileName} · CSV aircraft {preview.source?`${preview.source.typeCode}-${preview.source.subtype}`:"—"} · Open page {typeCode}-{subtype} · {preview.rows.length} weight rows · {preview.macColumns.length} %MAC columns · {preview.valueCount} trim values</strong>{preview.errors.length?<ul>{preview.errors.map((message,index)=><li key={index}>{message}</li>)}</ul>:<><p>Ready to replace the editable matrix. Review it and use the main C11.1 SAVE button.</p><SaveButton onClick={applyImport}>APPLY TO MATRIX</SaveButton></>}</div>}<div className="c11-matrix-scroll"><table><thead><tr><th>ACT TOW ({weightUnit})</th>{draft.macColumns.map((column,index)=><th key={index}>{editing?<div className="c11-column-input"><SaveInput aria-label={`%MAC column ${index+1}`} type="text" inputMode="decimal" placeholder="%MAC" value={column} onChange={event=>changeColumn(index,event.target.value)}/><SaveButton className="secondary" disabled={draft.macColumns.length<=2} aria-label={`Remove %MAC column ${index+1}`} onClick={()=>removeColumn(index)}>×</SaveButton></div>:<>{column}%</>}</th>)}{editing&&<th>Action</th>}</tr></thead><tbody>{draft.rows.map((row,rowIndex)=><tr key={rowIndex}><th>{editing?<SaveInput aria-label={`Actual TOW row ${rowIndex+1}`} type="text" inputMode="numeric" value={row.tow} onChange={event=>changeTow(rowIndex,event.target.value)}/>:weight(Number(row.tow))}</th>{row.trimValues.map((value,columnIndex)=><td key={columnIndex}>{editing?<SaveInput aria-label={`Trim row ${rowIndex+1} column ${columnIndex+1}`} type="text" inputMode="decimal" placeholder="—" value={value} onChange={event=>changeCell(rowIndex,columnIndex,event.target.value)}/>:value===""?<span className="c11-null">—</span>:value}</td>)}{editing&&<td><SaveButton className="secondary" disabled={draft.rows.length<=2} onClick={()=>removeRow(rowIndex)}>REMOVE</SaveButton></td>}</tr>)}</tbody></table></div>{editing&&<SaveButton className="secondary c7-add" onClick={addRow}>ADD ACT TOW ROW</SaveButton>}<p className="muted">Blank cells are stored as not applicable. They are never interpreted as zero.</p></section>;
}

export function AircraftC11({iata,initial,required=true,weightUnit="Kg"}:{iata:string;initial:AircraftC11Snapshot;required?:boolean;weightUnit?:string}){
 const[saved,setSaved]=useState(initial),[draft,setDraft]=useState(()=>draftFrom(initial)),[editing,setEditing]=useState(false),[chart,setChart]=useState(false),[error,setError]=useState(""),[pending,start,saveFeedback]=useSaveFeedback(),status=aircraftC11Status(saved,required);
 function changeLinear(key:LinearKey,value:string){if(numericPattern.test(value))setDraft(current=>({...current,linear:{...current.linear,[key]:value}}))}
 function chooseMethod(method:AircraftC11Method){setDraft(current=>method==="MATRIX"?matrixSeed({...current,method}):{...current,method})}
 function save(){start(async()=>{const values=draft.method==="LINEAR"?{method:"LINEAR",...draft.linear}:{method:"MATRIX",macColumns:draft.macColumns,rows:draft.rows};const result=await saveAircraftC11(iata,saved.typeCode,saved.subtype,saved.revision,values);if(!result.ok){setError(result.error);return}setError("");setSaved(result.snapshot);saveFeedback.complete(()=>{setDraft(draftFrom(result.snapshot));setEditing(false);setError("")})})}
 function beginEditing(){setChart(false);setDraft(draftFrom(saved));setEditing(true)}
 return <SaveScope feedback={saveFeedback}><section className="aircraft-c11"><SectionHeader id="aircraft-c11-heading" title="11. STABILISER TRIM SETTINGS" reference="(AHM565 Sheets C11.1, C11.2)"><div className="c11-heading-actions">{status==="configured"&&!editing&&<SaveButton className="secondary" onClick={()=>setChart(true)}>VIEW STAB CHART</SaveButton>}{required&&saved.canEdit&&!editing&&<SaveButton className="secondary" onClick={beginEditing}>EDIT</SaveButton>}</div><ConfigurationStatusBadge status={status} variant="large"/></SectionHeader><p className="c5-intro">{!required?"C11.1 and C11.2 are not required because neither STABTO nor STABLA is selected on C2.":"Configure either one linear stabiliser schedule or a weight/%MAC matrix. C11.2 is generated from the selected method."}</p>{chart&&status==="configured"&&!editing&&<StabiliserChart values={saved.values} weightUnit={weightUnit} onClose={()=>setChart(false)}/>} {required&&<section className="c11-values">{editing&&<fieldset className="c11-method"><legend>C11.1 Data Method</legend><label className={draft.method==="LINEAR"?"selected":""}><input type="radio" name="c11-method" checked={draft.method==="LINEAR"} onChange={()=>chooseMethod("LINEAR")}/><span><strong>LINEAR SCHEDULE</strong><small>One stabiliser relationship across the MAC/RC range.</small></span></label><label className={draft.method==="MATRIX"?"selected":""}><input type="radio" name="c11-method" checked={draft.method==="MATRIX"} onChange={()=>chooseMethod("MATRIX")}/><span><strong>WEIGHT / %MAC MATRIX</strong><small>Stabiliser settings vary by Actual TOW and aircraft CG.</small></span></label></fieldset>}{draft.method==="LINEAR"?<div className="c11-grid">{linearFields.map(([key,label])=><label key={key}>{label}{editing?<SaveInput aria-label={label} type="text" inputMode="decimal" value={draft.linear[key]} onChange={event=>changeLinear(key,event.target.value)}/>:<span className="stored-value">{format(saved.values[key])}</span>}</label>)}<label className="c11-rate">Rate of Change per 1% MAC/RC<span className="stored-value">{saved.exists?format(saved.values.rateOfChange):"Calculated on save"}</span></label></div>:<MatrixEditor draft={draft} editing={editing} weightUnit={weightUnit} typeCode={saved.typeCode} subtype={saved.subtype} savedValues={saved.values} onChange={setDraft}/>} {error&&<p className="field-error" role="alert">{error}</p>}{editing&&<div className="c7-actions"><SaveCancel className="secondary" onClick={()=>{setDraft(draftFrom(saved));setEditing(false);setError("")}}>CANCEL</SaveCancel><SaveSubmit disabled={pending} onClick={save}>SAVE</SaveSubmit></div>}</section>}</section></SaveScope>;
}
