"use client";
import {useSaveFeedback,SaveScope,SaveInput,SaveButton,SaveCancel,SaveSubmit} from "@/components/save-feedback";
import{useState}from"react";
import{SectionHeader}from"@/components/section-header";
import{saveAircraftC7}from"@/app/aircraft-c7-actions";
import{calculateAircraftC7Point,type AircraftC7InputSource,type AircraftC7Point,type AircraftC7Section,type AircraftC7SectionKey,type AircraftC7Snapshot}from"@/domain/aircraft-c7";
import type{AircraftC4Values}from"@/domain/aircraft-c4";
import{aircraftC7Statuses}from"@/domain/aircraft-c7-status";
import{ConfigurationStatusBadge}from"@/components/configuration-status-badge";
import{BalanceEnvelopeView}from"@/components/balance-envelope-chart";
import type{AircraftC5Values}from"@/domain/aircraft-c5";
import type{AircraftC5Applicability}from"@/domain/aircraft-c2-status";
import{displayUnit,formatNumeric}from"@/domain/display-standards";import{useIndexDecimalPlaces}from"@/components/index-display-preference";
const copy=<T,>(value:T):T=>structuredClone(value);
const shown=(value:number|null,places=2)=>value===null?"—":value.toFixed(places);
const input=(value:number|null)=>value===null?"":Number.isFinite(value)?String(value):"";
const number=(value:string)=>value===""?Number.NaN:Number(value);
const sourcesFor=(values:AircraftC7Snapshot["values"]):Record<AircraftC7SectionKey,AircraftC7InputSource[]>=>({idealTrim:values.idealTrim.points.map(point=>point.indexValue===null&&point.macValue!==null?"MAC":"INDEX"),tippingLimits:values.tippingLimits.points.map(point=>point.indexValue===null&&point.macValue!==null?"MAC":"INDEX")});
const calculatedValues=(values:AircraftC7Snapshot["values"],formula:AircraftC4Values|null)=>{const next=copy(values),sources=sourcesFor(values);for(const key of ["idealTrim","tippingLimits"] as const)next[key].points=next[key].points.map((point,index)=>calculateAircraftC7Point(point,sources[key][index],formula));return next};

function DecimalInput({label,value,onChange,readOnly=false,calculatedValue="",onActivate}:{label:string;value:number|null;onChange:(value:string)=>void;readOnly?:boolean;calculatedValue?:string;onActivate?:()=>void}){
  const[text,setText]=useState(()=>input(value));
  function update(next:string){
    if(next!==""&&!/^-?\d*(?:\.\d*)?$/.test(next))return;
    setText(next);
    onChange(next);
  }
  return <SaveInput aria-label={label} className={readOnly?"c7-calculated":undefined} type="text" inputMode="decimal" readOnly={readOnly} value={readOnly?calculatedValue:text} onFocus={()=>{if(readOnly){setText(calculatedValue);onActivate?.()}}} onChange={event=>update(event.target.value)}/>;
}

function PointRows({section,editing,sources,formula,unit,onSource,onChange,onAdd,onRemove}:{section:AircraftC7Section;editing:boolean;sources:AircraftC7InputSource[];formula:AircraftC4Values|null;unit:string;onSource:(index:number,source:AircraftC7InputSource)=>void;onChange:(index:number,key:keyof AircraftC7Point,value:string)=>void;onAdd:()=>void;onRemove:(index:number)=>void}){
  const indexDecimalPlaces=useIndexDecimalPlaces();
  if(!editing&&section.points.length===0)return <p className="c7-empty">No points have been saved.</p>;
  return <>{editing&&formula&&<p className="c7-calculation-note">Select the Index or % MAC/RC field to choose the value you want to enter. The other value is calculated from Weight and C4.</p>}{editing&&!formula&&<p className="c7-calculation-note">Complete C4 Formulae to calculate between Index and % MAC/RC.</p>}<div className="c7-table" role="table"><div className="c7-row c7-head" role="row"><span>Weight ({unit})</span><span>Index</span><span>% MAC/RC</span>{editing&&<span>Action</span>}</div>{section.points.map((storedPoint,index)=>{const source=sources[index]??"INDEX",point=calculateAircraftC7Point(storedPoint,source,formula);return <div className="c7-row" role="row" key={index}>{editing?<><div className="responsive-table-cell" data-label={`Weight (${unit})`}><SaveInput aria-label={`Weight row ${index+1}`} type="text" inputMode="numeric" value={input(point.weight)} onChange={event=>onChange(index,"weight",event.target.value)}/></div><div className="responsive-table-cell" data-label="Index"><DecimalInput label={`Index row ${index+1}${formula&&source==="MAC"?" Calculated":""}`} value={point.indexValue} onChange={value=>onChange(index,"indexValue",value)} readOnly={Boolean(formula&&source==="MAC")} calculatedValue={formatNumeric(point.indexValue,"index",indexDecimalPlaces)} onActivate={()=>onSource(index,"INDEX")}/></div><div className="responsive-table-cell" data-label="% MAC/RC"><DecimalInput label={`MAC row ${index+1}${formula&&source==="INDEX"?" Calculated":""}`} value={point.macValue} onChange={value=>onChange(index,"macValue",value)} readOnly={Boolean(formula&&source==="INDEX")} calculatedValue={point.macValue===null?"":shown(point.macValue)} onActivate={()=>onSource(index,"MAC")}/></div><SaveButton type="button" className="secondary" onClick={()=>onRemove(index)}>REMOVE</SaveButton></>:<><div className="responsive-table-cell" data-label={`Weight (${unit})`}><strong>{point.weight}</strong></div><div className="responsive-table-cell" data-label="Index"><strong>{formatNumeric(point.indexValue,"index",indexDecimalPlaces)}</strong></div><div className="responsive-table-cell" data-label="% MAC/RC"><strong>{shown(point.macValue)}</strong></div></>}</div>})}</div>{editing&&<SaveButton type="button" className="secondary c7-add" onClick={onAdd}>ADD POINT</SaveButton>}</>;
}

export function AircraftC7({iata,initial,c4Formula,envelopeValues,envelopeApplicability}:{iata:string;initial:AircraftC7Snapshot;c4Formula:AircraftC4Values|null;envelopeValues:AircraftC5Values|null;envelopeApplicability:AircraftC5Applicability}){
  const[saved,setSaved]=useState(initial),[draft,setDraft]=useState(()=>copy(initial.values)),[sources,setSources]=useState(()=>sourcesFor(initial.values)),[editing,setEditing]=useState<AircraftC7SectionKey|null>(null),[message,setMessage]=useState<AircraftC7SectionKey|null>(null),[error,setError]=useState(""),[showEnvelope,setShowEnvelope]=useState(false),[pending,start,saveFeedback]=useSaveFeedback();
  const savedCompletion=aircraftC7Statuses(saved.values,saved.maximumRampWeight),title=(key:AircraftC7SectionKey)=>key==="idealTrim"?"Ideal Trim":"Tipping Limits";
  function begin(key:AircraftC7SectionKey){setDraft(calculatedValues(saved.values,c4Formula));setSources(sourcesFor(saved.values));setEditing(key);setMessage(null);setError("")}
  function exit(){setDraft(copy(saved.values));setSources(sourcesFor(saved.values));setEditing(null);setError("")}
  function updatePoint(key:AircraftC7SectionKey,index:number,field:keyof AircraftC7Point,value:string){setDraft(current=>{const next=copy(current),point=next[key].points[index];if(field==="weight")point.weight=number(value);else point[field]=value===""?null:number(value);next[key].points[index]=calculateAircraftC7Point(point,field==="indexValue"?"INDEX":field==="macValue"?"MAC":sources[key][index]??"INDEX",c4Formula);return next})}
  function selectSource(key:AircraftC7SectionKey,index:number,source:AircraftC7InputSource){setSources(current=>({...current,[key]:current[key].map((value,row)=>row===index?source:value)}));setDraft(current=>{const next=copy(current);next[key].points[index]=calculateAircraftC7Point(next[key].points[index],source,c4Formula);return next})}
  function add(key:AircraftC7SectionKey){setDraft(current=>{const next=copy(current);next[key].points.push({weight:Number.NaN,indexValue:null,macValue:null});return next});setSources(current=>({...current,[key]:[...current[key],"INDEX"]}))}
  function remove(key:AircraftC7SectionKey,index:number){setDraft(current=>{const next=copy(current);next[key].points.splice(index,1);return next});setSources(current=>({...current,[key]:current[key].filter((_,row)=>row!==index)}))}
  function save(key:AircraftC7SectionKey){setError("");start(async()=>{const result=await saveAircraftC7(iata,saved.typeCode,saved.subtype,saved.revision,key,draft[key]);if(!result.ok){setError(result.error);return}setError("");setSaved(result.snapshot);saveFeedback.complete(()=>{setDraft(copy(result.snapshot.values));setSources(sourcesFor(result.snapshot.values));setEditing(null);setMessage(key)});})}
  const render=(key:AircraftC7SectionKey,description:string)=>{const section=editing===key?draft[key]:saved.values[key],status=editing===key?aircraftC7Statuses({...saved.values,[key]:section},saved.maximumRampWeight)[key]:savedCompletion[key];return <section className={`c7-card ${section.enabled?"enabled":"disabled"}`}><div className="c7-card-heading"><label className="c7-toggle"><SaveInput type="checkbox" checked={section.enabled} disabled={editing!==key} onChange={event=>setDraft(current=>({...current,[key]:{...current[key],enabled:event.target.checked}}))}/><span><strong>{title(key)}</strong><small>{description}</small></span></label><div className="c5-heading-actions">{message===key&&<span className="form-success c5-inline-success" role="status">SAVED</span>}{editing===key?<SaveCancel type="button" className="secondary" onClick={exit} disabled={pending}>EXIT</SaveCancel>:saved.canEdit&&<SaveButton type="button" className="secondary" onClick={()=>begin(key)} disabled={editing!==null}>EDIT</SaveButton>}<ConfigurationStatusBadge status={status}/></div></div>{section.enabled&&<PointRows section={section} editing={editing===key} sources={sources[key]} formula={c4Formula} unit={displayUnit(saved.weightUnit)} onSource={(index,source)=>selectSource(key,index,source)} onChange={(index,field,value)=>updatePoint(key,index,field,value)} onAdd={()=>add(key)} onRemove={index=>remove(key,index)}/>} {!section.enabled&&<p className="c7-unavailable">Select the checkbox while editing to make data entry available.</p>}{editing===key&&<div className="c7-actions"><SaveSubmit type="button" onClick={()=>save(key)} disabled={pending}>SAVE</SaveSubmit></div>}</section>};
  const canViewEnvelope=Boolean(envelopeValues&&savedCompletion.idealTrim==="configured");
  return <SaveScope feedback={saveFeedback}>{<section className="aircraft-c7"><SectionHeader id="aircraft-c7-heading" title="7. IDEAL TRIM, TIPPING ETC" reference="(AHM565 Sheet C7)">{canViewEnvelope&&<SaveButton type="button" className="secondary" onClick={()=>setShowEnvelope(true)} aria-expanded={showEnvelope} aria-controls="balance-envelope-view-heading">VIEW ENVELOPE</SaveButton>}<ConfigurationStatusBadge status={savedCompletion.page} variant="large"/></SectionHeader><p className="c5-intro">Record the aircraft Ideal Trim Line and Tipping Limits. Lateral Imbalance is provisioned for future use.</p>{showEnvelope&&envelopeValues&&<BalanceEnvelopeView values={envelopeValues} applicability={envelopeApplicability} unit={displayUnit(saved.weightUnit)} formula={c4Formula} idealTrimPoints={saved.values.idealTrim.points} onClose={()=>setShowEnvelope(false)}/>} {render("idealTrim","Specify Ideal Trim")}{render("tippingLimits","Aircraft Tipping Limits")}<section className="c7-card disabled"><div className="c7-card-heading"><label className="c7-toggle"><SaveInput type="checkbox" disabled/><span><strong>Lateral Imbalance</strong><small>UNSUPPORTED</small></span></label><div className="c5-heading-actions"><ConfigurationStatusBadge status={savedCompletion.lateralImbalance}/></div></div></section>{error&&<p className="field-error" role="alert">{error}</p>}</section>}</SaveScope>;
}
