"use client";

import {useMemo,useRef,useState,useTransition,type ReactNode} from "react";
import {FuelRowGenerator} from "@/components/fuel-row-generator";
import {mergeFuelRows} from "@/domain/fuel-row-generation";
import {saveAircraftC8} from "@/app/aircraft-c8-actions";
import {ConfigurationStatusBadge} from "@/components/configuration-status-badge";
import {SectionHeader} from "@/components/section-header";
import {AircraftC8NonStandard} from "@/components/aircraft-c8-non-standard";
import type {AircraftC4Values} from "@/domain/aircraft-c4";
import {aircraftC8Statuses} from "@/domain/aircraft-c8-status";
import {displayUnit,formatNumeric} from "@/domain/display-standards";
import {useIndexDecimalPlaces} from "@/components/index-display-preference";
import type {AircraftC8SectionKey,AircraftC8Snapshot,AircraftC8Values,StandardFuelRow,TaxiFuelRow} from "@/domain/aircraft-c8";

const copy=<T,>(value:T):T=>structuredClone(value);
const number=(value:string)=>value===""?Number.NaN:Number(value);
const optional=(value:string)=>value===""?null:Number(value);
const input=(value:number|null)=>value===null||!Number.isFinite(value)?"":String(value);
const shown=(value:number|null)=>value===null?"—":String(value);
const sgKey=(value:number)=>value.toFixed(6);
const smoothPath=(points:{x:number;y:number}[])=>points.length===0?"":points.length===1?`M ${points[0].x} ${points[0].y}`:points.slice(0,-1).reduce((path,point,index)=>{const previous=points[index-1]??point,next=points[index+1],following=points[index+2]??next,control1={x:point.x+(next.x-previous.x)/6,y:point.y+(next.y-previous.y)/6},control2={x:next.x-(following.x-point.x)/6,y:next.y-(following.y-point.y)/6};return `${path} C ${control1.x} ${control1.y}, ${control2.x} ${control2.y}, ${next.x} ${next.y}`},`M ${points[0].x} ${points[0].y}`);
type StandardEntry=Omit<StandardFuelRow,"specificGravity">;
type StandardDraft=StandardEntry&{draftId:number};
type StandardRowView=StandardEntry&{draftId?:number};
const isAutomaticOrigin=(row:StandardEntry)=>row.fuelWeight===0&&row.indexValue===0;
const standardEntry=(row:StandardFuelRow):StandardEntry=>({fuelVolume:row.fuelVolume,fuelWeight:row.fuelWeight,hArm:row.hArm,indexValue:row.indexValue});

function Cell({label,children}:{label:string;children:ReactNode}){return <div className="responsive-table-cell" data-label={label}>{children}</div>}
function DecimalInput({label,value,onChange}:{label:string;value:number|null;onChange:(value:string)=>void}){const[text,setText]=useState(()=>input(value));function update(next:string){if(next!==""&&!/^-?\d*(?:\.\d*)?$/.test(next))return;setText(next);onChange(next)}return <input aria-label={label} type="text" inputMode="decimal" value={text} onChange={event=>update(event.target.value)}/>}

function StandardRows({rows,editing,units,onChange,onRemove}:{rows:StandardRowView[];editing:boolean;units:{volume:string;weight:string;length:string};onChange:(index:number,key:keyof StandardEntry,value:string)=>void;onRemove:(index:number)=>void}){
 const indexDecimalPlaces=useIndexDecimalPlaces();
 if(!editing&&rows.length===0)return <p className="muted">No rows have been saved for this Specific Gravity.</p>;
 return <div className="c8-table" role="table"><div className="c8-row c8-standard-table c8-head" role="row"><span>Fuel Volume ({units.volume})</span><span>Fuel Weight ({units.weight})</span><span>H-Arm ({units.length})</span><span>Index</span>{editing&&<span>Action</span>}</div>{(editing?rows:rows.filter(row=>!isAutomaticOrigin(row))).map((row,index)=><div className="c8-row c8-standard-table" role="row" key={editing?row.draftId:`${row.fuelWeight}-${index}`}>{editing?<><Cell label={`Fuel Volume (${units.volume})`}><input aria-label={`Fuel Volume row ${index+1}`} type="text" inputMode="numeric" value={input(row.fuelVolume)} onChange={event=>onChange(index,"fuelVolume",event.target.value)}/></Cell><Cell label={`Fuel Weight (${units.weight})`}><input aria-label={`Fuel Weight row ${index+1}`} type="text" inputMode="numeric" value={input(row.fuelWeight)} onChange={event=>onChange(index,"fuelWeight",event.target.value)}/></Cell><Cell label={`H-Arm (${units.length})`}><DecimalInput key={`h-arm-${row.draftId??index}-${row.fuelWeight}`} label={`H-Arm row ${index+1}`} value={row.hArm} onChange={value=>onChange(index,"hArm",value)}/></Cell><Cell label="Index"><DecimalInput key={`index-${row.draftId??index}-${row.fuelWeight}`} label={`Index row ${index+1}`} value={row.indexValue} onChange={value=>onChange(index,"indexValue",value)}/></Cell><button type="button" className="secondary" onClick={()=>onRemove(index)}>REMOVE</button></>:<><Cell label={`Fuel Volume (${units.volume})`}><strong>{shown(row.fuelVolume)}</strong></Cell><Cell label={`Fuel Weight (${units.weight})`}><strong>{row.fuelWeight}</strong></Cell><Cell label={`H-Arm (${units.length})`}><strong className={row.hArm===null?"c8-null-arm":undefined}>{shown(row.hArm)}</strong></Cell><Cell label="Index"><strong>{formatNumeric(row.indexValue,"index",indexDecimalPlaces)}</strong></Cell></>}</div>)}</div>;
}

function FuelLoadingChart({rows,specificGravity,weightUnit}:{rows:StandardEntry[];specificGravity:number;weightUnit:string}){
 const indexDecimalPlaces=useIndexDecimalPlaces();
 const points=[...rows].filter(row=>Number.isFinite(row.fuelWeight)&&Number.isFinite(row.indexValue)).sort((a,b)=>a.fuelWeight-b.fuelWeight),width=560,height=560,left=88,right=28,top=30,bottom=86,plotWidth=width-left-right,plotHeight=height-top-bottom;
 if(points.length===0)return null;
 const rawXMin=Math.min(...points.map(point=>point.indexValue)),rawXMax=Math.max(...points.map(point=>point.indexValue)),xPadding=rawXMin===rawXMax?1:Math.max((rawXMax-rawXMin)*.08,.1),xMin=rawXMin-xPadding,xMax=rawXMax+xPadding,yMax=Math.max(...points.map(point=>point.fuelWeight),1),x=(value:number)=>left+(value-xMin)/(xMax-xMin)*plotWidth,y=(value:number)=>top+plotHeight-value/yMax*plotHeight,ticks=[0,1,2,3,4],path=smoothPath(points.map(point=>({x:x(point.indexValue),y:y(point.fuelWeight)})));
 return <section className="c8-chart-card" aria-labelledby="c8-fuel-chart-title"><div><h4 id="c8-fuel-chart-title">Fuel Loading Chart · Specific Gravity {specificGravity.toFixed(3)}</h4><p>Index deflection as Fuel Weight increases.</p></div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`Fuel loading chart for Specific Gravity ${specificGravity.toFixed(3)}. Index is on the horizontal axis and Fuel Weight is on the vertical axis.`}>{ticks.map(tick=>{const value=yMax*tick/4,position=y(value);return <g key={`y-${tick}`}><line className="c8-chart-grid" x1={left} x2={width-right} y1={position} y2={position}/><text className="c8-chart-tick" x={left-14} y={position+5} textAnchor="end">{Math.round(value)}</text></g>})}{ticks.map(tick=>{const value=xMin+(xMax-xMin)*tick/4,position=x(value);return <g key={`x-${tick}`}><line className="c8-chart-grid" x1={position} x2={position} y1={top} y2={top+plotHeight}/><text className="c8-chart-tick" x={position} y={top+plotHeight+28} textAnchor="middle">{formatNumeric(value,"index",indexDecimalPlaces)}</text></g>})}<line className="c8-chart-axis" x1={left} x2={left} y1={top} y2={top+plotHeight}/><line className="c8-chart-axis" x1={left} x2={width-right} y1={top+plotHeight} y2={top+plotHeight}/>{points.length>1&&<path className="c8-chart-line" d={path}/>}<text className="c8-chart-axis-label" x={left+plotWidth/2} y={height-14} textAnchor="middle">Index</text><text className="c8-chart-axis-label" x="22" y={top+plotHeight/2} textAnchor="middle" transform={`rotate(-90 22 ${top+plotHeight/2})`}>Fuel Weight ({weightUnit})</text></svg></section>;
}

function TaxiFuelRows({rows,editing,weightUnit,onChange,onDefault,onAdd,onRemove}:{rows:TaxiFuelRow[];editing:boolean;weightUnit:string;onChange:(index:number,key:"airportIata"|"taxiFuel",value:string)=>void;onDefault:(index:number)=>void;onAdd:()=>void;onRemove:(index:number)=>void}){
 if(!editing&&rows.length===0)return <p className="muted">No Taxi Fuel has been saved.</p>;
 return <><div className="c8-table" role="table"><div className="c8-row c8-taxi-fuel c8-head" role="row"><span>Default</span><span>Airport IATA</span><span>Taxi Fuel ({weightUnit})</span>{editing&&<span>Action</span>}</div>{rows.map((row,index)=><div className="c8-row c8-taxi-fuel" role="row" key={index}>{editing?<><Cell label="Default"><input aria-label={`Default Taxi Fuel row ${index+1}`} type="radio" name="c8-default-taxi-fuel" checked={row.isDefault} onChange={()=>onDefault(index)}/></Cell><Cell label="Airport IATA"><input aria-label={`Airport IATA row ${index+1}`} value={row.airportIata??""} maxLength={3} disabled={row.isDefault} placeholder={row.isDefault?"All Airports":"e.g. LHR"} onChange={event=>onChange(index,"airportIata",event.target.value.toUpperCase().replace(/[^A-Z]/g,""))}/></Cell><Cell label={`Taxi Fuel (${weightUnit})`}><input aria-label={`Taxi Fuel row ${index+1}`} type="text" inputMode="numeric" value={input(row.taxiFuel)} onChange={event=>onChange(index,"taxiFuel",event.target.value)}/></Cell><button type="button" className="secondary" onClick={()=>onRemove(index)}>REMOVE</button></>:<><Cell label="Default"><strong>{row.isDefault?"DEFAULT":"—"}</strong></Cell><Cell label="Airport IATA"><strong>{row.airportIata??"All Airports"}</strong></Cell><Cell label={`Taxi Fuel (${weightUnit})`}><strong>{row.taxiFuel}</strong></Cell></>}</div>)}</div>{editing&&<div className="c8-add-row-actions"><button type="button" className="secondary" onClick={onAdd}>ADD ROW</button></div>}</>;
}


export function AircraftC8({iata,initial,c4Formula}:{iata:string;initial:AircraftC8Snapshot;c4Formula:AircraftC4Values|null}){
 const [saved,setSaved]=useState(initial),[draft,setDraft]=useState<AircraftC8Values>(()=>copy(initial.values)),[editing,setEditing]=useState<AircraftC8SectionKey|null>(null),[message,setMessage]=useState<AircraftC8SectionKey|null>(null),[error,setError]=useState(""),[pending,start]=useTransition();
 const specificGravities=useMemo(()=>[...new Set(saved.values.standard.rows.map(row=>sgKey(row.specificGravity)))].map(Number).sort((a,b)=>a-b),[saved.values.standard.rows]);
 const standardDraftId=useRef(0),nextStandardDraftId=()=>++standardDraftId.current;
 const [selectedSg,setSelectedSg]=useState<number|null>(null),[chartVisible,setChartVisible]=useState(false),[originalSg,setOriginalSg]=useState<number|null>(null),[sgDraft,setSgDraft]=useState(""),[tableRows,setTableRows]=useState<StandardDraft[]>([]);
 const completion=aircraftC8Statuses(saved.values),units={volume:saved.liquidVolumeUnit,weight:displayUnit(saved.weightUnit),length:saved.lengthUnit};
 const selectedRows=saved.values.standard.rows.filter(row=>selectedSg!==null&&sgKey(row.specificGravity)===sgKey(selectedSg)).map(standardEntry);
 function collapseStandard(){setSelectedSg(null);setChartVisible(false)}
 function toggleTable(sg:number){if(editing)return;if(selectedSg!==null&&sgKey(selectedSg)===sgKey(sg)){setSelectedSg(null);setChartVisible(false)}else setSelectedSg(sg);setError("")}
 function beginStandard(add=false){const sg=add?null:selectedSg;if(!add&&sg===null)return;setChartVisible(false);setDraft(copy(saved.values));setEditing("standard");setMessage(null);setError("");setOriginalSg(sg);setSgDraft(sg===null?"":String(sg));setTableRows(sg===null?[]:saved.values.standard.rows.filter(row=>sgKey(row.specificGravity)===sgKey(sg)).filter(row=>!isAutomaticOrigin(row)).map(row=>({...standardEntry(row),draftId:nextStandardDraftId()})))}
 function beginNonStandard(){setDraft(copy(saved.values));setEditing("nonStandard");setMessage(null);setError("")}
 function beginTaxiFuel(){setDraft(copy(saved.values));setEditing("taxiFuel");setMessage(null);setError("")}
 function exit(){if(editing==="standard")setSelectedSg(null);setDraft(copy(saved.values));setEditing(null);setError("");setOriginalSg(null);setTableRows([])}
 function changeStandard(index:number,key:keyof StandardEntry,value:string){setTableRows(rows=>rows.map((row,i)=>i===index?{...row,[key]:key==="fuelVolume"||key==="hArm"?optional(value):number(value)}:row))}
 function addStandard(){setTableRows(rows=>[{draftId:nextStandardDraftId(),fuelVolume:null,fuelWeight:Number.NaN,hArm:null,indexValue:Number.NaN},...rows])}
 function removeStandard(index:number){setTableRows(rows=>rows.filter((_,i)=>i!==index))}
 function changeTaxiFuel(index:number,key:"airportIata"|"taxiFuel",value:string){setDraft(current=>{const next=copy(current),row=next.taxiFuel.rows[index];if(key==="airportIata")row.airportIata=value||null;else row.taxiFuel=number(value);return next})}
 function chooseDefaultTaxiFuel(index:number){setDraft(current=>{const next=copy(current);next.taxiFuel.rows=next.taxiFuel.rows.map((row,i)=>({...row,isDefault:i===index,airportIata:i===index?null:row.airportIata}));return next})}
 function addTaxiFuel(){setDraft(current=>({...current,taxiFuel:{rows:[...current.taxiFuel.rows,{isDefault:current.taxiFuel.rows.length===0,airportIata:null,taxiFuel:Number.NaN}]}}))}
 function removeTaxiFuel(index:number){setDraft(current=>({...current,taxiFuel:{rows:current.taxiFuel.rows.filter((_,i)=>i!==index)}}))}
 function saveStandard(){setError("");const sg=Number(sgDraft);if(Number.isFinite(sg)){const collision=specificGravities.some(existing=>sgKey(existing)===sgKey(sg)&&(originalSg===null||sgKey(existing)!==sgKey(originalSg)));if(collision){setError("That Specific Gravity table already exists. Select it and use EDIT.");return}}const others=saved.values.standard.rows.filter(row=>originalSg===null||sgKey(row.specificGravity)!==sgKey(originalSg)),values={enabled:draft.standard.enabled,rows:[...others,...saved.values.standard.rows.filter(row=>originalSg!==null&&sgKey(row.specificGravity)===sgKey(originalSg)&&isAutomaticOrigin(row)&&!tableRows.some(entry=>entry.fuelWeight===0)).map(row=>({...row,specificGravity:sg})),...tableRows.map(row=>({...standardEntry({...row,specificGravity:sg}),specificGravity:sg}))]};start(async()=>{const result=await saveAircraftC8(iata,saved.typeCode,saved.subtype,saved.revision,"standard",values);if(!result.ok){setError(result.error);return}setSaved(result.snapshot);setDraft(copy(result.snapshot.values));collapseStandard();setEditing(null);setMessage("standard");setOriginalSg(null);setTableRows([])})}
 function saveNonStandard(){setError("");start(async()=>{const result=await saveAircraftC8(iata,saved.typeCode,saved.subtype,saved.revision,"nonStandard",draft.nonStandard);if(!result.ok){setError(result.error);return}setSaved(result.snapshot);setDraft(copy(result.snapshot.values));setEditing(null);setMessage("nonStandard")})}
 function saveTaxiFuel(){setError("");start(async()=>{const result=await saveAircraftC8(iata,saved.typeCode,saved.subtype,saved.revision,"taxiFuel",draft.taxiFuel);if(!result.ok){setError(result.error);return}setSaved(result.snapshot);setDraft(copy(result.snapshot.values));setEditing(null);setMessage("taxiFuel")})}
 return <section className="aircraft-c8"><SectionHeader id="aircraft-c8-heading" title="8. FUEL LOADING SCHEDULE" reference="(AHM565 Sheet C8)"><ConfigurationStatusBadge status={completion.page} variant="large"/></SectionHeader>
  <section className={`c7-card ${saved.values.standard.enabled?"enabled":"disabled"}`}><div className="c7-card-heading"><label className="c7-toggle"><input type="checkbox" checked={editing==="standard"?draft.standard.enabled:saved.values.standard.enabled} disabled={editing!=="standard"} onChange={event=>setDraft(current=>({...current,standard:{...current.standard,enabled:event.target.checked}}))}/><span><strong>Standard Fuel Loading Schedule</strong><small>Each applicable Specific Gravity table requires at least two complete rows.</small></span></label><div className="c5-heading-actions">{message==="standard"&&<span className="form-success c5-inline-success" role="status">SAVED</span>}{editing!=="standard"&&saved.canEdit&&<><button type="button" className="secondary" onClick={()=>beginStandard(true)} disabled={editing!==null}>ADD TABLE</button>{selectedSg!==null&&<><button type="button" className="secondary" onClick={()=>setChartVisible(visible=>!visible)} disabled={editing!==null}>{chartVisible?"HIDE CHART":"VIEW CHART"}</button><button type="button" className="secondary" onClick={()=>beginStandard(false)} disabled={editing!==null}>EDIT</button></>}</>}<ConfigurationStatusBadge status={completion.standard}/></div></div>
   {editing==="standard"&&draft.standard.enabled?<><div className="c8-standard-toolbar"><div className="c8-sg-editor"><label htmlFor="c8-specific-gravity">Specific Gravity</label><input id="c8-specific-gravity" type="text" inputMode="decimal" value={sgDraft} onChange={event=>setSgDraft(event.target.value)}/><small>This value applies to every row saved in this table.</small></div><button type="button" className="secondary" onClick={addStandard}>ADD ROW</button></div><FuelRowGenerator weights={[0,...tableRows.map(row=>row.fuelWeight)]} unit={units.weight} onGenerate={weights=>setTableRows(rows=>mergeFuelRows(rows,weights,fuelWeight=>({draftId:nextStandardDraftId(),fuelVolume:null,fuelWeight,hArm:null,indexValue:Number.NaN})))}/><StandardRows rows={tableRows} editing units={units} onChange={changeStandard} onRemove={removeStandard}/></>:saved.values.standard.enabled?<>{specificGravities.length>0?<><fieldset className="c8-table-selector"><legend>Select a Specific Gravity Table</legend>{specificGravities.map(sg=>{const selected=selectedSg!==null&&sgKey(selectedSg)===sgKey(sg);return <button type="button" className="c8-sg-button" aria-pressed={selected} aria-expanded={selected} disabled={editing!==null} key={sgKey(sg)} onClick={()=>toggleTable(sg)}><span className="c8-sg-indicator" aria-hidden="true"/>{sg.toFixed(3)}</button>})}</fieldset>{selectedSg===null?<p className="muted c8-table-prompt">Select a Specific Gravity above to view its fuel loading table.</p>:<><div className="c8-add-row-actions"><button type="button" className="secondary" onClick={collapseStandard} disabled={editing!==null}>COLLAPSE TABLE</button></div>{chartVisible&&<FuelLoadingChart rows={selectedRows} specificGravity={selectedSg} weightUnit={units.weight}/>}<StandardRows rows={selectedRows} editing={false} units={units} onChange={changeStandard} onRemove={removeStandard}/><div className="c8-add-row-actions"><button type="button" className="secondary" onClick={collapseStandard} disabled={editing!==null}>COLLAPSE TABLE</button></div></>}</>:<p className="muted">No Specific Gravity tables have been saved. Select ADD TABLE to begin.</p>}</>:<p className="c7-unavailable">Select the checkbox while editing to make data entry available.</p>}{editing==="standard"&&<div className="c7-actions"><button type="button" className="secondary" onClick={exit} disabled={pending}>CANCEL</button><button type="button" onClick={saveStandard} disabled={pending}>SAVE</button></div>}
  </section>
  <section className={`c7-card ${saved.values.nonStandard.byTankEnabled||saved.values.nonStandard.byScheduleEnabled?"enabled":"disabled"}`}><div className="c7-card-heading"><div><strong>Non-Standard Fuel Loading</strong><small className="c8-reference-note">Select By Tank, By Schedule, or both.</small></div><div className="c5-heading-actions">{message==="nonStandard"&&<span className="form-success c5-inline-success" role="status">SAVED</span>}{editing!=="nonStandard"&&saved.canEdit&&<button type="button" className="secondary" onClick={beginNonStandard} disabled={editing!==null}>EDIT</button>}<ConfigurationStatusBadge status={completion.nonStandard}/></div></div><AircraftC8NonStandard value={editing==="nonStandard"?draft.nonStandard:saved.values.nonStandard} editing={editing==="nonStandard"} formula={c4Formula} volumeUnit={saved.liquidVolumeUnit} weightUnit={displayUnit(saved.weightUnit)} lengthUnit={saved.lengthUnit} onChange={value=>setDraft(current=>({...current,nonStandard:value}))}/>{editing==="nonStandard"&&<div className="c7-actions"><button type="button" className="secondary" onClick={exit} disabled={pending}>CANCEL</button><button type="button" onClick={saveNonStandard} disabled={pending}>SAVE</button></div>}</section>
  <section className="c7-card enabled"><div className="c7-card-heading"><div><strong>Taxi Fuel</strong><small className="c8-reference-note">Relevant to AHM565 Sheet C10</small></div><div className="c5-heading-actions">{message==="taxiFuel"&&<span className="form-success c5-inline-success" role="status">SAVED</span>}{editing!=="taxiFuel"&&saved.canEdit&&<button type="button" className="secondary" onClick={beginTaxiFuel} disabled={editing!==null}>EDIT</button>}<ConfigurationStatusBadge status={completion.taxiFuel}/></div></div><p className="muted c8-taxi-note">Set one default Taxi Fuel for this aircraft. Add airport-specific values only where required.</p><TaxiFuelRows rows={editing==="taxiFuel"?draft.taxiFuel.rows:saved.values.taxiFuel.rows} editing={editing==="taxiFuel"} weightUnit={displayUnit(saved.weightUnit)} onChange={changeTaxiFuel} onDefault={chooseDefaultTaxiFuel} onAdd={addTaxiFuel} onRemove={removeTaxiFuel}/>{editing==="taxiFuel"&&<div className="c7-actions"><button type="button" className="secondary" onClick={exit} disabled={pending}>CANCEL</button><button type="button" onClick={saveTaxiFuel} disabled={pending}>SAVE</button></div>}</section>
  {error&&<p className="field-error" role="alert">{error}</p>}
 </section>;
}
