"use client";
import {useSaveFeedback,SaveScope,SaveButton,SaveInput,SaveSubmit,SaveCancel} from "@/components/save-feedback";
import{useState}from"react";import{SectionHeader}from"@/components/section-header";import{ConfigurationStatusBadge}from"@/components/configuration-status-badge";import{saveAircraftC4}from"@/app/aircraft-c4-actions";import type{AircraftC4Snapshot,AircraftC4Values}from"@/domain/aircraft-c4";import{aircraftC4Status}from"@/domain/aircraft-c4-status";
const unitName:Record<string,string>={CM:"cm",M:"m",IN:"in",FT:"ft"};
const fields:{key:keyof AircraftC4Values;label:string;help:string;integer?:boolean;positive?:boolean;unit?:boolean}[]=[
  {key:"datum",label:"Datum / Nose Arm",help:"Balance Arm at the aircraft nose. Enter 0 when Datum Zero is the nose.",unit:true},
  {key:"referenceArm",label:"Reference Arm",help:"Distance from the reference datum to the selected reference station.",unit:true},
  {key:"constantK",label:"K Constant",help:"Plus value used to avoid negative index figures.",integer:true},
  {key:"constantC",label:"C Constant",help:"Denominator used to convert moment values into index values.",positive:true},
  {key:"macRcLength",label:"Length of MAC/RC",help:"Length of the Mean Aerodynamic Chord or Reference Chord.",positive:true,unit:true},
  {key:"lemacLerc",label:"LEMAC/LERC",help:"Distance from the reference datum to the leading edge of the MAC/RC.",unit:true}
];
export function AircraftC4({iata,initial}:{iata:string;initial:AircraftC4Snapshot}){const[saved,setSaved]=useState(initial),[draft,setDraft]=useState(initial.values),[editing,setEditing]=useState(!initial.exists),[error,setError]=useState(""),[pending,start,saveFeedback]=useSaveFeedback();const unit=unitName[saved.lengthUnit]??saved.lengthUnit,status=aircraftC4Status(saved);function change(key:keyof AircraftC4Values,value:string){setDraft(current=>({...current,[key]:value===""?Number.NaN:Number(value)}))}function save(){setError("");start(async()=>{const result=await saveAircraftC4(iata,saved.typeCode,saved.subtype,saved.revision,draft);if(!result.ok){setError(result.error);return}setError("");setSaved(result.snapshot);saveFeedback.complete(()=>{setDraft(result.snapshot.values);setEditing(false)});})}return <SaveScope feedback={saveFeedback}>{<section className="aircraft-c4"><SectionHeader id="aircraft-c4-heading" title="3. BASIC INDEX AND MAC FORMULA" reference="(AHM565 Sheet C4)"><ConfigurationStatusBadge status={status} variant="large"/></SectionHeader><p className="c4-unit-note">All length values use <strong>{unit}</strong>, as selected on Sheet C1.</p><div className="c4-formula-grid"><div className="c4-formula-card"><h3>Index Formula</h3><p><span>Index</span><strong>=</strong><span className="fraction"><span>W × (Balance Arm − Reference Arm)</span><span>C</span></span><strong>+ K</strong></p></div><div className="c4-formula-card"><h3>MAC/RC Formula</h3><p><span>% MAC/RC</span><strong>=</strong><span className="fraction"><span>C × (I − K) ÷ W + Reference Arm − LEMAC/LERC</span><span>MAC/RC ÷ 100</span></span></p></div></div><div className="c4-values"><div className="c4-values-actions c5-heading-actions">{saved.canEdit&&!editing&&<SaveButton className="secondary" onClick={()=>{setEditing(true)}}>EDIT</SaveButton>}<ConfigurationStatusBadge status={status}/></div>{fields.map(field=><div className="details-field" key={field.key}><label htmlFor={`c4-${field.key}`}>{field.label}{field.unit&&unit?` (${unit})`:""}</label>{editing?<SaveInput id={`c4-${field.key}`} type="number" inputMode={field.integer?"numeric":"decimal"} min={field.positive?0:undefined} value={Number.isFinite(draft[field.key])?draft[field.key]:""} onChange={event=>change(field.key,event.target.value)}/>:<p className="stored-value">{saved.values[field.key]}{field.unit&&unit?` ${unit}`:""}</p>}<small>{field.help}</small></div>)}</div>{error&&<p className="field-error" role="alert">{error}</p>}{editing&&<div className="logo-actions"><SaveSubmit disabled={pending} onClick={save}>SAVE FORMULA</SaveSubmit>{saved.exists&&<SaveCancel className="secondary" disabled={pending} onClick={()=>{setDraft(saved.values);setEditing(false);setError("")}}>Cancel</SaveCancel>}</div>}</section>}</SaveScope>}
