"use client";
import { CsvImportHelp } from "@/components/csv-import-help";
import{useState}from"react";import{SaveButton,SaveInput}from"@/components/save-feedback";import{aircraftG1CsvTemplate,parseAircraftG1Csv,type AircraftG1CsvResult}from"@/domain/aircraft-g1-csv";import type{AircraftG1Snapshot,G1CompatibilityRow}from"@/domain/aircraft-g1";

export function AircraftG1CsvImport({snapshot,onApply}:{snapshot:AircraftG1Snapshot;onApply:(rows:G1CompatibilityRow[],source:{typeCode:string;subtype:string})=>Promise<boolean>}){
 const[open,setOpen]=useState(false),[name,setName]=useState(""),[preview,setPreview]=useState<AircraftG1CsvResult|null>(null),[pending,setPending]=useState(false);
 async function load(file:File|undefined){if(!file)return;const result=parseAircraftG1Csv(await file.text(),snapshot);setName(file.name);setPreview(result);setOpen(true)}
 async function apply(){if(!preview||preview.errors.length||pending||!preview.source)return;setPending(true);const saved=await onApply(preview.rows,preview.source);setPending(false);if(saved){setOpen(false);setName("");setPreview(null)}}
 function download(){const blob=new Blob([aircraftG1CsvTemplate(snapshot)],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`g1-uld-compatibility-${snapshot.typeCode}-${snapshot.subtype}.csv`;link.click();URL.revokeObjectURL(url)}
 return <section className="d3-sheet-import g1-sheet-import"><div className="d3-sheet-import-heading"><div><strong>IMPORT ULD COMPATIBILITY</strong><p>Upload a Position Bay matrix using the B5 ULD identities as columns and Y/N answers.</p></div><div className="d3-csv-actions"><CsvImportHelp kind="g1"/><label className="secondary button-like">IMPORT CSV<SaveInput type="file" accept=".csv,text/csv" onChange={event=>void load(event.target.files?.[0])}/></label><SaveButton type="button" className="secondary" onClick={download}>DOWNLOAD TEMPLATE</SaveButton></div></div>{open&&preview&&<section className="d3-csv-preview"><div><strong>G1 IMPORT PREVIEW</strong><p>{name} · CSV aircraft {preview.source?`${preview.source.typeCode}-${preview.source.subtype}`:"—"} · Open page {snapshot.typeCode}-{snapshot.subtype} · {preview.bayCount} bays · {preview.identityCount} B5 ULD identities</p></div>{preview.errors.length?<div className="d3-csv-errors" role="alert"><strong>Resolve these CSV issues:</strong><ul>{preview.errors.map(error=><li key={error}>{error}</li>)}</ul></div>:<div className="d3-hold-import-summary"><div><strong>READY TO IMPORT</strong><span>{preview.rows.length} compatibility answers</span><small>All D3 Bays and B5 ULD Types are represented.</small></div></div>}<p className="muted">Importing saves this matrix as the reviewed G1 result. D3 positions and B5 specifications remain unchanged.</p><div className="d3-csv-preview-actions"><SaveButton type="button" className="secondary" disabled={pending} onClick={()=>{setOpen(false);setPreview(null);setName("")}}>CANCEL</SaveButton><SaveButton type="button" disabled={pending||preview.errors.length>0} onClick={()=>void apply()}>{pending?"IMPORTING":"IMPORT COMPATIBILITY"}</SaveButton></div></section>}</section>
}
