"use client";
import {useSaveFeedback,SaveScope,SaveButton,SaveInput,SaveCancel,SaveSubmit,SaveSelect} from "@/components/save-feedback";
import{useState}from"react";import{useIndexDecimalPlaces}from"@/components/index-display-preference";import{saveAircraftE5Approach,saveAircraftE5Rows}from"@/app/aircraft-e5-actions";import{ConfigurationStatusBadge}from"@/components/configuration-status-badge";import{SectionHeader}from"@/components/section-header";import{aircraftE5Status}from"@/domain/aircraft-e5-status";import{formatNumeric}from"@/domain/display-standards";import type{AircraftE5Snapshot,E5Approach,E5Option,E5Row}from"@/domain/aircraft-e5";
const numeric=(v:string)=>v.trim()===""?null:Number(v),blank=(variantCode:string):E5Row=>({fleetRowId:null,registration:"",variantCode,weight:null,index:null,actualWeight:null,actualIndex:null,macPercent:null,balanceArm:null,weightConfigurationCode:null,pantryCode:null,crewCode:null,remarks:null});
const principleNames=(s:AircraftE5Snapshot)=>s.principle==="BASIC_WEIGHT"?{weight:"Basic Weight",index:"Basic Index"}:{weight:"Dry Operating Weight",index:"Dry Operating Index"};
export function AircraftE5({iata,initial}:{iata:string;initial:AircraftE5Snapshot}){const[saved,setSaved]=useState(initial);return <section className="aircraft-e5"><SectionHeader id="aircraft-e5-heading" title="E5. FLEET/AIRCRAFT WEIGHTS" reference="(AHM565 Sheet E5)"><ConfigurationStatusBadge status={aircraftE5Status(saved)} variant="large"/></SectionHeader><p className="c5-intro">Choose one recording approach. E1.1 determines whether this page records Basic Weight and Basic Index or Dry Operating Weight and Dry Operating Index.</p><Approach iata={iata} saved={saved} setSaved={setSaved}/>{saved.approach&&<Rows iata={iata} saved={saved} setSaved={setSaved}/>}</section>}
function Approach({iata,saved,setSaved}:{iata:string;saved:AircraftE5Snapshot;setSaved:(s:AircraftE5Snapshot)=>void}){const[draft,setDraft]=useState<E5Approach|null>(saved.approach),[editing,setEditing]=useState(!saved.approach),[pending,start,saveFeedback]=useSaveFeedback(),[error,setError]=useState("");const save=()=>start(async()=>{const r=await saveAircraftE5Approach(iata,saved.typeCode,saved.subtype,saved.revision,draft);if(!r.ok){setError(r.error);return}setError("");setSaved(r.snapshot);saveFeedback.complete(()=>{setDraft(r.snapshot.approach);setEditing(false);setError("")});});return <SaveScope feedback={saveFeedback}>{<section className="e5-approach"><div className="d4-heading"><div><h3>WEIGHT RECORDING APPROACH</h3><p>Select one approach. Only its E5 section will be displayed.</p></div>{saved.canEdit&&!editing&&<SaveButton className="secondary" onClick={()=>{setDraft(saved.approach);setEditing(true)}}>EDIT</SaveButton>}</div><div className="e5-options"><label><SaveInput type="radio" name="e5-approach" checked={draft==="FLEET_WEIGHTS"} disabled={!editing} onChange={()=>setDraft("FLEET_WEIGHTS")}/><span><strong>Fleet Weights</strong><small>Apply a weight and index adjustment to the E1.2 Standard Fleet values.</small></span></label><label><SaveInput type="radio" name="e5-approach" checked={draft==="INDIVIDUAL_AIRCRAFT_WEIGHTS"} disabled={!editing} onChange={()=>setDraft("INDIVIDUAL_AIRCRAFT_WEIGHTS")}/><span><strong>Individual Aircraft Weights</strong><small>Record the actual weight and index for each registration.</small></span></label></div>{error&&<p className="field-error">{error}</p>}{editing&&<div className="e5-actions"><SaveCancel className="secondary" disabled={pending||!saved.approach} onClick={()=>{setDraft(saved.approach);setEditing(false);setError("")}}>CANCEL</SaveCancel><SaveSubmit disabled={pending||!draft} onClick={save}>{pending?"Saving…":"SAVE"}</SaveSubmit></div>}</section>}</SaveScope>}
function Rows({iata,saved,setSaved}:{iata:string;saved:AircraftE5Snapshot;setSaved:(s:AircraftE5Snapshot)=>void}){const[editing,setEditing]=useState(false),[draft,setDraft]=useState(saved.rows),[pending,start,saveFeedback]=useSaveFeedback(),[error,setError]=useState(""),[message,setMessage]=useState("");const fleet=saved.approach==="FLEET_WEIGHTS",names=principleNames(saved),begin=()=>{setDraft(saved.rows.map(x=>({...x})));setEditing(true);setError("");setMessage("")},change=(i:number,k:keyof E5Row,v:string)=>setDraft(rows=>rows.map((r,j)=>j===i?{...r,[k]:k==="registration"?v.toUpperCase().replace(/[^A-Z0-9-]/g,"").slice(0,10):["weight","index","macPercent","balanceArm"].includes(k)?numeric(v):v||null}:r)),save=()=>start(async()=>{const r=await saveAircraftE5Rows(iata,saved.typeCode,saved.subtype,saved.revision,draft);if(!r.ok){setError(r.error);return}setError("");setSaved(r.snapshot);saveFeedback.complete(()=>{setDraft(r.snapshot.rows);setEditing(false);setMessage("SAVED")});});return <SaveScope feedback={saveFeedback}>{<section className="e5-card"><div className="d4-heading"><div><h3>{fleet?"FLEET WEIGHTS":"INDIVIDUAL AIRCRAFT WEIGHTS"}</h3><p>{fleet?`The saved adjustment is added to Fleet ${names.weight} and Fleet ${names.index}.`:`Record the actual ${names.weight} and ${names.index} for each registration.`}</p></div><div className="d5-heading-actions">{message&&<span className="d5-saved">{message}</span>}{saved.canEdit&&!editing&&<SaveButton className="secondary" onClick={begin}>EDIT</SaveButton>}<ConfigurationStatusBadge status={aircraftE5Status(saved)} variant="large"/></div></div>{fleet&&<div className="e5-fleet-base"><Value label={`Fleet ${names.weight} (Kg)`} value={saved.fleetWeight} format="weight"/><Value label={`Fleet ${names.index}`} value={saved.fleetIndex} format="index"/></div>}<div className="e5-list">{(editing?draft:saved.rows).map((r,i)=><AircraftRow key={r.fleetRowId??`new-${i}`} row={r} index={i} saved={saved} editing={editing} change={change} remove={()=>setDraft(x=>x.filter((_,j)=>j!==i))}/>)}</div>{!saved.rows.length&&!editing&&<p className="d2-empty">No aircraft weights have been configured.</p>}{error&&<p className="field-error">{error}</p>}{editing&&<div className="d5-edit-footer"><SaveButton className="secondary" onClick={()=>setDraft(x=>[...x,blank(saved.variantOptions[0]?.code??saved.subtype)])}>ADD AIRCRAFT</SaveButton><div className="e4-footer-actions"><SaveCancel className="secondary" disabled={pending} onClick={()=>{setEditing(false);setError("")}}>CANCEL</SaveCancel><SaveSubmit disabled={pending} onClick={save}>{pending?"Saving…":"SAVE"}</SaveSubmit></div></div>}</section>}</SaveScope>}
function AircraftRow({row:r,index:i,saved,editing,change,remove}:{row:E5Row;index:number;saved:AircraftE5Snapshot;editing:boolean;change:(i:number,k:keyof E5Row,v:string)=>void;remove:()=>void}){const fleet=saved.approach==="FLEET_WEIGHTS",names=principleNames(saved),actualWeight=fleet&&r.weight!==null&&saved.fleetWeight!==null?saved.fleetWeight+r.weight:r.weight,actualIndex=fleet&&r.index!==null&&saved.fleetIndex!==null?saved.fleetIndex+r.index:r.index,calculatedWeightLabel=`Calculated ${names.weight==="Dry Operating Weight"?"Dry Operating Wt":names.weight} (Kg)`;return <article className="e5-aircraft"><div className={`e5-primary ${fleet?"fleet":"individual"} ${editing?"editing":""}`}><Field label="Registration" value={r.registration} editing={editing} change={v=>change(i,"registration",v)}/><SelectField label="Carrier Variant" value={r.variantCode} options={saved.variantOptions} editing={editing} required change={v=>change(i,"variantCode",v)}/><Field label={fleet?"Weight Adjustment (Kg)":`${names.weight} (Kg)`} value={r.weight} editing={editing} numeric format="weight" change={v=>change(i,"weight",v)}/><Field label={fleet?"Index Adjustment":names.index} value={r.index} editing={editing} numeric format="index" change={v=>change(i,"index",v)}/>{fleet&&<><Value label={calculatedWeightLabel} value={actualWeight} format="weight"/><Value label={`Calculated ${names.index}`} value={actualIndex} format="index"/></>}{editing&&<SaveButton className="secondary e5-remove" onClick={remove}>REMOVE</SaveButton>}</div><details className="e5-details" open={editing}><summary>OPTIONAL DETAILS</summary><div className={`e5-detail-grid ${fleet?"fleet":"individual"}`}><Field label="%MAC" value={r.macPercent} editing={editing} numeric change={v=>change(i,"macPercent",v)}/><Field label="Balance Arm" value={r.balanceArm} editing={editing} numeric change={v=>change(i,"balanceArm",v)}/><SelectField label="Weight Configuration Code" value={r.weightConfigurationCode} options={saved.configurationOptions} editing={editing} change={v=>change(i,"weightConfigurationCode",v)}/>{fleet&&<><SelectField label="Pantry Code" value={r.pantryCode} options={saved.pantryOptions} editing={editing} change={v=>change(i,"pantryCode",v)}/><SelectField label="Crew Code" value={r.crewCode} options={saved.crewOptions} editing={editing} change={v=>change(i,"crewCode",v)}/></>}<Field label="Remarks" value={r.remarks} editing={editing} change={v=>change(i,"remarks",v)}/></div></details></article>}
function Field({label,value,editing,change,numeric=false,format}:{label:string;value:string|number|null;editing:boolean;change:(v:string)=>void;numeric?:boolean;format?:"index"|"weight"}){const indexDecimalPlaces=useIndexDecimalPlaces();const displayFormat=format==="index"?"index":format==="weight"?"integer":"threeDecimals";return <label className="e5-field"><span>{label}</span>{editing?(numeric?<DecimalField value={value} change={change}/>:<SaveInput value={value??""} onChange={e=>change(e.target.value)}/>):<strong>{typeof value==="number"?formatNumeric(value,displayFormat,indexDecimalPlaces):value||"—"}</strong>}</label>}
function SelectField({label,value,options,editing,change,required=false}:{label:string;value:string|null;options:E5Option[];editing:boolean;change:(v:string)=>void;required?:boolean}){const selected=options.find(o=>o.code===value);return <label className="e5-field"><span>{label}</span>{editing?<SaveSelect value={value??""} onChange={e=>change(e.target.value)}>{!required&&<option value="">None / N/A</option>}{options.map(o=><option key={o.code} value={o.code}>{o.label||o.code}</option>)}</SaveSelect>:<strong>{selected?.label??value??"—"}</strong>}</label>}
function Value({label,value,format}:{label:string;value:number|null;format:"weight"|"index"}){const indexDecimalPlaces=useIndexDecimalPlaces();return <div className="e5-field"><span>{label}</span><strong>{value===null?"—":formatNumeric(value,format==="index"?"index":"integer",indexDecimalPlaces)}</strong></div>}

// Keep the typed decimal separator/sign until the user finishes entering the number.
function DecimalField({value,change}:{value:string|number|null;change:(value:string)=>void}) {
  const [text,setText]=useState(String(value??""));
  const [focused,setFocused]=useState(false);
  return <SaveInput type="text" inputMode="decimal" value={focused?text:String(value??"")}
    onFocus={()=>{setText(String(value??""));setFocused(true)}} onBlur={()=>setFocused(false)}
    onChange={event=>{
      const next=event.target.value;
      if(next!==""&&!/^-?\d*(?:\.\d*)?$/.test(next))return;
      setText(next);
      change(["-", ".", "-."].includes(next)?"":next);
    }}/>;
}
