"use client";

import {useMemo,useState,type Dispatch,type SetStateAction}from"react";
import type{AircraftC4Values}from"@/domain/aircraft-c4";
import type{AircraftC5Phase,AircraftC5Values}from"@/domain/aircraft-c5";
import type{AircraftC11Values}from"@/domain/aircraft-c11";
import type{AircraftC5Applicability}from"@/domain/aircraft-c2-status";
import type{AircraftD2Snapshot}from"@/domain/aircraft-d2";
import type{AircraftD8Snapshot}from"@/domain/aircraft-d8";
import{StabiliserChart}from"@/components/aircraft-c11";
import{FuelLoadingChart}from"@/components/aircraft-c8";
import{BalanceEnvelopeView,type LoadsheetEnvelopePoint}from"@/components/balance-envelope-chart";
import{HoldLayoutViewer,type HoldLoadOverlay}from"@/components/hold-layout-viewer";
import{SeatMapViewer,type SeatMapPassengerLoad}from"@/components/seat-map-viewer";
import{simulateLoadsheet,type SimulatorDeadloadKind,type SimulatorFuelPoint,type SimulatorPassengerWeights,type SimulatorResult}from"@/domain/loadsheet-simulator";

type Registration={registration:string;dow:number;doi:number;fuelConfigurationCode:string|null;maximumWeights:{mrw:number|null;tow:number|null;law:number|null;zfw:number|null}|null};
type Deviation={code:string;weight:number;index:number;base:boolean};
type CabinArea={id:string;description:string;indexPerWeightUnit:number;maximumSeats:number|null};
type LoadLocation={id:string;description:string;indexPerWeightUnit:number;maximumWeight:number|null;occupiedBayIds:string[]};
type FuelTable={id:string;label:string;configurationCode:string|null;specificGravity:number;points:SimulatorFuelPoint[]};
export type LoadsheetSimulatorData={carrierCode:string;typeCode:string;subtype:string;weightUnit:string;registrations:Registration[];crewCodes:Deviation[];pantryCodes:Deviation[];passengerWeights:SimulatorPassengerWeights;passengerWeightSource:string;cabinAreas:CabinArea[];locationsByConfiguration:Record<string,LoadLocation[]>;fuelTables:FuelTable[];defaultTaxiFuel:number;formula:AircraftC4Values;limits:AircraftC5Values;envelopeApplicability:AircraftC5Applicability;stabiliser:AircraftC11Values|null;holdSnapshot:AircraftD2Snapshot;seatMapSnapshot:AircraftD8Snapshot};
type PassengerDraft={male:string;female:string;child:string;infant:string};
type DeadloadDraft={kind:SimulatorDeadloadKind;locationId:string;weight:string};
type KnownKey="zfw"|"lizfw"|"macZfw"|"tow"|"litow"|"macTow"|"law"|"lilaw"|"macLaw"|"stabTo";
const knownFields:Array<[KnownKey,string]>=[["zfw","ZFW"],["lizfw","LIZFW"],["macZfw","MACZFW"],["tow","TOW"],["litow","LITOW"],["macTow","MACTOW"],["law","LAW"],["lilaw","LILAW"],["macLaw","MACLAW"],["stabTo","STABTO"]];
const phases:AircraftC5Phase[]=["zfw","tow","law"];
const number=(value:string)=>value.trim()===""?0:Number(value);
const fmt=(value:number,places=2)=>value.toLocaleString(undefined,{maximumFractionDigits:places,minimumFractionDigits:places});

type ComparisonTone="neutral"|"green"|"amber"|"red";
type ComparisonMetric="weight"|"index"|"mac"|"trim";
const tolerance:Record<ComparisonMetric,{green:number;amber:number}>={weight:{green:1,amber:10},index:{green:2,amber:3},mac:{green:1,amber:1.5},trim:{green:1,amber:1.5}};
export function comparisonTone(difference:number|null,metric:ComparisonMetric):ComparisonTone{if(difference===null||!Number.isFinite(difference))return"neutral";const amount=Math.abs(difference),band=tolerance[metric];return amount<=band.green?"green":amount<=band.amber?"amber":"red"}
const toneRank:Record<ComparisonTone,number>={neutral:0,green:1,amber:2,red:3};
const worstTone=(tones:ComparisonTone[])=>tones.length?tones.reduce((worst,tone)=>toneRank[tone]>toneRank[worst]?tone:worst,"neutral" as ComparisonTone):"neutral";

function Status({ok,label}:{ok:boolean;label:string}){return <span className={`sim-status ${ok?"ok":"bad"}`}>{label}: {ok?"PASS":"FAIL"}</span>}
function EnvelopeStatus({result}:{result:SimulatorResult["envelopes"][AircraftC5Phase]}){return <span className={`sim-status ${result.within?"ok":"bad"}`}>{result.code??"STANDARD"}: {result.within?"IN ENVELOPE":result.resolved?"OUTSIDE":"UNRESOLVED"}</span>}

export function LoadsheetSimulator({initial}:{initial:LoadsheetSimulatorData}){
 const[registration,setRegistration]=useState(initial.registrations[0]?.registration??""),[crewCode,setCrewCode]=useState(initial.crewCodes.find(row=>row.base)?.code??initial.crewCodes[0]?.code??""),[pantryCode,setPantryCode]=useState(initial.pantryCodes.find(row=>row.base)?.code??initial.pantryCodes[0]?.code??""),[fuelTableId,setFuelTableId]=useState(initial.fuelTables[0]?.id??"");
 const[passengers,setPassengers]=useState<Record<string,PassengerDraft>>(()=>Object.fromEntries(initial.cabinAreas.map(area=>[area.id,{male:"",female:"",child:"",infant:""}]))),[deadload,setDeadload]=useState<DeadloadDraft[]>([]),[blockFuel,setBlockFuel]=useState(""),[taxiFuel,setTaxiFuel]=useState(String(initial.defaultTaxiFuel||0)),[tripFuel,setTripFuel]=useState(""),[conditions,setConditions]=useState<Partial<Record<AircraftC5Phase,string>>>({}),[known,setKnown]=useState<Record<KnownKey,string>>(()=>Object.fromEntries(knownFields.map(([key])=>[key,""]))as Record<KnownKey,string>),[showEnvelope,setShowEnvelope]=useState(false),[showStabiliser,setShowStabiliser]=useState(false),[showFuelCurve,setShowFuelCurve]=useState(false);
 const selectedRegistration=initial.registrations.find(row=>row.registration===registration),crew=initial.crewCodes.find(row=>row.code===crewCode),pantry=initial.pantryCodes.find(row=>row.code===pantryCode),fuelTable=initial.fuelTables.find(row=>row.id===fuelTableId);
 const locations=initial.locationsByConfiguration[selectedRegistration?.fuelConfigurationCode??"ALL"]??initial.locationsByConfiguration.ALL??[];
 const result=useMemo(()=>{try{
  if(!selectedRegistration||!crew||!pantry||!fuelTable)throw new Error("Select a registration, crew code, pantry code and fuel table.");
  const limits={...initial.limits,maximumWeights:selectedRegistration.maximumWeights&&Object.values(selectedRegistration.maximumWeights).every(value=>value!==null)?{mrw:selectedRegistration.maximumWeights.mrw!,tow:selectedRegistration.maximumWeights.tow!,law:selectedRegistration.maximumWeights.law!,zfw:selectedRegistration.maximumWeights.zfw!}:initial.limits.maximumWeights};
  return{value:simulateLoadsheet({registration:{registration:selectedRegistration.registration,dow:selectedRegistration.dow,doi:selectedRegistration.doi,fuelConfigurationCode:selectedRegistration.fuelConfigurationCode},crew:{code:crew.code,weight:crew.weight,index:crew.index},pantry:{code:pantry.code,weight:pantry.weight,index:pantry.index},passengerWeights:initial.passengerWeights,passengers:initial.cabinAreas.map(area=>({areaId:area.id,indexPerWeightUnit:area.indexPerWeightUnit,maximumSeats:area.maximumSeats,male:number(passengers[area.id]?.male??""),female:number(passengers[area.id]?.female??""),child:number(passengers[area.id]?.child??""),infant:number(passengers[area.id]?.infant??"")})),deadload:deadload.filter(row=>row.locationId&&row.weight.trim()!=="").map(row=>{const location=locations.find(item=>item.id===row.locationId);if(!location)throw new Error(`Select a valid loading position for ${row.kind}.`);return{kind:row.kind,locationId:location.id,weight:number(row.weight),indexPerWeightUnit:location.indexPerWeightUnit,maximumWeight:location.maximumWeight,occupiedBayIds:location.occupiedBayIds}}),blockFuel:number(blockFuel),taxiFuel:number(taxiFuel),tripFuel:number(tripFuel),fuelCurve:fuelTable.points,formula:initial.formula,limits,stabiliser:initial.stabiliser,selectedConditionCodes:conditions}),error:null};
 }catch(error){return{value:null,error:error instanceof Error?error.message:"Check the simulator entries."}}},[selectedRegistration,crew,pantry,fuelTable,initial,passengers,deadload,locations,blockFuel,taxiFuel,tripFuel,conditions]);
 const updatePassenger=(id:string,key:keyof PassengerDraft,value:string)=>{if(/^\d*$/.test(value))setPassengers(rows=>({...rows,[id]:{...rows[id],[key]:value}}))};
 const updateDeadload=(index:number,patch:Partial<DeadloadDraft>)=>setDeadload(rows=>rows.map((row,i)=>i===index?{...row,...patch}:row));
 const conditionOptions=(phase:AircraftC5Phase)=>(initial.limits.envelopeModes?.[phase]??"STANDARD")==="CONDITIONAL"?(initial.limits.conditionalEnvelopes?.[phase]??[]).filter(row=>!row.configurationCode||row.configurationCode===selectedRegistration?.fuelConfigurationCode):[];
 const passengerOverlay:Record<string,SeatMapPassengerLoad>=Object.fromEntries(initial.cabinAreas.map(area=>{const row=passengers[area.id];return[area.id,{male:number(row?.male??""),female:number(row?.female??""),child:number(row?.child??""),infant:number(row?.infant??"")}]}));
 const holdOverlay:HoldLoadOverlay[]=deadload.filter(row=>row.locationId&&row.weight.trim()!=="").map(row=>({locationId:row.locationId,kind:row.kind,weight:number(row.weight),occupiedBayIds:locations.find(location=>location.id===row.locationId)?.occupiedBayIds??[]}));
 const envelopePoints:LoadsheetEnvelopePoint[]=result.value?[{phase:"zfw",label:"ZFW",weight:result.value.zfw,indexValue:result.value.lizfw,macValue:result.value.macZfw},{phase:"tow",label:"TOW",weight:result.value.tow,indexValue:result.value.litow,macValue:result.value.macTow},{phase:"law",label:"LAW",weight:result.value.law,indexValue:result.value.lilaw,macValue:result.value.macLaw}]:[];
 return <section className="loadsheet-simulator">
  <div className="sim-intro"><div><h2>EDP Loadsheet Verification Simulator</h2><p>Enter a known flight load. Every calculated weight and index is derived from the saved carrier and aircraft configuration.</p></div><b>READ-ONLY VERIFICATION</b></div>
  <section className="sim-card"><h3>1. Aircraft and operating codes</h3><div className="sim-fields"><label>Registration<select value={registration} onChange={event=>{setRegistration(event.target.value);const reg=initial.registrations.find(row=>row.registration===event.target.value);const compatible=initial.fuelTables.find(table=>!table.configurationCode||table.configurationCode===reg?.fuelConfigurationCode);if(compatible)setFuelTableId(compatible.id)}}>{initial.registrations.map(row=><option key={row.registration} value={row.registration}>{row.registration} · DOW {row.dow} · DOI {row.doi}{row.fuelConfigurationCode?` · ${row.fuelConfigurationCode}`:""}</option>)}</select></label><label>Crew Code<select value={crewCode} onChange={event=>setCrewCode(event.target.value)}>{initial.crewCodes.map(row=><option key={row.code} value={row.code}>{row.code}{row.base?" · BASE":""} · ΔW {row.weight} · ΔI {row.index}</option>)}</select></label><label>Pantry Code<select value={pantryCode} onChange={event=>setPantryCode(event.target.value)}>{initial.pantryCodes.map(row=><option key={row.code} value={row.code}>{row.code}{row.base?" · BASE":""} · ΔW {row.weight} · ΔI {row.index}</option>)}</select></label><label>Fuel Table<select value={fuelTableId} onChange={event=>setFuelTableId(event.target.value)}>{initial.fuelTables.filter(table=>!table.configurationCode||table.configurationCode===selectedRegistration?.fuelConfigurationCode).map(row=><option key={row.id} value={row.id}>{row.label}</option>)}</select></label></div>{selectedRegistration&&crew&&pantry&&<div className="sim-start"><span>DOW <strong>{fmt(selectedRegistration.dow+crew.weight+pantry.weight,0)} {initial.weightUnit}</strong></span><span>DOI <strong>{fmt(selectedRegistration.doi+crew.index+pantry.index)}</strong></span></div>}</section>
  <section className="sim-card"><div className="sim-section-heading"><div><h3>2. Passenger distribution</h3><p>{initial.passengerWeightSource}</p></div></div><div className="sim-table"><div className="sim-row sim-head"><span>Cabin Area</span><span>Male</span><span>Female</span><span>Child</span><span>Infant</span><span>Index / Weight Unit</span></div>{initial.cabinAreas.map(area=><div className="sim-row" key={area.id}><strong>{area.id}<small>{area.description}</small></strong>{(["male","female","child","infant"]as const).map(key=><input key={key} aria-label={`${area.id} ${key}`} inputMode="numeric" value={passengers[area.id]?.[key]??""} onChange={event=>updatePassenger(area.id,key,event.target.value)}/>) }<span>{area.indexPerWeightUnit}</span></div>)}</div></section>
  <section className="sim-card"><div className="sim-section-heading"><div><h3>3. Deadload distribution</h3><p>Add baggage, cargo and mail against a saved bulk area or ULD loading position. Enter the complete weight applied to that position, including the ULD where applicable.</p></div><button className="secondary" onClick={()=>setDeadload(rows=>[...rows,{kind:"BAGGAGE",locationId:"",weight:""}])}>ADD LOAD</button></div><div className="sim-deadload">{deadload.map((row,index)=><div className="sim-deadload-row" key={index}><select aria-label={`Deadload type ${index+1}`} value={row.kind} onChange={event=>updateDeadload(index,{kind:event.target.value as SimulatorDeadloadKind})}><option>BAGGAGE</option><option>CARGO</option><option>MAIL</option></select><select aria-label={`Deadload location ${index+1}`} value={row.locationId} onChange={event=>updateDeadload(index,{locationId:event.target.value})}><option value="">Select loading position</option>{locations.map(location=><option key={location.id} value={location.id}>{location.description} · Max {location.maximumWeight??"—"}</option>)}</select><input aria-label={`Deadload weight ${index+1}`} inputMode="numeric" placeholder={`Weight (${initial.weightUnit})`} value={row.weight} onChange={event=>/^\d*$/.test(event.target.value)&&updateDeadload(index,{weight:event.target.value})}/><button className="secondary" onClick={()=>setDeadload(rows=>rows.filter((_,i)=>i!==index))}>REMOVE</button></div>)}</div>{!deadload.length&&<p className="muted">No deadload entered.</p>}</section>
  <section className="sim-card"><h3>4. Fuel</h3><div className="sim-fields"><label>Block / Total Fuel ({initial.weightUnit})<input inputMode="numeric" value={blockFuel} onChange={event=>/^\d*$/.test(event.target.value)&&setBlockFuel(event.target.value)}/></label><label>Taxi Fuel ({initial.weightUnit})<input inputMode="numeric" value={taxiFuel} onChange={event=>/^\d*$/.test(event.target.value)&&setTaxiFuel(event.target.value)}/></label><label>Trip Fuel ({initial.weightUnit})<input inputMode="numeric" value={tripFuel} onChange={event=>/^\d*$/.test(event.target.value)&&setTripFuel(event.target.value)}/></label></div>{phases.map(phase=>conditionOptions(phase).some(row=>row.conditionBasis==="OTHER")&&<label className="sim-condition" key={phase}>{phase.toUpperCase()} operational condition<select value={conditions[phase]??""} onChange={event=>setConditions(value=>({...value,[phase]:event.target.value||undefined}))}><option value="">Select condition</option>{conditionOptions(phase).map(row=><option value={row.code} key={row.code}>{row.code} · {row.conditionDescription}</option>)}</select></label>)}</section>
  <section className="sim-card"><h3>5. Known / proven loadsheet</h3><p className="muted">Optional. Enter the published results you expect; the simulator will show the calculated difference for each populated field.</p><div className="sim-known">{knownFields.map(([key,label])=><label key={key}>{label}<input inputMode="decimal" value={known[key]} onChange={event=>/^-?\d*(?:\.\d*)?$/.test(event.target.value)&&setKnown(values=>({...values,[key]:event.target.value}))}/></label>)}</div></section>
  <section className="sim-card sim-output"><div className="sim-section-heading"><div><h3>6. Calculated EDP Loadsheet</h3><p>Use this result as the comparison record against the known, proven loadsheet.</p></div>{result.value&&<button className="secondary sim-print" onClick={()=>window.print()}>PRINT / SAVE PDF</button>}</div>{result.error?<p className="sim-prompt">{result.error}</p>:result.value&&<Result result={result.value} unit={initial.weightUnit} known={known} setKnown={setKnown}/>}</section>
  {result.value&&<section className="sim-card sim-visualisations"><div className="sim-section-heading"><div><h3>7. Load visualisation</h3><p>Review the entered load against the calibrated cabin, hold, fuel, balance-envelope and stabiliser geometry.</p></div></div><div className="sim-visualisation-actions"><SeatMapViewer iata={initial.carrierCode} snapshot={initial.seatMapSnapshot} passengerLoads={passengerOverlay} buttonLabel="VIEW LOADED SEAT MAP"/><HoldLayoutViewer iata={initial.carrierCode} d2={initial.holdSnapshot} editing={false} loads={holdOverlay} initialConfigurationCode={selectedRegistration?.fuelConfigurationCode} buttonLabel="VIEW LOADED HOLD LAYOUT"/><button type="button" className="secondary" onClick={()=>setShowFuelCurve(value=>!value)}>{showFuelCurve?"CLOSE FUEL CURVE":"VIEW LOADED FUEL CURVE"}</button><button type="button" className="secondary" onClick={()=>setShowEnvelope(value=>!value)}>{showEnvelope?"CLOSE BALANCE ENVELOPE":"VIEW LOADED BALANCE ENVELOPE"}</button>{initial.stabiliser&&result.value.stabTo!==null&&<button type="button" className="secondary" onClick={()=>setShowStabiliser(value=>!value)}>{showStabiliser?"CLOSE STAB CHART":"VIEW LOADED STAB CHART"}</button>}</div>{showFuelCurve&&fuelTable&&<FuelLoadingChart rows={fuelTable.points.map(point=>({fuelWeight:point.weight,indexValue:point.index}))} specificGravity={fuelTable.specificGravity} weightUnit={initial.weightUnit} title={`Fuel Loading Chart · ${fuelTable.label}`} markers={[{label:"TAKE-OFF FUEL",fuelWeight:result.value.takeoffFuel,indexValue:result.value.takeoffFuelIndex},{label:"LANDING FUEL",fuelWeight:result.value.landingFuel,indexValue:result.value.landingFuelIndex}]}/>} {showEnvelope&&<BalanceEnvelopeView values={initial.limits} applicability={initial.envelopeApplicability} unit={initial.weightUnit} formula={initial.formula} loadsheetPoints={envelopePoints} selectedConditionCodes={{zfw:result.value.envelopes.zfw.code??undefined,tow:result.value.envelopes.tow.code??undefined,law:result.value.envelopes.law.code??undefined}} combinedOnly onClose={()=>setShowEnvelope(false)}/>} {showStabiliser&&initial.stabiliser&&result.value.stabTo!==null&&<StabiliserChart values={initial.stabiliser} weightUnit={initial.weightUnit} point={{tow:result.value.tow,mac:result.value.macTow,trim:result.value.stabTo}} onClose={()=>setShowStabiliser(false)}/>}</section>}
  {result.value&&selectedRegistration&&crew&&pantry&&fuelTable&&<PrintReport initial={initial} result={result.value} registration={selectedRegistration} crew={crew} pantry={pantry} fuelTable={fuelTable} passengers={passengers} deadload={deadload} locations={locations} known={known}/>}
 </section>
}

function PrintReport({initial,result,registration,crew,pantry,fuelTable,passengers,deadload,locations,known}:{initial:LoadsheetSimulatorData;result:SimulatorResult;registration:Registration;crew:Deviation;pantry:Deviation;fuelTable:FuelTable;passengers:Record<string,PassengerDraft>;deadload:DeadloadDraft[];locations:LoadLocation[];known:Record<KnownKey,string>}){
 const unit=initial.weightUnit;
 const passengerRows=initial.cabinAreas.map(area=>{const row=passengers[area.id]??{male:"",female:"",child:"",infant:""},counts={male:number(row.male),female:number(row.female),child:number(row.child),infant:number(row.infant)},weight=counts.male*initial.passengerWeights.male+counts.female*initial.passengerWeights.female+counts.child*initial.passengerWeights.child+counts.infant*initial.passengerWeights.infant;return{area,...counts,total:counts.male+counts.female+counts.child+counts.infant,weight,index:weight*area.indexPerWeightUnit}});
 const deadloadRows=deadload.filter(row=>row.locationId&&row.weight.trim()!=="").map(row=>{const location=locations.find(item=>item.id===row.locationId),weight=number(row.weight);return{...row,description:location?.description??row.locationId,weight,index:weight*(location?.indexPerWeightUnit??0)}});
 const outputRows=[
  {phase:"ZFW",weight:result.zfw,index:result.lizfw,mac:result.macZfw,weightKey:"zfw" as KnownKey,indexKey:"lizfw" as KnownKey,macKey:"macZfw" as KnownKey,structural:result.structural.zfw,limit:"MZFW",envelope:result.envelopes.zfw},
  {phase:"TOW",weight:result.tow,index:result.litow,mac:result.macTow,weightKey:"tow" as KnownKey,indexKey:"litow" as KnownKey,macKey:"macTow" as KnownKey,structural:result.structural.tow,limit:"MTOW",envelope:result.envelopes.tow},
  {phase:"LAW",weight:result.law,index:result.lilaw,mac:result.macLaw,weightKey:"law" as KnownKey,indexKey:"lilaw" as KnownKey,macKey:"macLaw" as KnownKey,structural:result.structural.law,limit:"MLAW",envelope:result.envelopes.law},
 ];
 const printEnvelopePoints:LoadsheetEnvelopePoint[]=[{phase:"zfw",label:"ZFW",weight:result.zfw,indexValue:result.lizfw,macValue:result.macZfw},{phase:"tow",label:"TOW",weight:result.tow,indexValue:result.litow,macValue:result.macTow},{phase:"law",label:"LAW",weight:result.law,indexValue:result.lilaw,macValue:result.macLaw}];
 const shown=(value:string,places=2)=>value.trim()===""?"—":fmt(Number(value),places);
 return <section className="sim-print-report" aria-hidden="true">
  <header><div><p>DATA VERIFICATION REPORT</p><h2>EDP Loadsheet Audit</h2></div><div className="sim-print-meta"><span>Carrier / Aircraft</span><strong>{initial.carrierCode} / {initial.typeCode}-{initial.subtype}</strong></div></header>
  <section><h3>1. Aircraft and operating basis</h3><div className="sim-print-facts"><div><span>Registration</span><strong>{registration.registration}</strong></div><div><span>Crew Code</span><strong>{crew.code}{crew.base?" · BASE":""}</strong></div><div><span>Pantry Code</span><strong>{pantry.code}{pantry.base?" · BASE":""}</strong></div><div><span>Fuel Table</span><strong>{fuelTable.label}</strong></div><div><span>DOW</span><strong>{fmt(result.dow,0)} {unit}</strong></div><div><span>DOI</span><strong>{fmt(result.doi)}</strong></div></div></section>
  <section><h3>2. Passenger distribution</h3><table><thead><tr><th>Cabin Area</th><th>Male</th><th>Female</th><th>Child</th><th>Infant</th><th>Total</th><th>Weight</th><th>Index</th></tr></thead><tbody>{passengerRows.map(row=><tr key={row.area.id}><td>{row.area.id}</td><td>{row.male}</td><td>{row.female}</td><td>{row.child}</td><td>{row.infant}</td><td>{row.total}</td><td>{fmt(row.weight,0)}</td><td>{fmt(row.index)}</td></tr>)}</tbody><tfoot><tr><th colSpan={5}>Total</th><th>{passengerRows.reduce((sum,row)=>sum+row.total,0)}</th><th>{fmt(result.passengerWeight,0)} {unit}</th><th>{fmt(result.passengerIndex)}</th></tr></tfoot></table></section>
  <section><h3>3. Deadload distribution</h3>{deadloadRows.length?<table><thead><tr><th>Commodity</th><th>Loading position</th><th>Weight</th><th>Index</th></tr></thead><tbody>{deadloadRows.map((row,index)=><tr key={`${row.locationId}-${index}`}><td>{row.kind}</td><td>{row.description}</td><td>{fmt(row.weight,0)} {unit}</td><td>{fmt(row.index)}</td></tr>)}</tbody><tfoot><tr><th colSpan={2}>Total</th><th>{fmt(result.deadloadWeight,0)} {unit}</th><th>{fmt(result.deadloadIndex)}</th></tr></tfoot></table>:<p>No deadload entered.</p>}</section>
  <section><h3>4. Fuel</h3><div className="sim-print-facts fuel"><div><span>Block Fuel</span><strong>{fmt(result.blockFuel,0)} {unit}</strong></div><div><span>Taxi Fuel</span><strong>{fmt(result.blockFuel-result.takeoffFuel,0)} {unit}</strong></div><div><span>Take-off Fuel</span><strong>{fmt(result.takeoffFuel,0)} {unit}</strong></div><div><span>Take-off Fuel Index</span><strong>{fmt(result.takeoffFuelIndex)}</strong></div><div><span>Trip Fuel</span><strong>{fmt(result.tripFuel,0)} {unit}</strong></div><div><span>Landing Fuel</span><strong>{fmt(result.landingFuel,0)} {unit}</strong></div><div><span>Landing Fuel Index</span><strong>{fmt(result.landingFuelIndex)}</strong></div><div><span>STABTO</span><strong>{result.stabTo===null?"Unavailable":fmt(result.stabTo,1)}</strong></div></div></section>
  <section className="sim-print-page"><h3>5. Calculated and known comparison</h3><table className="sim-print-comparison"><thead><tr><th rowSpan={2}>Condition</th><th colSpan={5}>Calculated</th><th colSpan={3}>Known</th><th colSpan={3}>Difference</th><th rowSpan={2}>Result</th></tr><tr><th>Weight</th><th>Index</th><th>%MAC</th><th>Weight</th><th>Balance</th><th>Weight</th><th>Index</th><th>%MAC</th><th>Weight</th><th>Index</th><th>%MAC</th></tr></thead><tbody>{outputRows.map(row=>{const kw=known[row.weightKey].trim()===""?null:Number(known[row.weightKey]),ki=known[row.indexKey].trim()===""?null:Number(known[row.indexKey]),km=known[row.macKey].trim()===""?null:Number(known[row.macKey]),dw=kw===null?null:row.weight-kw,di=ki===null?null:row.index-ki,dm=km===null?null:row.mac-km,tones=[dw===null?"neutral":comparisonTone(dw,"weight"),di===null?"neutral":comparisonTone(di,"index"),dm===null?"neutral":comparisonTone(dm,"mac")] as ComparisonTone[],tone=worstTone(tones.filter(value=>value!=="neutral"));return <tr key={row.phase}><th>{row.phase}</th><td>{fmt(row.weight,0)}</td><td>{fmt(row.index)}</td><td>{fmt(row.mac,1)}</td><td className="sim-print-outcome"><span className={row.structural?"green":"red"} title={`${row.limit}: ${row.structural?"PASS":"FAIL"}`}/></td><td className="sim-print-outcome"><span className={row.envelope.within?"green":"red"} title={`${row.envelope.code??"STANDARD"}: ${row.envelope.within?"IN ENVELOPE":row.envelope.resolved?"OUTSIDE":"UNRESOLVED"}`}/></td><td>{shown(known[row.weightKey],0)}</td><td>{shown(known[row.indexKey])}</td><td>{shown(known[row.macKey],1)}</td><td>{dw===null?"—":fmt(dw,0)}</td><td>{di===null?"—":fmt(di)}</td><td>{dm===null?"—":fmt(dm,1)}</td><td className="sim-print-outcome"><span className={tone} title={tone==="neutral"?"Known values not entered":`${row.phase} simulated versus known: ${tone}`}/></td></tr>})}</tbody></table><p className="sim-print-note">Comparison tolerance: green ±1 {unit}, ±2.00 index, ±1.0% MAC; amber up to ±10 {unit}, ±3.00 index, ±1.5% MAC.</p></section>
  <section><h3>6. Calculation audit</h3><table><thead><tr><th>Item</th><th>Weight</th><th>Index</th></tr></thead><tbody>{result.contributions.map(row=><tr key={row.label}><td>{row.label}</td><td>{fmt(row.weight,0)} {unit}</td><td>{fmt(row.index)}</td></tr>)}</tbody></table></section>
  {result.warnings.length>0&&<section className="sim-print-findings"><h3>7. Verification findings</h3><ul>{result.warnings.map((warning,index)=><li key={index}>{warning}</li>)}</ul></section>}
  <section className="sim-print-envelope"><h3>{result.warnings.length?"8":"7"}. Balance envelope</h3><BalanceEnvelopeView values={initial.limits} applicability={initial.envelopeApplicability} unit={unit} formula={initial.formula} loadsheetPoints={printEnvelopePoints} selectedConditionCodes={{zfw:result.envelopes.zfw.code??undefined,tow:result.envelopes.tow.code??undefined,law:result.envelopes.law.code??undefined}} combinedOnly onClose={()=>{}}/></section>
 </section>
}

function ComparisonDot({tone,label,title}:{tone:ComparisonTone;label:string;title:string}){return <span className={`sim-comparison-dot ${tone}`} aria-label={`${label}: ${title}`} title={`${label}: ${title}`}/>}

function Result({result,unit,known,setKnown}:{result:SimulatorResult;unit:string;known:Record<KnownKey,string>;setKnown:Dispatch<SetStateAction<Record<KnownKey,string>>>}){
 const rows=[
  {phase:"ZFW",weight:result.zfw,index:result.lizfw,mac:result.macZfw,weightKey:"zfw" as KnownKey,indexKey:"lizfw" as KnownKey,macKey:"macZfw" as KnownKey,structural:result.structural.zfw,structuralLabel:"MZFW",envelope:result.envelopes.zfw},
  {phase:"TOW",weight:result.tow,index:result.litow,mac:result.macTow,weightKey:"tow" as KnownKey,indexKey:"litow" as KnownKey,macKey:"macTow" as KnownKey,structural:result.structural.tow,structuralLabel:"MTOW",envelope:result.envelopes.tow},
  {phase:"LAW",weight:result.law,index:result.lilaw,mac:result.macLaw,weightKey:"law" as KnownKey,indexKey:"lilaw" as KnownKey,macKey:"macLaw" as KnownKey,structural:result.structural.law,structuralLabel:"MLAW",envelope:result.envelopes.law},
 ];
 return <><div className="sim-summary"><div><span>DOW / DOI</span><strong>{fmt(result.dow,0)} / {fmt(result.doi)}</strong></div><div><span>Passenger Weight</span><strong>{fmt(result.passengerWeight,0)} {unit}</strong></div><div><span>Deadload Weight</span><strong>{fmt(result.deadloadWeight,0)} {unit}</strong></div><div><span>Payload</span><strong>{fmt(result.payload,0)} {unit}</strong></div></div>
 <div className="sim-result-comparison" role="table" aria-label="Calculated and known loadsheet comparison">
  <div className="sim-result-comparison-title calculated">Calculated</div><div className="sim-result-comparison-title known">Known comparison</div>
  <div className="sim-result-comparison-head calculated"><span>Condition</span><span>Weight</span><span>Loaded Index</span><span>%MAC</span><span>Structural</span><span>Balance Envelope</span></div>
  <div className="sim-result-comparison-head known"><span>Condition</span><span>Weight</span><span>Loaded Index</span><span>%MAC</span><span>Result</span></div>
  {rows.map(row=>{const knownWeight=known[row.weightKey].trim()===""?null:Number(known[row.weightKey]),knownIndex=known[row.indexKey].trim()===""?null:Number(known[row.indexKey]),knownMac=known[row.macKey].trim()===""?null:Number(known[row.macKey]),differences=[knownWeight===null?null:row.weight-knownWeight,knownIndex===null?null:row.index-knownIndex,knownMac===null?null:row.mac-knownMac],tones=[knownWeight===null?"neutral":comparisonTone(differences[0],"weight"),knownIndex===null?"neutral":comparisonTone(differences[1],"index"),knownMac===null?"neutral":comparisonTone(differences[2],"mac")] as ComparisonTone[],populated=tones.filter(tone=>tone!=="neutral"),tone=worstTone(populated),description=populated.length?`ΔW ${fmt(differences[0]??0,0)} ${unit}; ΔI ${fmt(differences[1]??0)}; ΔMAC ${fmt(differences[2]??0,1)}`:"Enter known values";return <div className="sim-result-comparison-pair" role="row" key={row.phase}>
   <div className="sim-result-calculated"><strong>{row.phase}</strong><span>{fmt(row.weight,0)}</span><span>{fmt(row.index)}</span><span>{fmt(row.mac,1)}</span><ComparisonDot tone={row.structural?"green":"red"} label={`${row.phase} ${row.structuralLabel}`} title={row.structural?"PASS":"FAIL"}/><ComparisonDot tone={row.envelope.within?"green":"red"} label={`${row.phase} balance envelope`} title={`${row.envelope.code??"STANDARD"}: ${row.envelope.within?"IN ENVELOPE":row.envelope.resolved?"OUTSIDE":"UNRESOLVED"}`}/></div>
   <div className="sim-result-known"><strong>{row.phase}</strong>{([row.weightKey,row.indexKey,row.macKey] as KnownKey[]).map((key,index)=><input key={key} aria-label={`Known ${row.phase} ${index===0?"weight":index===1?"loaded index":"percent MAC"}`} inputMode="decimal" value={known[key]} onChange={event=>/^-?\d*(?:\.\d*)?$/.test(event.target.value)&&setKnown(values=>({...values,[key]:event.target.value}))}/>) }<ComparisonDot tone={tone} label={`${row.phase} comparison`} title={description}/></div>
  </div>})}
 </div>
 <div className="sim-comparison-legend" aria-label="Comparison tolerances"><span><i className="green"/>Within tolerance</span><span><i className="amber"/>Review</span><span><i className="red"/>Outside tolerance</span><small>Green: ±1 {unit}, ±2.00 index, ±1.0% MAC. Amber: up to ±10 {unit}, ±3.00 index, ±1.5% MAC.</small></div>
 <div className="sim-fuel-summary"><span>Block Fuel <strong>{fmt(result.blockFuel,0)}</strong></span><span>Take-off Fuel <strong>{fmt(result.takeoffFuel,0)}</strong></span><span>Trip Fuel <strong>{fmt(result.tripFuel,0)}</strong></span><span>Landing Fuel <strong>{fmt(result.landingFuel,0)}</strong></span><span>STABTO <strong>{result.stabTo===null?"UNAVAILABLE":fmt(result.stabTo,1)}</strong></span></div>
 <details className="sim-audit"><summary>CALCULATION AUDIT</summary><div className="sim-audit-head" aria-hidden="true"><span>Item</span><span>Weight</span><span>Index</span></div>{result.contributions.map(row=><div key={row.label}><span>{row.label}</span><span>{fmt(row.weight,0)} {unit}</span><span>{fmt(row.index)}</span></div>)}</details>{result.warnings.length>0&&<div className="sim-warnings"><strong>Verification findings</strong><ul>{result.warnings.map((warning,index)=><li key={index}>{warning}</li>)}</ul></div>}</>}
