"use client";

import { useEffect, useMemo, useState, useTransition, type DragEvent } from "react";
import { proposeOperationalAutoload, reviseOperationalLoadPlan, type AutoloadActionState } from "@/app/load-control-actions";
import { LoadPlanningProblemInvalid, validateLoadPlanningSolution, type LoadPlanningAssignment, type LoadPlanningProblem, type LoadPlanningSolution, type SolverLoad, type SolverPosition } from "@/domain/load-planning-solver";
import { HoldDiagram } from "@/components/hold-layout-viewer";
import { BalanceEnvelopeView, type EnvelopeFuelProjection, type LoadsheetEnvelopePoint } from "@/components/balance-envelope-chart";
import { aircraftD2HoldId } from "@/domain/aircraft-d2";
import type { HoldLayout, LayoutSubdivision } from "@/domain/hold-layout";
import {estimatedZfwBalancePoint,projectedFuelCurve} from "@/domain/operational-balance-projection";

const empty: AutoloadActionState = { ok: false, message: "", problem: null, solution: null, warnings: [], layout: null, layoutOffsetX: 0, envelope: null, edition: null };
type GraphicSlot = { key: string; holdId: string; locationRef: string; positions: SolverPosition[] };
type DeckKey = "MAIN" | "LOWER";
type AssignmentRow = { assignment: LoadPlanningAssignment; load: SolverLoad | undefined; position: SolverPosition | undefined };

const slotKey = (position: SolverPosition) => `${position.holdId}|${position.locationRef ?? position.id}`;
const fits = (load: SolverLoad, position: SolverPosition) => load.loadType === position.loadType && load.weightKg <= position.maximumWeightKg && (load.loadType === "BULK" || position.acceptedUldCodes.includes(load.uldCode!)) && (load.loadType !== "BULK" || load.volumeLitres === null || position.maximumVolumeLitres === null || load.volumeLitres <= position.maximumVolumeLitres);
const overlap = (left: SolverPosition, right: SolverPosition) => left.occupiedBayIds.some((bay) => right.occupiedBayIds.includes(bay));
const deckFor = (position: SolverPosition): DeckKey => /MAIN|MDECK|UPPER|(^|\W)MD(\W|$)/.test(`${position.deckCode} ${position.holdId}`.toUpperCase()) ? "MAIN" : "LOWER";

const metrics = (problem: LoadPlanningProblem, solution: LoadPlanningSolution, assignments: LoadPlanningAssignment[]): LoadPlanningSolution => {
  const positions = new Map(problem.positions.map((position) => [position.id, position])), loads = new Map(problem.loads.map((load) => [load.id, load]));
  const assigned = assignments.map((assignment) => ({ assignment, load: loads.get(assignment.loadId)!, position: positions.get(assignment.positionId)! }));
  const sequencePenalty = assigned.reduce((total, left) => total + assigned.reduce((sum, right) => left.load.unloadOrder < right.load.unloadOrder && left.position.holdId === right.position.holdId && left.position.handlingRank > right.position.handlingRank ? sum + 1 : sum, 0), 0);
  const usedSimplicityGroups = new Set(assigned.map((row) => row.position.simplicityGroup)).size, totalIndex = assigned.reduce((sum, row) => sum + row.load.weightKg * row.position.indexPerKgScaled, 0), trimDeviationScaled = problem.idealTrimIndexScaled === null ? null : Math.abs(totalIndex - problem.idealTrimIndexScaled);
  return { ...solution, status: "FEASIBLE", assignments, sequencePenalty, usedSimplicityGroups, trimDeviationScaled, messages: ["The adjusted plan passed the independent position, overlap, segregation, Bulk capacity and special-load quantity checks."] };
};

export function LoadPlanningWorkspace({ iata, flightId, released, acceptedWeight, initialEdition, flightNumber, serviceDate, itinerary, sector, aircraft, registration }: { iata: string; flightId: string; released: boolean; acceptedWeight: number; initialEdition: number; flightNumber: string; serviceDate: string; itinerary: string; sector: string; aircraft: string; registration: string }) {
  const [pending, start] = useTransition(), [revisionPending, startRevision] = useTransition(), [result, setResult] = useState(empty), [assignments, setAssignments] = useState<LoadPlanningAssignment[]>([]), [selectedLoadId, setSelectedLoadId] = useState<string | null>(null), [adjusted, setAdjusted] = useState(false), [moveNotice, setMoveNotice] = useState<{ ok: boolean; text: string } | null>(null), [payload, setPayload] = useState({ released, acceptedWeight }), [activeDeck, setActiveDeck] = useState<DeckKey>("MAIN"), [showEnvelope, setShowEnvelope] = useState(false),[fuelCurveId,setFuelCurveId]=useState(""),[edition,setEdition]=useState(initialEdition);
  useEffect(() => { const update = (event: Event) => { const detail = (event as CustomEvent<{ flightId: string; released: boolean; acceptedWeight: number }>).detail; if (detail?.flightId === flightId) { setPayload({ released: detail.released, acceptedWeight: detail.acceptedWeight }); setResult(empty); setAssignments([]); setFuelCurveId(""); setAdjusted(false); setShowEnvelope(false); } }; window.addEventListener("wab:freight-acceptance", update); return () => window.removeEventListener("wab:freight-acceptance", update); }, [flightId]);
  const positions = useMemo(() => new Map(result.problem?.positions.map((position) => [position.id, position]) ?? []), [result.problem]), loads = useMemo(() => new Map(result.problem?.loads.map((load) => [load.id, load]) ?? []), [result.problem]);
  const currentSolution = useMemo(() => result.problem && result.solution && adjusted ? metrics(result.problem, result.solution, assignments) : result.solution, [adjusted, assignments, result.problem, result.solution]);
  const estimatedBalance=useMemo(()=>result.envelope?.formula&&result.envelope.operationalBaseIndex!==null&&result.problem&&currentSolution?estimatedZfwBalancePoint({weight:result.envelope.estimatedZfwWeight,baseIndex:result.envelope.operationalBaseIndex,problem:result.problem,assignments,formula:result.envelope.formula}):null,[assignments,currentSolution,result.envelope,result.problem]);
  const selectedFuelCurve=result.envelope?.fuelCurves.find(curve=>curve.id===fuelCurveId)??result.envelope?.fuelCurves[0]??null,fuelProjection:EnvelopeFuelProjection|null=estimatedBalance&&selectedFuelCurve&&result.envelope?{label:`${selectedFuelCurve.label} standard fuel-loading curve`,points:projectedFuelCurve(estimatedBalance,selectedFuelCurve.points,result.envelope.values.maximumWeights.tow)}:null,envelopePoints:LoadsheetEnvelopePoint[]=estimatedBalance?[{phase:"zfw",label:"eZFW",...estimatedBalance}]:[];
  const rows = useMemo(() => assignments.map((assignment) => ({ assignment, load: loads.get(assignment.loadId), position: positions.get(assignment.positionId) })).filter((row) => row.load && row.position).sort((a, b) => (a.load!.unloadOrder - b.load!.unloadOrder) || a.position!.description.localeCompare(b.position!.description)), [assignments, loads, positions]);
  const slots = useMemo(() => { const grouped = new Map<string, GraphicSlot>(); for (const position of result.problem?.positions ?? []) { const key = slotKey(position), current = grouped.get(key); if (current) current.positions.push(position); else grouped.set(key, { key, holdId: position.holdId, locationRef: position.locationRef ?? position.description, positions: [position] }); } return [...grouped.values()].sort((a, b) => (b.positions[0].balanceArm ?? -Infinity) - (a.positions[0].balanceArm ?? -Infinity) || a.locationRef.localeCompare(b.locationRef)); }, [result.problem]);
  const deckGroups = useMemo(() => { const decks = new Map<DeckKey, Map<string, GraphicSlot[]>>(); for (const slot of slots) { const deck = deckFor(slot.positions[0]); if (!decks.has(deck)) decks.set(deck, new Map()); const holds = decks.get(deck)!; holds.set(slot.holdId, [...(holds.get(slot.holdId) ?? []), slot]); } return decks; }, [slots]);
  const availableDecks = (["MAIN", "LOWER"] as DeckKey[]).filter((deck) => deckGroups.has(deck)), visibleDeck = availableDecks.includes(activeDeck) ? activeDeck : availableDecks[0] ?? "MAIN", visibleHoldGroups = [...(deckGroups.get(visibleDeck)?.entries() ?? [])];
  const run = () => start(async () => { setShowEnvelope(false); const next = await proposeOperationalAutoload(iata, flightId, edition); setResult(next); if (next.edition !== null) setEdition(next.edition); setAssignments(next.solution?.assignments ?? []); setFuelCurveId(next.envelope?.fuelCurves[0]?.id??""); setSelectedLoadId(null); setAdjusted(false); setMoveNotice(null); setActiveDeck(next.problem?.positions.some((position) => deckFor(position) === "MAIN") ? "MAIN" : "LOWER"); });
  const validate = (candidate: LoadPlanningAssignment[]) => { if (!result.problem || !result.solution) return null; const solution = metrics(result.problem, result.solution, candidate); validateLoadPlanningSolution(result.problem, solution); return solution; };
  const persistRevision = (candidate: LoadPlanningAssignment[], source: "MANUAL" | "RESET", successText: string) => {
    if (!result.problem || !result.solution) return;
    const solution = metrics(result.problem, result.solution, candidate);
    startRevision(async () => {
      const saved = await reviseOperationalLoadPlan(iata, flightId, edition, source, result.problem!, solution);
      if (!saved.ok) { setMoveNotice({ ok: false, text: saved.message }); return; }
      setAssignments(candidate); setEdition(saved.edition); setAdjusted(source === "MANUAL"); setSelectedLoadId(null); setMoveNotice({ ok: true, text: `${successText} Edition ${saved.edition}.` });
    });
  };
  const move = (loadId: string, target: GraphicSlot) => {
    if (!result.problem || !result.solution) return;
    const load = loads.get(loadId), sourceAssignment = assignments.find((row) => row.loadId === loadId), sourcePosition = sourceAssignment ? positions.get(sourceAssignment.positionId) : null;
    if (!load || !sourceAssignment || !sourcePosition) return;
    const label = load.description.split(" · ")[0]; let lastError = "This load cannot use the selected position.";
    for (const targetPosition of target.positions.filter((position) => fits(load, position))) {
      if (targetPosition.id === sourcePosition.id) { setSelectedLoadId(null); return; }
      const conflicts = targetPosition.loadType === "ULD" ? assignments.filter((row) => row.loadId !== loadId && overlap(positions.get(row.positionId)!, targetPosition)) : [], attempts: LoadPlanningAssignment[][] = [];
      if (!conflicts.length) attempts.push(assignments.map((row) => row.loadId === loadId ? { ...row, positionId: targetPosition.id } : row));
      else if (conflicts.length === 1) { const displaced = loads.get(conflicts[0].loadId)!; for (const replacement of targetForSourceSlot(result.problem.positions, sourcePosition).filter((position) => fits(displaced, position))) attempts.push(assignments.map((row) => row.loadId === loadId ? { ...row, positionId: targetPosition.id } : row.loadId === displaced.id ? { ...row, positionId: replacement.id } : row)); }
      for (const candidate of attempts) try { validate(candidate); const displacedLabel = conflicts.length ? loads.get(conflicts[0].loadId)?.description.split(" · ")[0] : null; persistRevision(candidate, "MANUAL", displacedLabel ? `${label} moved to ${target.locationRef}; ${displacedLabel} was exchanged into its previous position.` : `${label} moved to ${target.locationRef}.`); return; } catch (error) { lastError = error instanceof LoadPlanningProblemInvalid ? error.message : "This move is not valid."; }
    }
    setMoveNotice({ ok: false, text: lastError });
  };
  const drop = (event: DragEvent<HTMLDivElement>, slot: GraphicSlot) => { event.preventDefault(); const loadId = event.dataTransfer.getData("text/plain"); if (loadId) move(loadId, slot); }, status = adjusted ? "MANUALLY ADJUSTED" : currentSolution?.status ?? (payload.released ? "READY" : "AWAITING PAYLOAD");
  return <details className="load-planning-workspace operational-collapsible" open>
    <summary className="operational-collapsible-summary load-planning-heading"><div><p className="eyebrow">LOAD PLANNING</p><h2>AUTOLOAD proposal</h2><p>Place released ULD and Bulk loads using unloading sequence, loading simplicity and Ideal Trim priorities.</p></div><div className="operational-summary-facts"><span><small>RELEASED LOAD</small><strong>{Math.round(payload.acceptedWeight).toLocaleString()} KG</strong></span><span><small>EDITION</small><strong>{edition || "—"}</strong></span><span><small>ASSIGNMENTS</small><strong>{rows.length || "—"}</strong></span><span className={`summary-emphasis ${result.ok ? "ready" : "incomplete"}`}><small>SOLVER STATUS</small><strong>{status}</strong></span></div></summary>
    <div className="operational-collapsible-body"><div className="load-planning-intro"><div><strong>Proposed loading only</strong><span>The independent validator checks position compatibility, limits, locks, overlapping ULD footprints and special-load segregation before the proposal is displayed.</span></div><button type="button" onClick={run} disabled={!payload.released || pending}>{pending ? "CALCULATING…" : "AUTOLOAD"}</button></div>
      {!payload.released && <p className="load-control-notice error">Save and release the ULD/Bulk Load Weight Statement before running AUTOLOAD.</p>}{result.message && <p className={`load-control-notice ${result.ok ? "success" : "error"}`}>{result.message}</p>}{result.warnings.map((warning) => <p className="load-control-notice warning" key={warning}>{warning}</p>)}
      {currentSolution && <><div className="autoload-metrics"><span><small>ENGINE</small><strong>{currentSolution.engine}</strong></span><span><small>SOLVE TIME</small><strong>{formatSolveDuration(currentSolution.solveMilliseconds)}</strong></span><span><small>UNLOAD INVERSIONS</small><strong>{result.warnings.some(warning=>warning.includes("unloading accessibility"))?"Not fully scored":currentSolution.sequencePenalty ?? "—"}</strong></span><span><small>IDEAL TRIM DEVIATION</small><strong>{currentSolution.trimDeviationScaled === null ? "Not scored" : `${(currentSolution.trimDeviationScaled / 100_000).toFixed(2)} INDEX`}</strong></span>{result.envelope&&<button type="button" className="secondary autoload-envelope-button" aria-expanded={showEnvelope} aria-controls="balance-envelope-view-heading" onClick={()=>setShowEnvelope(current=>!current)}>{showEnvelope?"CLOSE ENVELOPE":"VIEW ENVELOPE"}</button>}</div>{showEnvelope&&result.envelope&&<>{result.envelope.fuelCurves.length>1&&<label className="operational-fuel-curve-select"><span>PLANNING FUEL CURVE</span><select value={selectedFuelCurve?.id??""} onChange={event=>setFuelCurveId(event.target.value)}>{result.envelope.fuelCurves.map(curve=><option value={curve.id} key={curve.id}>{curve.label}</option>)}</select></label>}<BalanceEnvelopeView values={result.envelope.values} applicability={result.envelope.applicability} unit={result.envelope.unit} formula={result.envelope.formula} idealTrimPoints={result.envelope.idealTrimPoints} loadsheetPoints={envelopePoints} fuelProjection={fuelProjection} combinedOnly onClose={()=>setShowEnvelope(false)}/></>}</>}
      {rows.length > 0 && <section className="load-plan-graphic" aria-labelledby="load-plan-graphic-heading"><header><div><p className="eyebrow">INTERACTIVE LOAD PLAN</p><h3 id="load-plan-graphic-heading">Aircraft loading positions</h3><p>Drag a load to another position, or select it and use PLACE HERE. Every change is validated before it is shown.</p></div><div className="load-plan-header-actions">{adjusted && <button type="button" className="secondary" disabled={revisionPending} onClick={() => persistRevision(result.solution?.assignments ?? [], "RESET", "AUTOLOAD proposal restored as")}>RESET TO AUTOLOAD</button>}<button type="button" className="secondary load-plan-print-button" disabled={revisionPending} onClick={() => window.print()}>PRINT</button></div></header>{moveNotice && <p className={`load-plan-move-notice ${moveNotice.ok ? "success" : "error"}`} role="status">{moveNotice.text}</p>}
        <div className="load-plan-deck-tabs" role="tablist" aria-label="Aircraft deck">{availableDecks.map((deck) => <button type="button" role="tab" aria-selected={visibleDeck === deck} className={visibleDeck === deck ? "active" : ""} key={deck} onClick={() => setActiveDeck(deck)}>{deck === "MAIN" ? "MAIN DECK" : "LOWER DECK"}</button>)}</div>
        <div className="load-plan-aircraft" role="tabpanel">{result.layout ? <AircraftLoadOverlay layout={result.layout} offsetX={result.layoutOffsetX} deck={visibleDeck} slots={visibleHoldGroups.flatMap(([, holdSlots]) => holdSlots)} rows={rows} loads={loads} selectedLoadId={selectedLoadId} onSelect={loadId => setSelectedLoadId(current => current === loadId ? null : loadId)} onMove={move} /> : <p className="load-control-notice warning">The calibrated aircraft overlay is unavailable. Use the position list below.</p>}</div>
        <details className="load-plan-position-details"><summary>Position list and capacity details</summary><div className="load-plan-orientation"><span>TAIL</span><span>NOSE</span></div>{visibleHoldGroups.map(([holdId, holdSlots]) => <section className="load-plan-hold" key={holdId}><h4>{holdName(holdId)}</h4><div className="load-plan-position-strip">{holdSlots.map((slot) => { const slotIds = new Set(slot.positions.map((position) => position.id)), slotRows = rows.filter((row) => slotIds.has(row.assignment.positionId)), selected = selectedLoadId ? loads.get(selectedLoadId) : null, canPlace = Boolean(selected && slot.positions.some((position) => fits(selected, position))), remaining = bulkRemaining(slot, slotRows.map((row) => row.load!)); return <div className={`load-plan-position ${selectedLoadId && canPlace ? "can-drop" : ""}`} key={slot.key} onDragOver={(event) => { if (canPlace) event.preventDefault(); }} onDrop={(event) => drop(event, slot)}><div className="load-plan-position-label"><strong>{slot.locationRef}</strong><small>{remaining ?? positionType(slot.positions)}</small></div><div className="load-plan-position-loads">{slotRows.length ? slotRows.map((row) => <LoadCard key={row.load!.id} load={row.load!} selected={selectedLoadId === row.load!.id} select={() => setSelectedLoadId((current) => current === row.load!.id ? null : row.load!.id)} />) : <span className="load-plan-empty">NOFIT</span>}</div>{selectedLoadId && canPlace && <button type="button" className="load-plan-place" onClick={() => move(selectedLoadId, slot)}>PLACE HERE</button>}</div>; })}</div></section>)}</details>
        <section className="load-plan-print-sheet" aria-hidden="true">
          <header><div><p>OPERATIONAL LOAD CONTROL</p><h2>LOADING INSTRUCTION</h2></div><div><span>FLIGHT</span><strong>{flightNumber}</strong><span>DATE</span><strong>{serviceDate}</strong><span>EDITION</span><strong>{edition}</strong></div></header>
          <div className="load-plan-print-facts"><span><small>FULL ITINERARY</small><strong>{itinerary}</strong></span><span><small>CURRENT SECTOR</small><strong>{sector}</strong></span><span><small>AIRCRAFT</small><strong>{aircraft}</strong></span><span><small>REGISTRATION</small><strong>{registration}</strong></span><span><small>STATUS</small><strong>{status}</strong></span><span><small>eZFW</small><strong>{estimatedBalance ? `${Math.round(estimatedBalance.weight).toLocaleString()} KG · ${estimatedBalance.indexValue.toFixed(2)} INDEX` : "NOT AVAILABLE"}</strong></span></div>
          {result.layout && <div className="load-plan-print-decks">{availableDecks.map(deck => <section key={deck}><h3>{deck === "MAIN" ? "MAIN DECK" : "LOWER DECK"}</h3><AircraftLoadOverlay layout={result.layout!} offsetX={result.layoutOffsetX} deck={deck} slots={[...(deckGroups.get(deck)?.values() ?? [])].flat()} rows={rows} loads={loads} selectedLoadId={null} onSelect={() => {}} onMove={() => {}} /></section>)}</div>}
          <section className="load-plan-print-signoff">
            <p>This aircraft has been loaded in accordance with the instructions including the deviations shown on the report.<br/>All containers/pallets and bulk load have been secured in accordance with company regulations.</p>
            <div><span className="load-plan-signoff-role"><strong>Person Responsible for Loading:</strong></span><span><strong>Signature:</strong><i/></span><span className="load-plan-signoff-role"><strong>Completed by:</strong></span><span><strong>Signature:</strong><i/></span></div>
          </section>
          <footer><strong>PRELIMINARY LOADING INSTRUCTION · EDITION {edition}</strong><span>Unload inversions: {currentSolution?.sequencePenalty ?? "—"} · Ideal Trim deviation: {currentSolution?.trimDeviationScaled === null || currentSolution?.trimDeviationScaled === undefined ? "Not scored" : `${(currentSolution.trimDeviationScaled / 100_000).toFixed(2)} index`}</span></footer>
        </section>
      </section>}
      {rows.length > 0 && <details className="autoload-detail-table"><summary>Assignment details</summary><div className="autoload-table"><div className="autoload-row head"><span>Load</span><span>Unload</span><span>Gross</span><span>Proposed position</span><span>Special information</span><span>Priority</span></div>{rows.map(({ assignment, load, position }) => {const special=specialInformation(load!);return <div className="autoload-row" key={assignment.loadId}><span data-label="Load"><strong>{load!.description.split(" · ")[0]}</strong><small>{load!.loadType}{load!.uldCode ? ` · ${load!.uldCode}` : ""}</small></span><span data-label="Unload"><strong>{unloadStation(load!)}</strong></span><span data-label="Gross"><strong>{load!.weightKg.toLocaleString()} KG</strong></span><span data-label="Proposed position"><strong>{position!.description}</strong></span><span data-label="Special information">{special.details.length?<strong>{special.details.join(" · ")}</strong>:<strong>—</strong>}{special.dangerous&&<small className="dangerous-goods">INC DGR</small>}</span><span data-label="Priority"><strong>{load!.unloadOrder + 1}</strong></span></div>})}</div></details>}{currentSolution?.messages.map((item) => <p className="autoload-note" key={item}>{item}</p>)}
      <p className="autoload-scope"><strong>Current proposal scope:</strong> payload placement, position weight and volume limits, ULD fit, physical overlap, door-based offload order where D4 door positions are configured, simplicity, Ideal Trim, master special-load incompatibilities, IATA DGR segregation and H1 location and quantity limits. Conditional rules remain blocked when their required details have not been recorded. Ground-stability sequence validation must also be added before a proposal can be committed as a loading instruction.</p>
    </div>
  </details>;
}

function AircraftLoadOverlay({ layout, offsetX, deck, slots, rows, loads, selectedLoadId, onSelect, onMove }: { layout: HoldLayout; offsetX: number; deck: DeckKey; slots: GraphicSlot[]; rows: AssignmentRow[]; loads: Map<string, SolverLoad>; selectedLoadId: string | null; onSelect: (loadId: string) => void; onMove: (loadId: string, slot: GraphicSlot) => void }) {
  const deckInfo = layout.decks.find((item) => deckFromLabel(`${item.code} ${item.name}`) === deck);
  if (!deckInfo) return <p className="load-control-notice warning">No calibrated {deck === "MAIN" ? "Main Deck" : "Lower Deck"} drawing is available.</p>;
  const aircraft = layout.calibration, fullViewWidth = aircraft.imageFrame.width, viewHeight = aircraft.imageFrame.height, fullViewX = aircraft.tailX - aircraft.span / 2 - fullViewWidth / 2, viewY = aircraft.centreY - viewHeight / 2;
  const plotted = slots.flatMap((slot) => { const geometry = slotGeometry(layout, slot); return geometry ? [{ slot, geometry }] : []; });
  const padding=fullViewWidth*.045,minX=plotted.length?Math.min(...plotted.map(item=>item.geometry.x+offsetX)):fullViewX,maxX=plotted.length?Math.max(...plotted.map(item=>item.geometry.x+offsetX+item.geometry.width)):fullViewX+fullViewWidth,viewX=Math.max(fullViewX,minX-padding),viewEnd=Math.min(fullViewX+fullViewWidth,maxX+padding),viewWidth=viewEnd-viewX;
  const selectedUldType = plotted.find((item) => item.geometry.uldType)?.geometry.uldType ?? null;
  return <div className="aircraft-load-overlay">
    <HoldDiagram layout={layout} deckCode={deckInfo.code} selectedUldType={selectedUldType} selectedArrangements={{}} offsetX={offsetX} loads={[]} fillAirframe hidePositionDetails viewport={{x:viewX,y:viewY,width:viewWidth,height:viewHeight}} />
    <div className="aircraft-load-overlay-layer" aria-label={`${deck === "MAIN" ? "Main Deck" : "Lower Deck"} loading diagram`}>{plotted.map(({ slot, geometry }) => {
      const slotIds = new Set(slot.positions.map((position) => position.id)), slotRows = rows.filter((row) => slotIds.has(row.assignment.positionId)), selected = selectedLoadId ? loads.get(selectedLoadId) : null, canPlace = Boolean(selected && slot.positions.some((position) => fits(selected, position))), remaining = bulkRemaining(slot, slotRows.map((row) => row.load!));
      const style = { left: `${((geometry.x + offsetX - viewX) / viewWidth) * 100}%`, top: `${((geometry.y - viewY) / viewHeight) * 100}%`, width: `${(geometry.width / viewWidth) * 100}%`, height: `${(geometry.height / viewHeight) * 100}%` };
      return <div className={`aircraft-overlay-slot ${slotRows.length ? "loaded" : "unused"} ${selectedLoadId && canPlace ? "can-drop" : ""}`} style={style} key={slot.key} onDragOver={(event) => { if (canPlace) event.preventDefault(); }} onDrop={(event) => { event.preventDefault(); const loadId = event.dataTransfer.getData("text/plain"); if (loadId) onMove(loadId, slot); }} title={`${slot.locationRef}${remaining ? ` · ${remaining}` : ""}`}>
        <span className="aircraft-overlay-position">{slot.locationRef}</span>
        {slotRows.map((row) => <LoadCard key={row.load!.id} load={row.load!} selected={selectedLoadId === row.load!.id} select={() => onSelect(row.load!.id)} />)}
        {!slotRows.length&&<span className="aircraft-overlay-nofit">NOFIT</span>}
        {remaining && <small className="aircraft-overlay-capacity">{remaining.replace("REMAINING ", "")}</small>}
        {selectedLoadId && canPlace && <button type="button" className="aircraft-overlay-place" onClick={() => onMove(selectedLoadId, slot)}>PLACE</button>}
      </div>;
    })}</div>
    <div className="aircraft-load-overlay-direction"><span>TAIL</span><span>NOSE</span></div>
  </div>;
}

function deckFromLabel(value: string): DeckKey { return /MAIN|MDECK|UPPER|(^|\W)MD(\W|$)/.test(value.toUpperCase()) ? "MAIN" : "LOWER"; }
function slotGeometry(layout: HoldLayout, slot: GraphicSlot): { x: number; y: number; width: number; height: number; uldType: string | null } | null {
  const hold = layout.holds.find((item) => aircraftD2HoldId(item) === slot.holdId);
  if (!hold) return null;
  const aircraft = layout.calibration;
  if (slot.positions[0].loadType === "ULD") {
    const accepted = new Set(slot.positions.flatMap((position) => position.acceptedUldCodes)), position = hold.uldPositions.find((item) => item.id === slot.locationRef && item.uldCodes.some((code) => accepted.has(code))) ?? hold.uldPositions.find((item) => item.id === slot.locationRef);
    if (!position) return null;
    const range = position.codeRanges?.find((item) => accepted.has(item.uldCode)), x = range?.x ?? position.x, width = range?.width ?? position.width, side = position.id.trim().toUpperCase().endsWith("L") ? "L" : position.id.trim().toUpperCase().endsWith("R") ? "R" : "FULL", inset = .35, gap = .18, availableHeight = aircraft.holdHeight - inset * 2, height = side === "FULL" ? availableHeight : availableHeight / 2 - gap / 2, y = side === "R" ? aircraft.holdY + inset + availableHeight / 2 + gap / 2 : aircraft.holdY + inset;
    return { x: x + .35, y, width: Math.max(0, width - .7), height, uldType: position.uldType };
  }
  const matches = hold.subdivisions.filter((item) => item.id === slot.locationRef || item.compartmentId === slot.locationRef), sections = matches.length ? matches : hold.subdivisions.length ? hold.subdivisions : [{ x: hold.x, width: hold.width } as LayoutSubdivision], x = Math.min(...sections.map((item) => item.x)), end = Math.max(...sections.map((item) => item.x + item.width));
  return { x: x + .35, y: aircraft.holdY + .35, width: Math.max(0, end - x - .7), height: aircraft.holdHeight - .7, uldType: null };
}

function targetForSourceSlot(positions: SolverPosition[], source: SolverPosition) { const key = slotKey(source); return positions.filter((position) => slotKey(position) === key); }
function formatSolveDuration(milliseconds:number){return milliseconds>=1000?`${(milliseconds/1000).toFixed(2)} s`:`${milliseconds.toLocaleString()} ms`;}
function holdName(value: string) { const upper = value.toUpperCase(); if (upper.includes("MDECK") || upper.includes("MAIN")) return "MAIN DECK"; const suffix = upper.includes(":") ? upper.slice(upper.lastIndexOf(":") + 1) : upper; if (suffix === "FWD" || suffix === "AFT") return `${suffix} HOLD`; if (/^\d+$/.test(suffix)) return `BULK HOLD ${suffix}`; return value; }
function positionType(positions: SolverPosition[]) { const first = positions[0]; return first.loadType === "BULK" ? `BULK · MAX ${first.maximumWeightKg.toLocaleString()} KG` : `ULD · ${[...new Set(positions.flatMap((position) => position.acceptedUldCodes))].join(" / ")}`; }
function unloadStation(load: SolverLoad) { return load.description.split("unload ")[1] ?? "—"; }
function bulkRemaining(slot: GraphicSlot, slotLoads: SolverLoad[]) { if (slot.positions[0].loadType !== "BULK") return null; const maximumWeight = slot.positions.reduce((sum, position) => sum + position.maximumWeightKg, 0), remainingWeight = Math.max(0, maximumWeight - slotLoads.reduce((sum, load) => sum + load.weightKg, 0)), volumes = slot.positions.map((position) => position.maximumVolumeLitres), maximumVolume = volumes.every((volume) => volume !== null) ? volumes.reduce<number>((sum, volume) => sum + volume!, 0) : null, usedVolume = slotLoads.reduce((sum, load) => sum + (load.volumeLitres ?? 0), 0); return `REMAINING ${remainingWeight.toLocaleString()} KG · ${maximumVolume === null ? "VOL N/A" : `${((Math.max(0, maximumVolume - usedVolume)) / 1000).toFixed(2)} m³`}`; }
function specialInformation(load:SolverLoad){const weighted=load.specialLoadDetails??[],weightedCodes=new Set(weighted.map(value=>value.split("/")[0])),unweighted=load.specialLoadCodes.filter(code=>!weightedCodes.has(code));return{details:[...weighted,...unweighted],dangerous:load.dangerousGoodsClasses.length>0};}
function LoadCard({ load, selected, select }: { load: SolverLoad; selected: boolean; select: () => void }) { const special=specialInformation(load),controlled=special.dangerous||special.details.length>0; return <button type="button" draggable={!load.lockedPositionId} aria-pressed={selected} className={`load-plan-card ${controlled ? "controlled" : ""} ${special.dangerous ? "dangerous" : ""} ${selected ? "selected" : ""}`} onClick={select} onDragStart={(event) => { event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/plain", load.id); }}><strong>{unloadStation(load)}</strong><span>{load.description.split(" · ")[0]}</span><span>{load.weightKg.toLocaleString()} KG</span>{special.details.length>0&&<small>{special.details.join(" · ")}</small>}{load.lockedPositionId && <small>LOCKED</small>}</button>; }
