"use client";

import { useEffect, useMemo, useState, useTransition, type DragEvent } from "react";
import { proposeOperationalAutoload, type AutoloadActionState } from "@/app/load-control-actions";
import { LoadPlanningProblemInvalid, validateLoadPlanningSolution, type LoadPlanningAssignment, type LoadPlanningProblem, type LoadPlanningSolution, type SolverLoad, type SolverPosition } from "@/domain/load-planning-solver";

const empty: AutoloadActionState = { ok: false, message: "", problem: null, solution: null, warnings: [] };
type GraphicSlot = { key: string; holdId: string; locationRef: string; positions: SolverPosition[] };
type DeckKey = "MAIN" | "LOWER";

const slotKey = (position: SolverPosition) => `${position.holdId}|${position.locationRef ?? position.id}`;
const fits = (load: SolverLoad, position: SolverPosition) => load.loadType === position.loadType && load.weightKg <= position.maximumWeightKg && (load.loadType === "BULK" || position.acceptedUldCodes.includes(load.uldCode!)) && (load.loadType !== "BULK" || load.volumeLitres === null || position.maximumVolumeLitres === null || load.volumeLitres <= position.maximumVolumeLitres);
const overlap = (left: SolverPosition, right: SolverPosition) => left.occupiedBayIds.some((bay) => right.occupiedBayIds.includes(bay));
const deckFor = (position: SolverPosition): DeckKey => /MAIN|MDECK|UPPER|(^|\W)MD(\W|$)/.test(`${position.deckCode} ${position.holdId}`.toUpperCase()) ? "MAIN" : "LOWER";

const metrics = (problem: LoadPlanningProblem, solution: LoadPlanningSolution, assignments: LoadPlanningAssignment[]): LoadPlanningSolution => {
  const positions = new Map(problem.positions.map((position) => [position.id, position])), loads = new Map(problem.loads.map((load) => [load.id, load]));
  const assigned = assignments.map((assignment) => ({ assignment, load: loads.get(assignment.loadId)!, position: positions.get(assignment.positionId)! }));
  const sequencePenalty = assigned.reduce((total, left) => total + assigned.reduce((sum, right) => left.load.unloadOrder < right.load.unloadOrder ? sum + Math.max(0, left.position.handlingRank - right.position.handlingRank) : sum, 0), 0);
  const usedSimplicityGroups = new Set(assigned.map((row) => row.position.simplicityGroup)).size, totalIndex = assigned.reduce((sum, row) => sum + row.load.weightKg * row.position.indexPerKgScaled, 0), trimDeviationScaled = problem.idealTrimIndexScaled === null ? null : Math.abs(totalIndex - problem.idealTrimIndexScaled);
  return { ...solution, status: "FEASIBLE", assignments, sequencePenalty, usedSimplicityGroups, trimDeviationScaled, messages: ["The adjusted plan passed the independent position, overlap, segregation, Bulk capacity and special-load quantity checks."] };
};

export function LoadPlanningWorkspace({ iata, flightId, released, acceptedWeight }: { iata: string; flightId: string; released: boolean; acceptedWeight: number }) {
  const [pending, start] = useTransition(), [result, setResult] = useState(empty), [assignments, setAssignments] = useState<LoadPlanningAssignment[]>([]), [selectedLoadId, setSelectedLoadId] = useState<string | null>(null), [adjusted, setAdjusted] = useState(false), [moveNotice, setMoveNotice] = useState<{ ok: boolean; text: string } | null>(null), [payload, setPayload] = useState({ released, acceptedWeight }), [activeDeck, setActiveDeck] = useState<DeckKey>("MAIN");
  useEffect(() => { const update = (event: Event) => { const detail = (event as CustomEvent<{ flightId: string; released: boolean; acceptedWeight: number }>).detail; if (detail?.flightId === flightId) { setPayload({ released: detail.released, acceptedWeight: detail.acceptedWeight }); setResult(empty); setAssignments([]); setAdjusted(false); } }; window.addEventListener("wab:freight-acceptance", update); return () => window.removeEventListener("wab:freight-acceptance", update); }, [flightId]);
  const positions = useMemo(() => new Map(result.problem?.positions.map((position) => [position.id, position]) ?? []), [result.problem]), loads = useMemo(() => new Map(result.problem?.loads.map((load) => [load.id, load]) ?? []), [result.problem]);
  const currentSolution = useMemo(() => result.problem && result.solution && adjusted ? metrics(result.problem, result.solution, assignments) : result.solution, [adjusted, assignments, result.problem, result.solution]);
  const rows = useMemo(() => assignments.map((assignment) => ({ assignment, load: loads.get(assignment.loadId), position: positions.get(assignment.positionId) })).filter((row) => row.load && row.position).sort((a, b) => (a.load!.unloadOrder - b.load!.unloadOrder) || a.position!.description.localeCompare(b.position!.description)), [assignments, loads, positions]);
  const slots = useMemo(() => { const grouped = new Map<string, GraphicSlot>(); for (const position of result.problem?.positions ?? []) { const key = slotKey(position), current = grouped.get(key); if (current) current.positions.push(position); else grouped.set(key, { key, holdId: position.holdId, locationRef: position.locationRef ?? position.description, positions: [position] }); } return [...grouped.values()].sort((a, b) => (b.positions[0].balanceArm ?? -Infinity) - (a.positions[0].balanceArm ?? -Infinity) || a.locationRef.localeCompare(b.locationRef)); }, [result.problem]);
  const deckGroups = useMemo(() => { const decks = new Map<DeckKey, Map<string, GraphicSlot[]>>(); for (const slot of slots) { const deck = deckFor(slot.positions[0]); if (!decks.has(deck)) decks.set(deck, new Map()); const holds = decks.get(deck)!; holds.set(slot.holdId, [...(holds.get(slot.holdId) ?? []), slot]); } return decks; }, [slots]);
  const availableDecks = (["MAIN", "LOWER"] as DeckKey[]).filter((deck) => deckGroups.has(deck)), visibleDeck = availableDecks.includes(activeDeck) ? activeDeck : availableDecks[0] ?? "MAIN", visibleHoldGroups = [...(deckGroups.get(visibleDeck)?.entries() ?? [])];
  const run = () => start(async () => { const next = await proposeOperationalAutoload(iata, flightId); setResult(next); setAssignments(next.solution?.assignments ?? []); setSelectedLoadId(null); setAdjusted(false); setMoveNotice(null); setActiveDeck(next.problem?.positions.some((position) => deckFor(position) === "MAIN") ? "MAIN" : "LOWER"); });
  const validate = (candidate: LoadPlanningAssignment[]) => { if (!result.problem || !result.solution) return null; const solution = metrics(result.problem, result.solution, candidate); validateLoadPlanningSolution(result.problem, solution); return solution; };
  const move = (loadId: string, target: GraphicSlot) => {
    if (!result.problem || !result.solution) return;
    const load = loads.get(loadId), sourceAssignment = assignments.find((row) => row.loadId === loadId), sourcePosition = sourceAssignment ? positions.get(sourceAssignment.positionId) : null;
    if (!load || !sourceAssignment || !sourcePosition) return;
    const label = load.description.split(" · ")[0]; let lastError = "This load cannot use the selected position.";
    for (const targetPosition of target.positions.filter((position) => fits(load, position))) {
      if (targetPosition.id === sourcePosition.id) { setSelectedLoadId(null); return; }
      const conflicts = targetPosition.loadType === "ULD" ? assignments.filter((row) => row.loadId !== loadId && overlap(positions.get(row.positionId)!, targetPosition)) : [], attempts: LoadPlanningAssignment[][] = [];
      if (!conflicts.length) attempts.push(assignments.map((row) => row.loadId === loadId ? { ...row, positionId: targetPosition.id } : row));
      else if (conflicts.length === 1) { const displaced = loads.get(conflicts[0].loadId)!; for (const replacement of targetForSourceSlot(result.problem.positions, sourcePosition).filter((position) => fits(displaced, position))) attempts.push(assignments.map((row) => row.loadId === loadId ? { ...row, positionId: targetPosition.id } : row.loadId === displaced.id ? { ...row, positionId: replacement.id } : row)); }
      for (const candidate of attempts) try { validate(candidate); setAssignments(candidate); setAdjusted(true); setSelectedLoadId(null); const displacedLabel = conflicts.length ? loads.get(conflicts[0].loadId)?.description.split(" · ")[0] : null; setMoveNotice({ ok: true, text: displacedLabel ? `${label} moved to ${target.locationRef}; ${displacedLabel} was exchanged into its previous position.` : `${label} moved to ${target.locationRef}.` }); return; } catch (error) { lastError = error instanceof LoadPlanningProblemInvalid ? error.message : "This move is not valid."; }
    }
    setMoveNotice({ ok: false, text: lastError });
  };
  const drop = (event: DragEvent<HTMLDivElement>, slot: GraphicSlot) => { event.preventDefault(); const loadId = event.dataTransfer.getData("text/plain"); if (loadId) move(loadId, slot); }, status = adjusted ? "MANUALLY ADJUSTED" : currentSolution?.status ?? (payload.released ? "READY" : "AWAITING PAYLOAD");
  return <details className="load-planning-workspace operational-collapsible" open>
    <summary className="operational-collapsible-summary load-planning-heading"><div><p className="eyebrow">LOAD PLANNING</p><h2>AUTOLOAD proposal</h2><p>Place released ULD and Bulk loads using unloading sequence, loading simplicity and Ideal Trim priorities.</p></div><div className="operational-summary-facts"><span><small>RELEASED LOAD</small><strong>{Math.round(payload.acceptedWeight).toLocaleString()} KG</strong></span><span><small>ASSIGNMENTS</small><strong>{rows.length || "—"}</strong></span><span className={`summary-emphasis ${result.ok ? "ready" : "incomplete"}`}><small>SOLVER STATUS</small><strong>{status}</strong></span></div></summary>
    <div className="operational-collapsible-body"><div className="load-planning-intro"><div><strong>Proposed loading only</strong><span>The independent validator checks position compatibility, limits, locks, overlapping ULD footprints and special-load segregation before the proposal is displayed.</span></div><button type="button" onClick={run} disabled={!payload.released || pending}>{pending ? "CALCULATING…" : "AUTOLOAD"}</button></div>
      {!payload.released && <p className="load-control-notice error">Save and release the ULD/Bulk Load Weight Statement before running AUTOLOAD.</p>}{result.message && <p className={`load-control-notice ${result.ok ? "success" : "error"}`}>{result.message}</p>}{result.warnings.map((warning) => <p className="load-control-notice warning" key={warning}>{warning}</p>)}
      {currentSolution && <div className="autoload-metrics"><span><small>ENGINE</small><strong>{currentSolution.engine}</strong></span><span><small>SOLVE TIME</small><strong>{currentSolution.solveMilliseconds.toLocaleString()} ms</strong></span><span><small>UNLOAD PENALTY</small><strong>{currentSolution.sequencePenalty ?? "—"}</strong></span><span><small>IDEAL TRIM DEVIATION</small><strong>{currentSolution.trimDeviationScaled === null ? "Not scored" : (currentSolution.trimDeviationScaled / 100_000).toFixed(2)}</strong></span></div>}
      {rows.length > 0 && <section className="load-plan-graphic" aria-labelledby="load-plan-graphic-heading"><header><div><p className="eyebrow">INTERACTIVE LOAD PLAN</p><h3 id="load-plan-graphic-heading">Aircraft loading positions</h3><p>Drag a load to another position, or select it and use PLACE HERE. Every change is validated before it is shown.</p></div>{adjusted && <button type="button" className="secondary" onClick={() => { setAssignments(result.solution?.assignments ?? []); setAdjusted(false); setSelectedLoadId(null); setMoveNotice({ ok: true, text: "AUTOLOAD proposal restored." }); }}>RESET TO AUTOLOAD</button>}</header>{moveNotice && <p className={`load-plan-move-notice ${moveNotice.ok ? "success" : "error"}`} role="status">{moveNotice.text}</p>}
        <div className="load-plan-deck-tabs" role="tablist" aria-label="Aircraft deck">{availableDecks.map((deck) => <button type="button" role="tab" aria-selected={visibleDeck === deck} className={visibleDeck === deck ? "active" : ""} key={deck} onClick={() => setActiveDeck(deck)}>{deck === "MAIN" ? "MAIN DECK" : "LOWER DECK"}</button>)}</div>
        <div className="load-plan-aircraft" role="tabpanel"><div className="load-plan-orientation"><span>TAIL</span><span>NOSE</span></div>{visibleHoldGroups.map(([holdId, holdSlots]) => <section className="load-plan-hold" key={holdId}><h4>{holdName(holdId)}</h4><div className="load-plan-position-strip">{holdSlots.map((slot) => { const slotIds = new Set(slot.positions.map((position) => position.id)), slotRows = rows.filter((row) => slotIds.has(row.assignment.positionId)), selected = selectedLoadId ? loads.get(selectedLoadId) : null, canPlace = Boolean(selected && slot.positions.some((position) => fits(selected, position))), remaining = bulkRemaining(slot, slotRows.map((row) => row.load!)); return <div className={`load-plan-position ${selectedLoadId && canPlace ? "can-drop" : ""}`} key={slot.key} onDragOver={(event) => { if (canPlace) event.preventDefault(); }} onDrop={(event) => drop(event, slot)}><div className="load-plan-position-label"><strong>{slot.locationRef}</strong><small>{remaining ?? positionType(slot.positions)}</small></div><div className="load-plan-position-loads">{slotRows.length ? slotRows.map((row) => <LoadCard key={row.load!.id} load={row.load!} selected={selectedLoadId === row.load!.id} select={() => setSelectedLoadId((current) => current === row.load!.id ? null : row.load!.id)} />) : <span className="load-plan-empty">EMPTY</span>}</div>{selectedLoadId && canPlace && <button type="button" className="load-plan-place" onClick={() => move(selectedLoadId, slot)}>PLACE HERE</button>}</div>; })}</div></section>)}</div>
      </section>}
      {rows.length > 0 && <details className="autoload-detail-table"><summary>Assignment details</summary><div className="autoload-table"><div className="autoload-row head"><span>Load</span><span>Unload</span><span>Gross</span><span>Proposed position</span><span>Priority</span></div>{rows.map(({ assignment, load, position }) => <div className="autoload-row" key={assignment.loadId}><span data-label="Load"><strong>{load!.description.split(" · ")[0]}</strong><small>{load!.loadType}{load!.uldCode ? ` · ${load!.uldCode}` : ""}</small></span><span data-label="Unload"><strong>{unloadStation(load!)}</strong></span><span data-label="Gross"><strong>{load!.weightKg.toLocaleString()} KG</strong></span><span data-label="Proposed position"><strong>{position!.description}</strong></span><span data-label="Priority"><strong>{load!.unloadOrder + 1}</strong></span></div>)}</div></details>}{currentSolution?.messages.map((item) => <p className="autoload-note" key={item}>{item}</p>)}
      <p className="autoload-scope"><strong>Current proposal scope:</strong> payload placement, position weight and volume limits, ULD fit, physical overlap, offload order, simplicity, Ideal Trim, master special-load incompatibilities, IATA DGR segregation and H1 location and quantity limits. Conditional rules remain blocked when their required details have not been recorded. Ground-stability sequence validation must also be added before a proposal can be committed as a loading instruction.</p>
    </div>
  </details>;
}

function targetForSourceSlot(positions: SolverPosition[], source: SolverPosition) { const key = slotKey(source); return positions.filter((position) => slotKey(position) === key); }
function holdName(value: string) { const upper = value.toUpperCase(); if (upper.includes("MDECK") || upper.includes("MAIN")) return "MAIN DECK"; const suffix = upper.includes(":") ? upper.slice(upper.lastIndexOf(":") + 1) : upper; if (suffix === "FWD" || suffix === "AFT") return `${suffix} HOLD`; if (/^\d+$/.test(suffix)) return `BULK HOLD ${suffix}`; return value; }
function positionType(positions: SolverPosition[]) { const first = positions[0]; return first.loadType === "BULK" ? `BULK · MAX ${first.maximumWeightKg.toLocaleString()} KG` : `ULD · ${[...new Set(positions.flatMap((position) => position.acceptedUldCodes))].join(" / ")}`; }
function unloadStation(load: SolverLoad) { return load.description.split("unload ")[1] ?? "—"; }
function bulkRemaining(slot: GraphicSlot, slotLoads: SolverLoad[]) { if (slot.positions[0].loadType !== "BULK") return null; const maximumWeight = slot.positions.reduce((sum, position) => sum + position.maximumWeightKg, 0), remainingWeight = Math.max(0, maximumWeight - slotLoads.reduce((sum, load) => sum + load.weightKg, 0)), volumes = slot.positions.map((position) => position.maximumVolumeLitres), maximumVolume = volumes.every((volume) => volume !== null) ? volumes.reduce<number>((sum, volume) => sum + volume!, 0) : null, usedVolume = slotLoads.reduce((sum, load) => sum + (load.volumeLitres ?? 0), 0); return `REMAINING ${remainingWeight.toLocaleString()} KG · ${maximumVolume === null ? "VOL N/A" : `${((Math.max(0, maximumVolume - usedVolume)) / 1000).toFixed(2)} m³`}`; }
function LoadCard({ load, selected, select }: { load: SolverLoad; selected: boolean; select: () => void }) { const codes = load.specialLoadCodes, dangerous = load.dangerousGoodsClasses.length > 0, controlled = dangerous || codes.length > 0; return <button type="button" draggable={!load.lockedPositionId} aria-pressed={selected} className={`load-plan-card ${controlled ? "controlled" : ""} ${dangerous ? "dangerous" : ""} ${selected ? "selected" : ""}`} onClick={select} onDragStart={(event) => { event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/plain", load.id); }}><strong>{unloadStation(load)}</strong><span>{load.description.split(" · ")[0]}</span><span>{load.weightKg.toLocaleString()} KG</span>{codes.length > 0 && <small>{codes.join(" · ")}</small>}{load.lockedPositionId && <small>LOCKED</small>}</button>; }
