"use client";
import{useState,useTransition}from"react";
import{useRouter}from"next/navigation";
import{createManualSchedule,saveManualScheduleItinerary}from"@/app/flight-schedule-actions";
import{AircraftConfigurationFields,AirportField,ServiceTypeField}from"@/components/schedule-reference-fields";
import type{FlightScheduleImport,FlightScheduleWorkspace,ManualScheduleLegInput}from"@/ports/flight-schedule-repository";

type ItinerarySegment=Pick<ManualScheduleLegInput,"departureAirport"|"departureTime"|"arrivalAirport"|"arrivalTime"|"arrivalDayOffset">;
const segment=(departureAirport=""):ItinerarySegment=>({departureAirport,departureTime:"",arrivalAirport:"",arrivalTime:"",arrivalDayOffset:0});
const blank=(iata:string):ManualScheduleLegInput=>({airlineDesignator:iata,flightNumber:"",operationalSuffix:"",itineraryVariation:"01",legSequence:1,serviceType:"",periodStart:"",periodEnd:"",operatingDays:"1111111",...segment(),aircraftType:"",aircraftSubtype:"",aircraftConfiguration:null});
const names=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
export function ManualScheduleEntry({iata,imports,workspace}:{iata:string;imports:FlightScheduleImport[];workspace:FlightScheduleWorkspace}){
  const editable=imports.filter(item=>item.sourceFormat==="MANUAL"&&["DRAFT","VALIDATED"].includes(item.status));
  const[name,setName]=useState(""),[season,setSeason]=useState(""),[importId,setImportId]=useState(editable[0]?.importId??""),[draft,setDraft]=useState(blank(iata)),[segments,setSegments]=useState<ItinerarySegment[]>([segment()]),[feedback,setFeedback]=useState({ok:false,message:""}),[pending,start]=useTransition(),router=useRouter();
  const change=<K extends keyof ManualScheduleLegInput>(key:K,value:ManualScheduleLegInput[K])=>setDraft(current=>({...current,[key]:value}));
  const updateSegment=<K extends keyof ItinerarySegment>(index:number,key:K,value:ItinerarySegment[K])=>setSegments(current=>current.map((item,position)=>position===index?{...item,[key]:value}:key==="arrivalAirport"&&position===index+1&&(!item.departureAirport||item.departureAirport===current[index].arrivalAirport)?{...item,departureAirport:String(value)}:item));
  const addSegment=()=>setSegments(current=>current.length>=20?current:[...current,segment(current.at(-1)?.arrivalAirport??"")]);
  const removeSegment=(index:number)=>setSegments(current=>{const next=current.filter((_,position)=>position!==index);if(index>0&&index<next.length)next[index]={...next[index],departureAirport:next[index-1].arrivalAirport};return next});
  const referenceReady=workspace.serviceTypes.length>0&&workspace.airports.length>0&&workspace.aircraft.length>0;
  const create=()=>start(async()=>{const result=await createManualSchedule(iata,name,season);setFeedback(result);if(result.ok&&result.importId){setImportId(result.importId);router.refresh()}});
  const save=()=>start(async()=>{const values=segments.map((item,index)=>({...draft,...item,legSequence:index+1}));const result=await saveManualScheduleItinerary(iata,importId,values);setFeedback(result);if(result.ok){setDraft(blank(iata));setSegments([segment()]);router.refresh()}});
  return <details className="configuration-card manual-schedule"><summary>CREATE OR EXTEND A MANUAL SCHEDULE</summary><p className="muted">Use this when the carrier cannot provide an SSIM file. Enter the complete itinerary and save every ordered segment together.</p>
    <div className="manual-edition-create"><label>Schedule name<input value={name} onChange={event=>setName(event.target.value)} placeholder="Winter 2026/27 manual schedule"/></label><label>Season code<input value={season} onChange={event=>setSeason(event.target.value)} placeholder="W26/27"/></label><button type="button" onClick={create} disabled={pending}>CREATE EDITION</button></div>
    <div className="manual-leg-heading"><h3>Add a flight itinerary</h3><label>Manual edition<select value={importId} onChange={event=>setImportId(event.target.value)}><option value="">Select or create an edition</option>{editable.map(item=><option key={item.importId} value={item.importId}>{item.fileName} · {item.status}</option>)}</select></label></div>
    {!referenceReady&&<p className="save-feedback error">Manual flights require Service Type and airport master data, plus at least one configured carrier aircraft. Supply the missing master data before adding a flight.</p>}
    <div className="manual-leg-grid">
      <label>Flight number (up to 4 characters)<input value={draft.flightNumber} maxLength={4} onChange={event=>change("flightNumber",event.target.value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,4))} placeholder="040, 1040 or 401A"/></label><label>Operational suffix<input value={draft.operationalSuffix} maxLength={1} onChange={event=>change("operationalSuffix",event.target.value.toUpperCase().replace(/[^A-Z0-9]/g,""))} placeholder="Optional"/></label><label>Variation<input value={draft.itineraryVariation} onChange={event=>change("itineraryVariation",event.target.value.toUpperCase().replace(/[^A-Z0-9]/g,""))}/></label><ServiceTypeField value={draft.serviceType} workspace={workspace} change={change}/>
      <label>Period start<input type="date" value={draft.periodStart} onChange={event=>change("periodStart",event.target.value)}/></label><label>Period end<input type="date" value={draft.periodEnd} onChange={event=>change("periodEnd",event.target.value)}/></label><fieldset><legend>Operating days</legend>{names.map((day,index)=><label key={day}><input type="checkbox" checked={draft.operatingDays[index]==="1"} onChange={event=>change("operatingDays",Array.from(draft.operatingDays).map((value,position)=>position===index?(event.target.checked?"1":"0"):value).join(""))}/>{day}</label>)}</fieldset>
    </div>
    <div className="manual-itinerary-segments">{segments.map((item,index)=><section className="manual-itinerary-segment" key={index}><div className="manual-itinerary-segment-heading"><h4>SEGMENT {index+1}</h4>{segments.length>1&&<button type="button" className="secondary" onClick={()=>removeSegment(index)}>REMOVE SEGMENT</button>}</div><div className="manual-segment-grid"><AirportField label="Departure airport" value={item.departureAirport} workspace={workspace} onChange={value=>updateSegment(index,"departureAirport",value)}/><label>Departure time<input type="time" value={item.departureTime} onChange={event=>updateSegment(index,"departureTime",event.target.value)}/></label><AirportField label="Arrival airport" value={item.arrivalAirport} workspace={workspace} onChange={value=>updateSegment(index,"arrivalAirport",value)}/><label>Arrival time<input type="time" value={item.arrivalTime} onChange={event=>updateSegment(index,"arrivalTime",event.target.value)}/></label><label>Arrival day<select value={item.arrivalDayOffset} onChange={event=>updateSegment(index,"arrivalDayOffset",Number(event.target.value))}><option value={0}>Same day</option><option value={1}>Next day</option><option value={2}>Two days later</option></select></label></div></section>)}</div>
    <button type="button" className="secondary manual-add-segment" onClick={addSegment} disabled={pending||segments.length>=20}>ADD SEGMENT</button>
    <div className="manual-leg-grid manual-itinerary-aircraft"><AircraftConfigurationFields draft={draft} workspace={workspace} change={change}/></div>
    {feedback.message&&<p className={feedback.ok?"save-feedback success":"save-feedback error"}>{feedback.message}</p>}<div className="c7-actions"><button type="button" onClick={save} disabled={pending||!importId||!referenceReady}>{pending?"SAVING…":"SAVE ITINERARY"}</button></div>
  </details>;
}
