"use client";
import Link from"next/link";
import{useState,useTransition}from"react";
import{useRouter}from"next/navigation";
import{deleteManualScheduleLeg,deleteScheduleEdition,saveManualScheduleLeg}from"@/app/flight-schedule-actions";
import{AircraftConfigurationFields,AirportField,ServiceTypeField}from"@/components/schedule-reference-fields";
import type{FlightScheduleEdition,FlightScheduleWorkspace,ManualScheduleLegInput,ScheduleEditionLeg}from"@/ports/flight-schedule-repository";

const weekday=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
const blank=(iata:string):ManualScheduleLegInput=>({airlineDesignator:iata,flightNumber:"",operationalSuffix:"",itineraryVariation:"01",legSequence:1,serviceType:"",periodStart:"",periodEnd:"",operatingDays:"1111111",departureAirport:"",arrivalAirport:"",departureTime:"",arrivalTime:"",arrivalDayOffset:0,aircraftType:"",aircraftSubtype:"",aircraftConfiguration:null});
const fromLeg=(iata:string,leg:ScheduleEditionLeg,workspace:FlightScheduleWorkspace):ManualScheduleLegInput=>{const matches=workspace.aircraft.filter(item=>item.typeCode===leg.aircraftType&&(!leg.aircraftConfiguration||workspace.aircraftConfigurations.some(configuration=>configuration.typeCode===item.typeCode&&configuration.subtype===item.subtype&&configuration.code===leg.aircraftConfiguration))),subtype=leg.aircraftSubtype??(matches.length===1?matches[0].subtype:"");return{airlineDesignator:iata,flightNumber:leg.flightNumber,operationalSuffix:leg.operationalSuffix,itineraryVariation:leg.itineraryVariation,legSequence:leg.legSequence,serviceType:leg.serviceType,periodStart:leg.periodStart,periodEnd:leg.periodEnd,operatingDays:leg.operatingDays,departureAirport:leg.departureAirport,arrivalAirport:leg.arrivalAirport,departureTime:leg.departureTime,arrivalTime:leg.arrivalTime,arrivalDayOffset:leg.arrivalDayOffset,aircraftType:leg.aircraftType??"",aircraftSubtype:subtype,aircraftConfiguration:leg.aircraftConfiguration}};
const date=(value:string|null)=>value?new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${value}T00:00:00Z`)):"—";
const days=(value:string)=>weekday.filter((_,index)=>value[index]==="1").join(" ");

function ManualLegEditor({iata,editionId,leg,workspace,onClose}:{iata:string;editionId:string;leg:ScheduleEditionLeg|null;workspace:FlightScheduleWorkspace;onClose:()=>void}){
 const[draft,setDraft]=useState(()=>leg?fromLeg(iata,leg,workspace):blank(iata)),[feedback,setFeedback]=useState({ok:false,message:""}),[pending,start]=useTransition(),router=useRouter();
 const change=<K extends keyof ManualScheduleLegInput>(key:K,value:ManualScheduleLegInput[K])=>setDraft(current=>({...current,[key]:value}));
 const save=()=>start(async()=>{const result=await saveManualScheduleLeg(iata,editionId,draft,leg?.scheduleLegId??null);setFeedback(result);if(result.ok){onClose();router.refresh()}});
 return <div className="schedule-leg-maintenance"><h3>{leg?`Amend ${iata}${leg.flightNumber}`:"Add flight leg"}</h3><div className="manual-leg-grid">
  <label>Flight number<input value={draft.flightNumber} maxLength={4} onChange={event=>change("flightNumber",event.target.value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,4))} placeholder="040, 1040 or 401A"/></label>
  <label>Operational suffix<input value={draft.operationalSuffix} maxLength={1} onChange={event=>change("operationalSuffix",event.target.value.toUpperCase().replace(/[^A-Z0-9]/g,""))} placeholder="Optional"/></label>
  <label>Variation<input value={draft.itineraryVariation} maxLength={8} onChange={event=>change("itineraryVariation",event.target.value.toUpperCase().replace(/[^A-Z0-9]/g,""))}/></label>
  <label>Leg sequence<input type="number" min="1" max="99" value={draft.legSequence} onChange={event=>change("legSequence",Number(event.target.value))}/></label>
  <ServiceTypeField value={draft.serviceType} workspace={workspace} change={change}/>
  <label>Period start<input type="date" value={draft.periodStart} onChange={event=>change("periodStart",event.target.value)}/></label><label>Period end<input type="date" value={draft.periodEnd} onChange={event=>change("periodEnd",event.target.value)}/></label>
  <fieldset><legend>Operating days</legend>{weekday.map((day,index)=><label key={day}><input type="checkbox" checked={draft.operatingDays[index]==="1"} onChange={event=>change("operatingDays",Array.from(draft.operatingDays).map((value,position)=>position===index?(event.target.checked?"1":"0"):value).join(""))}/>{day}</label>)}</fieldset>
  <AirportField label="Departure airport" value={draft.departureAirport} workspace={workspace} onChange={value=>change("departureAirport",value)}/><label>Departure time<input type="time" value={draft.departureTime} onChange={event=>change("departureTime",event.target.value)}/></label>
  <AirportField label="Arrival airport" value={draft.arrivalAirport} workspace={workspace} onChange={value=>change("arrivalAirport",value)}/><label>Arrival time<input type="time" value={draft.arrivalTime} onChange={event=>change("arrivalTime",event.target.value)}/></label>
  <label>Arrival day<select value={draft.arrivalDayOffset} onChange={event=>change("arrivalDayOffset",Number(event.target.value))}><option value={0}>Same day</option><option value={1}>Next day</option><option value={2}>Two days later</option></select></label>
  <AircraftConfigurationFields draft={draft} workspace={workspace} change={change}/>
 </div>{feedback.message&&<p className={feedback.ok?"save-feedback success":"save-feedback error"}>{feedback.message}</p>}<div className="c7-actions"><button type="button" onClick={save} disabled={pending}>{pending?"SAVING…":leg?"SAVE CHANGES":"ADD FLIGHT LEG"}</button><button type="button" className="secondary" onClick={onClose}>CANCEL</button></div></div>;
}

export function ScheduleEditionReview({iata,edition,workspace}:{iata:string;edition:FlightScheduleEdition;workspace:FlightScheduleWorkspace}){
 const[editing,setEditing]=useState<string|null>(null),[feedback,setFeedback]=useState({ok:false,message:""}),[pending,start]=useTransition(),router=useRouter(),base=`/carrier/${encodeURIComponent(iata)}/flight-schedules`;
 const selected=editing&&editing!=="NEW"?edition.legs.find(leg=>leg.scheduleLegId===editing)??null:null;
 const removeLeg=(id:string)=>{if(!window.confirm("Delete this flight leg from the manual schedule edition?"))return;start(async()=>{const result=await deleteManualScheduleLeg(iata,edition.importId,id);setFeedback(result);if(result.ok){setEditing(null);router.refresh()}})};
 const removeEdition=()=>{if(!window.confirm(`Delete schedule edition “${edition.name}” and all of its flight legs?`))return;start(async()=>{const result=await deleteScheduleEdition(iata,edition.importId);setFeedback(result);if(result.ok){router.replace(base);router.refresh()}})};
 return <section className="configuration-card schedule-edition-review">
  <div className="schedule-review-heading"><div><p className="eyebrow">SCHEDULE REVIEW</p><h2>{edition.name}</h2><p className="muted">{edition.sourceFormat==="MANUAL"?"Manual entry":"SSIM Chapter 7"} · {date(edition.coverageStart)} – {date(edition.coverageEnd)} · {edition.legCount.toLocaleString()} flight legs</p></div><div className="schedule-review-actions"><span className={`schedule-status ${edition.status.toLowerCase()}`}>{edition.status}</span><Link className="button-link secondary" href={base}>CLOSE REVIEW</Link>{edition.canEdit&&<button type="button" onClick={()=>setEditing("NEW")}>ADD FLIGHT</button>}{edition.canDelete&&<button type="button" className="danger" disabled={pending} onClick={removeEdition}>DELETE EDITION</button>}</div></div>
  {edition.sourceFormat!=="MANUAL"&&<p className="schedule-review-note">SSIM flight legs are retained exactly as supplied. Review them here; upload a corrected SSIM edition when source data needs amendment.</p>}
  {edition.sourceFormat==="MANUAL"&&!edition.canEdit&&<p className="schedule-review-note">This edition is published and retained as an immutable operational record. Create a replacement manual edition to make changes.</p>}
  {feedback.message&&<p className={feedback.ok?"save-feedback success":"save-feedback error"}>{feedback.message}</p>}
  {editing&&<ManualLegEditor key={editing} iata={iata} editionId={edition.importId} leg={selected} workspace={workspace} onClose={()=>setEditing(null)}/>}
  <div className="schedule-review-table-wrap"><table className="schedule-review-table"><thead><tr><th>Flight</th><th>Route</th><th>Times</th><th>Operating days</th><th>Period</th><th>Aircraft</th>{edition.canEdit&&<th>Actions</th>}</tr></thead><tbody>{edition.legs.map(leg=><tr key={leg.scheduleLegId}><th>{iata}{leg.flightNumber}{leg.operationalSuffix}</th><td>{leg.departureAirport} → {leg.arrivalAirport}</td><td>{leg.departureTime} – {leg.arrivalTime}{leg.arrivalDayOffset?` +${leg.arrivalDayOffset}`:""}</td><td>{days(leg.operatingDays)}</td><td>{date(leg.periodStart)} – {date(leg.periodEnd)}</td><td>{leg.aircraftType??"—"}{leg.aircraftSubtype?`-${leg.aircraftSubtype}`:""}{leg.aircraftConfiguration?` / ${leg.aircraftConfiguration}`:""}</td>{edition.canEdit&&<td><div className="schedule-row-actions"><button type="button" className="secondary" onClick={()=>setEditing(leg.scheduleLegId)}>AMEND</button><button type="button" className="danger secondary" disabled={pending} onClick={()=>removeLeg(leg.scheduleLegId)}>DELETE</button></div></td>}</tr>)}{edition.legs.length===0&&<tr><td colSpan={edition.canEdit?7:6}>No flight legs have been added to this edition.</td></tr>}</tbody></table></div>
 </section>;
}
