"use client";
import{useMemo,useState,useTransition}from"react";
import{useRouter}from"next/navigation";
import{deleteScheduleSegmentDefault,saveScheduleSegmentDefault}from"@/app/flight-schedule-actions";
import{scheduleAircraftCarriesPassengers,scheduleAircraftSubtype}from"@/domain/flight-schedules";
import type{FlightScheduleParameters,FlightScheduleSegmentDefault,FlightScheduleWorkspace}from"@/ports/flight-schedule-repository";

type Segment={departureAirport:string;arrivalAirport:string;aircraftType:string;flightCount:number;saved:FlightScheduleSegmentDefault|null};
const key=(departure:string,arrival:string,type:string)=>`${departure}|${arrival}|${type}`;
const basis=(method:string,variation:string|null)=>`${method[0]}${method.slice(1).toLowerCase()}${variation?` · ${variation}`:""}`;

function SegmentEditor({iata,segment,workspace,onClose}:{iata:string;segment:Segment;workspace:FlightScheduleWorkspace;onClose:()=>void}){
 const matchingLegs=workspace.legs.filter(leg=>leg.departureAirport===segment.departureAirport&&leg.arrivalAirport===segment.arrivalAirport&&leg.aircraftType===segment.aircraftType),subtypes=workspace.aircraft.filter(item=>item.typeCode===segment.aircraftType),initialSubtype=segment.saved?.aircraftSubtype??scheduleAircraftSubtype(matchingLegs[0]??{aircraftSubtype:null,parameters:null},subtypes[0]?.subtype??"");
 const[draft,setDraft]=useState<FlightScheduleParameters>(segment.saved??{aircraftSubtype:initialSubtype,crewCode:"",pantryCode:"",passengerWeightBasis:"STANDARD",passengerVariation:null,baggageWeightBasis:"STANDARD",baggageVariation:null,remarks:""}),[state,setState]=useState({ok:false,message:""}),[pending,start]=useTransition(),router=useRouter();
 const crew=workspace.crewCodes.filter(item=>item.typeCode===segment.aircraftType&&item.subtype===draft.aircraftSubtype),pantry=workspace.pantryCodes.filter(item=>item.typeCode===segment.aircraftType&&item.subtype===draft.aircraftSubtype),carriesPassengers=scheduleAircraftCarriesPassengers(workspace.aircraft,segment.aircraftType,draft.aircraftSubtype);
 const update=<K extends keyof FlightScheduleParameters>(field:K,value:FlightScheduleParameters[K])=>setDraft(current=>({...current,[field]:value,...(field==="aircraftSubtype"?{crewCode:"",pantryCode:""}:{})}));
 const save=()=>start(async()=>{const result=await saveScheduleSegmentDefault(iata,segment.departureAirport,segment.arrivalAirport,segment.aircraftType,draft);setState(result);if(result.ok){router.refresh();onClose()}});
 return <div className="segment-default-editor"><div className="schedule-parameter-grid">
  <label>Aircraft subtype<select value={draft.aircraftSubtype} onChange={event=>update("aircraftSubtype",event.target.value)}><option value="">Select subtype</option>{subtypes.map(item=><option key={item.subtype} value={item.subtype}>{item.typeCode}-{item.subtype} · {item.name}</option>)}</select></label>
  <label>Crew code<select value={draft.crewCode} onChange={event=>update("crewCode",event.target.value)}><option value="">Select crew code</option>{crew.map(item=><option key={item.code}>{item.code}</option>)}</select></label>
  <label>Pantry code<select value={draft.pantryCode} onChange={event=>update("pantryCode",event.target.value)}><option value="">Select pantry code</option>{pantry.map(item=><option key={item.code}>{item.code}</option>)}</select></label>
  {carriesPassengers&&<label>Passenger weights<select value={draft.passengerWeightBasis} onChange={event=>update("passengerWeightBasis",event.target.value as FlightScheduleParameters["passengerWeightBasis"])}><option value="STANDARD">Standard</option><option value="VARIATION">Flight variation</option><option value="ACTUAL">Actual weights</option></select></label>}
  {carriesPassengers&&draft.passengerWeightBasis==="VARIATION"&&<label>Passenger variation<select value={draft.passengerVariation??""} onChange={event=>update("passengerVariation",event.target.value||null)}><option value="">Select variation</option>{workspace.variations.map(item=><option key={item.code} value={item.code}>{item.code} · {item.description}</option>)}</select></label>}
  {carriesPassengers&&<label>Baggage weights<select value={draft.baggageWeightBasis} onChange={event=>update("baggageWeightBasis",event.target.value as FlightScheduleParameters["baggageWeightBasis"])}><option value="STANDARD">Standard</option><option value="VARIATION">Flight variation</option><option value="ACTUAL">Actual weights</option></select></label>}
  {carriesPassengers&&draft.baggageWeightBasis==="VARIATION"&&<label>Baggage variation<select value={draft.baggageVariation??""} onChange={event=>update("baggageVariation",event.target.value||null)}><option value="">Select variation</option>{workspace.variations.map(item=><option key={item.code} value={item.code}>{item.code} · {item.description}</option>)}</select></label>}
  {!carriesPassengers&&<p className="schedule-freighter-note">Passenger and baggage parameters are not required for this freighter.</p>}
  <label className="schedule-remarks">Remarks<textarea value={draft.remarks} onChange={event=>update("remarks",event.target.value)} maxLength={1000}/></label>
 </div>{state.message&&<p className={state.ok?"save-feedback success":"save-feedback error"}>{state.message}</p>}<div className="c7-actions"><button type="button" onClick={save} disabled={pending}>{pending?"SAVING…":"SAVE SEGMENT DEFAULTS"}</button><button type="button" className="secondary" onClick={onClose}>CANCEL</button></div></div>;
}

export function ScheduleSegmentDefaults({iata,workspace}:{iata:string;workspace:FlightScheduleWorkspace}){
 const[open,setOpen]=useState<string|null>(null),[state,setState]=useState({ok:false,message:""}),[pending,start]=useTransition(),router=useRouter();
 const segments=useMemo(()=>{const rows=new Map<string,Segment>();for(const saved of workspace.segmentDefaults)rows.set(key(saved.departureAirport,saved.arrivalAirport,saved.aircraftType),{...saved,flightCount:0,saved});for(const leg of workspace.legs){if(!leg.aircraftType)continue;const id=key(leg.departureAirport,leg.arrivalAirport,leg.aircraftType),current=rows.get(id);rows.set(id,current?{...current,flightCount:current.flightCount+1}:{departureAirport:leg.departureAirport,arrivalAirport:leg.arrivalAirport,aircraftType:leg.aircraftType,flightCount:1,saved:null})}return[...rows.values()].sort((a,b)=>key(a.departureAirport,a.arrivalAirport,a.aircraftType).localeCompare(key(b.departureAirport,b.arrivalAirport,b.aircraftType)))},[workspace]);
 const remove=(segment:Segment)=>{if(!window.confirm(`Remove the saved defaults for ${segment.departureAirport}–${segment.arrivalAirport}? Matching flights without their own override will require review again.`))return;start(async()=>{const result=await deleteScheduleSegmentDefault(iata,segment.departureAirport,segment.arrivalAirport,segment.aircraftType);setState(result);if(result.ok){setOpen(null);router.refresh()}})};
 return <section className="configuration-card segment-defaults"><div className="schedule-section-heading"><div><h2>SEGMENT DEFAULT PARAMETERS</h2><p className="muted">Set each directional route once. Defaults apply to matching legs in the current schedule and are reused when later schedules are published. Configure an individual flight only when it is an exception.</p></div><span className="segment-default-progress">{segments.filter(item=>item.saved).length} / {segments.length} configured</span></div>
  {state.message&&<p className={state.ok?"save-feedback success":"save-feedback error"}>{state.message}</p>}
  {segments.length?<div className="segment-default-table"><div className="segment-default-row head"><span>Segment</span><span>Scheduled legs</span><span>Aircraft</span><span>Crew</span><span>Pantry</span><span>Passenger weights</span><span>Baggage weights</span><span>Status</span><span>Actions</span></div>{segments.map(segment=>{const id=key(segment.departureAirport,segment.arrivalAirport,segment.aircraftType),saved=segment.saved,carriesPassengers=scheduleAircraftCarriesPassengers(workspace.aircraft,segment.aircraftType,saved?.aircraftSubtype??"");return <div className="segment-default-item" key={id}><div className="segment-default-row"><strong>{segment.departureAirport} → {segment.arrivalAirport}</strong><span>{segment.flightCount}</span><span>{saved?`${segment.aircraftType}-${saved.aircraftSubtype}`:segment.aircraftType}</span><span>{saved?.crewCode??"—"}</span><span>{saved?.pantryCode??"—"}</span><span>{saved?(carriesPassengers?basis(saved.passengerWeightBasis,saved.passengerVariation):"N/A"):"—"}</span><span>{saved?(carriesPassengers?basis(saved.baggageWeightBasis,saved.baggageVariation):"N/A"):"—"}</span><span className={saved?"schedule-readiness ready":"schedule-readiness"}>{saved?"DEFAULT SAVED":"SET DEFAULTS"}</span><span className="segment-default-actions"><button type="button" className="secondary" onClick={()=>setOpen(open===id?null:id)}>{open===id?"CLOSE":saved?"REVIEW":"CONFIGURE"}</button>{saved&&<button type="button" className="danger secondary" disabled={pending} onClick={()=>remove(segment)}>REMOVE</button>}</span></div>{open===id&&<SegmentEditor iata={iata} segment={segment} workspace={workspace} onClose={()=>setOpen(null)}/>}</div>})}</div>:<p className="d2-empty">Publish a schedule to create its segment list.</p>}
 </section>;
}
