"use client";
import {useSaveFeedback,SaveScope,SaveInput,SaveButton,SaveSubmit,SaveCancel} from "@/components/save-feedback";
import Link from "next/link";
import {useState,useRef,useEffect} from "react";
import {SectionHeader} from "@/components/section-header";
import {saveUlds,saveUldApplicability,saveUldInventoryApplicability} from "@/app/uld-actions";
import {ConfigurationStatusBadge} from "@/components/configuration-status-badge";
import {b5Completion} from "@/domain/b5-status";
import {displayUnit} from "@/domain/display-standards";
import {customUld,newInventoryRange,normaliseUldSerial,validateUlds,uldEditRow,uldDisplayValue,setMasterUldSelected,type UldRow,type UldSnapshot} from "@/domain/uld-specifications";
function invalidInventoryRows(rows:UldRow[]):Set<string>{const invalid=new Set<string>();for(const row of rows){const seen=new Set<string>();row.inventory.forEach((range,index)=>{const start=range.serialStart.padStart(5,"0"),end=range.serialEnd.padStart(5,"0"),key=`${range.carrierCode}:${start}:${end}`;if(!/^[A-Z0-9]{2}$/.test(range.carrierCode)||!/^[0-9]{1,5}$/.test(range.serialStart)||!/^[0-9]{1,5}$/.test(range.serialEnd)||Number(range.serialStart)>Number(range.serialEnd)||seen.has(key))invalid.add(`${row.code}:${index}`);seen.add(key);});}return invalid;}
export function UldSpecifications({iata,typeCode,subtype,initial}:{iata:string;typeCode:string;subtype:string;initial:UldSnapshot}){
 const [saved,setSaved]=useState(initial),[draft,setDraft]=useState(initial.rows),[editing,setEditing]=useState(false),[editingCode,setEditingCode]=useState<string|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[attentionRows,setAttentionRows]=useState<Set<string>>(new Set());const [pending,startTransition,saveFeedback]=useSaveFeedback();
 const [masterFilter,setMasterFilter]=useState(""),[inventoryEditing,setInventoryEditing]=useState(false);
 const [customOpen,setCustomOpen]=useState(false),[customCode,setCustomCode]=useState(""),[customType,setCustomType]=useState(""),[customError,setCustomError]=useState("");
 const addedInput=useRef<HTMLInputElement>(null);const [addedCode,setAddedCode]=useState("");
 useEffect(()=>{if(addedCode){addedInput.current?.focus({preventScroll:true});addedInput.current?.scrollIntoView({behavior:"smooth",block:"center"});}},[addedCode]);
 const rows=editing?draft:saved.rows;const completion=b5Completion(saved);const weightUnit=displayUnit(saved.weightUnit);const volumeUnit=saved.volumeUnit==="m3"?"m³":saved.volumeUnit==="ft3"?"ft³":"Unit not set";
 function update(code:string,key:"tare"|"maximum"|"volume",value:string){setDraft(current=>current.map(r=>r.code===code?{...r,[key]:value}:r));}
 function updateInventory(code:string,index:number,key:"carrierCode"|"serialStart"|"serialEnd",value:string){const normalised=key==="carrierCode"?value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,2):value.replace(/\D/g,"").slice(0,5);setAttentionRows(current=>{const next=new Set(current);next.delete(`${code}:${index}`);return next;});setDraft(current=>current.map(r=>r.code===code?{...r,inventory:r.inventory.map((range,i)=>i===index?{...range,[key]:normalised}:range)}:r));}
 function beginEdit(code:string|null){setCustomOpen(false);setCustomError("");setCustomCode("");setCustomType("");setDraft(saved.rows.map(uldEditRow));setEditingCode(code);setEditing(true);setMasterFilter("");setAddedCode("");setError("");setMessage("");setAttentionRows(new Set());}
 function saveSpecifications(){setError("");setAttentionRows(new Set());try{validateUlds(draft,saved);}catch(e){setError(e instanceof Error?e.message:"Check the ULD entries.");setAttentionRows(invalidInventoryRows(draft));return;}startTransition(async()=>{try{const r=await saveUlds(iata,typeCode,subtype,saved.revision,draft);if(r.ok){setError("");setSaved(r.snapshot);saveFeedback.complete(()=>{setEditing(false);setEditingCode(null);setAttentionRows(new Set());setMessage("");});}else setError(r.error);}catch{setError("Unable to save. Your entries are still here; please try again.");}});}
 return <SaveScope feedback={saveFeedback}>{<section className="overview carrier-details passenger-weights uld-specifications" aria-labelledby="uld-title"><SectionHeader id="uld-title" title="5. ULD SPECIFICATIONS" reference="(AHM565 Sheet B5)"><ConfigurationStatusBadge status={completion.page} variant="large"/></SectionHeader>
 {!saved.canView?<p>ULD specifications are not available for your account.</p>:<>
 <section className="commodity-section"><div className="details-heading"><label className="b4-section-toggle"><SaveInput type="checkbox" checked={saved.utilisesUlds} disabled={pending||editing||!saved.canEdit} onChange={event=>{const checked=event.target.checked;if(!checked&&saved.rows.length>0&&!window.confirm("Unchecking this option will permanently delete all ULD specifications and saved inventory for this aircraft. Continue?")){event.target.checked=true;return;}setError("");startTransition(async()=>{const result=await saveUldApplicability(iata,typeCode,subtype,saved.revision,checked);if(result.ok){setError("");setSaved(result.snapshot);saveFeedback.complete(()=>{setDraft(result.snapshot.rows);setMessage(checked?"ULD specifications now apply to this aircraft.":"B5 skipped for this aircraft. All ULD specifications and inventory for this aircraft have been deleted.");});}else setError(result.error);});}}/><span><strong>This Aircraft Type Can Accept Unit Load Devices</strong><small>When selected, configure at least one ULD Type for this aircraft.</small></span></label><div className="c5-heading-actions"><ConfigurationStatusBadge status={completion.specifications}/>{!editing&&!inventoryEditing&&saved.utilisesUlds&&saved.canEdit&&saved.weightUnit&&saved.volumeUnit&&<SaveButton className="secondary" onClick={()=>beginEdit(null)}>EDIT</SaveButton>}</div></div>{!saved.utilisesUlds&&<p className="muted">B5 is skipped for this aircraft. No ULD specifications are required for this aircraft.</p>}{saved.utilisesUlds&&!saved.rows.length&&<p className="field-error">At least one ULD Type must be configured.</p>}</section>
 <p>{saved.weightUnit&&saved.volumeUnit?`Weights are in ${weightUnit} and volumes are in ${volumeUnit}, as selected on Sheet B1.`:<>Save Weight and Volume Units on <Link href={`/carrier/${encodeURIComponent(iata)}?sheet=B1`}>B1</Link> before adding ULDs.</>}</p>
 {!saved.canEdit&&<p className="muted">ULD specifications are read-only for your account.</p>}
 <form className={saved.utilisesUlds?"":"section-disabled"} noValidate onSubmit={e=>e.preventDefault()}><fieldset disabled={pending}><legend className="sr-only">Carrier ULD Specifications</legend>
 {editing&&editingCode===null&&<div className="variation-suggestions uld-master-selection"><div className="uld-master-selection-heading"><div><strong>Select ULD IDs from the Master List</strong><p>Check every ULD identity accepted by this aircraft. Master weights and volume are added as editable starting values.</p></div><span className="badge">{draft.filter(row=>!row.isCustom).length} SELECTED</span></div><label htmlFor="uld-master-filter">Find a ULD ID or Type</label><SaveInput id="uld-master-filter" type="search" value={masterFilter} placeholder="For example AKE or LD3" onChange={event=>setMasterFilter(event.target.value.toUpperCase())}/><div className="uld-master-checklist">{saved.master.filter(master=>!masterFilter||master.code.includes(masterFilter)||master.type.includes(masterFilter)).map(master=>{const checked=draft.some(row=>!row.isCustom&&row.code===master.code);return <label className={checked?"selected":""} key={master.code}><SaveInput type="checkbox" checked={checked} disabled={!checked&&draft.length>=200} onChange={event=>{if(!event.target.checked){const existing=saved.rows.find(row=>row.code===master.code);if(existing?.inventory.length&&!window.confirm(`Removing ${master.code} will also remove its saved inventory when you Save. Continue?`))return;}setDraft(current=>setMasterUldSelected(master,saved,current,event.target.checked));setAddedCode("");setMessage(event.target.checked?`${master.code} selected. Review its values below before saving.`:`${master.code} removed from the draft.`);}}/><span><strong>{master.code}</strong><small>{master.type}{master.mainDeckOnly?" · Main Deck Only":""}</small></span></label>})}</div><p>Selections and removals take effect together when you select Save. Choose exactly one Default for each ULD Type in the details below.</p></div>}
 {editing&&editingCode===null&&<div className="variation-suggestions"><SaveButton type="button" className="secondary" disabled={draft.length>=200} onClick={()=>{setCustomOpen(v=>!v);setCustomError("");}}>Add a Carrier ULD</SaveButton><p>Use this option when your ULD is not in the Master List. It will be saved for this carrier only.</p>{customOpen&&<><div className="passenger-weight-grid"><div><label htmlFor="custom-uld-code">ULD Code</label><SaveInput id="custom-uld-code" value={customCode} maxLength={3} onChange={e=>setCustomCode(e.target.value.toUpperCase())}/></div><div><label htmlFor="custom-uld-type">ULD Type</label><SaveInput id="custom-uld-type" value={customType} maxLength={6} onChange={e=>setCustomType(e.target.value.toUpperCase())}/></div></div><p>A ULD Code is limited to Three Letters or Numbers. ULD Type is limited to Six Letters, Numbers or Hyphens. A ULD Type may be a New Type or One already In Use with your carrier.</p>{customError&&<p role="alert" className="field-error">{customError}</p>}<SaveButton type="button" className="secondary" onClick={()=>{try{const row=customUld(customCode,customType,draft);setDraft(current=>[...current,row]);setAddedCode(row.code);setCustomOpen(false);setCustomCode("");setCustomType("");setCustomError("");setMessage(`${row.code} added to your draft. Enter its weights and volume, then select Save.`);}catch(e){setCustomError(e instanceof Error?e.message:"Check the ULD Code and Type.");}}}>Add to ULD List</SaveButton></>}</div>}
 {!rows.length&&<p>No ULD specifications have been saved.</p>}
 {rows.map((row:UldRow)=>{const rowEditing=editing&&(editingCode===null||editingCode===row.code);return <article className={`baggage-card uld-card${rowEditing?" uld-card-editing":""}`} key={row.code}><div className="uld-card-heading"><h3>{row.code} — {row.type}</h3>{rowEditing&&<label className="crew-checkbox"><SaveInput type="radio" name={`default-${row.type}`} checked={row.isDefault} onChange={()=>setDraft(current=>current.map(r=>r.type===row.type?{...r,isDefault:r.code===row.code}:r))}/>Default for {row.type}</label>} {!rowEditing&&row.isDefault&&<span className="badge">Default for {row.type}</span>}{!editing&&saved.utilisesUlds&&saved.canEdit&&<SaveButton className="secondary uld-remove" type="button" onClick={()=>beginEdit(row.code)}>EDIT {row.code}</SaveButton>}{rowEditing&&editingCode===null&&<SaveButton className="secondary uld-remove" type="button" onClick={()=>setDraft(current=>current.filter(r=>r.code!==row.code))}>Remove {row.code}</SaveButton>}</div>
 {(row.isCustom||(!row.isCustom&&saved.master.find(m=>m.code===row.code)?.mainDeckOnly))&&<p className="muted uld-kind">{row.isCustom?"Carrier ULD":"Main Deck Only"}</p>}
 <div className="passenger-weight-grid">{([['tare','Tare Weight',weightUnit],['maximum','Max Weight',weightUnit],['volume','Maximum Volume',volumeUnit]] as const).map(([key,label,unit])=><div key={key}><label htmlFor={rowEditing?`${row.code}-${key}`:undefined}>{label} ({unit})</label>{rowEditing?<SaveInput id={`${row.code}-${key}`} ref={row.code===addedCode&&key==="tare"?addedInput:undefined} type="number" step={key==="volume"?"0.01":"1"} min={key==="tare"?"0":key==="volume"?"0.01":"1"} value={row[key]} onChange={e=>update(row.code,key,e.target.value)}/>:<p className="passenger-value">{uldDisplayValue(row[key],key)}</p>}</div>)}</div>

 </article>})}
 {editing&&<>{error&&<p role="alert" className="field-error">{error}</p>}<div className="logo-actions"><SaveSubmit type="button" onClick={saveSpecifications}>SAVE</SaveSubmit><SaveCancel type="button" className="secondary" onClick={()=>{setEditing(false);setEditingCode(null);setAddedCode("");setMessage("");setError("");}}>CANCEL</SaveCancel></div></>}
 </fieldset></form>
 <section className="commodity-section uld-inventory-section"><div className="details-heading"><label className="b4-section-toggle"><SaveInput type="checkbox" checked={saved.recordsInventory} disabled={pending||editing||inventoryEditing||!saved.canEdit||!saved.utilisesUlds||saved.rows.length===0} onChange={event=>{const checked=event.target.checked;if(!checked&&saved.rows.some(row=>row.inventory.length>0)&&!window.confirm("Turning off ULD inventory will permanently remove all saved stock-number ranges. Continue?")){event.target.checked=true;return;}setError("");startTransition(async()=>{const result=await saveUldInventoryApplicability(iata,typeCode,subtype,saved.revision,checked);if(result.ok){setSaved(result.snapshot);setDraft(result.snapshot.rows);saveFeedback.complete(()=>{setMessage(checked?"ULD inventory management enabled.":"ULD inventory management disabled.");});}else setError(result.error);});}}/><span><strong>I want to record my ULD stock numbers</strong><small>When selected, every saved ULD identity is presented together for inventory management.</small></span></label><div className="c5-heading-actions"><ConfigurationStatusBadge status={completion.inventory}/>{saved.recordsInventory&&!editing&&!inventoryEditing&&saved.canEdit&&saved.rows.length>0&&<SaveButton className="secondary" type="button" onClick={()=>{setDraft(saved.rows.map(uldEditRow));setInventoryEditing(true);setError("");setMessage("");setAttentionRows(new Set());}}>EDIT INVENTORY</SaveButton>}</div></div>
 {!saved.recordsInventory?<p className="muted">ULD stock-number management is not selected.</p>:<div className="uld-inventory-all">{(inventoryEditing?draft:saved.rows).map(row=><article className="baggage-card uld-card" key={`inventory-${row.code}`}><div className="uld-card-heading"><h3>{row.code} — {row.type}</h3><span className="badge">{row.inventory.length} RANGE{row.inventory.length===1?"":"S"}</span></div>{inventoryEditing?(<div className="uld-inventory">{row.inventory.map((range,index)=><div className={`uld-inventory-row${attentionRows.has(`${row.code}:${index}`)?" attention-frame":""}`} key={range.id??index}><div><label htmlFor={`${row.code}-serial-start-${index}`}>Start Serial</label><SaveInput id={`${row.code}-serial-start-${index}`} type="text" inputMode="numeric" maxLength={5} value={range.serialStart} onChange={e=>updateInventory(row.code,index,"serialStart",e.target.value)} onBlur={()=>range.serialStart&&updateInventory(row.code,index,"serialStart",normaliseUldSerial(range.serialStart))}/></div><div><label htmlFor={`${row.code}-serial-end-${index}`}>End Serial</label><SaveInput id={`${row.code}-serial-end-${index}`} type="text" inputMode="numeric" maxLength={5} value={range.serialEnd} onChange={e=>updateInventory(row.code,index,"serialEnd",e.target.value)} onBlur={()=>range.serialEnd&&updateInventory(row.code,index,"serialEnd",normaliseUldSerial(range.serialEnd))}/></div><div><label htmlFor={`${row.code}-carrier-code-${index}`}>Carrier Code</label><SaveInput id={`${row.code}-carrier-code-${index}`} type="text" maxLength={2} value={range.carrierCode} onChange={e=>updateInventory(row.code,index,"carrierCode",e.target.value)}/></div><div className="uld-inventory-actions"><SaveButton type="button" className="secondary" onClick={()=>setDraft(current=>current.map(item=>item.code===row.code?{...item,inventory:item.inventory.filter((_,i)=>i!==index)}:item))}>REMOVE</SaveButton></div></div>)}<SaveButton type="button" className="secondary uld-inventory-add" disabled={row.inventory.length>=100} onClick={()=>setDraft(current=>current.map(item=>item.code===row.code?{...item,inventory:[...item.inventory,newInventoryRange()]}:item))}>ADD STOCK RANGE</SaveButton></div>):row.inventory.length?<div className="uld-inventory-values">{row.inventory.map(range=><div key={range.id??`${range.carrierCode}-${range.serialStart}`}><span>{range.carrierCode}</span><strong>{range.serialStart}–{range.serialEnd}</strong></div>)}</div>:<p className="muted">No stock-number ranges recorded.</p>}</article>)}</div>}
 {error&&!editing&&<p role="alert" className="field-error">{error}</p>}
 {inventoryEditing&&<><div className="logo-actions"><SaveSubmit type="button" disabled={pending} onClick={()=>{setError("");setAttentionRows(new Set());try{validateUlds(draft,saved);}catch(e){setError(e instanceof Error?e.message:"Check the inventory entries.");setAttentionRows(invalidInventoryRows(draft));return;}startTransition(async()=>{const result=await saveUlds(iata,typeCode,subtype,saved.revision,draft);if(result.ok){setSaved(result.snapshot);saveFeedback.complete(()=>{setInventoryEditing(false);setDraft(result.snapshot.rows);setMessage("");});}else setError(result.error);});}}>SAVE</SaveSubmit><SaveCancel type="button" className="secondary" onClick={()=>{setInventoryEditing(false);setDraft(saved.rows);setError("");}}>CANCEL</SaveCancel></div></>}
 </section><p role="status" aria-live="polite">{message}</p></>}
 </section>}</SaveScope>;
}
