"use client";
import Link from "next/link";
import {useState,useTransition,useRef,useEffect} from "react";
import {SectionHeader} from "@/components/section-header";
import {saveUlds,saveUldApplicability} from "@/app/uld-actions";
import {ConfigurationStatusBadge} from "@/components/configuration-status-badge";
import {b5Completion} from "@/domain/b5-status";
import {displayUnit} from "@/domain/display-standards";
import {adoptUld,customUld,newInventoryRange,normaliseUldSerial,validateUlds,uldEditRow,uldDisplayValue,type UldRow,type UldSnapshot} from "@/domain/uld-specifications";
function invalidInventoryRows(rows:UldRow[]):Set<string>{const invalid=new Set<string>();for(const row of rows){const seen=new Set<string>();row.inventory.forEach((range,index)=>{const start=range.serialStart.padStart(5,"0"),end=range.serialEnd.padStart(5,"0"),key=`${range.carrierCode}:${start}:${end}`;if(!/^[A-Z0-9]{2}$/.test(range.carrierCode)||!/^[0-9]{1,5}$/.test(range.serialStart)||!/^[0-9]{1,5}$/.test(range.serialEnd)||Number(range.serialStart)>Number(range.serialEnd)||seen.has(key))invalid.add(`${row.code}:${index}`);seen.add(key);});}return invalid;}
export function UldSpecifications({iata,typeCode,subtype,initial}:{iata:string;typeCode:string;subtype:string;initial:UldSnapshot}){
 const [saved,setSaved]=useState(initial),[draft,setDraft]=useState(initial.rows),[editing,setEditing]=useState(false),[editingCode,setEditingCode]=useState<string|null>(null),[selected,setSelected]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[attentionRows,setAttentionRows]=useState<Set<string>>(new Set());const [pending,startTransition]=useTransition();
 const [customOpen,setCustomOpen]=useState(false),[customCode,setCustomCode]=useState(""),[customType,setCustomType]=useState(""),[customError,setCustomError]=useState("");
 const addedInput=useRef<HTMLInputElement>(null);const [addedCode,setAddedCode]=useState("");
 useEffect(()=>{if(addedCode){addedInput.current?.focus({preventScroll:true});addedInput.current?.scrollIntoView({behavior:"smooth",block:"center"});}},[addedCode]);
 const rows=editing?draft:saved.rows;const completion=b5Completion(saved);const weightUnit=displayUnit(saved.weightUnit);const volumeUnit=saved.volumeUnit==="m3"?"m³":saved.volumeUnit==="ft3"?"ft³":"Unit not set";
 function update(code:string,key:"tare"|"maximum"|"volume",value:string){setDraft(current=>current.map(r=>r.code===code?{...r,[key]:value}:r));}
 function inventoryEnabled(code:string,enabled:boolean){setDraft(current=>current.map(r=>r.code===code?{...r,inventory:enabled?(r.inventory.length?r.inventory:[newInventoryRange()]):[]}:r));}
 function updateInventory(code:string,index:number,key:"carrierCode"|"serialStart"|"serialEnd",value:string){const normalised=key==="carrierCode"?value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,2):value.replace(/\D/g,"").slice(0,5);setAttentionRows(current=>{const next=new Set(current);next.delete(`${code}:${index}`);return next;});setDraft(current=>current.map(r=>r.code===code?{...r,inventory:r.inventory.map((range,i)=>i===index?{...range,[key]:normalised}:range)}:r));}
 function saveInventoryRange(code:string,index:number){setError("");const draftRow=draft.find(r=>r.code===code),savedRow=saved.rows.find(r=>r.code===code);if(!draftRow||!savedRow){setError("Save the new ULD before adding its inventory.");setAttentionRows(new Set([`${code}:${index}`]));return;}const range=draftRow.inventory[index];if(!range){setError("Check the ULD inventory range.");setAttentionRows(new Set([`${code}:${index}`]));return;}const inventory=range.id?savedRow.inventory.map(item=>item.id===range.id?range:item):[...savedRow.inventory,range];const payload=saved.rows.map(row=>row.code===code?{...row,inventory}:row);try{validateUlds(payload,saved);}catch(e){setError(e instanceof Error?e.message:"Check the ULD inventory range.");setAttentionRows(new Set([`${code}:${index}`]));return;}startTransition(async()=>{try{const result=await saveUlds(iata,typeCode,subtype,saved.revision,payload);if(!result.ok){setError(result.error);setAttentionRows(new Set([`${code}:${index}`]));return;}const persisted=result.snapshot.rows.find(r=>r.code===code)?.inventory??[];const otherUnsaved=draftRow.inventory.filter((item,i)=>i!==index&&item.id===null);setSaved(result.snapshot);setDraft(current=>current.map(row=>row.code===code?{...row,inventory:[...persisted,...otherUnsaved]}:row));setAttentionRows(new Set());setMessage(`${code} inventory range saved.`);}catch{setError("Unable to save this inventory range. Your entries are still here; please try again.");setAttentionRows(new Set([`${code}:${index}`]));}});}
 function beginEdit(code:string|null){setCustomOpen(false);setCustomError("");setCustomCode("");setCustomType("");setDraft(saved.rows.map(uldEditRow));setEditingCode(code);setEditing(true);setSelected("");setAddedCode("");setError("");setMessage("");setAttentionRows(new Set());}
 return <section className="overview carrier-details passenger-weights uld-specifications" aria-labelledby="uld-title"><SectionHeader id="uld-title" title="5. ULD SPECIFICATIONS" reference="(AHM565 Sheet B5)"><ConfigurationStatusBadge status={completion.page} variant="large"/></SectionHeader>
 {!saved.canView?<p>ULD specifications are not available for your account.</p>:<>
 <section className="commodity-section"><div className="details-heading"><label className="b4-section-toggle"><input type="checkbox" checked={saved.utilisesUlds} disabled={pending||editing||!saved.canEdit} onChange={event=>{const checked=event.target.checked;if(!checked&&saved.rows.length>0&&!window.confirm("Unchecking this option will permanently delete all ULD specifications and saved inventory for this aircraft. Continue?")){event.target.checked=true;return;}setError("");startTransition(async()=>{const result=await saveUldApplicability(iata,typeCode,subtype,saved.revision,checked);if(result.ok){setSaved(result.snapshot);setDraft(result.snapshot.rows);setMessage(checked?"ULD specifications now apply to this aircraft.":"B5 skipped for this aircraft. All ULD specifications and inventory for this aircraft have been deleted.");}else setError(result.error);});}}/><span><strong>This Aircraft Type Can Accept Unit Load Devices</strong><small>When selected, configure at least one ULD Type for this aircraft.</small></span></label><div className="c5-heading-actions"><ConfigurationStatusBadge status={completion.specifications}/>{!editing&&saved.utilisesUlds&&saved.canEdit&&saved.weightUnit&&saved.volumeUnit&&<button className="secondary" onClick={()=>beginEdit(null)}>EDIT</button>}</div></div>{!saved.utilisesUlds&&<p className="muted">B5 is skipped for this aircraft. No ULD specifications are required for this aircraft.</p>}{saved.utilisesUlds&&!saved.rows.length&&<p className="field-error">At least one ULD Type must be configured.</p>}</section>
 <p>{saved.weightUnit&&saved.volumeUnit?`Weights are in ${weightUnit} and volumes are in ${volumeUnit}, as selected on Sheet B1.`:<>Save Weight and Volume Units on <Link href={`/carrier/${encodeURIComponent(iata)}?sheet=B1`}>B1</Link> before adding ULDs.</>}</p>
 {!saved.canEdit&&<p className="muted">ULD specifications are read-only for your account.</p>}
 <form className={saved.utilisesUlds?"":"section-disabled"} noValidate onSubmit={e=>{e.preventDefault();setError("");setAttentionRows(new Set());try{validateUlds(draft,saved);}catch(e){setError(e instanceof Error?e.message:"Check the ULD entries.");setAttentionRows(invalidInventoryRows(draft));return;}startTransition(async()=>{try{const r=await saveUlds(iata,typeCode,subtype,saved.revision,draft);if(r.ok){setSaved(r.snapshot);setEditing(false);setEditingCode(null);setAttentionRows(new Set());setMessage("ULD specifications saved.");}else setError(r.error);}catch{setError("Unable to save. Your entries are still here; please try again.");}});}}><fieldset disabled={pending}><legend className="sr-only">Carrier ULD Specifications</legend>
 {editing&&editingCode===null&&<div className="variation-suggestions"><label htmlFor="uld-master">Select a ULD from the Master List</label><div className="uld-adopt"><select id="uld-master" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a ULD</option>{saved.master.filter(m=>!draft.some(r=>r.code===m.code)).map(m=><option key={m.code} value={m.code}>{m.code} — {m.type}{m.mainDeckOnly?" — Main Deck Only":""}</option>)}</select><button type="button" className="secondary" disabled={!selected||draft.length>=200} onClick={()=>{const master=saved.master.find(m=>m.code===selected);if(master){setDraft(current=>[...current,adoptUld(master,saved,current)]);setSelected("");setAddedCode(master.code);setMessage(`${master.code} added to your draft. Review its values and select Save to keep it.`);}}}>Add ULD</button></div><p>Select a code above, then choose Add ULD. Master values are a starting point. Review and amend them for your carrier, and select one Default for each ULD Type. Changes and removals take effect when you Save.</p></div>}
 {editing&&editingCode===null&&<div className="variation-suggestions"><button type="button" className="secondary" disabled={draft.length>=200} onClick={()=>{setCustomOpen(v=>!v);setCustomError("");}}>Add a Carrier ULD</button><p>Use this option when your ULD is not in the Master List. It will be saved for this carrier only.</p>{customOpen&&<><div className="passenger-weight-grid"><div><label htmlFor="custom-uld-code">ULD Code</label><input id="custom-uld-code" value={customCode} maxLength={3} onChange={e=>setCustomCode(e.target.value.toUpperCase())}/></div><div><label htmlFor="custom-uld-type">ULD Type</label><input id="custom-uld-type" value={customType} maxLength={6} onChange={e=>setCustomType(e.target.value.toUpperCase())}/></div></div><p>A ULD Code is limited to Three Letters or Numbers. ULD Type is limited to Six Letters, Numbers or Hyphens. A ULD Type may be a New Type or One already In Use with your carrier.</p>{customError&&<p role="alert" className="field-error">{customError}</p>}<button type="button" className="secondary" onClick={()=>{try{const row=customUld(customCode,customType,draft);setDraft(current=>[...current,row]);setAddedCode(row.code);setCustomOpen(false);setCustomCode("");setCustomType("");setCustomError("");setMessage(`${row.code} added to your draft. Enter its weights and volume, then select Save.`);}catch(e){setCustomError(e instanceof Error?e.message:"Check the ULD Code and Type.");}}}>Add to ULD List</button></>}</div>}
 {!rows.length&&<p>No ULD specifications have been saved.</p>}
 {rows.map((row:UldRow)=>{const rowEditing=editing&&(editingCode===null||editingCode===row.code);return <article className={`baggage-card uld-card${rowEditing?" uld-card-editing":""}`} key={row.code}><div className="uld-card-heading"><h3>{row.code} — {row.type}</h3>{rowEditing&&<label className="crew-checkbox"><input type="radio" name={`default-${row.type}`} checked={row.isDefault} onChange={()=>setDraft(current=>current.map(r=>r.type===row.type?{...r,isDefault:r.code===row.code}:r))}/>Default for {row.type}</label>} {!rowEditing&&row.isDefault&&<span className="badge">Default for {row.type}</span>}{!editing&&saved.utilisesUlds&&saved.canEdit&&<button className="secondary uld-remove" type="button" onClick={()=>beginEdit(row.code)}>EDIT {row.code}</button>}{rowEditing&&editingCode===null&&<button className="secondary uld-remove" type="button" onClick={()=>setDraft(current=>current.filter(r=>r.code!==row.code))}>Remove {row.code}</button>}</div>
 {(row.isCustom||(!row.isCustom&&saved.master.find(m=>m.code===row.code)?.mainDeckOnly))&&<p className="muted uld-kind">{row.isCustom?"Carrier ULD":"Main Deck Only"}</p>}
 <div className="passenger-weight-grid">{([['tare','Tare Weight',weightUnit],['maximum','Max Weight',weightUnit],['volume','Maximum Volume',volumeUnit]] as const).map(([key,label,unit])=><div key={key}><label htmlFor={rowEditing?`${row.code}-${key}`:undefined}>{label} ({unit})</label>{rowEditing?<input id={`${row.code}-${key}`} ref={row.code===addedCode&&key==="tare"?addedInput:undefined} type="number" step={key==="volume"?"0.01":"1"} min={key==="tare"?"0":key==="volume"?"0.01":"1"} value={row[key]} onChange={e=>update(row.code,key,e.target.value)}/>:<p className="passenger-value">{uldDisplayValue(row[key],key)}</p>}</div>)}</div>
 {rowEditing&&<div className="uld-inventory"><label className="crew-checkbox uld-inventory-toggle"><input type="checkbox" checked={row.inventory.length>0} onChange={e=>inventoryEnabled(row.code,e.target.checked)}/>Record my ULD inventory.</label>{(row.inventory.length?row.inventory:[newInventoryRange()]).map((range,index)=><div className={`uld-inventory-row${attentionRows.has(`${row.code}:${index}`)?" attention-frame":""}`} key={range.id??index}><div><label htmlFor={`${row.code}-serial-start-${index}`}>Start Serial</label><input id={`${row.code}-serial-start-${index}`} aria-invalid={attentionRows.has(`${row.code}:${index}`)||undefined} type="text" inputMode="numeric" maxLength={5} disabled={!row.inventory.length} value={range.serialStart} onChange={e=>updateInventory(row.code,index,"serialStart",e.target.value)} onBlur={()=>range.serialStart&&updateInventory(row.code,index,"serialStart",normaliseUldSerial(range.serialStart))}/></div><div><label htmlFor={`${row.code}-serial-end-${index}`}>End Serial</label><input id={`${row.code}-serial-end-${index}`} aria-invalid={attentionRows.has(`${row.code}:${index}`)||undefined} type="text" inputMode="numeric" maxLength={5} disabled={!row.inventory.length} value={range.serialEnd} onChange={e=>updateInventory(row.code,index,"serialEnd",e.target.value)} onBlur={()=>range.serialEnd&&updateInventory(row.code,index,"serialEnd",normaliseUldSerial(range.serialEnd))}/></div><div><label htmlFor={`${row.code}-carrier-code-${index}`}>Carrier Code</label><input id={`${row.code}-carrier-code-${index}`} aria-invalid={attentionRows.has(`${row.code}:${index}`)||undefined} type="text" maxLength={2} disabled={!row.inventory.length} value={range.carrierCode} onChange={e=>updateInventory(row.code,index,"carrierCode",e.target.value)}/></div><div className="uld-inventory-actions">{range.id===null&&<button type="button" disabled={!row.inventory.length||!saved.rows.some(r=>r.code===row.code)} onClick={()=>saveInventoryRange(row.code,index)}>Save</button>}<button type="button" className="secondary" disabled={!row.inventory.length} onClick={()=>setDraft(current=>current.map(r=>r.code===row.code?{...r,inventory:r.inventory.filter((_,i)=>i!==index)}:r))}>Remove</button></div></div>)}<button type="button" className="secondary uld-inventory-add" disabled={!row.inventory.length||row.inventory.length>=100} onClick={()=>setDraft(current=>current.map(r=>r.code===row.code?{...r,inventory:[...r.inventory,newInventoryRange()]}:r))}>ADD</button><p className="muted uld-inventory-note">Use ADD to accommodate broken/non-sequential Serial Numbers<br/>Carrier Code is not limited your Company IATA Code</p></div>}
 </article>})}
 {editing&&<>{error&&<p role="alert" className="field-error">{error}</p>}<div className="logo-actions"><button type="submit">{pending?"Saving…":editingCode===null?"Save ULDs":"Save ULD"}</button><button type="button" className="secondary" onClick={()=>{setEditing(false);setEditingCode(null);setAddedCode("");setMessage("");setError("");}}>Cancel</button></div></>}
 </fieldset></form><p role="status" aria-live="polite">{message}</p></>}
 </section>;
}
