import{AuthenticationRequired,CarrierUnavailable}from"@/domain/models";
import{OperationalFlightInvalid,validFreightPlanning,validServiceDate,validUuid}from"@/domain/operational-flights";
import type{AuthService}from"@/ports/auth-service";
import type{CarrierRepository}from"@/ports/carrier-repository";
import type{AdHocFlightInput,OperationalFlightRepository}from"@/ports/operational-flight-repository";
import{validFreightAcceptance}from"@/domain/freight-acceptance";
const code=(value:unknown,label:string,pattern:RegExp)=>{const result=String(value??"").trim().toUpperCase();if(!pattern.test(result))throw new OperationalFlightInvalid(`Enter a valid ${label}.`);return result};
const optional=(value:unknown)=>String(value??"").trim().toUpperCase()||null;
function adHoc(value:unknown):AdHocFlightInput{const row=value as Record<string,unknown>,departureAirport=code(row.departureAirport,"departure airport",/^[A-Z]{3}$/),arrivalAirport=code(row.arrivalAirport,"arrival airport",/^[A-Z]{3}$/),departureTime=String(row.departureTime??""),arrivalTime=String(row.arrivalTime??"");if(departureAirport===arrivalAirport)throw new OperationalFlightInvalid("Departure and arrival airports must be different.");if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(departureTime)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(arrivalTime))throw new OperationalFlightInvalid("Enter valid departure and arrival times.");const arrivalDayOffset=Number(row.arrivalDayOffset);if(!Number.isInteger(arrivalDayOffset)||arrivalDayOffset<0||arrivalDayOffset>2)throw new OperationalFlightInvalid("Select a valid arrival day.");const remarks=String(row.remarks??"").trim()||null;if(remarks&&remarks.length>2000)throw new OperationalFlightInvalid("Keep remarks within 2,000 characters.");return{serviceDate:validServiceDate(row.serviceDate),flightNumber:code(row.flightNumber,"flight number",/^(?:\d{1,4}|\d{1,3}[A-Z])$/),operationalSuffix:code(row.operationalSuffix??"","operational suffix",/^[A-Z0-9]?$/),serviceType:code(row.serviceType,"service type",/^[A-Z0-9]$/),departureAirport,arrivalAirport,departureTime,arrivalTime,arrivalDayOffset,aircraftType:code(row.aircraftType,"aircraft type",/^[A-Z0-9]{2,4}$/),aircraftSubtype:code(row.aircraftSubtype,"aircraft subtype",/^[A-Z0-9]{1,4}$/),aircraftConfiguration:optional(row.aircraftConfiguration),aircraftRegistration:optional(row.aircraftRegistration),remarks}}
export function createOperationalFlights(auth:AuthService,carriers:CarrierRepository,repository:OperationalFlightRepository){const access=async(iata:string)=>{const user=await auth.currentUser();if(!user)throw new AuthenticationRequired();const carrier=await carriers.findAuthorised(iata);if(!carrier)throw new CarrierUnavailable();return{user,carrier}};return{async board(iata:string,date:unknown,airport:unknown){const context=await access(iata),cleanAirport=String(airport??"").trim().toUpperCase();if(cleanAirport&&!/^[A-Z]{3}$/.test(cleanAirport))throw new OperationalFlightInvalid("Select a valid airport.");return{...context,board:await repository.board(iata,validServiceDate(date),cleanAirport||null)}},async start(iata:string,scheduleLegId:unknown,date:unknown){await access(iata);return repository.start(iata,validUuid(scheduleLegId),validServiceDate(date))},async createAdHoc(iata:string,input:unknown){await access(iata);return repository.createAdHoc(iata,adHoc(input))},async get(iata:string,id:unknown){const context=await access(iata);return{...context,flight:await repository.get(iata,validUuid(id))}},async saveFreightPlanning(iata:string,id:unknown,version:unknown,input:unknown){await access(iata);const cleanVersion=Number(version);if(!Number.isSafeInteger(cleanVersion)||cleanVersion<1)throw new OperationalFlightInvalid("Reload the flight before saving.");return repository.saveFreightPlanning(iata,validUuid(id),cleanVersion,validFreightPlanning(input))},async saveFreightAcceptance(iata:string,id:unknown,version:unknown,input:unknown){await access(iata);const cleanVersion=Number(version),flightId=validUuid(id);if(!Number.isSafeInteger(cleanVersion)||cleanVersion<0)throw new OperationalFlightInvalid("Reload the acceptance statement before saving.");const flight=await repository.get(iata,flightId),unloadingStations=[...new Set(flight.itinerary.legs.filter(leg=>leg.legSequence>=flight.legSequence).map(leg=>leg.arrivalAirport))];return repository.saveFreightAcceptance(iata,flightId,cleanVersion,validFreightAcceptance(input,unloadingStations,flight.freightAcceptance.specialLoadOptions,flight.freightAcceptance.uldLimits,flight.freightAcceptance.planningDensities))},async saveLoadPlan(iata:string,id:unknown,expectedEdition:number,source:"AUTOLOAD"|"MANUAL"|"RESET",solution:import("@/domain/load-planning-solver").LoadPlanningSolution){await access(iata);return repository.saveLoadPlan(iata,validUuid(id),expectedEdition,source,solution)}}}
