begin;

alter table "Basic_Carrier_Record"."Operational_Freight_Acceptance_Items" add column if not exists "Included_Loads" jsonb not null default '[]'::jsonb;
update "Basic_Carrier_Record"."Operational_Freight_Acceptance_Items" set "Commodity"='OTHER' where "Commodity" not in('CARGO','MAIL','OTHER');
do $$declare r record;begin for r in select c.conname from pg_constraint c join pg_class t on t.oid=c.conrelid join pg_namespace n on n.oid=t.relnamespace where n.nspname='Basic_Carrier_Record' and t.relname='Operational_Freight_Acceptance_Items' and c.contype='c' and pg_get_constraintdef(c.oid) like '%Commodity%' loop execute format('alter table "Basic_Carrier_Record"."Operational_Freight_Acceptance_Items" drop constraint %I',r.conname);end loop;end$$;
alter table "Basic_Carrier_Record"."Operational_Freight_Acceptance_Items" add constraint "operational_freight_acceptance_commodity_check" check("Commodity" in('CARGO','MAIL','OTHER'));
alter table "Basic_Carrier_Record"."Operational_Freight_Acceptance_Items" add constraint "operational_freight_acceptance_included_loads_check" check(jsonb_typeof("Included_Loads")='array');

create or replace function "Basic_Carrier_Record".get_operational_freight_acceptance(p_iata text,p_operational_flight_id uuid)
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare f "Basic_Carrier_Record"."Operational_Flights"%rowtype;h "Basic_Carrier_Record"."Operational_Freight_Acceptance"%rowtype;planning jsonb;items jsonb;special_options jsonb;total numeric:=0;offer numeric;applicable boolean;can_operate boolean;
begin
 p_iata:=upper(btrim(p_iata));
 if(select auth.uid())is null or not(private.has_carrier_permission(p_iata,'LOAD_CONTROL_VIEW')or private.has_global_permission('LOAD_CONTROL_VIEW'))then raise exception 'Load Control access denied' using errcode='42501';end if;
 can_operate:=private.has_carrier_permission(p_iata,'LOAD_CONTROL_OPERATE')or private.has_global_permission('LOAD_CONTROL_OPERATE');select coalesce(jsonb_agg(jsonb_build_object('code',btrim(m."Special_Load_Code"),'description',btrim(m."Special_Load_Code_Description"),'dangerousGoods',m."Special_Load_Is_DGR",'cargoAircraftOnly',m."Cargo_Aircraft_Only")order by btrim(m."Special_Load_Code")),'[]'::jsonb)into special_options from "Basic_Carrier_Record"."MASTER_IATA_Special_Load_Codes" m;
 select*into f from "Basic_Carrier_Record"."Operational_Flights" where "Carrier_IATA"=p_iata and "Operational_Flight_ID"=p_operational_flight_id;
 if not found then raise exception 'Operational flight not found' using errcode='P0002';end if;
 planning:="Basic_Carrier_Record".get_operational_freight_planning(p_iata,p_operational_flight_id);applicable:=coalesce((planning->>'applicable')::boolean,false);offer:=nullif(planning->>'cargoOfferWeight','')::numeric;
 if not applicable then return jsonb_build_object('applicable',false,'canEdit',can_operate,'version',0,'status','EMPTY','source',null,'sourceReference',null,'rawMessage',null,'items','[]'::jsonb,'totalWeight',0,'cargoOfferWeight',offer,'remainingOffer',offer,'withinOffer',true,'updatedAt',null,'specialLoadOptions',special_options);end if;
 select*into h from "Basic_Carrier_Record"."Operational_Freight_Acceptance" where "Operational_Flight_ID"=p_operational_flight_id and "Carrier_IATA"=p_iata;
 select coalesce(jsonb_agg(jsonb_build_object('lineId',i."Line_ID",'loadType',i."Load_Type",'uldId',i."ULD_ID",'grossWeight',i."Gross_Weight",'netWeight',i."Net_Weight",'unloadingStation',btrim(i."Station_Of_Unloading"),'destination',btrim(i."Destination"),'commodity',i."Commodity",'pieces',i."Pieces",'volume',i."Volume_M3",'specialHandlingCodes',to_jsonb(i."Special_Handling_Codes"),'includedLoads',i."Included_Loads",'dangerousGoods',i."Dangerous_Goods",'remarks',i."Remarks",'source',i."Source",'sourceReference',i."Source_Reference")order by i."Sequence_Number"),'[]'::jsonb),coalesce(sum(i."Gross_Weight"),0)into items,total from "Basic_Carrier_Record"."Operational_Freight_Acceptance_Items" i where i."Operational_Flight_ID"=p_operational_flight_id and i."Carrier_IATA"=p_iata;
 return jsonb_build_object('applicable',true,'canEdit',can_operate,'version',coalesce(h."Version",0),'status',case when h."Operational_Flight_ID"is null then'EMPTY'else h."Status"end,'source',h."Source",'sourceReference',h."Source_Reference",'rawMessage',h."Raw_Message",'items',items,'totalWeight',total,'cargoOfferWeight',offer,'remainingOffer',case when offer is null then null else offer-total end,'withinOffer',offer is null or total<=offer,'updatedAt',h."Updated_At",'specialLoadOptions',special_options);
end;$$;
revoke all on function "Basic_Carrier_Record".get_operational_freight_acceptance(text,uuid)from public,anon;grant execute on function "Basic_Carrier_Record".get_operational_freight_acceptance(text,uuid)to authenticated;

create or replace function "Basic_Carrier_Record".save_operational_freight_acceptance(p_iata text,p_operational_flight_id uuid,p_version integer,p_values jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare f "Basic_Carrier_Record"."Operational_Flights"%rowtype;h "Basic_Carrier_Record"."Operational_Freight_Acceptance"%rowtype;planning jsonb;item jsonb;seq integer:=0;source text:=upper(btrim(p_values->>'source'));source_ref text:=nullif(btrim(p_values->>'sourceReference'),'');raw_message text:=nullif(btrim(p_values->>'rawMessage'),'');load_type text;uld_id text;gross numeric;net numeric;unload text;destination text;commodity text;pieces integer;volume numeric;item_source text;item_ref text;remarks text;shcs text[];included_loads jsonb;included_total numeric;included_dg boolean;dg boolean;total numeric:=0;offer numeric;seen_uld text[]:='{}';allowed_unloading text[];
begin
 p_iata:=upper(btrim(p_iata));
 if(select auth.uid())is null or not(private.has_carrier_permission(p_iata,'LOAD_CONTROL_OPERATE')or private.has_global_permission('LOAD_CONTROL_OPERATE'))then raise exception 'Load Control operation denied' using errcode='42501';end if;
 if p_values is null or jsonb_typeof(p_values)<>'object'or source not in('MANUAL','CSV','AHM581','MIXED')or jsonb_typeof(p_values->'items')<>'array'or jsonb_array_length(p_values->'items')not between 1 and 250 or char_length(coalesce(source_ref,''))>200 or char_length(coalesce(raw_message,''))>100000 then raise exception 'Check the freight acceptance statement' using errcode='22023';end if;
 select*into f from "Basic_Carrier_Record"."Operational_Flights" where "Carrier_IATA"=p_iata and "Operational_Flight_ID"=p_operational_flight_id for update;
 if not found then raise exception 'Operational flight not found' using errcode='P0002';end if;
 select coalesce(array_agg(distinct upper(btrim(leg->>'arrivalAirport'))),array[upper(btrim(f."Arrival_Airport_IATA"))]) into allowed_unloading from jsonb_array_elements(coalesce(f."Itinerary_Snapshot"->'legs','[]'::jsonb)) leg where coalesce(nullif(leg->>'legSequence','')::integer,f."Leg_Sequence_Number")>=f."Leg_Sequence_Number";
 planning:="Basic_Carrier_Record".get_operational_freight_planning(p_iata,p_operational_flight_id);if not coalesce((planning->>'applicable')::boolean,false)then raise exception 'Freight acceptance is available for freighter aircraft' using errcode='23514';end if;if not coalesce((planning->>'ready')::boolean,false)then raise exception 'Complete the Cargo Offer before accepting freight' using errcode='55000';end if;offer:=nullif(planning->>'cargoOfferWeight','')::numeric;
 select*into h from "Basic_Carrier_Record"."Operational_Freight_Acceptance" where "Operational_Flight_ID"=p_operational_flight_id for update;
 if found then if h."Version"<>p_version then raise exception 'The acceptance statement changed. Reload before saving.' using errcode='40001';end if;else if p_version<>0 then raise exception 'The acceptance statement changed. Reload before saving.' using errcode='40001';end if;end if;
 for item in select value from jsonb_array_elements(p_values->'items')loop seq:=seq+1;load_type:=upper(btrim(item->>'loadType'));uld_id:=nullif(upper(btrim(item->>'uldId')),'');gross:=nullif(item->>'grossWeight','')::numeric;net:=nullif(item->>'netWeight','')::numeric;unload:=upper(btrim(item->>'unloadingStation'));destination:=upper(btrim(item->>'destination'));commodity:=upper(btrim(item->>'commodity'));pieces:=nullif(item->>'pieces','')::integer;volume:=nullif(item->>'volume','')::numeric;item_source:=upper(btrim(item->>'source'));item_ref:=nullif(btrim(item->>'sourceReference'),'');remarks:=nullif(btrim(item->>'remarks'),'');included_loads:=coalesce(item->'includedLoads','[]'::jsonb);if jsonb_typeof(included_loads)<>'array'then raise exception 'Check included loads on row %',seq using errcode='22023';end if;if exists(select 1 from jsonb_array_elements(included_loads)x where jsonb_typeof(x)<>'object'or upper(btrim(x->>'code'))!~'^[A-Z0-9]{2,5}$'or case when coalesce(x->>'weight','')~'^\d+(\.\d+)?$'then(x->>'weight')::numeric<=0 else true end or not exists(select 1 from "Basic_Carrier_Record"."MASTER_IATA_Special_Load_Codes"m where btrim(m."Special_Load_Code")=upper(btrim(x->>'code'))))then raise exception 'Check included IATA special-load codes on row %',seq using errcode='22023';end if;select coalesce(jsonb_agg(jsonb_build_object('code',btrim(m."Special_Load_Code"),'weight',(x->>'weight')::numeric,'dangerousGoods',m."Special_Load_Is_DGR")),'[]'::jsonb),coalesce(sum((x->>'weight')::numeric),0),coalesce(bool_or(m."Special_Load_Is_DGR"),false)into included_loads,included_total,included_dg from jsonb_array_elements(included_loads)x join "Basic_Carrier_Record"."MASTER_IATA_Special_Load_Codes"m on btrim(m."Special_Load_Code")=upper(btrim(x->>'code'));dg:=coalesce((item->>'dangerousGoods')::boolean,false)or included_dg;select coalesce(array_agg(upper(btrim(value))),array[]::text[])into shcs from jsonb_array_elements_text(coalesce(item->'specialHandlingCodes','[]'::jsonb));if exists(select 1 from unnest(shcs)c where not exists(select 1 from "Basic_Carrier_Record"."MASTER_IATA_Special_Load_Codes"m where btrim(m."Special_Load_Code")=c))then raise exception 'Check IATA special handling codes on row %',seq using errcode='22023';end if;
  if load_type not in('ULD','BULK')or gross is null or gross<=0 or(net is not null and(net<0 or net>gross))or unload!~'^[A-Z]{3}$'or not(unload=any(allowed_unloading))or destination!~'^[A-Z]{3}$'or commodity not in('CARGO','MAIL','OTHER')or included_total>gross or item_source not in('MANUAL','CSV','AHM581')or(pieces is not null and pieces<0)or(volume is not null and volume<0)or char_length(coalesce(item_ref,''))>200 or char_length(coalesce(remarks,''))>1000 then raise exception 'Check freight acceptance row %',seq using errcode='22023';end if;
  if(load_type='ULD'and(uld_id is null or uld_id!~'^[A-Z]{3}[A-Z0-9]{4,8}$'or volume is not null))or(load_type='BULK'and uld_id is not null)then raise exception 'Check ULD/Bulk identity on row %',seq using errcode='22023';end if;
  if uld_id is not null then if uld_id=any(seen_uld)then raise exception 'ULD % appears more than once',uld_id using errcode='23505';end if;seen_uld:=array_append(seen_uld,uld_id);end if;total:=total+gross;
 end loop;
 if offer is not null and total>offer then raise exception 'Accepted gross weight exceeds the Cargo Offer by % KG',round(total-offer) using errcode='23514';end if;
 insert into "Basic_Carrier_Record"."Operational_Freight_Acceptance"("Operational_Flight_ID","Carrier_IATA","Status","Source","Source_Reference","Raw_Message")values(p_operational_flight_id,p_iata,'ACCEPTED',source,source_ref,raw_message)on conflict("Operational_Flight_ID")do update set "Status"='ACCEPTED',"Source"=excluded."Source","Source_Reference"=excluded."Source_Reference","Raw_Message"=excluded."Raw_Message","Version"="Basic_Carrier_Record"."Operational_Freight_Acceptance"."Version"+1,"Updated_At"=now(),"Updated_By"=auth.uid();
 delete from "Basic_Carrier_Record"."Operational_Freight_Acceptance_Items"where"Operational_Flight_ID"=p_operational_flight_id;
 seq:=0;for item in select value from jsonb_array_elements(p_values->'items')loop seq:=seq+1;load_type:=upper(btrim(item->>'loadType'));uld_id:=nullif(upper(btrim(item->>'uldId')),'');gross:=(item->>'grossWeight')::numeric;net:=nullif(item->>'netWeight','')::numeric;unload:=upper(btrim(item->>'unloadingStation'));destination:=upper(btrim(item->>'destination'));commodity:=upper(btrim(item->>'commodity'));pieces:=nullif(item->>'pieces','')::integer;volume:=nullif(item->>'volume','')::numeric;item_source:=upper(btrim(item->>'source'));item_ref:=nullif(btrim(item->>'sourceReference'),'');remarks:=nullif(btrim(item->>'remarks'),'');included_loads:=coalesce(item->'includedLoads','[]'::jsonb);if jsonb_typeof(included_loads)<>'array'then raise exception 'Check included loads on row %',seq using errcode='22023';end if;if exists(select 1 from jsonb_array_elements(included_loads)x where jsonb_typeof(x)<>'object'or upper(btrim(x->>'code'))!~'^[A-Z0-9]{2,5}$'or case when coalesce(x->>'weight','')~'^\d+(\.\d+)?$'then(x->>'weight')::numeric<=0 else true end or not exists(select 1 from "Basic_Carrier_Record"."MASTER_IATA_Special_Load_Codes"m where btrim(m."Special_Load_Code")=upper(btrim(x->>'code'))))then raise exception 'Check included IATA special-load codes on row %',seq using errcode='22023';end if;select coalesce(jsonb_agg(jsonb_build_object('code',btrim(m."Special_Load_Code"),'weight',(x->>'weight')::numeric,'dangerousGoods',m."Special_Load_Is_DGR")),'[]'::jsonb),coalesce(sum((x->>'weight')::numeric),0),coalesce(bool_or(m."Special_Load_Is_DGR"),false)into included_loads,included_total,included_dg from jsonb_array_elements(included_loads)x join "Basic_Carrier_Record"."MASTER_IATA_Special_Load_Codes"m on btrim(m."Special_Load_Code")=upper(btrim(x->>'code'));dg:=coalesce((item->>'dangerousGoods')::boolean,false)or included_dg;select coalesce(array_agg(upper(btrim(value))),array[]::text[])into shcs from jsonb_array_elements_text(coalesce(item->'specialHandlingCodes','[]'::jsonb));if exists(select 1 from unnest(shcs)c where not exists(select 1 from "Basic_Carrier_Record"."MASTER_IATA_Special_Load_Codes"m where btrim(m."Special_Load_Code")=c))then raise exception 'Check IATA special handling codes on row %',seq using errcode='22023';end if;insert into "Basic_Carrier_Record"."Operational_Freight_Acceptance_Items"("Operational_Flight_ID","Carrier_IATA","Sequence_Number","Load_Type","ULD_ID","Gross_Weight","Net_Weight","Station_Of_Unloading","Destination","Commodity","Pieces","Volume_M3","Special_Handling_Codes","Included_Loads","Dangerous_Goods","Remarks","Source","Source_Reference")values(p_operational_flight_id,p_iata,seq,load_type,uld_id,gross,net,unload,destination,commodity,pieces,volume,shcs,included_loads,dg,remarks,item_source,item_ref);end loop;
 update "Basic_Carrier_Record"."Operational_Flights"set"Status"=case when"Status"='INITIATED'then'LOAD_PLANNING'else"Status"end where"Operational_Flight_ID"=p_operational_flight_id and"Carrier_IATA"=p_iata;
 return "Basic_Carrier_Record".get_operational_freight_acceptance(p_iata,p_operational_flight_id);
end;$$;
revoke all on function "Basic_Carrier_Record".save_operational_freight_acceptance(text,uuid,integer,jsonb)from public,anon;grant execute on function "Basic_Carrier_Record".save_operational_freight_acceptance(text,uuid,integer,jsonb)to authenticated;
notify pgrst,'reload schema';
commit;
