begin;
create or replace function "Basic_Carrier_Record".get_aircraft_d3(p_iata text,p_type_code text,p_subtype text) returns jsonb language plpgsql stable security invoker set search_path='' as $$
declare tc text:=upper(btrim(p_type_code));st text:=upper(btrim(p_subtype));can_view boolean:=(select auth.uid()) is not null and (private.has_carrier_permission(p_iata,'AIRCRAFT_CONFIG_VIEW') or private.has_global_permission('AIRCRAFT_CONFIG_VIEW'));can_edit boolean:=private.has_carrier_permission(p_iata,'AIRCRAFT_CONFIG_EDIT') or private.has_global_permission('AIRCRAFT_CONFIG_EDIT');holds jsonb;uld_types jsonb;uld_options jsonb;configs jsonb;
begin
if not can_view then raise exception 'Not authorised' using errcode='42501';end if;
if not exists(select 1 from "Basic_Carrier_Record"."Basic_Aircraft_Data" where "Carrier_IATA"=p_iata and "Aircraft_Type_IATA"=tc and "Aircraft_Series_Subtype"=st) then raise exception 'Aircraft not found' using errcode='23503';end if;
select coalesce(jsonb_agg(jsonb_build_object('id',btrim(h."Hold_Name_ID"),'compartments',coalesce((select jsonb_agg(btrim(c."Compartment_ID") order by btrim(c."Compartment_ID")) from "Basic_Carrier_Record"."Aircraft_Compartments" c where c."Carrier_IATA"=h."Carrier_IATA" and c."Aircraft_Type_IATA"=h."Aircraft_Type_IATA" and c."Aircraft_Series_Subtype"=h."Aircraft_Series_Subtype" and c."Hold_Name_ID"=h."Hold_Name_ID"),'[]'::jsonb)) order by btrim(h."Hold_Name_ID")),'[]'::jsonb) into holds from "Basic_Carrier_Record"."Aircraft_Holds" h where h."Carrier_IATA"=p_iata and h."Aircraft_Type_IATA"=tc and h."Aircraft_Series_Subtype"=st and btrim(h."Hold_Type")='ULD';
select coalesce(jsonb_agg(t."ULD_Type" order by t."ULD_Type"),'[]'::jsonb) into uld_types from (select distinct "ULD_Type" from "Basic_Carrier_Record"."Carrier_ULD_Specifications" where "Carrier_IATA"=p_iata and "Aircraft_Type_IATA"=tc and "Aircraft_Series_Subtype"=st) t;
select coalesce(jsonb_agg(jsonb_build_object('code',m."ULD_ID",'type',m."ULD_Type",'baseCode',m."ULD_Base_Code",'baseWidth',m."ULD_Base_Width",'baseLength',m."ULD_Base_Length") order by m."ULD_ID"),'[]'::jsonb) into uld_options from "Basic_Carrier_Record"."MASTER_ULD_List" m;
select coalesce(jsonb_agg(jsonb_build_object(
 'holdId',c."Hold_Name_ID",'code',c."ULD_Configuration_Code",'description',c."Configuration_Description",'expectedPositionCount',c."Expected_Physical_Positions",
 'atomicBays',coalesce((select jsonb_agg(jsonb_build_object('id',b."Atomic_Bay_ID",'compartmentId',b."Compartment_ID",'lateralCentroid',b."Lateral_Arm_Centroid",'lateralFrom',b."Lateral_Arm_From",'lateralTo',b."Lateral_Arm_To",'balanceCentroid',b."Balance_Arm_Centroid",'balanceFrom',b."Balance_Arm_From",'balanceTo',b."Balance_Arm_To",'colour',b."Atomic_Bay_Colour") order by b."Balance_Arm_Centroid",b."Atomic_Bay_ID") from "Basic_Carrier_Record"."Carrier_ULD_Atomic_Bays" b where b."Carrier_IATA"=c."Carrier_IATA" and b."Aircraft_Type_IATA"=c."Aircraft_Type_IATA" and b."Aircraft_Series_Subtype"=c."Aircraft_Series_Subtype" and b."Hold_Name_ID"=c."Hold_Name_ID" and b."ULD_Configuration_Code"=c."ULD_Configuration_Code"),'[]'::jsonb),
 'rows',coalesce((select jsonb_agg(jsonb_build_object('rowType',p."ULD_Row_Type",'positionId',p."ULD_Position_ID",'compartmentId',p."Compartment_ID",'uldType',p."ULD_Type",'uldBaseCode',p."ULD_Base_Code",'groupId',p."ULD_Group_ID",'occupiedBayIds',coalesce((select jsonb_agg(o."Atomic_Bay_ID" order by o."Atomic_Bay_ID") from "Basic_Carrier_Record"."Carrier_ULD_Position_Occupancy" o where o."ULD_Position_UUID"=p."ULD_Position_UUID"),'[]'::jsonb),'maxWeight',p."ULD_Position_Max_Weight",'volume',p."ULD_Position_Volume",'lateralCentroid',p."Lateral_Arm_Centroid",'lateralFrom',p."Lateral_Arm_From",'lateralTo',p."Lateral_Arm_To",'balanceCentroid',p."Balance_Arm_Centroid",'balanceFrom',p."Balance_Arm_From",'balanceTo',p."Balance_Arm_To",'indexPerWeightUnit',p."Index_Per_Weight_Unit",'colour',p."ULD_Position_Colour") order by p."ULD_Position_ID",p."ULD_Type") from "Basic_Carrier_Record"."Carrier_ULD_Positions" p where p."Carrier_IATA"=c."Carrier_IATA" and p."Aircraft_Type_IATA"=c."Aircraft_Type_IATA" and p."Aircraft_Series_Subtype"=c."Aircraft_Series_Subtype" and p."Hold_Name_ID"=c."Hold_Name_ID" and p."ULD_Configuration_Code"=c."ULD_Configuration_Code"),'[]'::jsonb)
) order by c."Hold_Name_ID",c."ULD_Configuration_Code"),'[]'::jsonb) into configs from "Basic_Carrier_Record"."Carrier_ULD_Position_Configurations" c where c."Carrier_IATA"=p_iata and c."Aircraft_Type_IATA"=tc and c."Aircraft_Series_Subtype"=st;
return jsonb_build_object('canView',can_view,'canEdit',can_edit,'revision',md5(jsonb_build_object('holds',holds,'uldTypes',uld_types,'uldOptions',uld_options,'configurations',configs)::text),'typeCode',tc,'subtype',st,'uldHolds',holds,'uldTypes',uld_types,'uldOptions',uld_options,'configurations',configs);end$$;
notify pgrst,'reload schema';
commit;
